import FormalSchemes.AdicHausdorff

set_option linter.style.header false

/-!
# Completeness of a subring for the contracted ideal

`AlgebraicGeometry.isHausdorff_comap_subtype` (`FormalSchemes.TateInvNodeChartAmbient`) proves
that a subring `S` of a Hausdorff adic ring `A` is Hausdorff for the contracted ideal
`K.comap S.subtype`, with no hypothesis at all. The completeness half is **not** the same
argument, and this file isolates exactly what it costs.

## The asymmetry this file is about

`IsPrecomplete J S` quantifies over the powers `J ^ n` of the ideal `J` itself. For
`J = K.comap S.subtype` that is the **power filtration of the contracted ideal**, not the
**induced filtration** `(K ^ n).comap S.subtype`. Only one containment between them is free,
and it is `Ideal.pow_comap_subtype_le_comap_pow` below:

```
(K.comap S.subtype) ^ n ≤ (K ^ n).comap S.subtype
```

An element of `S` lying in `K ^ n` is a sum of `n`-fold products of elements of `K`, and nothing
forces those factors to lie in `S`, so the reverse containment is not available in general.
Hausdorffness needs only the free direction; precompleteness needs the other one. That is why
`AlgebraicGeometry.isHausdorff_comap_subtype` is unconditional and why the slogan "a closed
subring of a complete ring is complete" does not, as stated, produce `IsPrecomplete J S`.

## What is here

The two obligations are separated, and only one of them carries a hypothesis.

* `Subring.IsAdicallyClosed`: `S` contains every element of `A` it approximates.
* `Subring.IsInducedPrecomplete`: every sequence in `S` that is Cauchy for the **induced**
  filtration has a limit in `S`, again for the induced filtration. This is the topological
  statement "a closed subset of a complete space is complete", with no ideal of `S` in it.
* `Subring.isInducedPrecomplete_of_isAdicallyClosed`: **unconditional** — closedness plus
  `IsPrecomplete K A` gives `IsInducedPrecomplete`.
* `Subring.HasCofinalInducedFiltration`: the bridge, `∀ n, ∃ m, (K ^ m).comap S.subtype ≤
  (K.comap S.subtype) ^ n`.
* `Subring.isPrecomplete_comap_subtype` and `Subring.isAdicComplete_comap_subtype`: the two
  combined. The second takes the Hausdorff half as a hypothesis, so that a caller can supply
  `AlgebraicGeometry.isHausdorff_comap_subtype` rather than have it reproved here.

Two sufficient conditions for the bridge are proved, since the point of the file is a correct
hypothesis set rather than an unconditional theorem:

* `Subring.hasCofinalInducedFiltration_of_retraction`: `K` is generated by `K ∩ S` and there is a
  retraction `A → S` that is linear over `S`. Then the bridge holds with `m = n`.
* `Subring.hasCofinalInducedFiltration_span_singleton`: `K = (c)` for `c ∈ S` and `S` is
  saturated for multiplication by `c`. Again `m = n`.
* `RingHom.mem_eqLocus_of_mul_mem`: an equalizer subring is saturated for multiplication by any
  `c` in it whose image is left-regular — the source of the previous item's hypothesis.

`isHausdorff_comap` generalises `AlgebraicGeometry.isHausdorff_comap_subtype` from a subring
inclusion to any injective ring homomorphism, which is what a transport along a ring isomorphism
needs. Three further transport lemmas along a ring isomorphism — `Subring.mem_map_ringEquiv`,
`Subring.map_ringEquiv_inf` and `Subring.map_ringEquiv_eqLocus` — are proved as well: they are
what lets a subring cut out by an equalizer on one side of an isomorphism be recognised as one on
the other.

Finally, the closedness half for the shape the Tate cluster meets it in:

* `RingHom.mem_eqLocus_of_forall_sub_mem_pow` and `RingHom.isAdicallyClosed_eqLocus`: the
  equalizer of two maps that carry `J ^ m` into `K ^ m` is adically closed when the target is
  Hausdorff. This is the `RingHom`-level spelling of "continuous", the same one
  `AlgebraicGeometry.eq_zero_of_forall_sub_ker_mem_pow`
  (`FormalSchemes.TateInvSeparatingKerClosed`) uses.
* `Subring.IsAdicallyClosed.inf` and `RingHom.isAdicallyClosed_inf_eqLocus`: an intersection of
  two such equalizers, with targets in two different rings.

## What is *not* proved

**No unconditional completeness statement is obtained, and none is claimed.**
`Subring.HasCofinalInducedFiltration` is a hypothesis of every conclusion that mentions
`IsPrecomplete (K.comap S.subtype) S`, and the file exhibits no `(A, K, S)` at which it fails —
that would be a separate result. The two sufficient conditions above are sufficient only; neither
is shown necessary.

## References

* [Bosch, *Lectures on Formal and Rigid Geometry*, LNM 2105], §7 — adic rings and ideals of
  definition.
* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. 0, §7.2.
-/

universe u

namespace Ideal

variable {A : Type u} [CommRing A]

/-- **The `SModEq` spelling of the adic filtration on a ring is a difference membership.**
Mathlib states `IsHausdorff` and `IsPrecomplete` with `SModEq` at the submodule `K ^ n • ⊤`;
`Ideal.mem_smul_top_self_iff` (`FormalSchemes.AdicHausdorff`) collapses that submodule to the
ideal, and `SModEq.sub_mem` turns the congruence into a membership. -/
theorem smodEq_pow_iff_sub_mem {K : Ideal A} {n : ℕ} {x y : A} :
    x ≡ y [SMOD (K ^ n • ⊤ : Submodule A A)] ↔ x - y ∈ K ^ n := by
  rw [SModEq.sub_mem, Ideal.mem_smul_top_self_iff]

/-- **The free containment between the two filtrations**: the power filtration of a contracted
ideal is finer than the contraction of the power filtration. This is the direction
`AlgebraicGeometry.isHausdorff_comap_subtype` uses, and the *only* one available without a
hypothesis; see this file's module docstring. -/
theorem pow_comap_le_comap_pow {C : Type u} [CommRing C] (K : Ideal A) (φ : C →+* A) (n : ℕ) :
    (K.comap φ) ^ n ≤ (K ^ n).comap φ := by
  rw [← Ideal.map_le_iff_le_comap, Ideal.map_pow]
  exact pow_le_pow_left' Ideal.map_comap_le n

/-- The subring case of `Ideal.pow_comap_le_comap_pow`, which is the one this file uses. -/
theorem pow_comap_subtype_le_comap_pow (K : Ideal A) (S : Subring A) (n : ℕ) :
    (K.comap S.subtype) ^ n ≤ (K ^ n).comap S.subtype :=
  pow_comap_le_comap_pow K S.subtype n

end Ideal

/-- **Hausdorffness pulls back along an injective ring homomorphism.** An element of every power
of `K.comap φ` has image in every power of `K` by `Ideal.pow_comap_le_comap_pow`, so its image
vanishes and injectivity finishes. `AlgebraicGeometry.isHausdorff_comap_subtype`
(`FormalSchemes.TateInvNodeChartAmbient`) is this at `φ = S.subtype`; the form here is what a
transport along a ring isomorphism needs. -/
theorem isHausdorff_comap {A C : Type u} [CommRing A] [CommRing C] (φ : C →+* A) (K : Ideal A)
    (hinj : Function.Injective φ) (hK : IsHausdorff K A) : IsHausdorff (K.comap φ) C where
  haus' x hx := by
    have hval : ∀ n : ℕ, φ x ∈ K ^ n := by
      intro n
      have h1 : x ∈ (K.comap φ) ^ n := by
        have h := hx n
        rwa [SModEq.zero, Ideal.mem_smul_top_self_iff] at h
      exact Ideal.pow_comap_le_comap_pow K φ n h1
    have hzero : φ x = 0 :=
      hK.haus _ fun n => by rw [SModEq.zero, Ideal.mem_smul_top_self_iff]; exact hval n
    exact hinj (hzero.trans (map_zero φ).symm)

namespace Subring

variable {A : Type u} [CommRing A]

/-- **`S` is adically closed in `A`**: an element of `A` approximated to every order by elements
of `S` lies in `S`. This is closedness for the `K`-adic topology, written without a topology. -/
def IsAdicallyClosed (S : Subring A) (K : Ideal A) : Prop :=
  ∀ a : A, (∀ n : ℕ, ∃ s ∈ S, a - s ∈ K ^ n) → a ∈ S

/-- **`S` is complete for the filtration induced from `K`.** The Cauchy condition and the
conclusion are both stated with `K ^ n` in the ambient ring, so no ideal of `S` occurs: this is
the purely topological completeness statement, and it is what closedness actually buys.

`Subring.isPrecomplete_comap_subtype` is what converts it into Mathlib's `IsPrecomplete`, and it
needs `Subring.HasCofinalInducedFiltration` to do so. -/
def IsInducedPrecomplete (S : Subring A) (K : Ideal A) : Prop :=
  ∀ f : ℕ → S, (∀ m n : ℕ, m ≤ n → (f n : A) - (f m : A) ∈ K ^ m) →
    ∃ L : S, ∀ n : ℕ, (L : A) - (f n : A) ∈ K ^ n

/-- **The filtration bridge**: the induced filtration is cofinal with the power filtration of the
contracted ideal. The reverse containment is free
(`Ideal.pow_comap_subtype_le_comap_pow`), so this is exactly the missing half. -/
def HasCofinalInducedFiltration (S : Subring A) (K : Ideal A) : Prop :=
  ∀ n : ℕ, ∃ m : ℕ, (K ^ m).comap S.subtype ≤ (K.comap S.subtype) ^ n

/-- **Membership in the image of a subring under a ring isomorphism** is membership of the
preimage. `Subring.mem_map` produces an existential; over an isomorphism the witness is forced. -/
theorem mem_map_ringEquiv {B : Type u} [CommRing B] (e : A ≃+* B) (T : Subring A) {x : B} :
    x ∈ Subring.map e.toRingHom T ↔ e.symm x ∈ T := by
  constructor
  · rintro ⟨a, ha, rfl⟩
    simpa using ha
  · exact fun h => ⟨e.symm x, h, by simp⟩

/-- **A ring isomorphism carries an intersection of subrings to the intersection of the images.**
-/
theorem map_ringEquiv_inf {B : Type u} [CommRing B] (e : A ≃+* B) (T₁ T₂ : Subring A) :
    Subring.map e.toRingHom (T₁ ⊓ T₂) =
      Subring.map e.toRingHom T₁ ⊓ Subring.map e.toRingHom T₂ := by
  ext x
  simp only [mem_map_ringEquiv, Subring.mem_inf]

/-- **A ring isomorphism carries an equalizer subring to the equalizer of the precomposed maps.**
-/
theorem map_ringEquiv_eqLocus {B C : Type u} [CommRing B] [CommRing C] (e : A ≃+* B)
    (f g : A →+* C) : Subring.map e.toRingHom (f.eqLocus g) =
      (f.comp e.symm.toRingHom).eqLocus (g.comp e.symm.toRingHom) := by
  refine SetLike.ext fun x => ?_
  rw [mem_map_ringEquiv]
  simp only [RingHom.mem_eqLocus, RingHom.coe_comp, Function.comp_apply,
    RingEquiv.toRingHom_eq_coe, RingHom.coe_coe]

/-- **An intersection of two adically closed subrings is adically closed.** -/
theorem IsAdicallyClosed.inf {S T : Subring A} {K : Ideal A} (hS : S.IsAdicallyClosed K)
    (hT : T.IsAdicallyClosed K) : (S ⊓ T).IsAdicallyClosed K := by
  intro a ha
  refine Subring.mem_inf.2 ⟨hS a fun n => ?_, hT a fun n => ?_⟩
  · obtain ⟨s, hs, hsa⟩ := ha n
    exact ⟨s, (Subring.mem_inf.1 hs).1, hsa⟩
  · obtain ⟨s, hs, hsa⟩ := ha n
    exact ⟨s, (Subring.mem_inf.1 hs).2, hsa⟩

/-- **Closedness gives completeness for the induced filtration, unconditionally.** The limit of
the sequence is taken in `A`, where it exists by `IsPrecomplete K A`, and closedness puts it back
in `S`; the estimates `L - f n ∈ K ^ n` are the ones the ambient limit already satisfies, so no
comparison of filtrations occurs. -/
theorem isInducedPrecomplete_of_isAdicallyClosed {S : Subring A} {K : Ideal A}
    [IsPrecomplete K A] (hcl : S.IsAdicallyClosed K) : S.IsInducedPrecomplete K := by
  intro f hf
  have hcauchy : ∀ {m n : ℕ}, m ≤ n →
      (f m : A) ≡ (f n : A) [SMOD (K ^ m • ⊤ : Submodule A A)] := by
    intro m n hmn
    rw [Ideal.smodEq_pow_iff_sub_mem]
    have h := neg_mem (hf m n hmn)
    rwa [neg_sub] at h
  obtain ⟨L, hL⟩ := IsPrecomplete.prec' (I := K) (M := A) (fun n => (f n : A)) hcauchy
  have hL' : ∀ n : ℕ, L - (f n : A) ∈ K ^ n := by
    intro n
    have h := hL n
    rw [Ideal.smodEq_pow_iff_sub_mem] at h
    have h2 := neg_mem h
    rwa [neg_sub] at h2
  exact ⟨⟨L, hcl L fun n => ⟨(f n : A), (f n).2, hL' n⟩⟩, hL'⟩

/-- **Completeness for the induced filtration plus the bridge is Mathlib's `IsPrecomplete`.**
A `K.comap S.subtype`-Cauchy sequence is Cauchy for the induced filtration by the free
containment, so it has an induced-filtration limit `L`; the bridge is what turns the estimate
`L - f m ∈ K ^ m` back into `f n - L ∈ (K.comap S.subtype) ^ n`, after comparing `f n` with
`f (max n m)`. -/
theorem isPrecomplete_comap_subtype {S : Subring A} {K : Ideal A} (hip : S.IsInducedPrecomplete K)
    (hbr : S.HasCofinalInducedFiltration K) : IsPrecomplete (K.comap S.subtype) S where
  prec' f hf := by
    have hfA : ∀ m n : ℕ, m ≤ n → (f n : A) - (f m : A) ∈ K ^ m := by
      intro m n hmn
      have h := hf hmn
      rw [Ideal.smodEq_pow_iff_sub_mem] at h
      have h2 : f n - f m ∈ (K.comap S.subtype) ^ m := by
        have h3 := neg_mem h
        rwa [neg_sub] at h3
      exact Ideal.pow_comap_subtype_le_comap_pow K S m h2
    obtain ⟨L, hL⟩ := hip f hfA
    refine ⟨L, fun n => ?_⟩
    rw [Ideal.smodEq_pow_iff_sub_mem]
    obtain ⟨m, hm⟩ := hbr n
    have hLp : L - f (max n m) ∈ (K.comap S.subtype) ^ n := by
      refine hm ?_
      rw [Ideal.mem_comap]
      exact Ideal.pow_le_pow_right (le_max_right n m) (hL (max n m))
    have hfp : f n - f (max n m) ∈ (K.comap S.subtype) ^ n := by
      have h := hf (le_max_left n m)
      rwa [Ideal.smodEq_pow_iff_sub_mem] at h
    have hsplit : f n - L = (f n - f (max n m)) - (L - f (max n m)) := by ring
    rw [hsplit]
    exact sub_mem hfp hLp

/-- **The adic-completeness statement, with its three inputs named.** The Hausdorff half is a
hypothesis rather than a reproof: `AlgebraicGeometry.isHausdorff_comap_subtype`
(`FormalSchemes.TateInvNodeChartAmbient`) supplies it for any subring of a Hausdorff adic ring. -/
theorem isAdicComplete_comap_subtype {S : Subring A} {K : Ideal A}
    (hh : IsHausdorff (K.comap S.subtype) S) (hip : S.IsInducedPrecomplete K)
    (hbr : S.HasCofinalInducedFiltration K) : IsAdicComplete (K.comap S.subtype) S where
  toIsHausdorff := hh
  toIsPrecomplete := isPrecomplete_comap_subtype hip hbr

/-- **A retraction linear over the subring buys the bridge, with `m = n`.** If `K` is generated by
its contraction — the "generators lie in the subring" hypothesis — and `ρ : A → S` is additive,
fixes `S` and satisfies `ρ (s * a) = s * ρ a`, then `ρ` carries `K ^ n` into
`(K.comap S.subtype) ^ n` and fixes the elements of `S` inside it. -/
theorem hasCofinalInducedFiltration_of_retraction {S : Subring A} {K : Ideal A}
    (hgen : K ≤ (K.comap S.subtype).map S.subtype) (ρ : A →+ S)
    (hmul : ∀ (s : S) (a : A), ρ ((s : A) * a) = s * ρ a) (hid : ∀ s : S, ρ (s : A) = s) :
    S.HasCofinalInducedFiltration K := by
  intro n
  refine ⟨n, fun x hx => ?_⟩
  set J : Ideal S := K.comap S.subtype with hJ
  have hmem : (x : A) ∈ (J ^ n).map S.subtype := by
    have hpow : K ^ n ≤ ((J.map S.subtype)) ^ n := pow_le_pow_left' hgen n
    rw [← Ideal.map_pow] at hpow
    exact hpow (Ideal.mem_comap.1 hx)
  let T : Ideal A :=
    { carrier := {y : A | ∀ a : A, ρ (a * y) ∈ J ^ n}
      zero_mem' := by intro a; simp
      add_mem' := by
        intro y z hy hz a
        rw [mul_add, map_add]
        exact add_mem (hy a) (hz a)
      smul_mem' := by
        intro c y hy a
        rw [smul_eq_mul, ← mul_assoc]
        exact hy (a * c) }
  have hle : (J ^ n).map S.subtype ≤ T := by
    refine Ideal.map_le_iff_le_comap.2 fun j hj => ?_
    intro a
    have hja : ρ (a * S.subtype j) = j * ρ a := by rw [mul_comm]; exact hmul j a
    rw [hja]
    exact Ideal.mul_mem_right _ _ hj
  have hx1 := hle hmem 1
  rwa [one_mul, hid] at hx1

/-- **Saturation for a single generator buys the bridge, with `m = n`.** If `K` is principal on a
`c ∈ S` and every `a : A` with `c * a ∈ S` already lies in `S`, then an element of `S` divisible
by `c ^ n` in `A` is `c ^ n` times an element of `S`. -/
theorem hasCofinalInducedFiltration_span_singleton {S : Subring A} {c : A} (hc : c ∈ S)
    (hsat : ∀ a : A, c * a ∈ S → a ∈ S) : S.HasCofinalInducedFiltration (Ideal.span {c}) := by
  have hpow : ∀ (n : ℕ) (a : A), c ^ n * a ∈ S → a ∈ S := by
    intro n
    induction n with
    | zero => intro a ha; simpa using ha
    | succ k ih =>
      intro a ha
      refine hsat a (ih (c * a) ?_)
      rwa [← mul_assoc, ← pow_succ]
  intro n
  refine ⟨n, fun x hx => ?_⟩
  rw [Ideal.mem_comap, Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hx
  obtain ⟨a, ha⟩ := hx
  have haS : a ∈ S := hpow n a (by rw [← ha]; exact x.2)
  have hcJ : (⟨c, hc⟩ : S) ∈ (Ideal.span {c}).comap S.subtype := by
    rw [Ideal.mem_comap]
    exact Ideal.mem_span_singleton_self c
  have hxeq : x = (⟨c, hc⟩ : S) ^ n * ⟨a, haS⟩ := Subtype.ext (by simpa using ha)
  rw [hxeq]
  exact Ideal.mul_mem_right _ _ (Ideal.pow_mem_pow hcJ n)

end Subring

namespace RingHom

variable {A B : Type u} [CommRing A] [CommRing B]

/-- **An equalizer subring is saturated for multiplication by an element with left-regular
image.** If `c` lies in the equalizer and `f c` is left-regular in `B`, then `c * a` lying in the
equalizer forces `a` to. This is the source of the hypothesis of
`Subring.hasCofinalInducedFiltration_span_singleton` in the cases the tree meets. -/
theorem mem_eqLocus_of_mul_mem {f g : A →+* B} {c : A} (hc : c ∈ f.eqLocus g)
    (hreg : IsLeftRegular (f c)) {a : A} (hca : c * a ∈ f.eqLocus g) : a ∈ f.eqLocus g := by
  refine RingHom.mem_eqLocus.2 (hreg ?_)
  have h := RingHom.mem_eqLocus.1 hca
  rw [map_mul, map_mul, ← RingHom.mem_eqLocus.1 hc] at h
  exact h

/-- **The equalizer of two adically continuous maps into a Hausdorff target is adically closed.**
"Continuous" is the `RingHom`-level condition `v ∈ J ^ m → f v ∈ K ^ m`, the same spelling
`AlgebraicGeometry.eq_zero_of_forall_sub_ker_mem_pow`
(`FormalSchemes.TateInvSeparatingKerClosed`) uses. From `f a - g a = (f a - f s) - (g a - g s)`
and `f s = g s`, the difference lies in every `K ^ m`, so `IsHausdorff.haus` kills it. -/
theorem mem_eqLocus_of_forall_sub_mem_pow {J : Ideal A} {K : Ideal B} {f g : A →+* B}
    (hf : ∀ (m : ℕ) {v : A}, v ∈ J ^ m → f v ∈ K ^ m)
    (hg : ∀ (m : ℕ) {v : A}, v ∈ J ^ m → g v ∈ K ^ m) (hK : IsHausdorff K B) {a : A}
    (ha : ∀ m : ℕ, ∃ s ∈ f.eqLocus g, a - s ∈ J ^ m) : a ∈ f.eqLocus g := by
  have hzero : f a - g a = 0 := by
    refine hK.haus _ fun m => ?_
    rw [SModEq.zero, Ideal.mem_smul_top_self_iff]
    obtain ⟨s, hs, hsa⟩ := ha m
    have h1 : f a - f s ∈ K ^ m := by rw [← map_sub]; exact hf m hsa
    have h2 : g a - g s ∈ K ^ m := by rw [← map_sub]; exact hg m hsa
    have hdecomp : f a - g a = (f a - f s) - (g a - g s) := by
      rw [RingHom.mem_eqLocus.1 hs]; ring
    rw [hdecomp]
    exact sub_mem h1 h2
  exact RingHom.mem_eqLocus.2 (sub_eq_zero.1 hzero)

/-- **`Subring.IsAdicallyClosed` for an equalizer**, the packaged form of
`RingHom.mem_eqLocus_of_forall_sub_mem_pow`. -/
theorem isAdicallyClosed_eqLocus {J : Ideal A} {K : Ideal B} {f g : A →+* B}
    (hf : ∀ (m : ℕ) {v : A}, v ∈ J ^ m → f v ∈ K ^ m)
    (hg : ∀ (m : ℕ) {v : A}, v ∈ J ^ m → g v ∈ K ^ m) (hK : IsHausdorff K B) :
    (f.eqLocus g).IsAdicallyClosed J :=
  fun _ ha => mem_eqLocus_of_forall_sub_mem_pow hf hg hK ha

/-- **An intersection of two such equalizers is adically closed**, with the two targets allowed
to be different rings. This is the shape `AlgebraicGeometry.tateInvChartAnnulusSubring`
(`FormalSchemes.TateInvChartAnnulusRing`) has. -/
theorem isAdicallyClosed_inf_eqLocus {B₁ B₂ : Type u} [CommRing B₁] [CommRing B₂] {J : Ideal A}
    {K₁ : Ideal B₁} {K₂ : Ideal B₂} {f₁ g₁ : A →+* B₁} {f₂ g₂ : A →+* B₂}
    (hf₁ : ∀ (m : ℕ) {v : A}, v ∈ J ^ m → f₁ v ∈ K₁ ^ m)
    (hg₁ : ∀ (m : ℕ) {v : A}, v ∈ J ^ m → g₁ v ∈ K₁ ^ m)
    (hf₂ : ∀ (m : ℕ) {v : A}, v ∈ J ^ m → f₂ v ∈ K₂ ^ m)
    (hg₂ : ∀ (m : ℕ) {v : A}, v ∈ J ^ m → g₂ v ∈ K₂ ^ m) (hK₁ : IsHausdorff K₁ B₁)
    (hK₂ : IsHausdorff K₂ B₂) : (f₁.eqLocus g₁ ⊓ f₂.eqLocus g₂).IsAdicallyClosed J :=
  (isAdicallyClosed_eqLocus hf₁ hg₁ hK₁).inf (isAdicallyClosed_eqLocus hf₂ hg₂ hK₂)

end RingHom
