import FormalSchemes.SpfMap
import FormalSchemes.AdicQuotient
import Mathlib.RingTheory.Spectrum.Prime.RingHom

set_option linter.style.header false

/-!
# Adic morphisms of formal spectra, and closed formal subschemes

A morphism of formal spectra is **adic** if the ideal of definition of the source is generated
by (the image of) the ideal of definition of the target: `J = I·S` (EGA I, 10.12). Adic
morphisms are the ones along which the tower of thickenings is preserved level by level, and
they are the morphisms one restricts to when doing relative formal geometry.

This file gives the affine notion on ring homomorphisms, its stability properties, and the
first examples:

* the identity is adic, and adic morphisms compose (`IsAdicHom.id`, `IsAdicHom.comp`);
* the quotient of an adic ring by an adically closed ideal is adic over it
  (`IsAdicHom.of_map`), which is the affine model of a **closed formal subscheme**
  (EGA I, 10.14): `Spf (R ⧸ a) ⟶ Spf R`.

## Main definitions

* `IsAdicHom I J φ`: the ring homomorphism `φ : R →+* S` carries the ideal of definition `I`
  onto a generating set of `J`, i.e. `I.map φ = J`.
* `IsAdicHom.spfMap`: the induced morphism of locally ringed spaces `Spf S ⟶ Spf R`.
* `closedFormalSubscheme`: the closed formal subscheme `Spf (R ⧸ a) ⟶ Spf R` attached to an
  adically closed ideal `a` of an adic ring.
* `closedSubschemeBase`: its underlying continuous map, and `range_closedSubschemeBase` /
  `isClosedEmbedding_closedSubschemeBase`: this map is a closed topological embedding whose range
  is the vanishing locus `V(ā)` of the image of `a` in `R ⧸ I` — the topological half of the
  statement that a closed formal subscheme is a closed immersion.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.12, §10.14.
-/

noncomputable section

open Ideal AlgebraicGeometry Topology

universe u

variable {R S T : Type u} [CommRing R] [CommRing S] [CommRing T]

/-- A ring homomorphism between adic rings is **adic** if the ideal of definition of the target
is generated by the image of the ideal of definition of the source. -/
def IsAdicHom (I : Ideal R) (J : Ideal S) (φ : R →+* S) : Prop :=
  I.map φ = J

namespace IsAdicHom

variable {I : Ideal R} {J : Ideal S} {K : Ideal T} {φ : R →+* S} {ψ : S →+* T}

/-- An adic homomorphism carries the ideal of definition into that of the target, hence induces
a morphism of formal spectra. -/
theorem le_comap (h : IsAdicHom I J φ) : I ≤ J.comap φ :=
  Ideal.map_le_iff_le_comap.mp h.le

theorem id (I : Ideal R) : IsAdicHom I I (RingHom.id R) :=
  Ideal.map_id I

theorem comp (h₁ : IsAdicHom I J φ) (h₂ : IsAdicHom J K ψ) : IsAdicHom I K (ψ.comp φ) := by
  rw [IsAdicHom, ← Ideal.map_map, h₁, h₂]

/-- The morphism of locally ringed spaces `Spf S ⟶ Spf R` induced by an adic homomorphism. -/
def spfMap [TopologicalSpace R] [IsAdicRing I] [TopologicalSpace S] [IsAdicRing J]
    (h : IsAdicHom I J φ) :
    FormalSpectrum.locallyRingedSpaceObj J ⟶ FormalSpectrum.locallyRingedSpaceObj I :=
  FormalSpectrum.locallyRingedSpaceMap I J φ h.le_comap

/-- An algebra whose ideal of definition is the extension of that of the base is adic over it.
This covers the closed formal subschemes: the quotient of an adic ring by an adically closed
ideal, with the image filtration. -/
theorem of_map (I : Ideal R) {A : Type u} [CommRing A] [Algebra R A] :
    IsAdicHom I (I.map (algebraMap R A)) (algebraMap R A) :=
  rfl

end IsAdicHom

/-!
### Closed formal subschemes
-/

section ClosedSubscheme

variable (I : Ideal R) [TopologicalSpace R] [IsAdicRing I] (a : Ideal R)

/-- The quotient `R ⧸ a` of an adic ring by an adically closed ideal, with the image of the
ideal of definition, is an adic ring — the affine model of a closed formal subscheme. -/
theorem isAdicRing_quotient (ha : (Ideal.Quotient.mk a).AdicKerClosed I) :
    letI : TopologicalSpace (R ⧸ a) := (I.map (Ideal.Quotient.mk a)).adicTopology
    IsAdicRing (I.map (Ideal.Quotient.mk a)) := by
  letI : Algebra R (R ⧸ a) := (Ideal.Quotient.mk a).toAlgebra
  haveI : IsAdicComplete I R := ‹IsAdicRing I›.toIsAdicComplete
  exact IsAdicRing.of_surjective_of_kerClosed I Ideal.Quotient.mk_surjective ha

/-- The **closed formal subscheme** `Spf (R ⧸ a) ⟶ Spf R` attached to an adically closed ideal
`a` of an adic ring `R` (EGA I, 10.14): the morphism of locally ringed spaces induced by the
quotient map, which is adic. -/
def closedFormalSubscheme (ha : (Ideal.Quotient.mk a).AdicKerClosed I) :
    letI : TopologicalSpace (R ⧸ a) := (I.map (Ideal.Quotient.mk a)).adicTopology
    letI := isAdicRing_quotient I a ha
    FormalSpectrum.locallyRingedSpaceObj (I.map (Ideal.Quotient.mk a)) ⟶
      FormalSpectrum.locallyRingedSpaceObj I :=
  letI : TopologicalSpace (R ⧸ a) := (I.map (Ideal.Quotient.mk a)).adicTopology
  letI := isAdicRing_quotient I a ha
  FormalSpectrum.locallyRingedSpaceMap I (I.map (Ideal.Quotient.mk a)) (Ideal.Quotient.mk a)
    (Ideal.map_le_iff_le_comap.mp le_rfl)

/-!
#### The underlying closed embedding

The topological content of EGA I 10.14: the underlying map of a closed formal subscheme is a
closed embedding onto the vanishing locus of the ideal cut out by `a`. This is the `base_closed`
half of the eventual `IsClosedImmersion` statement — the closed-subscheme analogue of the open
embedding `FormalSpectrum.isOpenEmbedding_basicOpenChartBase` of the basic-open chart. Since the
inducing ring map `R ⧸ I → (R ⧸ a) ⧸ (I·(R ⧸ a))` is a quotient (hence surjective) map, no
`I.FG` hypothesis is needed here, unlike the open case.
-/

/-- The **underlying continuous map** `Spf (R ⧸ a) → Spf R` of the closed formal subscheme
`closedFormalSubscheme`, induced by the quotient map `R → R ⧸ a` via `FormalSpectrum.map`. -/
def closedSubschemeBase :
    FormalSpectrum (I.map (Ideal.Quotient.mk a)) → FormalSpectrum I :=
  FormalSpectrum.map I (I.map (Ideal.Quotient.mk a)) (Ideal.Quotient.mk a) Ideal.le_comap_map

omit [TopologicalSpace R] [IsAdicRing I] in
/-- The **range** of the base map of a closed formal subscheme is the vanishing locus `V(ā)` of the
image `ā = a·(R ⧸ I)` of `a` in the level-`0` thickening `R ⧸ I`: the closed formal subscheme is
supported on the closed subset cut out by `a` (EGA I, 10.14). -/
theorem range_closedSubschemeBase :
    Set.range (closedSubschemeBase I a) =
      (PrimeSpectrum.zeroLocus (a.map (Ideal.Quotient.mk I)) : Set (FormalSpectrum I)) := by
  change Set.range (PrimeSpectrum.comap
      (Ideal.quotientMap (I.map (Ideal.Quotient.mk a)) (Ideal.Quotient.mk a)
        Ideal.le_comap_map)) = _
  rw [range_comap_of_surjective _ _
      (Ideal.quotientMap_surjective Ideal.Quotient.mk_surjective),
    Ideal.ker_quotientMap_mk]

omit [TopologicalSpace R] [IsAdicRing I] in
/-- The base map of a closed formal subscheme is a **closed topological embedding** (EGA I, 10.14):
`Spf (R ⧸ a)` maps homeomorphically onto the closed subset `V(ā) ⊆ Spf R`. This is the topological
`base_closed` half of the statement that `closedFormalSubscheme` is a closed immersion. -/
theorem isClosedEmbedding_closedSubschemeBase :
    IsClosedEmbedding (closedSubschemeBase I a) := by
  change IsClosedEmbedding (PrimeSpectrum.comap
    (Ideal.quotientMap (I.map (Ideal.Quotient.mk a)) (Ideal.Quotient.mk a) Ideal.le_comap_map))
  exact PrimeSpectrum.isClosedEmbedding_comap_of_surjective _ _
    (Ideal.quotientMap_surjective Ideal.Quotient.mk_surjective)

end ClosedSubscheme
