import FormalSchemes.AdicSubringComplete
import Mathlib.RingTheory.Filtration

set_option linter.style.header false

/-!
# The filtration bridge at a module-finite subring, for an arbitrary ideal

`FormalSchemes.AdicSubringComplete` reduces adic completeness of a subring `S ⊆ A` for the
contracted ideal `K.comap S.subtype` to `Subring.HasCofinalInducedFiltration`, and proves that
bridge under either of two hypotheses: an `S`-linear retraction `A → S`, or `K` principal on a
`c ∈ S` for which `S` is saturated under multiplication by `c`
(`Subring.hasCofinalInducedFiltration_span_singleton`, the one
`FormalSchemes.AdicSubringPrincipal` and the whole Tate node-chart cluster run on).

**Both of those hypotheses constrain `K`.** The retraction criterion needs `K` generated by
`K ∩ S`, and the saturation criterion needs `K` *principal*; the saturation argument is
`a ∈ S ∩ (cᵐ) ⟹ a = cᵐ·b ⟹ b ∈ S`, and it does not survive several generators, because
`a ∈ S ∩ Kᵐ` is then a **sum** of monomials in the generators and the sum does not split. This
file supplies a third sufficient condition which constrains `K` only by "generated by `K ∩ S`" —
in particular it is **not** a principality hypothesis, and it is the classical reason the bridge
holds.

## The criterion

Write `J := K.comap S.subtype` for the contracted ideal and view `A` as an `S`-module. If `K` is
generated by `J` — that is, `K = J·A` — then `Kᵐ = Jᵐ·A`, and the bridge is exactly the statement
that the `J`-adic topology of `S` is the topology induced from the `K`-adic topology of `A`. For a
Noetherian `S` over which `A` is module-finite that is the **Artin–Rees lemma**
(`Ideal.exists_pow_inf_eq_pow_smul`) applied to the submodule `S ⊆ A`: it produces one `k` with
`Jⁿ⁺ᵏ·A ∩ S ≤ Jⁿ`, uniformly in `n`, so the bridge holds with `m = n + k`.

Unlike the two existing criteria this one does **not** give `m = n`: the `k` is the Artin–Rees
constant of the pair `(S ⊆ A, J)` and there is no reason for it to vanish. Both criteria already
on the tree give `m = n`, so this is the first statement here that uses the unquantified `∃ m` of
`Subring.HasCofinalInducedFiltration` rather than merely tolerating it.

## Main results

* `Subring.hasCofinalInducedFiltration_of_module_finite` — **the bridge, for an arbitrary ideal
  generated by its contraction**, when `S` is Noetherian and `A` is a finite `S`-module.
* `Subring.isAdicComplete_comap_of_module_finite` — the two assembled with the Hausdorff and
  closedness halves, the module-finite analogue of
  `Subring.isAdicComplete_comap_span_singleton_inf_eqLocus`.

The *other* obligation of that assembly's consumers — finite generation of the contracted ideal,
which `Subring.fg_comap_span_singleton` (`FormalSchemes.AdicSubringPrincipal`) has to buy with
the saturation hypothesis — is `IsNoetherian.noetherian` under this criterion's Noetherian
hypothesis, so it gets no statement of its own here.

## The witness, and why it is not covered by either existing criterion

`Subring.cuspSubring R`, the subring `R[X², X³]` of `R[X]`, is the witness, at the two-generator
ideal `K = (X², r)` for an arbitrary `r : R`:

* `Subring.hasCofinalInducedFiltration_cuspSubring` — the criterion applies.
* `Subring.not_saturated_cuspSubring` — **saturation fails at `c = X²`**: `X²·X = X³ ∈ S` while
  `X ∉ S`. So `Subring.hasCofinalInducedFiltration_span_singleton` is unavailable at this subring
  already for the principal ideal `(X²)`, let alone at the two-generator `K`.
* `Subring.not_exists_retraction_cuspSubring` — **no retraction linear over `S` exists**: such a
  `ρ` would satisfy `X²·ρ X = ρ (X³) = X³`, forcing `(ρ X).coeff 1 = 1`, while every element of
  `S` has vanishing `X`-coefficient. So `Subring.hasCofinalInducedFiltration_of_retraction` is
  unavailable too, with the exact hypotheses it is stated with.

So the criterion below is **not subsumed** by either of the two already on the tree: here is one
explicit `(A, K, S)` at which it applies and neither of them can be stated. The converse
non-subsumptions are not proved — nothing here exhibits an `(A, K, S)` where an existing
criterion applies and this one does not.

## What is *not* proved

* **No unconditional multi-generator statement.** Whether the saturation criterion generalises to
  a finitely generated `K` — `S ∩ c_i·A = c_i·S` for each generator, no Noetherian and no
  finiteness hypothesis — is **open**, and nothing here settles it in either direction. What is
  recorded above is only where the one-generator proof breaks.
* **Nothing here is claimed about the Tate node chart.** The consumer of the principal criterion
  is `AlgebraicGeometry.isAdicComplete_tateInvNodeChartAwayIdeal_of_principal'`
  (`FormalSchemes.TateInvNodeChartBaseGenerator`), whose subring is an intersection of two
  equalizers. Feeding it the criterion below needs three inputs that are not on this tree:
  `IsNoetherianRing` of that intersection, `Module.Finite` of the away-completion algebra over it,
  and `K ≤ (K.comap S.subtype).map S.subtype` for the ideal in play. The criterion is stated for
  an arbitrary subring precisely so that what is missing is a list of named hypotheses rather
  than a rewrite.
* No `(A, K, S)` at which `Subring.HasCofinalInducedFiltration` **fails** is exhibited here, so
  none of the three criteria is shown necessary.

## References

* [Atiyah–Macdonald, *Introduction to Commutative Algebra*][atiyah-macdonald], Ch. 10 — the
  Artin–Rees lemma (10.9) and the topology it compares (10.10, 10.15).
-/

universe u

namespace Subring

variable {A : Type u} [CommRing A]

/-!
### `J • ⊤` as an ideal of the ambient ring

Artin–Rees is stated for `S`-submodules of `A`, while the bridge is stated for ideals of `A`. The
two sides meet at `J • (⊤ : Submodule ↥S A)`, which is *both*: it is the `S`-submodule Artin–Rees
filters by, and it is the `A`-ideal generated by the image of `J`, because `⊤` absorbs
multiplication by `A`.
-/

/-- **`J • ⊤` is an ideal of `A`, not merely an `S`-submodule.** Multiplication by `a : A` moves
inside the right-hand factor of `j • x`, which `⊤` absorbs. -/
def smulTopIdeal (S : Subring A) (J : Ideal ↥S) : Ideal A where
  carrier := (J • (⊤ : Submodule ↥S A) : Submodule ↥S A)
  zero_mem' := zero_mem _
  add_mem' := fun ha hb => add_mem ha hb
  smul_mem' := by
    intro c y hy
    refine Submodule.smul_induction_on hy (fun j hj a _ => ?_) (fun y z hy hz => ?_)
    · have hcomm : c • ((j : A) * a) = (j : A) * (c * a) := by
        simp only [smul_eq_mul]; ring
      rw [show ((j : ↥S) • a) = (j : A) * a from rfl, hcomm]
      exact Submodule.smul_mem_smul hj Submodule.mem_top
    · rw [smul_eq_mul, mul_add]
      exact add_mem hy hz

/-- **The ideal generated by the image of `J` lands in `J • ⊤`**: a generator `j` is `j • 1`. -/
theorem map_le_smulTopIdeal (S : Subring A) (J : Ideal ↥S) :
    J.map S.subtype ≤ S.smulTopIdeal J := by
  refine Ideal.map_le_iff_le_comap.2 fun j hj => ?_
  change (j : A) ∈ (J • (⊤ : Submodule ↥S A) : Submodule ↥S A)
  have hj1 : (j : A) = j • (1 : A) := by change (j : A) = (j : A) * 1; rw [mul_one]
  rw [hj1]
  exact Submodule.smul_mem_smul hj Submodule.mem_top

/-- **…and `J • 1` contracts back to `J`.** `(1 : Submodule ↥S A)` is the image of `S`, so
`J • 1` is the image of `J`, and `Subring.subtype` is injective. -/
theorem mem_of_mem_smul_one (S : Subring A) (J : Ideal ↥S) (x : ↥S)
    (hx : (x : A) ∈ (J • (1 : Submodule ↥S A) : Submodule ↥S A)) : x ∈ J := by
  have hle : (J • (1 : Submodule ↥S A) : Submodule ↥S A) ≤
      Submodule.map (Algebra.linearMap ↥S A) J := by
    refine Submodule.smul_le.2 fun j hj y hy => ?_
    obtain ⟨s, rfl⟩ := Submodule.mem_one.1 hy
    exact ⟨j * s, Ideal.mul_mem_right _ _ hj, by simp [Algebra.smul_def]⟩
  obtain ⟨y, hy, hyx⟩ := hle hx
  exact (Subtype.ext hyx : y = x) ▸ hy

/-!
### The criterion
-/

/-- **Artin–Rees buys the bridge, for an arbitrary ideal generated by its contraction.** With
`J = K.comap S.subtype`, the hypothesis of this theorem says `K = J·A`, hence `Kᵐ = Jᵐ·A`;
Artin–Rees for the `S`-submodule `S ⊆ A` of the finite `S`-module `A` produces a single `k` with
`Jⁿ⁺ᵏ·A ∩ S ≤ Jⁿ` for every `n`, which is the bridge at `m = n + k`.

Neither hypothesis on `K` present in the two criteria of `FormalSchemes.AdicSubringComplete` is
used: `K` is arbitrary apart from being generated by its contraction, and in particular **not
principal**. What is used instead is Noetherian-ness of `S` and module-finiteness of `A` over it
— see the module docstring for a witness at which this criterion applies and neither of the other
two does. -/
theorem hasCofinalInducedFiltration_of_module_finite {S : Subring A} {K : Ideal A}
    [IsNoetherianRing ↥S] [Module.Finite ↥S A]
    (hgen : K ≤ (K.comap S.subtype).map S.subtype) :
    S.HasCofinalInducedFiltration K := by
  set J : Ideal ↥S := K.comap S.subtype with hJ
  obtain ⟨k, hk⟩ := Ideal.exists_pow_inf_eq_pow_smul J (1 : Submodule ↥S A)
  intro n
  refine ⟨n + k, fun x hx => ?_⟩
  have hmap : (x : A) ∈ (J ^ (n + k)).map S.subtype := by
    have hpow : K ^ (n + k) ≤ (J.map S.subtype) ^ (n + k) := pow_le_pow_left' hgen _
    rw [← Ideal.map_pow] at hpow
    exact hpow hx
  have hinf : (x : A) ∈
      (J ^ (n + k) • (⊤ : Submodule ↥S A) ⊓ (1 : Submodule ↥S A) : Submodule ↥S A) :=
    ⟨S.map_le_smulTopIdeal _ hmap, Submodule.mem_one.2 ⟨x, rfl⟩⟩
  rw [hk (n + k) (Nat.le_add_left k n), Nat.add_sub_cancel] at hinf
  have hmono : (J ^ n • (J ^ k • (⊤ : Submodule ↥S A) ⊓ (1 : Submodule ↥S A)) :
      Submodule ↥S A) ≤ (J ^ n • (1 : Submodule ↥S A) : Submodule ↥S A) :=
    smul_mono_right _ inf_le_right
  exact S.mem_of_mem_smul_one _ x (hmono hinf)

/-- **Adic completeness of the contracted ideal at a module-finite subring.** The three inputs of
`Subring.isAdicComplete_comap_subtype`, with the bridge supplied by
`Subring.hasCofinalInducedFiltration_of_module_finite`. This is the module-finite analogue of
`Subring.isAdicComplete_comap_span_singleton_inf_eqLocus`
(`FormalSchemes.AdicSubringPrincipal`), and it carries no hypothesis on the shape of `K`. -/
theorem isAdicComplete_comap_of_module_finite {S : Subring A} {K : Ideal A}
    [IsNoetherianRing ↥S] [Module.Finite ↥S A] [IsPrecomplete K A]
    (hgen : K ≤ (K.comap S.subtype).map S.subtype)
    (hh : IsHausdorff (K.comap S.subtype) ↥S) (hcl : S.IsAdicallyClosed K) :
    IsAdicComplete (K.comap S.subtype) ↥S :=
  isAdicComplete_comap_subtype hh (isInducedPrecomplete_of_isAdicallyClosed hcl)
    (hasCofinalInducedFiltration_of_module_finite hgen)

end Subring

/-!
## The witness: `R[X², X³] ⊆ R[X]`

The cusp subring is the standard example of a module-finite subring that is neither saturated for
a generator of the ambient ideal nor a linear retract of the ambient ring, so it separates the new
criterion from both existing ones. Everything below is stated at an arbitrary Noetherian `R`, and
the ideal is `(X², r)` for an arbitrary `r : R` — a two-generator ideal, which is the point:
`Subring.hasCofinalInducedFiltration_span_singleton` cannot be stated at it at all.
-/

namespace Subring

open Polynomial

variable (R : Type u) [CommRing R]

/-- **The `X`-coefficient-zero subalgebra of `R[X]`**, an upper bound for `R[X², X³]` used only to
show `X` is outside it. It is a subalgebra because `(f·g).coeff 1 = f₀·g₁ + f₁·g₀`. -/
def coeffOneZeroSubalgebra : Subalgebra R R[X] where
  carrier := {f : R[X] | f.coeff 1 = 0}
  mul_mem' := by
    intro f g hf hg
    simp only [Set.mem_setOf_eq] at hf hg ⊢
    simp [Polynomial.coeff_mul, Finset.Nat.antidiagonal_succ, hf, hg]
  add_mem' := by
    intro f g hf hg
    simp only [Set.mem_setOf_eq] at hf hg ⊢
    simp [hf, hg]
  algebraMap_mem' := by
    intro r
    simp only [Set.mem_setOf_eq, Polynomial.algebraMap_eq]
    simp

/-- **The cusp subring `R[X², X³] ⊆ R[X]`.** -/
noncomputable def cuspSubring : Subring R[X] :=
  (Algebra.adjoin R ({X ^ 2, X ^ 3} : Set R[X])).toSubring

variable {R}

theorem sq_mem_cuspSubring : (X : R[X]) ^ 2 ∈ cuspSubring R :=
  Algebra.subset_adjoin (by simp)

theorem cube_mem_cuspSubring : (X : R[X]) ^ 3 ∈ cuspSubring R :=
  Algebra.subset_adjoin (by simp)

theorem C_mem_cuspSubring (r : R) : (C r : R[X]) ∈ cuspSubring R :=
  Subalgebra.algebraMap_mem _ r

/-- **Every element of the cusp subring has vanishing `X`-coefficient.** -/
theorem coeff_one_eq_zero_of_mem_cuspSubring {f : R[X]} (hf : f ∈ cuspSubring R) :
    f.coeff 1 = 0 := by
  have hle : Algebra.adjoin R ({X ^ 2, X ^ 3} : Set R[X]) ≤ coeffOneZeroSubalgebra R := by
    refine Algebra.adjoin_le ?_
    rintro g (rfl | rfl) <;> simp [coeffOneZeroSubalgebra, Polynomial.coeff_X_pow]
  exact hle hf

variable (R) in
/-- **`X` is not in the cusp subring.** -/
theorem X_not_mem_cuspSubring [Nontrivial R] : (X : R[X]) ∉ cuspSubring R := by
  intro hX
  have := coeff_one_eq_zero_of_mem_cuspSubring hX
  simp at this

variable (R) in
/-- **`R[X]` is generated by `1` and `X` over the cusp subring**, so it is module-finite over it:
`Xⁿ⁺²  = X²·Xⁿ` and `X²` lies in the subring. -/
instance module_finite_cuspSubring : Module.Finite ↥(cuspSubring R) R[X] := by
  classical
  refine ⟨⟨{1, X}, ?_⟩⟩
  have hXpow : ∀ n : ℕ, (X : R[X]) ^ n ∈
      Submodule.span ↥(cuspSubring R) (({1, X} : Finset R[X]) : Set R[X]) := by
    intro n
    induction n using Nat.strong_induction_on with
    | _ n ih =>
      match n with
      | 0 => exact Submodule.subset_span (by simp)
      | 1 => exact Submodule.subset_span (by simp)
      | (m + 2) =>
        have hstep : (X : R[X]) ^ (m + 2) =
            (⟨X ^ 2, sq_mem_cuspSubring⟩ : ↥(cuspSubring R)) • (X : R[X]) ^ m := by
          change (X : R[X]) ^ (m + 2) = (X : R[X]) ^ 2 * (X : R[X]) ^ m
          ring
        rw [hstep]
        exact Submodule.smul_mem _ _ (ih m (by omega))
  refine top_le_iff.mp fun f _ => ?_
  induction f using Polynomial.induction_on' with
  | add p q hp hq => exact add_mem (hp trivial) (hq trivial)
  | monomial n a =>
    have hmon : (monomial n a : R[X]) =
        (⟨C a, C_mem_cuspSubring a⟩ : ↥(cuspSubring R)) • (X : R[X]) ^ n := by
      change (monomial n a : R[X]) = C a * X ^ n
      rw [Polynomial.C_mul_X_pow_eq_monomial]
    rw [hmon]
    exact Submodule.smul_mem _ _ (hXpow n)

variable (R) in
instance isNoetherianRing_cuspSubring [IsNoetherianRing R] :
    IsNoetherianRing ↥(cuspSubring R) := by
  haveI : Algebra.FiniteType R ↥(Algebra.adjoin R ({X ^ 2, X ^ 3} : Set R[X])) :=
    Algebra.FiniteType.adjoin_of_finite (Set.toFinite _)
  have h : IsNoetherianRing ↥(Algebra.adjoin R ({X ^ 2, X ^ 3} : Set R[X])) :=
    Algebra.FiniteType.isNoetherianRing R ↥(Algebra.adjoin R ({X ^ 2, X ^ 3} : Set R[X]))
  exact h

/-- **The criterion applies to the cusp subring at the two-generator ideal `(X², r)`.** -/
theorem hasCofinalInducedFiltration_cuspSubring [IsNoetherianRing R] (r : R) :
    (cuspSubring R).HasCofinalInducedFiltration
      (Ideal.span ({X ^ 2, C r} : Set R[X])) := by
  refine hasCofinalInducedFiltration_of_module_finite (Ideal.span_le.2 ?_)
  rintro g (rfl | rfl)
  · exact Ideal.mem_map_of_mem (cuspSubring R).subtype
      (Ideal.mem_comap.2 (Ideal.subset_span (by simp)) :
        (⟨X ^ 2, sq_mem_cuspSubring⟩ : ↥(cuspSubring R)) ∈ _)
  · exact Ideal.mem_map_of_mem (cuspSubring R).subtype
      (Ideal.mem_comap.2 (Ideal.subset_span (by simp)) :
        (⟨C r, C_mem_cuspSubring r⟩ : ↥(cuspSubring R)) ∈ _)

/-- **The saturation hypothesis fails at the cusp subring**, already for the single generator
`X²`: `X²·X = X³` lies in the subring and `X` does not. So
`Subring.hasCofinalInducedFiltration_span_singleton` is unavailable here. -/
theorem not_saturated_cuspSubring [Nontrivial R] :
    ¬ ∀ a : R[X], (X : R[X]) ^ 2 * a ∈ cuspSubring R → a ∈ cuspSubring R := by
  intro hsat
  exact X_not_mem_cuspSubring R
    (hsat X (by rw [show (X : R[X]) ^ 2 * X = X ^ 3 by ring]; exact cube_mem_cuspSubring))

/-- **No retraction linear over the cusp subring exists**, so
`Subring.hasCofinalInducedFiltration_of_retraction` is unavailable here too. Such a `ρ` would give
`X² · ρ X = ρ (X³) = X³` in the subring, hence `(ρ X).coeff 1 = 1`, contradicting
`Subring.coeff_one_eq_zero_of_mem_cuspSubring`. -/
theorem not_exists_retraction_cuspSubring [Nontrivial R] :
    ¬ ∃ ρ : R[X] →+ ↥(cuspSubring R),
      (∀ (s : ↥(cuspSubring R)) (a : R[X]), ρ ((s : R[X]) * a) = s * ρ a) ∧
        ∀ s : ↥(cuspSubring R), ρ (s : R[X]) = s := by
  rintro ⟨ρ, hmul, hid⟩
  set g : R[X] := (ρ X : R[X]) with hg
  have hcube : (X : R[X]) ^ 2 * g = X ^ 3 := by
    have h1 := hmul ⟨X ^ 2, sq_mem_cuspSubring⟩ X
    have h2 : ((X : R[X]) ^ 2 : R[X]) * X = ((⟨X ^ 3, cube_mem_cuspSubring⟩ :
        ↥(cuspSubring R)) : R[X]) := by
      change (X : R[X]) ^ 2 * X = X ^ 3
      ring
    rw [h2, hid] at h1
    have := congrArg (fun s : ↥(cuspSubring R) => (s : R[X])) h1
    simpa [hg, mul_comm] using this.symm
  have hcoeff : g.coeff 1 = 1 := by
    have hc : ((X : R[X]) ^ 2 * g).coeff (1 + 2) = g.coeff 1 := Polynomial.coeff_X_pow_mul g 2 1
    rw [hcube] at hc
    simpa [Polynomial.coeff_X_pow] using hc.symm
  have hzero : g.coeff 1 = 0 := coeff_one_eq_zero_of_mem_cuspSubring (ρ X).2
  rw [hcoeff] at hzero
  exact one_ne_zero hzero

end Subring
