import FormalSchemes.TateTransition
import FormalSchemes.CompletionToSpec

set_option linter.style.header false

/-!
# The special fibre of the Tate annulus, and evaluation of the annulus at a discrete point

Fix an adic base `(R, I)` and a Tate parameter `q ∈ R`, and let `A = R{x, y}/(x·y − q)` be the
coordinate ring of the formal Tate annulus (`FormalSchemes.TateAnnulus`). Its **special fibre** is
`A ⧸ I·A`, the ring whose prime spectrum is the underlying space of `Spf A`
(`FormalSchemes.FormalSpectrum`).

`FormalSchemes.AnnulusNontrivial` builds one map out of `A` killing `I`: the augmentation
`A → R ⧸ I` at `x = y = 0`. This file generalises that construction and adds the finiteness fact
that makes it useful.

## What is here

* `AlgebraicGeometry.annulusEvalHom`: evaluation `A →+* S` at any point `s : Fin 2 → S` of a
  **discrete** `R`-algebra `S` (one that is `⊥`-adically complete and kills `I`) satisfying the Tate
  relation `s₀ · s₁ = q`. This is `RestrictedPowerSeries.evalHom` at `L = ⊥`, descended along the
  presentation `R{x, y} ↠ A`. `annulusAug` is the case `S = R ⧸ I`, `s = (0, 0)`.
* `AlgebraicGeometry.annulusFibreEval`: its further descent to the special fibre `A ⧸ I·A`.
* `AlgebraicGeometry.annulusFibre_ext`: **the special fibre is generated by `x` and `y`.** Two ring
  homomorphisms out of `A ⧸ I·A` agreeing on the image of `R` and on the two coordinates are equal.
  This is what makes evaluation maps out of the special fibre *computable*: `A` itself is a
  completion, so a map out of it is not determined by the images of `x` and `y`, but modulo `I` the
  completion collapses to the polynomial ring (`AdicCompletion.quotientEquiv`) and the two
  coordinates do generate.

## Main results

* `AlgebraicGeometry.annulusFibreMk_surjective`
* `AlgebraicGeometry.annulusFibre_ext`

## References

* [Bosch, *Lectures on Formal and Rigid Geometry*, LNM 2105], §9.
* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.
-/

noncomputable section

open Ideal

universe u

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable {S : Type u} [CommRing S] [Algebra R S] [IsAdicComplete (⊥ : Ideal S) S]

/-! ### Evaluation of the annulus at a discrete point -/

/-- **Evaluation of the Tate annulus at a point of a discrete `R`-algebra.** For an `R`-algebra `S`
that is `⊥`-adically complete and in which `I` acts as zero, and a pair `s = (s₀, s₁)` of elements
of `S` satisfying the Tate relation `s₀ · s₁ = q`, evaluation of restricted power series at `s`
descends to `A = R{x, y}/(x·y − q)`. The augmentation `annulusAug` is the case `S = R ⧸ I`,
`s = (0, 0)`. -/
def annulusEvalHom (hIS : I.map (algebraMap R S) ≤ ⊥) (s : Fin 2 → S)
    (hrel : s 0 * s 1 = algebraMap R S q) : annulusAlgebra R I q →+* S :=
  Ideal.Quotient.lift (annulusIdeal R I q)
    (RestrictedPowerSeries.evalHom R I 2 (⊥ : Ideal S) hIS s) <| by
      intro a ha
      rw [annulusIdeal, Ideal.mem_span_singleton] at ha
      obtain ⟨b, rfl⟩ := ha
      have hrel0 : RestrictedPowerSeries.evalHom R I 2 (⊥ : Ideal S) hIS s
          (annulusRel R I q) = 0 := by
        rw [annulusRel, map_sub, map_mul, RestrictedPowerSeries.evalHom_algebraMap,
          show annulusX R I = AdicCompletion.of _ _ (MvPolynomial.X 0) from rfl,
          show annulusY R I = AdicCompletion.of _ _ (MvPolynomial.X 1) from rfl,
          RestrictedPowerSeries.evalHom_of, RestrictedPowerSeries.evalHom_of,
          MvPolynomial.aeval_X, MvPolynomial.aeval_X, hrel, sub_self]
      rw [map_mul, hrel0, zero_mul]

@[simp]
theorem annulusEvalHom_mk (hIS : I.map (algebraMap R S) ≤ ⊥) (s : Fin 2 → S)
    (hrel : s 0 * s 1 = algebraMap R S q) (z : annulusRing R I) :
    annulusEvalHom R I q hIS s hrel (annulusMk R I q z) =
      RestrictedPowerSeries.evalHom R I 2 (⊥ : Ideal S) hIS s z := rfl

@[simp]
theorem annulusEvalHom_overlapX (hIS : I.map (algebraMap R S) ≤ ⊥) (s : Fin 2 → S)
    (hrel : s 0 * s 1 = algebraMap R S q) :
    annulusEvalHom R I q hIS s hrel (overlapX R I q) = s 0 := by
  rw [overlapX, annulusEvalHom_mk,
    show annulusX R I = AdicCompletion.of _ _ (MvPolynomial.X 0) from rfl,
    RestrictedPowerSeries.evalHom_of, MvPolynomial.aeval_X]

@[simp]
theorem annulusEvalHom_overlapY (hIS : I.map (algebraMap R S) ≤ ⊥) (s : Fin 2 → S)
    (hrel : s 0 * s 1 = algebraMap R S q) :
    annulusEvalHom R I q hIS s hrel (overlapY R I q) = s 1 := by
  rw [overlapY, annulusEvalHom_mk,
    show annulusY R I = AdicCompletion.of _ _ (MvPolynomial.X 1) from rfl,
    RestrictedPowerSeries.evalHom_of, MvPolynomial.aeval_X]

theorem annulusEvalHom_algebraMap (hIS : I.map (algebraMap R S) ≤ ⊥) (s : Fin 2 → S)
    (hrel : s 0 * s 1 = algebraMap R S q) (r : R) :
    annulusEvalHom R I q hIS s hrel (algebraMap R (annulusAlgebra R I q) r) =
      algebraMap R S r := by
  rw [← AlgHom.commutes (annulusMk R I q) r, annulusEvalHom_mk,
    RestrictedPowerSeries.evalHom_algebraMap]

/-! ### The special fibre -/

/-- The **special fibre** `A ⧸ I·A` of the Tate annulus: the ring whose prime spectrum is the
underlying space of `Spf A`. -/
abbrev annulusFibre : Type u := annulusAlgebra R I q ⧸ annulusIdealOfDefinition R I q

/-- The residue of the coordinate `x` in the special fibre. -/
abbrev fibreX : annulusFibre R I q := Ideal.Quotient.mk _ (overlapX R I q)

/-- The residue of the coordinate `y` in the special fibre. -/
abbrev fibreY : annulusFibre R I q := Ideal.Quotient.mk _ (overlapY R I q)

/-- **Evaluation on the special fibre.** `annulusEvalHom` kills `I·A`, since `I` acts as zero on the
target, so it descends to `A ⧸ I·A`. -/
def annulusFibreEval (hIS : I.map (algebraMap R S) ≤ ⊥) (s : Fin 2 → S)
    (hrel : s 0 * s 1 = algebraMap R S q) : annulusFibre R I q →+* S :=
  Ideal.Quotient.lift (annulusIdealOfDefinition R I q) (annulusEvalHom R I q hIS s hrel) <| by
    have hle : annulusIdealOfDefinition R I q ≤
        RingHom.ker (annulusEvalHom R I q hIS s hrel) := by
      rw [← annulus_map_eq, Ideal.map_le_iff_le_comap]
      intro r hr
      simp only [Ideal.mem_comap, RingHom.mem_ker, annulusEvalHom_algebraMap]
      exact Ideal.mem_bot.mp (hIS (Ideal.mem_map_of_mem _ hr))
    exact fun a ha => hle ha

@[simp]
theorem annulusFibreEval_mk (hIS : I.map (algebraMap R S) ≤ ⊥) (s : Fin 2 → S)
    (hrel : s 0 * s 1 = algebraMap R S q) (a : annulusAlgebra R I q) :
    annulusFibreEval R I q hIS s hrel (Ideal.Quotient.mk _ a) =
      annulusEvalHom R I q hIS s hrel a := rfl

@[simp]
theorem annulusFibreEval_fibreX (hIS : I.map (algebraMap R S) ≤ ⊥) (s : Fin 2 → S)
    (hrel : s 0 * s 1 = algebraMap R S q) :
    annulusFibreEval R I q hIS s hrel (fibreX R I q) = s 0 := by
  rw [fibreX, annulusFibreEval_mk, annulusEvalHom_overlapX]

@[simp]
theorem annulusFibreEval_fibreY (hIS : I.map (algebraMap R S) ≤ ⊥) (s : Fin 2 → S)
    (hrel : s 0 * s 1 = algebraMap R S q) :
    annulusFibreEval R I q hIS s hrel (fibreY R I q) = s 1 := by
  rw [fibreY, annulusFibreEval_mk, annulusEvalHom_overlapY]

theorem annulusFibreEval_algebraMap (hIS : I.map (algebraMap R S) ≤ ⊥) (s : Fin 2 → S)
    (hrel : s 0 * s 1 = algebraMap R S q) (r : R) :
    annulusFibreEval R I q hIS s hrel (algebraMap R (annulusFibre R I q) r) =
      algebraMap R S r := by
  rw [show algebraMap R (annulusFibre R I q) r =
      Ideal.Quotient.mk _ (algebraMap R (annulusAlgebra R I q) r) from rfl,
    annulusFibreEval_mk, annulusEvalHom_algebraMap]

/-! ### The special fibre is generated by the two coordinates -/

/-- The `R`-algebra map `R[x, y] → A ⧸ I·A` onto the special fibre. -/
def annulusFibreMk : MvPolynomial (Fin 2) R →+* annulusFibre R I q :=
  ((Ideal.Quotient.mk (annulusIdealOfDefinition R I q)).comp
    (annulusMk R I q).toRingHom).comp
      (algebraMap (MvPolynomial (Fin 2) R) (annulusRing R I))

theorem annulusFibreMk_C (r : R) : annulusFibreMk R I q (MvPolynomial.C r) =
    algebraMap R (annulusFibre R I q) r := by
  simp only [annulusFibreMk, RingHom.comp_apply,
    RestrictedPowerSeries.algebraMap_MvPolynomial_apply,
    RestrictedPowerSeries.of_C_eq_algebraMap]
  rw [show (annulusMk R I q).toRingHom (algebraMap R (RestrictedPowerSeries R I 2) r) =
      algebraMap R (annulusAlgebra R I q) r from (annulusMk R I q).commutes r]
  rfl

theorem annulusFibreMk_X_zero : annulusFibreMk R I q (MvPolynomial.X 0) = fibreX R I q := rfl

theorem annulusFibreMk_X_one : annulusFibreMk R I q (MvPolynomial.X 1) = fibreY R I q := rfl

/-- **The special fibre is a quotient of the polynomial ring `R[x, y]`.** Modulo `I` the completion
defining `R{x, y}` collapses (`AdicCompletion.quotientEquiv`, in the packaged form
`formalCompletion.surjective_residueMap`), so every element of `A ⧸ I·A` is a polynomial in the two
coordinates. -/
theorem annulusFibreMk_surjective (hI : I.FG) : Function.Surjective (annulusFibreMk R I q) := by
  intro b
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective b
  obtain ⟨z, rfl⟩ := Ideal.Quotient.mk_surjective a
  obtain ⟨p, hp⟩ := formalCompletion.surjective_residueMap (MvPolynomial (Fin 2) R)
    (I.map (algebraMap R (MvPolynomial (Fin 2) R))) (hI.map _)
    (Ideal.Quotient.mk (RestrictedPowerSeries.idealOfDefinition R I 2) z)
  refine ⟨p, ?_⟩
  have hp' : Ideal.Quotient.mk (RestrictedPowerSeries.idealOfDefinition R I 2) z =
      Ideal.Quotient.mk (RestrictedPowerSeries.idealOfDefinition R I 2)
        (algebraMap (MvPolynomial (Fin 2) R) (annulusRing R I) p) := hp.symm
  have hmem : z - algebraMap (MvPolynomial (Fin 2) R) (annulusRing R I) p ∈
      RestrictedPowerSeries.idealOfDefinition R I 2 :=
    Ideal.Quotient.eq.mp hp'
  have hmap : annulusMk R I q (z - algebraMap (MvPolynomial (Fin 2) R) (annulusRing R I) p) ∈
      annulusIdealOfDefinition R I q := Ideal.mem_map_of_mem _ hmem
  rw [map_sub] at hmap
  simp only [annulusFibreMk, RingHom.comp_apply]
  exact (Ideal.Quotient.eq.mpr hmap).symm

/-- **Ring homomorphisms out of the special fibre are determined by the two coordinates.** The
computational form of `annulusFibreMk_surjective`, and the reason evaluation maps out of
`A ⧸ I·A` can be identified by inspecting their values on `x` and `y`. -/
theorem annulusFibre_ext {T : Type u} [CommRing T] (hI : I.FG) (f g : annulusFibre R I q →+* T)
    (hC : ∀ r : R, f (algebraMap R (annulusFibre R I q) r) =
      g (algebraMap R (annulusFibre R I q) r))
    (hX : f (fibreX R I q) = g (fibreX R I q)) (hY : f (fibreY R I q) = g (fibreY R I q)) :
    f = g := by
  refine RingHom.ext fun b => ?_
  obtain ⟨p, rfl⟩ := annulusFibreMk_surjective R I q hI b
  have key : f.comp (annulusFibreMk R I q) = g.comp (annulusFibreMk R I q) := by
    refine MvPolynomial.ringHom_ext (fun r => ?_) (fun i => ?_)
    · simp only [RingHom.comp_apply, annulusFibreMk_C]; exact hC r
    · fin_cases i
      · exact hX
      · exact hY
  exact congrArg (fun (h : MvPolynomial (Fin 2) R →+* T) => h p) key

end AlgebraicGeometry
