import Mathlib.RingTheory.ReesAlgebra
import Mathlib.RingTheory.Ideal.Quotient.Noetherian

set_option linter.style.header false

/-!
# The associated graded ring of an ideal-adic filtration

For a commutative ring `B` and an ideal `K : Ideal B`, the **associated graded ring** is
```
gr_K(B) := ⨁_{n : ℕ} K^n / K^{n+1}
```
with multiplication `K^m/K^{m+1} × K^n/K^{n+1} → K^{m+n}/K^{m+n+1}` induced by multiplication in
`B`. It is the algebraic gadget underlying Atiyah–Macdonald's proof that a complete Noetherian ring
is Noetherian (Prop. 10.25 / 10.26), which the restricted-power-series development (issue 98) needs.

Rather than build the graded ring by hand, we realise it as a quotient of the **Rees algebra**
`reesAlgebra K = ⨁_n K^n · X^n ⊆ B[X]`: the ideal `J` of the Rees algebra generated by the image of
`K` (constants from `K`) has degree-`n` part `K^{n+1} · X^n`, so
```
reesAlgebra K ⧸ J
```
has degree-`n` part `K^n · X^n / K^{n+1} · X^n ≅ K^n / K^{n+1}` — the associated graded ring.
This makes the ring structure and, crucially, the **Noetherianness** essentially free: the Rees
algebra of an ideal over a Noetherian ring is Noetherian (`reesAlgebra` is of finite type), and a
quotient of a Noetherian ring is Noetherian.

## Main definitions

* `AssociatedGraded K`: the associated graded ring `gr_K(B)`, as `reesAlgebra K ⧸ J`.

## Main results

* `AssociatedGraded.instIsNoetherianRing`: `gr_K(B)` is Noetherian when `B` is Noetherian
  (Atiyah–Macdonald 10.24).

## References

* [Atiyah–Macdonald, *Introduction to Commutative Algebra*], Ch. 10 (§10.22, Prop. 10.24).
* Stacks Tag 00JV, 00IN.
-/

open Polynomial

noncomputable section

universe u

variable {B : Type u} [CommRing B]

namespace AssociatedGraded

/-- The **degree-shifting ideal** of the Rees algebra `reesAlgebra K`: the ideal generated by the
image of `K` (as constant polynomials). Its degree-`n` homogeneous part is `K^{n+1} · X^n`, so the
quotient by it has degree-`n` part `K^n/K^{n+1}`. -/
def shiftIdeal (K : Ideal B) : Ideal (reesAlgebra K) :=
  Ideal.map (algebraMap B (reesAlgebra K)) K

end AssociatedGraded

/-- The **associated graded ring** `gr_K(B) = ⨁_n K^n/K^{n+1}` of the `K`-adic filtration of `B`,
realised as the quotient of the Rees algebra `reesAlgebra K` by its degree-shifting ideal. -/
def AssociatedGraded (K : Ideal B) : Type u :=
  reesAlgebra K ⧸ AssociatedGraded.shiftIdeal K

namespace AssociatedGraded

variable (K : Ideal B)

instance : CommRing (AssociatedGraded K) :=
  inferInstanceAs (CommRing (reesAlgebra K ⧸ shiftIdeal K))

/-- The canonical projection `reesAlgebra K → gr_K(B)`. -/
def mk : reesAlgebra K →+* AssociatedGraded K :=
  Ideal.Quotient.mk (shiftIdeal K)

theorem mk_surjective : Function.Surjective (mk K) :=
  Ideal.Quotient.mk_surjective

/-- **Atiyah–Macdonald 10.24.** The associated graded ring of a Noetherian ring is Noetherian. -/
instance instIsNoetherianRing [IsNoetherianRing B] : IsNoetherianRing (AssociatedGraded K) :=
  inferInstanceAs (IsNoetherianRing (reesAlgebra K ⧸ shiftIdeal K))

end AssociatedGraded
