import Mathlib.RingTheory.ReesAlgebra
import Mathlib.RingTheory.Ideal.Quotient.Noetherian
import Mathlib.Algebra.GradedMonoid
import Mathlib.RingTheory.GradedAlgebra.Basic
import Mathlib.Algebra.DirectSum.Decomposition
import Mathlib.LinearAlgebra.DFinsupp

set_option linter.style.header false

/-!
# The associated graded ring of an ideal-adic filtration

For a commutative ring `B` and an ideal `K : Ideal B`, the **associated graded ring** is
```
gr_K(B) := ⨁_{n : ℕ} K^n / K^{n+1}
```
with multiplication `K^m/K^{m+1} × K^n/K^{n+1} → K^{m+n}/K^{m+n+1}` induced by multiplication in
`B`. It is the algebraic gadget underlying Atiyah–Macdonald's proof that a complete Noetherian ring
is Noetherian (Prop. 10.25 / 10.26), which the restricted-power-series development (issue 98) needs.

Rather than build the graded ring by hand, we realise it as a quotient of the **Rees algebra**
`reesAlgebra K = ⨁_n K^n · X^n ⊆ B[X]`: the ideal `J` of the Rees algebra generated by the image of
`K` (constants from `K`) has degree-`n` part `K^{n+1} · X^n`, so
```
reesAlgebra K ⧸ J
```
has degree-`n` part `K^n · X^n / K^{n+1} · X^n ≅ K^n / K^{n+1}` — the associated graded ring.
This makes the ring structure and, crucially, the **Noetherianness** essentially free: the Rees
algebra of an ideal over a Noetherian ring is Noetherian (`reesAlgebra` is of finite type), and a
quotient of a Noetherian ring is Noetherian.

## Main definitions

* `AssociatedGraded K`: the associated graded ring `gr_K(B)`, as `reesAlgebra K ⧸ J`.
* `AssociatedGraded.deg n`: the **leading-form map** `K^n → gr_K(B)`, `k ↦ [k·X^n]`, realising the
  projection onto the degree-`n` piece `K^n/K^{n+1}`.
* `AssociatedGraded.grPiece n`: the degree-`n` graded piece (image of `deg n`).

## Main results

* `AssociatedGraded.instIsNoetherianRing`: `gr_K(B)` is Noetherian when `B` is Noetherian
  (Atiyah–Macdonald 10.24).
* `AssociatedGraded.deg_mul`, `AssociatedGraded.deg_zero_one`: leading forms are multiplicative
  across degrees and the unit sits in degree `0`.
* `AssociatedGraded.deg_eq_zero_of_mem_succ`: `deg n` kills the next filtration step `K^{n+1}`, so
  it factors through `K^n/K^{n+1}`.
* `SetLike.GradedMonoid (grPiece K)` and `AssociatedGraded.iSup_grPiece`: the graded pieces form a
  graded monoid inside `gr_K(B)` and generate it.
* `AssociatedGraded.instGradedRing`: the decomposition is **direct**, so `gr_K(B) = ⨁_n K^n/K^{n+1}`
  is a genuine `GradedRing` — the graded pieces `grPiece n` are `iSupIndep` (`isInternal_grPiece`).
* `AssociatedGraded.deg_eq_zero_iff`: the faithfulness `deg n k = 0 ↔ k ∈ K^{n+1}`, so each `deg n`
  descends to an *injection* `K^n/K^{n+1} ↪ gr_K(B)`.

The directness rests on the coefficient bound `AssociatedGraded.coeff_mem_of_mem_shiftIdeal`: every
coefficient of an element of `shiftIdeal K` lies one filtration step deeper. This graded structure
(with the leading forms, their vanishing on `K^{n+1}`, and multiplicativity) is the interface the
successive-approximation argument of Atiyah–Macdonald 10.25 consumes — in particular the projections
`DirectSum.decompose` onto homogeneous components that it needs.

## References

* [Atiyah–Macdonald, *Introduction to Commutative Algebra*], Ch. 10 (§10.22, Prop. 10.24).
* Stacks Tag 00JV, 00IN.
-/

open Polynomial

noncomputable section

universe u

variable {B : Type u} [CommRing B]

namespace AssociatedGraded

/-- The **degree-shifting ideal** of the Rees algebra `reesAlgebra K`: the ideal generated by the
image of `K` (as constant polynomials). Its degree-`n` homogeneous part is `K^{n+1} · X^n`, so the
quotient by it has degree-`n` part `K^n/K^{n+1}`. -/
def shiftIdeal (K : Ideal B) : Ideal (reesAlgebra K) :=
  Ideal.map (algebraMap B (reesAlgebra K)) K

end AssociatedGraded

/-- The **associated graded ring** `gr_K(B) = ⨁_n K^n/K^{n+1}` of the `K`-adic filtration of `B`,
realised as the quotient of the Rees algebra `reesAlgebra K` by its degree-shifting ideal. -/
def AssociatedGraded (K : Ideal B) : Type u :=
  reesAlgebra K ⧸ AssociatedGraded.shiftIdeal K

namespace AssociatedGraded

variable (K : Ideal B)

instance : CommRing (AssociatedGraded K) :=
  inferInstanceAs (CommRing (reesAlgebra K ⧸ shiftIdeal K))

instance : Algebra B (AssociatedGraded K) :=
  inferInstanceAs (Algebra B (reesAlgebra K ⧸ shiftIdeal K))

/-- The canonical projection `reesAlgebra K → gr_K(B)` as a `B`-algebra homomorphism. -/
def mkₐ : reesAlgebra K →ₐ[B] AssociatedGraded K :=
  Ideal.Quotient.mkₐ B (shiftIdeal K)

/-- The canonical projection `reesAlgebra K → gr_K(B)`. -/
def mk : reesAlgebra K →+* AssociatedGraded K :=
  Ideal.Quotient.mk (shiftIdeal K)

@[simp] theorem mkₐ_toRingHom : (mkₐ K).toRingHom = mk K := rfl

@[simp] theorem mkₐ_apply (p : reesAlgebra K) : mkₐ K p = mk K p := rfl

theorem mk_surjective : Function.Surjective (mk K) :=
  Ideal.Quotient.mk_surjective

theorem mk_eq_zero_iff (p : reesAlgebra K) : mk K p = 0 ↔ p ∈ shiftIdeal K :=
  Ideal.Quotient.eq_zero_iff_mem

/-- **Atiyah–Macdonald 10.24.** The associated graded ring of a Noetherian ring is Noetherian. -/
instance instIsNoetherianRing [IsNoetherianRing B] : IsNoetherianRing (AssociatedGraded K) :=
  inferInstanceAs (IsNoetherianRing (reesAlgebra K ⧸ shiftIdeal K))

/-! ### Leading forms and the graded pieces

The degree-`n` piece of `gr_K(B)` is `K^n/K^{n+1}`. We realise the projection `K^n → K^n/K^{n+1}`
concretely as the **leading-form map** `deg n : K^n → gr_K(B)` sending `k ∈ K^n` to the class of the
monomial `k·X^n ∈ reesAlgebra K`. These maps are additive, `B`-linear, kill `K^{n+1} ⊆ K^n`, are
multiplicative across degrees, and their images generate `gr_K(B)`. This is the interface the
successive-approximation argument of Atiyah–Macdonald 10.25 (issue 144) consumes. -/

/-- The monomial `k · X^n` as an element of the Rees algebra, for `k ∈ K^n`. -/
def monomialRees (n : ℕ) : (K ^ n : Ideal B) →ₗ[B] reesAlgebra K where
  toFun k := ⟨monomial n (k : B), by
    intro i
    rw [coeff_monomial]
    split_ifs with h
    · exact h ▸ k.2
    · exact zero_mem _⟩
  map_add' k₁ k₂ := by
    ext1
    simp only [map_add, AddMemClass.coe_add]
  map_smul' b k := by
    ext1
    simp only [SetLike.val_smul, map_smul, RingHom.id_apply]

@[simp] theorem monomialRees_coe (n : ℕ) (k : (K ^ n : Ideal B)) :
    ((monomialRees K n k : reesAlgebra K) : B[X]) = monomial n (k : B) := rfl

/-- The **leading-form map** `deg n : K^n → gr_K(B)`, `k ↦ [k·X^n]`, landing in the degree-`n` piece
`K^n/K^{n+1}` of the associated graded ring. -/
def deg (n : ℕ) : (K ^ n : Ideal B) →ₗ[B] AssociatedGraded K :=
  (mkₐ K).toLinearMap ∘ₗ monomialRees K n

theorem deg_apply (n : ℕ) (k : (K ^ n : Ideal B)) :
    deg K n k = mk K (monomialRees K n k) := rfl

/-- Leading forms are multiplicative across degrees, at the level of the Rees algebra. -/
theorem monomialRees_mul (m n : ℕ) (a : (K ^ m : Ideal B)) (b : (K ^ n : Ideal B)) :
    monomialRees K m a * monomialRees K n b =
      monomialRees K (m + n) ⟨(a : B) * b, by
        rw [pow_add]; exact Ideal.mul_mem_mul a.2 b.2⟩ := by
  ext1
  simp only [MulMemClass.coe_mul, monomialRees_coe, monomial_mul_monomial]

/-- The unit: `1 = [1·X^0] ∈ K^0/K^1`. -/
theorem monomialRees_zero_one :
    monomialRees K 0 ⟨1, by simp⟩ = 1 := by
  ext1
  simp only [monomialRees_coe, OneMemClass.coe_one, monomial_zero_left, map_one]

/-- **Leading forms are multiplicative across degrees.** `deg m a · deg n b = deg (m+n) (a·b)`. -/
theorem deg_mul (m n : ℕ) (a : (K ^ m : Ideal B)) (b : (K ^ n : Ideal B)) :
    deg K m a * deg K n b =
      deg K (m + n) ⟨(a : B) * b, by
        rw [pow_add]; exact Ideal.mul_mem_mul a.2 b.2⟩ := by
  rw [deg_apply, deg_apply, deg_apply, ← map_mul, monomialRees_mul]

/-- The unit lands in degree zero. -/
theorem deg_zero_one : deg K 0 ⟨1, by simp⟩ = 1 := by
  rw [deg_apply, monomialRees_zero_one, map_one]

/-- The **degree-shifting ideal** of the Rees algebra absorbs any monomial whose coefficient lies
one filtration step deeper: if `x ∈ K^{n+1}`, then `x·X^n ∈ shiftIdeal K`. -/
theorem monomial_mem_shiftIdeal (n : ℕ) {x : B} (hx : x ∈ K ^ (n + 1))
    (p : reesAlgebra K) (hp : (p : B[X]) = monomial n x) : p ∈ shiftIdeal K := by
  rw [pow_succ] at hx
  induction hx using Submodule.mul_induction_on' generalizing p with
  | mem_mul_mem a ha c hc =>
    -- `a ∈ K^n`, `c ∈ K`, and `p` has coefficient monomial `n (a·c)`.
    have hqa : ∀ i, (monomial n a).coeff i ∈ K ^ i := fun i => by
      rw [coeff_monomial]; split_ifs with h
      · exact h ▸ ha
      · exact zero_mem _
    have h1 : (↑(algebraMap B (reesAlgebra K) c) : B[X]) = C c := by
      simp [Polynomial.algebraMap_eq]
    have hne : p = algebraMap B (reesAlgebra K) c * ⟨monomial n a, hqa⟩ := by
      apply Subtype.ext
      rw [hp, MulMemClass.coe_mul, h1]
      rw [(rfl : (↑(⟨monomial n a, hqa⟩ : reesAlgebra K) : B[X]) = monomial n a)]
      rw [C_mul_monomial, mul_comm a c]
    rw [hne]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ hc)
  | add x hx y hy ihx ihy =>
    -- `p` has coefficient `monomial n (x+y)`; split as a sum.
    have hxn : x ∈ K ^ n := Ideal.mul_le_right hx
    have hyn : y ∈ K ^ n := Ideal.mul_le_right hy
    rw [show p = monomialRees K n ⟨x, hxn⟩ + monomialRees K n ⟨y, hyn⟩ by
      apply Subtype.ext
      rw [hp, AddMemClass.coe_add, monomialRees_coe, monomialRees_coe, ← map_add]]
    exact Ideal.add_mem _ (ihx _ rfl) (ihy _ rfl)

/-- **Leading forms kill the next filtration step.** If `k ∈ K^n` in fact lies in `K^{n+1}`, its
degree-`n` leading form vanishes. This is what makes `deg n` factor through `K^n/K^{n+1}`. -/
theorem deg_eq_zero_of_mem_succ (n : ℕ) (k : (K ^ n : Ideal B)) (hk : (k : B) ∈ K ^ (n + 1)) :
    deg K n k = 0 := by
  rw [deg_apply, mk_eq_zero_iff]
  exact monomial_mem_shiftIdeal K n hk _ (monomialRees_coe K n k)

/-! ### The graded pieces and the internal grading

The degree-`n` piece `𝒢 n := image of deg n` is a copy of `K^n/K^{n+1}` sitting inside `gr_K(B)`.
The leading-form multiplicativity `deg_mul` and unit `deg_zero_one` make the family `𝒢` a graded
monoid inside `gr_K(B)`, and the pieces generate the whole ring. (Directness of the decomposition —
which would upgrade this to a full `GradedRing` instance — is left to a follow-up; see the module
docstring.) -/

/-- The degree-`n` **graded piece** of `gr_K(B)`, the image of the leading-form map `deg n`. It is
the copy of `K^n/K^{n+1}` inside `gr_K(B)`. -/
def grPiece (n : ℕ) : Submodule B (AssociatedGraded K) :=
  LinearMap.range (deg K n)

theorem mem_grPiece {n : ℕ} {x : AssociatedGraded K} :
    x ∈ grPiece K n ↔ ∃ k : (K ^ n : Ideal B), deg K n k = x :=
  LinearMap.mem_range

theorem deg_mem_grPiece (n : ℕ) (k : (K ^ n : Ideal B)) : deg K n k ∈ grPiece K n :=
  ⟨k, rfl⟩

/-- The graded pieces form a **graded monoid** inside `gr_K(B)`: the unit sits in degree `0`, and
the product of a degree-`i` and a degree-`j` element lands in degree `i+j`. -/
instance : SetLike.GradedMonoid (grPiece K) where
  one_mem := ⟨⟨1, by simp⟩, deg_zero_one K⟩
  mul_mem i j x y hx hy := by
    obtain ⟨a, rfl⟩ := hx
    obtain ⟨b, rfl⟩ := hy
    refine ⟨⟨(a : B) * b, ?_⟩, (deg_mul K i j a b).symm⟩
    rw [pow_add]; exact Ideal.mul_mem_mul a.2 b.2

/-- The graded pieces **generate** `gr_K(B)`: every element is a finite sum of leading forms. -/
theorem iSup_grPiece : ⨆ n, grPiece K n = ⊤ := by
  rw [eq_top_iff]
  rintro x -
  obtain ⟨p, rfl⟩ := mk_surjective K x
  -- write `p` as the sum of its monomials in the Rees algebra, then map down
  have hp : p = ∑ i ∈ (p : B[X]).support,
      monomialRees K i ⟨(p : B[X]).coeff i, p.2 i⟩ := by
    apply Subtype.ext
    rw [AddSubmonoidClass.coe_finsetSum]
    simp only [monomialRees_coe]
    exact (Polynomial.as_sum_support (p : B[X]))
  rw [hp, map_sum]
  refine Submodule.sum_mem _ fun i _ => ?_
  exact Submodule.mem_iSup_of_mem i (deg_mem_grPiece K i _)

/-! ### Directness of the grading and the `GradedRing` instance

The graded pieces `grPiece n` not only generate `gr_K(B)` (`iSup_grPiece`) but do so *directly*:
`gr_K(B) = ⨁_n Kⁿ/Kⁿ⁺¹` as an internal direct sum. The essential input is a coefficient bound on
the degree-shifting ideal — every coefficient of an element of `shiftIdeal K` lies one filtration
step deeper (`coeff_mem_of_mem_shiftIdeal`) — which makes the leading-form maps `deg n` jointly
injective. This upgrades the `SetLike.GradedMonoid` structure to a full `GradedRing`, and yields the
faithfulness of individual leading forms `deg_eq_zero_iff`. -/

/-- Every coefficient of an element of the degree-shifting ideal lies one filtration step deeper:
if `p ∈ shiftIdeal K`, then `(p : B[X]).coeff r ∈ K^(r+1)` for every `r`. This is the exact
converse bookkeeping to `monomial_mem_shiftIdeal`, and pins down the degree-`r` homogeneous part of
`shiftIdeal K` as `K^(r+1)·X^r`. -/
theorem coeff_mem_of_mem_shiftIdeal {p : reesAlgebra K} (hp : p ∈ shiftIdeal K) :
    ∀ r, ((p : reesAlgebra K) : B[X]).coeff r ∈ K ^ (r + 1) := by
  have hp' : p ∈ Submodule.span (reesAlgebra K)
      (⇑(algebraMap B (reesAlgebra K)) '' (K : Set B)) := hp
  clear hp
  induction hp' using Submodule.span_induction with
  | mem q hq =>
      obtain ⟨k, hk, rfl⟩ := hq
      intro r
      have hCk : ((algebraMap B (reesAlgebra K) k : reesAlgebra K) : B[X]) = C k := by
        simp [Polynomial.algebraMap_eq]
      rw [hCk, coeff_C]
      split_ifs with h
      · simpa [h] using hk
      · exact zero_mem _
  | zero => intro r; simp
  | add x y _ _ ihx ihy =>
      intro r
      have hxy : ((x + y : reesAlgebra K) : B[X]) = (x : B[X]) + (y : B[X]) := by
        push_cast; ring
      rw [hxy, coeff_add]
      exact Ideal.add_mem _ (ihx r) (ihy r)
  | smul a x _ ih =>
      intro r
      have hax : ((a • x : reesAlgebra K) : B[X]) = (a : B[X]) * (x : B[X]) := by
        rw [smul_eq_mul]; push_cast; ring
      rw [hax, Polynomial.coeff_mul]
      refine Ideal.sum_mem _ ?_
      rintro ⟨i, j⟩ hij
      rw [Finset.mem_antidiagonal] at hij
      have hai : (a : B[X]).coeff i ∈ K ^ i := (mem_reesAlgebra_iff (I := K) (a : B[X])).mp a.2 i
      have hxj : (x : B[X]).coeff j ∈ K ^ (j + 1) := ih j
      have hmul : (a : B[X]).coeff i * (x : B[X]).coeff j ∈ K ^ i * K ^ (j + 1) :=
        Ideal.mul_mem_mul hai hxj
      rw [← pow_add] at hmul
      rwa [show i + (j + 1) = r + 1 by omega] at hmul

/-- **Faithfulness of leading forms.** A degree-`n` leading form vanishes in `gr_K(B)` iff its
representative already lies in `K^(n+1)`. The reverse implication is `deg_eq_zero_of_mem_succ`; the
forward implication uses the coefficient bound `coeff_mem_of_mem_shiftIdeal`. In particular `deg n`
descends to an *injection* `K^n/K^(n+1) ↪ gr_K(B)`. -/
theorem deg_eq_zero_iff (n : ℕ) (k : (K ^ n : Ideal B)) :
    deg K n k = 0 ↔ (k : B) ∈ K ^ (n + 1) := by
  refine ⟨fun h => ?_, deg_eq_zero_of_mem_succ K n k⟩
  rw [deg_apply, mk_eq_zero_iff] at h
  have := coeff_mem_of_mem_shiftIdeal K h n
  rwa [monomialRees_coe, coeff_monomial, if_pos rfl] at this

/-- The leading-form maps `deg n` are jointly injective: the canonical map `⨁_n grPiece n → gr_K(B)`
is injective. This is the directness of the grading. -/
theorem coeLinearMap_grPiece_injective :
    Function.Injective (DirectSum.coeLinearMap (grPiece K)) := by
  classical
  rw [← LinearMap.ker_eq_bot, LinearMap.ker_eq_bot']
  intro x hx
  have hchoose : ∀ n, ∃ k : (K ^ n : Ideal B), deg K n k = (x n : AssociatedGraded K) :=
    fun n => LinearMap.mem_range.mp (x n).2
  choose rep hrep using hchoose
  set P : reesAlgebra K := ∑ n ∈ x.support, monomialRees K n (rep n) with hP
  -- The image of `x` under the sum map is `mk P`.
  have hRHS : DirectSum.coeLinearMap (grPiece K) x
      = ∑ n ∈ x.support, ((x n : grPiece K n) : AssociatedGraded K) := by
    conv_lhs => rw [← DirectSum.sum_support_of x]
    rw [map_sum]
    exact Finset.sum_congr rfl fun n _ => DirectSum.coeLinearMap_of _ n _
  have hmkP : mk K P = ∑ n ∈ x.support, ((x n : grPiece K n) : AssociatedGraded K) := by
    rw [hP, map_sum]
    exact Finset.sum_congr rfl fun n _ => by rw [← deg_apply]; exact hrep n
  have hP0 : mk K P = 0 := by rw [hmkP, ← hRHS]; exact hx
  have hcoeff := coeff_mem_of_mem_shiftIdeal K ((mk_eq_zero_iff K P).mp hP0)
  -- Read off each component of `x` from a coefficient of `P`.
  refine DFinsupp.ext fun n => ?_
  change (x n : grPiece K n) = 0
  by_cases hn : n ∈ x.support
  · have hcoeffn : ((P : reesAlgebra K) : B[X]).coeff n = (rep n : B) := by
      rw [hP, AddSubmonoidClass.coe_finsetSum, Polynomial.finsetSum_coeff,
        Finset.sum_eq_single n (fun m _ hmn => by
            rw [monomialRees_coe, coeff_monomial, if_neg hmn])
          (fun h => absurd hn h), monomialRees_coe, coeff_monomial, if_pos rfl]
    have hmem : (rep n : B) ∈ K ^ (n + 1) := hcoeffn ▸ hcoeff n
    have hz : (↑(x n) : AssociatedGraded K) = 0 := by
      rw [← hrep n]; exact (deg_eq_zero_iff K n (rep n)).mpr hmem
    exact Subtype.ext (hz.trans (ZeroMemClass.coe_zero _).symm)
  · rw [DFinsupp.mem_support_iff, not_not] at hn; exact hn

/-- The graded pieces of `gr_K(B)` form an **internal direct sum**: `gr_K(B) = ⨁_n Kⁿ/Kⁿ⁺¹`. -/
theorem isInternal_grPiece : DirectSum.IsInternal (grPiece K) :=
  DirectSum.isInternal_submodule_of_iSupIndep_of_iSup_eq_top
    (iSupIndep_of_dfinsupp_lsum_injective _ (coeLinearMap_grPiece_injective K))
    (iSup_grPiece K)

/-- **The `GradedRing` structure on the associated graded ring.** With the internal direct-sum
decomposition (`isInternal_grPiece`) on top of the graded-monoid structure, `gr_K(B) = ⨁_n Kⁿ/Kⁿ⁺¹`
is a graded ring, with degree-`n` piece `grPiece n ≅ Kⁿ/Kⁿ⁺¹`. -/
noncomputable instance instGradedRing : GradedRing (grPiece K) :=
  haveI gm : SetLike.GradedMonoid (grPiece K) := inferInstance
  haveI dec : DirectSum.Decomposition (grPiece K) := (isInternal_grPiece K).chooseDecomposition
  { gm, dec with }

end AssociatedGraded
