import Mathlib.RingTheory.ReesAlgebra
import Mathlib.RingTheory.Ideal.Quotient.Noetherian
import Mathlib.Algebra.GradedMonoid

set_option linter.style.header false

/-!
# The associated graded ring of an ideal-adic filtration

For a commutative ring `B` and an ideal `K : Ideal B`, the **associated graded ring** is
```
gr_K(B) := ⨁_{n : ℕ} K^n / K^{n+1}
```
with multiplication `K^m/K^{m+1} × K^n/K^{n+1} → K^{m+n}/K^{m+n+1}` induced by multiplication in
`B`. It is the algebraic gadget underlying Atiyah–Macdonald's proof that a complete Noetherian ring
is Noetherian (Prop. 10.25 / 10.26), which the restricted-power-series development (issue 98) needs.

Rather than build the graded ring by hand, we realise it as a quotient of the **Rees algebra**
`reesAlgebra K = ⨁_n K^n · X^n ⊆ B[X]`: the ideal `J` of the Rees algebra generated by the image of
`K` (constants from `K`) has degree-`n` part `K^{n+1} · X^n`, so
```
reesAlgebra K ⧸ J
```
has degree-`n` part `K^n · X^n / K^{n+1} · X^n ≅ K^n / K^{n+1}` — the associated graded ring.
This makes the ring structure and, crucially, the **Noetherianness** essentially free: the Rees
algebra of an ideal over a Noetherian ring is Noetherian (`reesAlgebra` is of finite type), and a
quotient of a Noetherian ring is Noetherian.

## Main definitions

* `AssociatedGraded K`: the associated graded ring `gr_K(B)`, as `reesAlgebra K ⧸ J`.
* `AssociatedGraded.deg n`: the **leading-form map** `K^n → gr_K(B)`, `k ↦ [k·X^n]`, realising the
  projection onto the degree-`n` piece `K^n/K^{n+1}`.
* `AssociatedGraded.grPiece n`: the degree-`n` graded piece (image of `deg n`).

## Main results

* `AssociatedGraded.instIsNoetherianRing`: `gr_K(B)` is Noetherian when `B` is Noetherian
  (Atiyah–Macdonald 10.24).
* `AssociatedGraded.deg_mul`, `AssociatedGraded.deg_zero_one`: leading forms are multiplicative
  across degrees and the unit sits in degree `0`.
* `AssociatedGraded.deg_eq_zero_of_mem_succ`: `deg n` kills the next filtration step `K^{n+1}`, so
  it factors through `K^n/K^{n+1}`.
* `SetLike.GradedMonoid (grPiece K)` and `AssociatedGraded.iSup_grPiece`: the graded pieces form a
  graded monoid inside `gr_K(B)` and generate it.

Directness of the homogeneous decomposition — which would upgrade `grPiece` to a full `GradedRing`
instance — is not established here; it is the natural next increment. The above interface (leading
forms, the vanishing on `K^{n+1}`, and multiplicativity) is what the successive-approximation
argument of Atiyah–Macdonald 10.25 consumes.

## References

* [Atiyah–Macdonald, *Introduction to Commutative Algebra*], Ch. 10 (§10.22, Prop. 10.24).
* Stacks Tag 00JV, 00IN.
-/

open Polynomial

noncomputable section

universe u

variable {B : Type u} [CommRing B]

namespace AssociatedGraded

/-- The **degree-shifting ideal** of the Rees algebra `reesAlgebra K`: the ideal generated by the
image of `K` (as constant polynomials). Its degree-`n` homogeneous part is `K^{n+1} · X^n`, so the
quotient by it has degree-`n` part `K^n/K^{n+1}`. -/
def shiftIdeal (K : Ideal B) : Ideal (reesAlgebra K) :=
  Ideal.map (algebraMap B (reesAlgebra K)) K

end AssociatedGraded

/-- The **associated graded ring** `gr_K(B) = ⨁_n K^n/K^{n+1}` of the `K`-adic filtration of `B`,
realised as the quotient of the Rees algebra `reesAlgebra K` by its degree-shifting ideal. -/
def AssociatedGraded (K : Ideal B) : Type u :=
  reesAlgebra K ⧸ AssociatedGraded.shiftIdeal K

namespace AssociatedGraded

variable (K : Ideal B)

instance : CommRing (AssociatedGraded K) :=
  inferInstanceAs (CommRing (reesAlgebra K ⧸ shiftIdeal K))

instance : Algebra B (AssociatedGraded K) :=
  inferInstanceAs (Algebra B (reesAlgebra K ⧸ shiftIdeal K))

/-- The canonical projection `reesAlgebra K → gr_K(B)` as a `B`-algebra homomorphism. -/
def mkₐ : reesAlgebra K →ₐ[B] AssociatedGraded K :=
  Ideal.Quotient.mkₐ B (shiftIdeal K)

/-- The canonical projection `reesAlgebra K → gr_K(B)`. -/
def mk : reesAlgebra K →+* AssociatedGraded K :=
  Ideal.Quotient.mk (shiftIdeal K)

@[simp] theorem mkₐ_toRingHom : (mkₐ K).toRingHom = mk K := rfl

@[simp] theorem mkₐ_apply (p : reesAlgebra K) : mkₐ K p = mk K p := rfl

theorem mk_surjective : Function.Surjective (mk K) :=
  Ideal.Quotient.mk_surjective

theorem mk_eq_zero_iff (p : reesAlgebra K) : mk K p = 0 ↔ p ∈ shiftIdeal K :=
  Ideal.Quotient.eq_zero_iff_mem

/-- **Atiyah–Macdonald 10.24.** The associated graded ring of a Noetherian ring is Noetherian. -/
instance instIsNoetherianRing [IsNoetherianRing B] : IsNoetherianRing (AssociatedGraded K) :=
  inferInstanceAs (IsNoetherianRing (reesAlgebra K ⧸ shiftIdeal K))

/-! ### Leading forms and the graded pieces

The degree-`n` piece of `gr_K(B)` is `K^n/K^{n+1}`. We realise the projection `K^n → K^n/K^{n+1}`
concretely as the **leading-form map** `deg n : K^n → gr_K(B)` sending `k ∈ K^n` to the class of the
monomial `k·X^n ∈ reesAlgebra K`. These maps are additive, `B`-linear, kill `K^{n+1} ⊆ K^n`, are
multiplicative across degrees, and their images generate `gr_K(B)`. This is the interface the
successive-approximation argument of Atiyah–Macdonald 10.25 (issue 144) consumes. -/

/-- The monomial `k · X^n` as an element of the Rees algebra, for `k ∈ K^n`. -/
def monomialRees (n : ℕ) : (K ^ n : Ideal B) →ₗ[B] reesAlgebra K where
  toFun k := ⟨monomial n (k : B), by
    intro i
    rw [coeff_monomial]
    split_ifs with h
    · exact h ▸ k.2
    · exact zero_mem _⟩
  map_add' k₁ k₂ := by
    ext1
    simp only [map_add, AddMemClass.coe_add]
  map_smul' b k := by
    ext1
    simp only [SetLike.val_smul, map_smul, RingHom.id_apply]

@[simp] theorem monomialRees_coe (n : ℕ) (k : (K ^ n : Ideal B)) :
    ((monomialRees K n k : reesAlgebra K) : B[X]) = monomial n (k : B) := rfl

/-- The **leading-form map** `deg n : K^n → gr_K(B)`, `k ↦ [k·X^n]`, landing in the degree-`n` piece
`K^n/K^{n+1}` of the associated graded ring. -/
def deg (n : ℕ) : (K ^ n : Ideal B) →ₗ[B] AssociatedGraded K :=
  (mkₐ K).toLinearMap ∘ₗ monomialRees K n

theorem deg_apply (n : ℕ) (k : (K ^ n : Ideal B)) :
    deg K n k = mk K (monomialRees K n k) := rfl

/-- Leading forms are multiplicative across degrees, at the level of the Rees algebra. -/
theorem monomialRees_mul (m n : ℕ) (a : (K ^ m : Ideal B)) (b : (K ^ n : Ideal B)) :
    monomialRees K m a * monomialRees K n b =
      monomialRees K (m + n) ⟨(a : B) * b, by
        rw [pow_add]; exact Ideal.mul_mem_mul a.2 b.2⟩ := by
  ext1
  simp only [MulMemClass.coe_mul, monomialRees_coe, monomial_mul_monomial]

/-- The unit: `1 = [1·X^0] ∈ K^0/K^1`. -/
theorem monomialRees_zero_one :
    monomialRees K 0 ⟨1, by simp⟩ = 1 := by
  ext1
  simp only [monomialRees_coe, OneMemClass.coe_one, monomial_zero_left, map_one]

/-- **Leading forms are multiplicative across degrees.** `deg m a · deg n b = deg (m+n) (a·b)`. -/
theorem deg_mul (m n : ℕ) (a : (K ^ m : Ideal B)) (b : (K ^ n : Ideal B)) :
    deg K m a * deg K n b =
      deg K (m + n) ⟨(a : B) * b, by
        rw [pow_add]; exact Ideal.mul_mem_mul a.2 b.2⟩ := by
  rw [deg_apply, deg_apply, deg_apply, ← map_mul, monomialRees_mul]

/-- The unit lands in degree zero. -/
theorem deg_zero_one : deg K 0 ⟨1, by simp⟩ = 1 := by
  rw [deg_apply, monomialRees_zero_one, map_one]

/-- The **degree-shifting ideal** of the Rees algebra absorbs any monomial whose coefficient lies
one filtration step deeper: if `x ∈ K^{n+1}`, then `x·X^n ∈ shiftIdeal K`. -/
theorem monomial_mem_shiftIdeal (n : ℕ) {x : B} (hx : x ∈ K ^ (n + 1))
    (p : reesAlgebra K) (hp : (p : B[X]) = monomial n x) : p ∈ shiftIdeal K := by
  rw [pow_succ] at hx
  induction hx using Submodule.mul_induction_on' generalizing p with
  | mem_mul_mem a ha c hc =>
    -- `a ∈ K^n`, `c ∈ K`, and `p` has coefficient monomial `n (a·c)`.
    have hqa : ∀ i, (monomial n a).coeff i ∈ K ^ i := fun i => by
      rw [coeff_monomial]; split_ifs with h
      · exact h ▸ ha
      · exact zero_mem _
    have h1 : (↑(algebraMap B (reesAlgebra K) c) : B[X]) = C c := by
      simp [Polynomial.algebraMap_eq]
    have hne : p = algebraMap B (reesAlgebra K) c * ⟨monomial n a, hqa⟩ := by
      apply Subtype.ext
      rw [hp, MulMemClass.coe_mul, h1]
      rw [(rfl : (↑(⟨monomial n a, hqa⟩ : reesAlgebra K) : B[X]) = monomial n a)]
      rw [C_mul_monomial, mul_comm a c]
    rw [hne]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ hc)
  | add x hx y hy ihx ihy =>
    -- `p` has coefficient `monomial n (x+y)`; split as a sum.
    have hxn : x ∈ K ^ n := Ideal.mul_le_right hx
    have hyn : y ∈ K ^ n := Ideal.mul_le_right hy
    rw [show p = monomialRees K n ⟨x, hxn⟩ + monomialRees K n ⟨y, hyn⟩ by
      apply Subtype.ext
      rw [hp, AddMemClass.coe_add, monomialRees_coe, monomialRees_coe, ← map_add]]
    exact Ideal.add_mem _ (ihx _ rfl) (ihy _ rfl)

/-- **Leading forms kill the next filtration step.** If `k ∈ K^n` in fact lies in `K^{n+1}`, its
degree-`n` leading form vanishes. This is what makes `deg n` factor through `K^n/K^{n+1}`. -/
theorem deg_eq_zero_of_mem_succ (n : ℕ) (k : (K ^ n : Ideal B)) (hk : (k : B) ∈ K ^ (n + 1)) :
    deg K n k = 0 := by
  rw [deg_apply, mk_eq_zero_iff]
  exact monomial_mem_shiftIdeal K n hk _ (monomialRees_coe K n k)

/-! ### The graded pieces and the internal grading

The degree-`n` piece `𝒢 n := image of deg n` is a copy of `K^n/K^{n+1}` sitting inside `gr_K(B)`.
The leading-form multiplicativity `deg_mul` and unit `deg_zero_one` make the family `𝒢` a graded
monoid inside `gr_K(B)`, and the pieces generate the whole ring. (Directness of the decomposition —
which would upgrade this to a full `GradedRing` instance — is left to a follow-up; see the module
docstring.) -/

/-- The degree-`n` **graded piece** of `gr_K(B)`, the image of the leading-form map `deg n`. It is
the copy of `K^n/K^{n+1}` inside `gr_K(B)`. -/
def grPiece (n : ℕ) : Submodule B (AssociatedGraded K) :=
  LinearMap.range (deg K n)

theorem mem_grPiece {n : ℕ} {x : AssociatedGraded K} :
    x ∈ grPiece K n ↔ ∃ k : (K ^ n : Ideal B), deg K n k = x :=
  LinearMap.mem_range

theorem deg_mem_grPiece (n : ℕ) (k : (K ^ n : Ideal B)) : deg K n k ∈ grPiece K n :=
  ⟨k, rfl⟩

/-- The graded pieces form a **graded monoid** inside `gr_K(B)`: the unit sits in degree `0`, and
the product of a degree-`i` and a degree-`j` element lands in degree `i+j`. -/
instance : SetLike.GradedMonoid (grPiece K) where
  one_mem := ⟨⟨1, by simp⟩, deg_zero_one K⟩
  mul_mem i j x y hx hy := by
    obtain ⟨a, rfl⟩ := hx
    obtain ⟨b, rfl⟩ := hy
    refine ⟨⟨(a : B) * b, ?_⟩, (deg_mul K i j a b).symm⟩
    rw [pow_add]; exact Ideal.mul_mem_mul a.2 b.2

/-- The graded pieces **generate** `gr_K(B)`: every element is a finite sum of leading forms. -/
theorem iSup_grPiece : ⨆ n, grPiece K n = ⊤ := by
  rw [eq_top_iff]
  rintro x -
  obtain ⟨p, rfl⟩ := mk_surjective K x
  -- write `p` as the sum of its monomials in the Rees algebra, then map down
  have hp : p = ∑ i ∈ (p : B[X]).support,
      monomialRees K i ⟨(p : B[X]).coeff i, p.2 i⟩ := by
    apply Subtype.ext
    rw [AddSubmonoidClass.coe_finsetSum]
    simp only [monomialRees_coe]
    exact (Polynomial.as_sum_support (p : B[X]))
  rw [hp, map_sum]
  refine Submodule.sum_mem _ fun i _ => ?_
  exact Submodule.mem_iSup_of_mem i (deg_mem_grPiece K i _)

end AssociatedGraded
