import FormalSchemes.BasicOpenChart

set_option linter.style.header false

/-!
# The thickenings of a completed localization (EGA I, 10.6.10)

`FormalSchemes/BasicOpenChart.lean` identifies the **residue ring** of the completed localization
`R{1/f}` with a localization of the residue ring of `R`:

```
awayCompletionResidueEquiv : R{1/f} ⧸ (I·R{1/f}) ≃+* (R ⧸ I)_f̄
```

That is the level-`1` case, and it is what the affine basic-open chart `Spf R{1/f} ⟶ Spf R` needs on
*spaces*. Running the affine colimit property on a chart needs the same statement at **every**
level of the tower, together with the compatibility of those identifications with the tower's own
transition maps. This file supplies both.

## Why umbrella 59 wants it

The colimit property for a non-affine target (EGA I, 10.6.10) is approached by covering `X` by
affines, pulling the cover back to `|Spf R|` (`ThickeningCoverPullback.lean`), refining it by basic
opens `D(r)` (`ThickeningBasicOpenRefinement.lean`), restricting the compatible family to a chart
(`ThickeningChartRestrict.lean`), and then running the **affine** case `thickeningRestrictionEquiv`
(`IndSchemeColimitEquiv.lean`) on each chart. That last step is for the ring `R{1/r}`, so it needs
the thickenings of `R{1/r}` to be the localized thickenings of `R` — as an isomorphism of *towers*,
not just level by level. That is `awayCompletionResidueEquivPow` together with
`residueAwayMap_comp_equivPow`, over a codomain that `residueAwayMap_refl` and
`residueAwayMap_comp_residueAwayMap` establish is a tower in the first place.

Nothing in this file is geometry: no morphism of locally ringed spaces appears, and there is no
`IsAdicRing` hypothesis. The only hypothesis is `hI : I.FG`, exactly as in the level-`1` case
(`IsAdicRing` does not supply it).

## Main results

* `FormalSpectrum.awayCompletionResidueEquivPow`: `R{1/f} ⧸ (I·R{1/f})ⁿ ≃+* (R ⧸ Iⁿ)_f̄`, the
  level-`n` generalisation of `awayCompletionResidueEquiv`.
* `FormalSpectrum.awayCompletionResidueEquivPow_apply_mk` and
  `awayCompletionResidueEquivPow_comp_quotientMap`: what it does to elements coming from `R`, in
  applied and composed form. Cite these rather than unfolding the `RingEquiv`.
* `FormalSpectrum.residueAwayMap`: the transition map `(R ⧸ Iᵐ)_f̄ →+* (R ⧸ Iⁿ)_f̄` of the
  localized tower, for `n ≤ m`, with `residueAwayMap_refl` and
  `residueAwayMap_comp_residueAwayMap` saying that it is functorial — i.e. that
  `n ↦ (R ⧸ Iⁿ)_f̄` is a tower.
* `FormalSpectrum.residueAwayMap_comp_equivPow`: **the tower square commutes.** This is the
  theorem; the identifications above are levelwise, and this together with the two functoriality
  lemmas is what makes them a map of towers.
* `FormalSpectrum.residueAwayMap_comp_equivPow_step`: the same for consecutive levels, stated
  against `stepRingHom (awayCompletionIdeal I f) n`, which is the spelling the thickening tower of
  `R{1/f}` actually uses.

## Implementation notes

The composite defining `awayCompletionResidueEquivPow` is *completion does not change the
thickenings* (`AdicCompletion.quotientEquivPow`) followed by *localization commutes with quotient*
(`Localization.awayQuotientEquiv`), with `Ideal.map_pow` bridging `(Iⁿ).map` and `(I.map)ⁿ` via
`Ideal.quotEquivOfEq`.

One trap, worth stating because the level-`1` proof in `BasicOpenChart.lean` looks like a template
and is not one. That proof opens by unfolding `AdicCompletion.quotientEquiv`, which is legitimate
there because `quotientEquiv` is *defined* as `quotEquivOfEq ∘ quotientEquivPow`. Unfolding
`quotientEquivPow` itself instead exposes `RingHom.quotientKerEquivOfSurjective`, after which every
tactic fails with *"not type-correct under the `instances` transparency level"*. The fix is to not
unfold at all — `AdicCompletion.quotientEquivPow_mk` is already the API lemma and closes the goal in
one line. No transparency bump is needed anywhere in this file.

The tower square is proved by transporting it to the localization side: `residueAwayMap` is shown
equal to the conjugate of the completion-side transition map, and *that* is an equality of ring
homomorphisms out of a localization of a quotient, so `IsLocalization.ringHom_ext` followed by
`Ideal.Quotient.ringHom_ext` reduces it to elements of `R`, where it is the computation rule. Going
the other way round does not work: the source `R{1/f} ⧸ (I·R{1/f})ᵐ` is a quotient of a
*completion*, which is not generated by the image of `R`, so no `ringHom_ext` applies to it
directly.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.6 (10.6.10).
* [The Stacks Project, Tag 0AI2](https://stacks.math.columbia.edu/tag/0AI2)
-/

noncomputable section

universe u

namespace FormalSpectrum

variable {R : Type u} [CommRing R] (I : Ideal R) (f : R)

/-- **The `n`-th thickening of the completed localization is the localized `n`-th thickening**:
`R{1/f} ⧸ (I·R{1/f})ⁿ ≃+* (R ⧸ Iⁿ)_f̄`. The level-`n` generalisation of
`awayCompletionResidueEquiv`, which is the case `n = 1`.

Completion does not change the thickenings (`AdicCompletion.quotientEquivPow`) and localization
commutes with quotient (`Localization.awayQuotientEquiv`); `Ideal.map_pow` is the only bridging
needed between the two. -/
def awayCompletionResidueEquivPow (hI : I.FG) (n : ℕ) :
    (awayCompletion I f) ⧸ (awayCompletionIdeal I f) ^ n ≃+*
      Localization.Away (Ideal.Quotient.mk (I ^ n) f) :=
  (AdicCompletion.quotientEquivPow (I.map (algebraMap R (Localization.Away f)))
      (hI.map _) n).trans
    ((Ideal.quotEquivOfEq (Ideal.map_pow (algebraMap R (Localization.Away f)) I n).symm).trans
      (Localization.awayQuotientEquiv f (I ^ n)).symm)

/-- The level-`n` identification `AdicCompletion.quotientEquivPow` sends the residue of the
completion image of `b : B` to the residue of `b`.

Do **not** unfold `quotientEquivPow` here: it exposes `RingHom.quotientKerEquivOfSurjective`, after
which the goal is no longer type-correct at `instances` transparency. `quotientEquivPow_mk` is the
API lemma and closes it directly. -/
private theorem quotientEquivPow_mk_algebraMap {B : Type u} [CommRing B] (K : Ideal B) (hK : K.FG)
    (n : ℕ) (b : B) :
    AdicCompletion.quotientEquivPow K hK n
        (Ideal.Quotient.mk (AdicCompletion.idealOfDefinition K ^ n)
          (algebraMap B (AdicCompletion K B) b)) =
      Ideal.Quotient.mk (K ^ n) b := by
  rw [AdicCompletion.quotientEquivPow_mk, AlgHom.commutes, Ideal.Quotient.algebraMap_eq]

/-- **Computation rule**: on the residue of the image of `r : R`, the identification is the
localization map applied to the residue of `r`. Cite this rather than unfolding the `RingEquiv`. -/
theorem awayCompletionResidueEquivPow_apply_mk (hI : I.FG) (n : ℕ) (r : R) :
    awayCompletionResidueEquivPow I f hI n
        (Ideal.Quotient.mk ((awayCompletionIdeal I f) ^ n) (awayCompletionHom I f r)) =
      algebraMap (R ⧸ I ^ n) (Localization.Away (Ideal.Quotient.mk (I ^ n) f))
        (Ideal.Quotient.mk (I ^ n) r) := by
  rw [awayCompletionResidueEquivPow]
  simp only [RingEquiv.coe_trans, Function.comp_apply]
  simp only [awayCompletionHom, RingHom.comp_apply]
  rw [quotientEquivPow_mk_algebraMap, Ideal.quotEquivOfEq_mk, RingEquiv.symm_apply_eq,
    Localization.awayQuotientEquiv_algebraMap]
  rfl

/-- The computation rule read backwards, which is the form the tower square needs. -/
theorem awayCompletionResidueEquivPow_symm_algebraMap (hI : I.FG) (n : ℕ) (r : R) :
    (awayCompletionResidueEquivPow I f hI n).symm
        (algebraMap (R ⧸ I ^ n) (Localization.Away (Ideal.Quotient.mk (I ^ n) f))
          (Ideal.Quotient.mk (I ^ n) r)) =
      Ideal.Quotient.mk ((awayCompletionIdeal I f) ^ n) (awayCompletionHom I f r) :=
  (RingEquiv.symm_apply_eq _).mpr (awayCompletionResidueEquivPow_apply_mk I f hI n r).symm

/-- `Iⁿ` extends to `(I·R{1/f})ⁿ` along the structural map, by `map_awayCompletionHom` and
`Ideal.map_pow`. -/
theorem map_pow_awayCompletionHom (n : ℕ) :
    (I ^ n).map (awayCompletionHom I f) = (awayCompletionIdeal I f) ^ n := by
  rw [Ideal.map_pow, map_awayCompletionHom]

/-- The structural map carries `Iⁿ` into `(I·R{1/f})ⁿ`, so it descends to the `n`-th
thickenings. -/
theorem le_comap_pow_awayCompletionHom (n : ℕ) :
    I ^ n ≤ ((awayCompletionIdeal I f) ^ n).comap (awayCompletionHom I f) :=
  Ideal.map_le_iff_le_comap.mp (map_pow_awayCompletionHom I f n).le

/-- **Computation rule, composed form**: the level-`n` descent of the structural map
`R → R{1/f}`, transported along the identification, is the localization map
`R ⧸ Iⁿ → (R ⧸ Iⁿ)_f̄`. The level-`n` analogue of
`awayCompletionResidueEquiv_comp_residueRingHom`. -/
theorem awayCompletionResidueEquivPow_comp_quotientMap (hI : I.FG) (n : ℕ) :
    (awayCompletionResidueEquivPow I f hI n).toRingHom.comp
        (Ideal.quotientMap ((awayCompletionIdeal I f) ^ n) (awayCompletionHom I f)
          (le_comap_pow_awayCompletionHom I f n)) =
      algebraMap (R ⧸ I ^ n) (Localization.Away (Ideal.Quotient.mk (I ^ n) f)) := by
  refine Ideal.Quotient.ringHom_ext (RingHom.ext fun r => ?_)
  simp only [RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom]
  rw [Ideal.quotientMap_mk, awayCompletionResidueEquivPow_apply_mk]

/-- **The transition map of the localized tower**, `(R ⧸ Iᵐ)_f̄ →+* (R ⧸ Iⁿ)_f̄` for `n ≤ m`: the
functorial map of localizations induced by `Ideal.Quotient.factor`. -/
def residueAwayMap {m n : ℕ} (h : n ≤ m) :
    Localization.Away (Ideal.Quotient.mk (I ^ m) f) →+*
      Localization.Away (Ideal.Quotient.mk (I ^ n) f) :=
  IsLocalization.map (T := Submonoid.powers (Ideal.Quotient.mk (I ^ n) f))
    (Localization.Away (Ideal.Quotient.mk (I ^ n) f))
    (Ideal.Quotient.factor (Ideal.pow_le_pow_right h))
    (Submonoid.powers_le.mpr (by
      simp only [Submonoid.mem_comap]
      rw [Ideal.Quotient.factor_mk]
      exact Submonoid.mem_powers _))

/-- The transition map of the localized tower is the identity on elements coming from `R`. -/
theorem residueAwayMap_algebraMap {m n : ℕ} (h : n ≤ m) (x : R) :
    residueAwayMap I f h (algebraMap (R ⧸ I ^ m) _ (Ideal.Quotient.mk (I ^ m) x)) =
      algebraMap (R ⧸ I ^ n) _ (Ideal.Quotient.mk (I ^ n) x) := by
  rw [residueAwayMap, IsLocalization.map_eq, Ideal.Quotient.factor_mk]

/-- **The localized tower is a tower**, part one: the transition map at `n ≤ n` is the identity.

Both this and `residueAwayMap_comp_residueAwayMap` are needed for `residueAwayMap_comp_equivPow`
below to deserve the name *map of towers*: that theorem says a square commutes, and it is these
two that say the codomain of `awayCompletionResidueEquivPow` is a tower at all. -/
theorem residueAwayMap_refl (n : ℕ) : residueAwayMap I f (le_refl n) = RingHom.id _ := by
  refine IsLocalization.ringHom_ext (Submonoid.powers (Ideal.Quotient.mk (I ^ n) f)) ?_
  refine Ideal.Quotient.ringHom_ext (RingHom.ext fun r => ?_)
  simp only [RingHom.comp_apply, RingHom.id_apply]
  rw [residueAwayMap_algebraMap]

/-- **The localized tower is a tower**, part two: the transition maps compose.

Both sides are maps out of a localization of a quotient, so `IsLocalization.ringHom_ext` and
`Ideal.Quotient.ringHom_ext` reduce the goal to elements of `R`, where all three transition maps
are `residueAwayMap_algebraMap`. -/
theorem residueAwayMap_comp_residueAwayMap {k n m : ℕ} (h₁ : k ≤ n) (h₂ : n ≤ m) :
    (residueAwayMap I f h₁).comp (residueAwayMap I f h₂) = residueAwayMap I f (h₁.trans h₂) := by
  refine IsLocalization.ringHom_ext (Submonoid.powers (Ideal.Quotient.mk (I ^ m) f)) ?_
  refine Ideal.Quotient.ringHom_ext (RingHom.ext fun r => ?_)
  simp only [RingHom.comp_apply]
  rw [residueAwayMap_algebraMap, residueAwayMap_algebraMap, residueAwayMap_algebraMap]

/-- **The identifications are a map of towers.** The square

```
R{1/f} ⧸ (I·R{1/f})ᵐ  ──≃──▶  (R ⧸ Iᵐ)_f̄
      │ factor                      │ residueAwayMap
      ▼                             ▼
R{1/f} ⧸ (I·R{1/f})ⁿ  ──≃──▶  (R ⧸ Iⁿ)_f̄
```

commutes for `n ≤ m`. Together with `awayCompletionResidueEquivPow` this is what lets the affine
colimit property for `R{1/f}` be read off from the tower of `R`.

Proved on the localization side: the source of the square is a quotient of a *completion*, which is
not generated by the image of `R`, so no `ringHom_ext` applies to it; conjugating by the
identification turns the goal into an equality of maps out of a localization of a quotient, where
`IsLocalization.ringHom_ext` and `Ideal.Quotient.ringHom_ext` reduce it to the computation rule. -/
theorem residueAwayMap_comp_equivPow (hI : I.FG) {m n : ℕ} (h : n ≤ m) :
    (residueAwayMap I f h).comp (awayCompletionResidueEquivPow I f hI m).toRingHom =
      (awayCompletionResidueEquivPow I f hI n).toRingHom.comp
        (Ideal.Quotient.factor (Ideal.pow_le_pow_right h)) := by
  have key : residueAwayMap I f h =
      ((awayCompletionResidueEquivPow I f hI n).toRingHom.comp
        (Ideal.Quotient.factor (Ideal.pow_le_pow_right h))).comp
          (awayCompletionResidueEquivPow I f hI m).symm.toRingHom := by
    refine IsLocalization.ringHom_ext (Submonoid.powers (Ideal.Quotient.mk (I ^ m) f)) ?_
    refine Ideal.Quotient.ringHom_ext (RingHom.ext fun r => ?_)
    simp only [RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom]
    rw [residueAwayMap_algebraMap, awayCompletionResidueEquivPow_symm_algebraMap,
      Ideal.Quotient.factor_mk, awayCompletionResidueEquivPow_apply_mk]
  rw [key, RingHom.comp_assoc, RingEquiv.symm_toRingHom_comp_toRingHom, RingHom.comp_id]

/-- **The tower square at consecutive levels**, stated against `stepRingHom`, which is the spelling
the thickening tower of `R{1/f}` uses (`FormalSchemes/StructureSheaf.lean`). This is the form
`thickeningRestrictionEquiv` will consume on a chart. -/
theorem residueAwayMap_comp_equivPow_step (hI : I.FG) (n : ℕ) :
    (residueAwayMap I f (Nat.le_succ (n + 1))).comp
        (awayCompletionResidueEquivPow I f hI (n + 1 + 1)).toRingHom =
      (awayCompletionResidueEquivPow I f hI (n + 1)).toRingHom.comp
        (stepRingHom (awayCompletionIdeal I f) n).hom :=
  residueAwayMap_comp_equivPow I f hI (Nat.le_succ (n + 1))

section Witness

/-! ### Non-vacuity

The only hypothesis is `hI : I.FG`, which holds at `I = ⊥` — where every thickening is `R` itself
and the statements say nothing. The witness below discharges it at `I = (6) ⊆ ℤ`, which is neither
`⊥` nor `⊤`, with `f = 2`. No adic hypothesis and no witness module are involved: nothing in this
file mentions `IsAdicRing`.

**Why `(6)` and not `(2)`.** For the *residue-side* localization `(R ⧸ Iⁿ)_f̄` to be a proper
localization rather than an isomorphism, `f` has to be a non-unit modulo `I`; for it to be nonzero,
`f` must not be nilpotent there. Over `ℤ` at `I = (2)` **no such `f` exists**: `ℤ ⧸ 2ⁿ` is a local
ring, so every element is a unit or lies in the maximal ideal and is therefore nilpotent — an odd
`f` gives an isomorphism and an even one gives the zero ring. `ℤ ⧸ 6` is not local, and `2` is
neither a unit nor nilpotent in it; both facts are proved below rather than asserted, since a
non-vacuity claim is the one statement in a file that the build does not otherwise check.

Note that the *completion*-side localization is non-degenerate for either choice, since neither `2`
nor `3` is a unit in `ℤ`; it is only the residue side that `(2)` degenerates. -/

private theorem fg_sixIdeal : (Ideal.span {(6 : ℤ)}).FG :=
  Submodule.fg_span (Set.finite_singleton _)

/-- `2` is **not a unit** modulo `6`: it kills `3`, which is nonzero. -/
private theorem not_isUnit_two_mod_six :
    ¬ IsUnit (Ideal.Quotient.mk (Ideal.span {(6 : ℤ)}) 2) := by
  intro hu
  have h3 : Ideal.Quotient.mk (Ideal.span {(6 : ℤ)}) 3 = 0 := by
    refine hu.mul_left_cancel ?_
    rw [mul_zero, ← map_mul, Ideal.Quotient.eq_zero_iff_mem]
    exact Ideal.mem_span_singleton.mpr ⟨1, by ring⟩
  rw [Ideal.Quotient.eq_zero_iff_mem, Ideal.mem_span_singleton] at h3
  obtain ⟨c, hc⟩ := h3
  omega

/-- `2` is **not nilpotent** modulo `6`: `2 ^ k ≡ 0` would force `3 ∣ 2 ^ k`.

`Prime (3 : ℤ)` is not in this project's Mathlib import closure, so the divisibility is refuted
over `ℕ` through `Nat.Coprime` instead; that needs no new import. -/
private theorem not_isNilpotent_two_mod_six :
    ¬ IsNilpotent (Ideal.Quotient.mk (Ideal.span {(6 : ℤ)}) 2) := by
  rintro ⟨k, hk⟩
  rw [← map_pow, Ideal.Quotient.eq_zero_iff_mem, Ideal.mem_span_singleton] at hk
  have h3 : (3 : ℤ) ∣ 2 ^ k := dvd_trans ⟨2, by ring⟩ hk
  have hn : (3 : ℕ) ∣ 2 ^ k := by
    have hcast : ((3 : ℕ) : ℤ) ∣ ((2 ^ k : ℕ) : ℤ) := by push_cast; exact h3
    exact_mod_cast hcast
  have hc : Nat.Coprime 3 (2 ^ k) := Nat.Coprime.pow_right k (by decide)
  simpa using hc.eq_one_of_dvd hn

/-- The tower square, at an ideal that is neither `⊥` nor `⊤` and an `f` that is neither a unit nor
nilpotent modulo it (`not_isUnit_two_mod_six`, `not_isNilpotent_two_mod_six`). -/
example (n : ℕ) :
    (residueAwayMap (Ideal.span {(6 : ℤ)}) 2 (Nat.le_succ (n + 1))).comp
        (awayCompletionResidueEquivPow (Ideal.span {(6 : ℤ)}) 2 fg_sixIdeal (n + 1 + 1)).toRingHom =
      (awayCompletionResidueEquivPow (Ideal.span {(6 : ℤ)}) 2 fg_sixIdeal (n + 1)).toRingHom.comp
        (stepRingHom (awayCompletionIdeal (Ideal.span {(6 : ℤ)}) 2) n).hom :=
  residueAwayMap_comp_equivPow_step (Ideal.span {(6 : ℤ)}) 2 fg_sixIdeal n

/-- The localized tower really is a tower, at the same witness. -/
example (n : ℕ) :
    (residueAwayMap (Ideal.span {(6 : ℤ)}) 2 (Nat.le_succ n)).comp
        (residueAwayMap (Ideal.span {(6 : ℤ)}) 2 (Nat.le_succ (n + 1))) =
      residueAwayMap (Ideal.span {(6 : ℤ)}) 2 ((Nat.le_succ n).trans (Nat.le_succ (n + 1))) :=
  residueAwayMap_comp_residueAwayMap (Ideal.span {(6 : ℤ)}) 2 _ _

end Witness

end FormalSpectrum

end
