import FormalSchemes.AssociatedGraded
import Mathlib.RingTheory.AdicCompletion.Basic
import Mathlib.Algebra.DirectSum.Internal
import Mathlib.RingTheory.Noetherian.Defs
import Mathlib.LinearAlgebra.Finsupp.LinearCombination

set_option linter.style.header false

/-!
# A complete separated ring with Noetherian associated graded is Noetherian

This file proves **Atiyah–Macdonald, Proposition 10.25**: if a commutative ring `A` is complete and
separated for the `J`-adic topology (`[IsAdicComplete J A]`) and its associated graded ring
`gr_J(A)` (`AssociatedGraded J`, from `FormalSchemes/AssociatedGraded.lean`) is Noetherian, then `A`
itself is Noetherian.

This is Part 2 (the crux) of issue 98 — the completion analogue of the Hilbert basis theorem —
feeding the assembly `AdicCompletion K B` Noetherian (AM 10.26).

## Strategy (leading forms + successive approximation)

Fix an ideal `a : Ideal A`; we show it is finitely generated. Consider the **initial ideal**
`in(a) ⊆ gr_J(A)`, generated by the leading forms `deg r ⟨w, _⟩` of elements `w ∈ a`. Since
`gr_J(A)` is Noetherian, `in(a)` is generated by *finitely many* leading forms
`deg (dᵢ) ⟨xᵢ, _⟩` of elements `xᵢ ∈ a`. We claim the `xᵢ` generate `a`: given `y ∈ a`, build by
successive approximation coefficients `cᵢ` with `y = ∑ᵢ cᵢ xᵢ`; the coefficient series converges by
`IsPrecomplete` and equals `y` by `IsHausdorff`.

## Main result

* `AssociatedGraded.isNoetherianRing_of_isAdicComplete_of_isNoetherianRing_associatedGraded`

## References

* [Atiyah–Macdonald, *Introduction to Commutative Algebra*], Prop. 10.25.
* Stacks Tag 00MB, 05GH.
-/

open Polynomial DirectSum

noncomputable section

universe u

/-- If the span of a set `S` in a commutative ring is finitely generated, then already a finite
subset of `S` spans it. -/
theorem Ideal.exists_finset_subset_span_eq {C : Type*} [CommRing C] {S : Set C}
    (h : (Ideal.span S).FG) :
    ∃ G : Finset C, ↑G ⊆ S ∧ Ideal.span (↑G : Set C) = Ideal.span S := by
  classical
  obtain ⟨F, hF⟩ := h
  have hmem : ∀ f ∈ F, ∃ T : Finset C, ↑T ⊆ S ∧ f ∈ Ideal.span (↑T : Set C) := by
    intro f hf
    have : f ∈ Ideal.span S := by rw [← hF]; exact Ideal.subset_span (F.mem_coe.mpr hf)
    exact Submodule.mem_span_finite_of_mem_span this
  choose T hTS hfT using hmem
  refine ⟨F.attach.biUnion fun f => T f.1 f.2, ?_, ?_⟩
  · intro x hx
    simp only [Finset.coe_biUnion, Finset.coe_attach, Set.mem_iUnion, Finset.mem_coe] at hx
    obtain ⟨f, -, hxT⟩ := hx
    exact hTS f.1 f.2 hxT
  · apply le_antisymm
    · apply Ideal.span_le.mpr
      intro x hx
      simp only [Finset.coe_biUnion, Finset.coe_attach, Set.mem_iUnion, Finset.mem_coe] at hx
      obtain ⟨f, -, hxT⟩ := hx
      exact Ideal.subset_span (hTS f.1 f.2 hxT)
    · rw [← hF, Ideal.span_le]
      intro f hf
      have hsub : (↑(T f (F.mem_coe.mp hf)) : Set C)
          ⊆ ↑(F.attach.biUnion fun f => T f.1 f.2) := by
        intro x hx
        simp only [Finset.coe_biUnion, Finset.coe_attach, Set.mem_iUnion, Finset.mem_coe]
        exact ⟨⟨f, F.mem_coe.mp hf⟩, trivial, hx⟩
      exact Ideal.span_mono hsub (hfT f (F.mem_coe.mp hf))

namespace AssociatedGraded

variable {A : Type u} [CommRing A] (J : Ideal A)

/-- Two leading forms of the same element `v` in equal degrees agree. -/
theorem deg_congr {m m' : ℕ} (h : m = m') {v : A} (hv : v ∈ J ^ m) (hv' : v ∈ J ^ m') :
    deg J m ⟨v, hv⟩ = deg J m' ⟨v, hv'⟩ := by
  subst h; rfl

/-- Multiplicativity of leading forms with a degree/value adjustment. -/
theorem deg_mul_congr {p q n : ℕ} (h : p + q = n) (u : (J ^ p : Ideal A)) (v : (J ^ q : Ideal A))
    {w : A} (hw : w ∈ J ^ n) (hval : (u : A) * (v : A) = w) :
    deg J p u * deg J q v = deg J n ⟨w, hw⟩ := by
  subst h; rw [deg_mul]; congr 1; exact Subtype.ext hval

/-- The projection onto the degree-`n` piece fixes an element that already lies in it. -/
theorem proj_of_mem (n : ℕ) {x : AssociatedGraded J} (hx : x ∈ grPiece J n) :
    GradedRing.proj (grPiece J) n x = x := by
  rw [GradedRing.proj_apply]
  lift x to grPiece J n using hx with x'
  rw [DirectSum.decompose_coe, DirectSum.of_eq_same]

/-- The `J`-adic module filtration `J^n • ⊤` of `A` (as a module over itself) is just `J^n`. -/
theorem mem_pow_smul_top_iff {n : ℕ} {x : A} :
    x ∈ (J ^ n • ⊤ : Submodule A A) ↔ x ∈ J ^ n := by
  rw [smul_eq_mul, Ideal.mul_top]

/-- The finite leading-form data extracted from a Noetherian associated graded ring: finitely many
elements `xx i ∈ a` whose leading forms `deg (dd i) ⟨xx i, _⟩` generate the initial ideal of `a`. -/
structure LeadingData {A : Type u} [CommRing A] (J a : Ideal A) where
  /-- The (finite) index set of generators. -/
  ι : Type u
  /-- Finiteness of the index set. -/
  fintypeι : Fintype ι
  /-- The `J`-order of each generator's leading form. -/
  dd : ι → ℕ
  /-- The generators, elements of `a`. -/
  xx : ι → A
  /-- Each generator sits in the corresponding filtration step. -/
  hxJ : ∀ i, xx i ∈ J ^ dd i
  /-- Each generator lies in `a`. -/
  hxa : ∀ i, xx i ∈ a
  /-- The leading forms of the generators span the initial ideal: every element of `a` of order `r`
  has its degree-`r` leading form in their span. -/
  hspan : ∀ (r : ℕ) (w : A) (hwr : w ∈ J ^ r), w ∈ a →
    deg J r ⟨w, hwr⟩ ∈ Ideal.span (Set.range fun i => deg J (dd i) ⟨xx i, hxJ i⟩)

attribute [instance] LeadingData.fintypeι

section Approximation

variable {J} {a : Ideal A} (D : LeadingData J a)

/-- **One approximation step.** For `w ∈ a` of `J`-order at least `r`, there are coefficients
`c i ∈ J^(r - d i)` with `w - ∑ᵢ c i · xᵢ` still in `a` but of order at least `r+1`. -/
theorem oneStep (r : ℕ) (w : A) (hwa : w ∈ a) (hwr : w ∈ J ^ r) :
    ∃ c : D.ι → A, (∀ i, c i ∈ J ^ (r - D.dd i)) ∧
      w - ∑ i, c i * D.xx i ∈ a ∧ w - ∑ i, c i * D.xx i ∈ J ^ (r + 1) := by
  classical
  have hmem := D.hspan r w hwr hwa
  rw [Submodule.mem_span_range_iff_exists_fun] at hmem
  obtain ⟨cc, hcc⟩ := hmem
  simp only [smul_eq_mul] at hcc
  have hcomp : ∀ i, ∃ k : (J ^ (r - D.dd i) : Ideal A),
      deg J (r - D.dd i) k
        = (decompose (grPiece J) (cc i) (r - D.dd i) : AssociatedGraded J) := by
    intro i
    exact (mem_grPiece J).mp (SetLike.coe_mem (decompose (grPiece J) (cc i) (r - D.dd i)))
  choose k hk using hcomp
  set c : D.ι → A := fun i => if D.dd i ≤ r then (k i : A) else 0 with hc
  have hci : ∀ i, c i * D.xx i ∈ J ^ r := by
    intro i
    by_cases hle : D.dd i ≤ r
    · simp only [hc, hle, if_true]
      have := Ideal.mul_mem_mul (k i).2 (D.hxJ i)
      rwa [← pow_add, Nat.sub_add_cancel hle] at this
    · simp only [hc, hle, if_false, zero_mul]; exact zero_mem _
  refine ⟨c, ?_, ?_, ?_⟩
  · intro i
    by_cases hle : D.dd i ≤ r
    · simp only [hc, hle, if_true]; exact (k i).2
    · simp only [hc, hle, if_false]; exact zero_mem _
  · have : ∑ i, c i * D.xx i ∈ a :=
      Ideal.sum_mem _ fun i _ => Ideal.mul_mem_left _ _ (D.hxa i)
    exact Ideal.sub_mem _ hwa this
  · -- project the leading-form equation onto degree `r`
    have hterm : ∀ i, GradedRing.proj (grPiece J) r (cc i * deg J (D.dd i) ⟨D.xx i, D.hxJ i⟩)
        = deg J r ⟨c i * D.xx i, hci i⟩ := by
      intro i
      have hLeadMem : deg J (D.dd i) ⟨D.xx i, D.hxJ i⟩ ∈ grPiece J (D.dd i) :=
        deg_mem_grPiece J (D.dd i) ⟨D.xx i, D.hxJ i⟩
      by_cases hle : D.dd i ≤ r
      · rw [GradedRing.proj_apply]
        have hcoe : (decompose (grPiece J) (cc i * deg J (D.dd i) ⟨D.xx i, D.hxJ i⟩) r
            : AssociatedGraded J)
            = (decompose (grPiece J) (cc i) (r - D.dd i) : AssociatedGraded J)
              * deg J (D.dd i) ⟨D.xx i, D.hxJ i⟩ := by
          have hh := coe_decompose_mul_add_of_right_mem (grPiece J)
            (i := r - D.dd i) (a := cc i) hLeadMem
          rwa [Nat.sub_add_cancel hle] at hh
        rw [hcoe, ← hk i]
        refine deg_mul_congr J (Nat.sub_add_cancel hle) (k i) ⟨D.xx i, D.hxJ i⟩ (hci i) ?_
        simp only [hc, hle, if_true]
      · have hL : GradedRing.proj (grPiece J) r (cc i * deg J (D.dd i) ⟨D.xx i, D.hxJ i⟩) = 0 := by
          rw [GradedRing.proj_apply]
          lift (deg J (D.dd i) ⟨D.xx i, D.hxJ i⟩) to grPiece J (D.dd i) using hLeadMem with hh
          rw [decompose_mul, DirectSum.decompose_coe]
          exact coe_mul_of_apply_of_not_le (grPiece J) (decompose (grPiece J) (cc i)) hh r hle
        rw [hL]
        have hval : c i * D.xx i = 0 := by simp only [hc, hle, if_false, zero_mul]
        rw [show (⟨c i * D.xx i, hci i⟩ : (J ^ r : Ideal A)) = 0 from
          Subtype.ext (by simpa using hval), map_zero]
    have hsum : deg J r ⟨w, hwr⟩ = ∑ i, deg J r ⟨c i * D.xx i, hci i⟩ := by
      have hproj : GradedRing.proj (grPiece J) r (deg J r ⟨w, hwr⟩) = deg J r ⟨w, hwr⟩ :=
        proj_of_mem J r (deg_mem_grPiece J r ⟨w, hwr⟩)
      calc deg J r ⟨w, hwr⟩
          = GradedRing.proj (grPiece J) r (deg J r ⟨w, hwr⟩) := hproj.symm
        _ = GradedRing.proj (grPiece J) r (∑ i, cc i * deg J (D.dd i) ⟨D.xx i, D.hxJ i⟩) := by
              rw [hcc]
        _ = ∑ i, GradedRing.proj (grPiece J) r (cc i * deg J (D.dd i) ⟨D.xx i, D.hxJ i⟩) := by
              rw [map_sum]
        _ = ∑ i, deg J r ⟨c i * D.xx i, hci i⟩ := Finset.sum_congr rfl fun i _ => hterm i
    have hsum' : ∑ i, deg J r ⟨c i * D.xx i, hci i⟩
        = deg J r (∑ i, (⟨c i * D.xx i, hci i⟩ : (J ^ r : Ideal A))) := by rw [map_sum]
    have hsub : deg J r (⟨w, hwr⟩ - ∑ i, (⟨c i * D.xx i, hci i⟩ : (J ^ r : Ideal A))) = 0 := by
      rw [map_sub, ← hsum', ← hsum, sub_self]
    have hcoe : ((⟨w, hwr⟩ - ∑ i, (⟨c i * D.xx i, hci i⟩ : (J ^ r : Ideal A)))
        : (J ^ r : Ideal A)) = (w - ∑ i, c i * D.xx i : A) := by
      rw [AddSubgroupClass.coe_sub, AddSubmonoidClass.coe_finsetSum]
    have := (deg_eq_zero_iff J r _).mp hsub
    rwa [hcoe] at this

/-- The remainder state after `s` approximation steps: an element of `a` of `J`-order `≥ s`. -/
private def stateSeq (y : A) (hya : y ∈ a) : ∀ s : ℕ, {w : A // w ∈ a ∧ w ∈ J ^ s}
  | 0 => ⟨y, hya, by rw [pow_zero, Ideal.one_eq_top]; trivial⟩
  | (s + 1) =>
      let prev := stateSeq y hya s
      let step := oneStep D s prev.1 prev.2.1 prev.2.2
      ⟨prev.1 - ∑ i, step.choose i * D.xx i, step.choose_spec.2.1, step.choose_spec.2.2⟩

/-- The coefficients chosen at approximation step `s`. -/
private def coeffSeq (y : A) (hya : y ∈ a) (s : ℕ) : D.ι → A :=
  (oneStep D s (stateSeq D y hya s).1 (stateSeq D y hya s).2.1 (stateSeq D y hya s).2.2).choose

theorem coeffSeq_mem (y : A) (hya : y ∈ a) (s : ℕ) (i : D.ι) :
    coeffSeq D y hya s i ∈ J ^ (s - D.dd i) :=
  (oneStep D s (stateSeq D y hya s).1 (stateSeq D y hya s).2.1
    (stateSeq D y hya s).2.2).choose_spec.1 i

theorem stateSeq_zero (y : A) (hya : y ∈ a) : (stateSeq D y hya 0).1 = y := rfl

theorem stateSeq_succ (y : A) (hya : y ∈ a) (s : ℕ) :
    (stateSeq D y hya (s + 1)).1
      = (stateSeq D y hya s).1 - ∑ i, coeffSeq D y hya s i * D.xx i := rfl

theorem stateSeq_mem_pow (y : A) (hya : y ∈ a) (s : ℕ) :
    (stateSeq D y hya s).1 ∈ J ^ s :=
  (stateSeq D y hya s).2.2

/-- Partial sums of the coefficient series for generator `i`. -/
private def partSum (y : A) (hya : y ∈ a) (N : ℕ) (i : D.ι) : A :=
  ∑ s ∈ Finset.range N, coeffSeq D y hya s i

/-- After `N` steps the partial correction reproduces `y` up to the order-`N` remainder. -/
theorem y_sub_partSum (y : A) (hya : y ∈ a) (N : ℕ) :
    y - ∑ i, partSum D y hya N i * D.xx i = (stateSeq D y hya N).1 := by
  induction N with
  | zero =>
      simp only [partSum, Finset.range_zero, Finset.sum_empty, zero_mul, Finset.sum_const_zero,
        sub_zero, stateSeq_zero]
  | succ N ih =>
      have hps : ∀ i, partSum D y hya (N + 1) i
          = partSum D y hya N i + coeffSeq D y hya N i := by
        intro i; simp only [partSum, Finset.sum_range_succ]
      simp only [hps, add_mul, Finset.sum_add_distrib]
      rw [stateSeq_succ, ← ih]; ring

end Approximation

/-- **Atiyah–Macdonald, Prop. 10.25.** A `J`-adically complete and separated ring whose associated
graded ring `gr_J(A)` is Noetherian is itself Noetherian. -/
theorem isNoetherianRing_of_isAdicComplete_of_isNoetherianRing_associatedGraded
    {A : Type u} [CommRing A] (J : Ideal A) [IsAdicComplete J A]
    (hgr : IsNoetherianRing (AssociatedGraded J)) : IsNoetherianRing A := by
  classical
  haveI := hgr
  rw [isNoetherianRing_iff_ideal_fg]
  intro a
  set S : Set (AssociatedGraded J) :=
    {g | ∃ (r : ℕ) (w : A) (hwr : w ∈ J ^ r), w ∈ a ∧ deg J r ⟨w, hwr⟩ = g} with hS
  have hSfg : (Ideal.span S).FG := Ideal.fg_of_isNoetherianRing _
  obtain ⟨G, hGS, hGspan⟩ := Ideal.exists_finset_subset_span_eq hSfg
  have hdata : ∀ g : {x // x ∈ G},
      ∃ (r : ℕ) (w : A) (hwr : w ∈ J ^ r), w ∈ a ∧ deg J r ⟨w, hwr⟩ = (g : AssociatedGraded J) := by
    rintro ⟨g, hg⟩
    exact hGS (Finset.mem_coe.mpr hg)
  choose dd xx hxJ hxa hgen using hdata
  have hrange : (Set.range fun i : {x // x ∈ G} => deg J (dd i) ⟨xx i, hxJ i⟩)
      = (↑G : Set (AssociatedGraded J)) := by
    rw [show (fun i : {x // x ∈ G} => deg J (dd i) ⟨xx i, hxJ i⟩)
        = fun i : {x // x ∈ G} => (i : AssociatedGraded J) from funext fun i => hgen i]
    ext g; simp [Subtype.range_coe_subtype]
  have hspan : ∀ (r : ℕ) (w : A) (hwr : w ∈ J ^ r), w ∈ a →
      deg J r ⟨w, hwr⟩ ∈ Ideal.span (Set.range fun i : {x // x ∈ G} =>
        deg J (dd i) ⟨xx i, hxJ i⟩) := by
    intro r w hwr hwa
    rw [hrange, hGspan]
    exact Ideal.subset_span ⟨r, w, hwr, hwa, rfl⟩
  set D : LeadingData J a :=
    { ι := {x // x ∈ G}, fintypeι := inferInstance, dd := dd, xx := xx,
      hxJ := hxJ, hxa := hxa, hspan := hspan } with hD
  refine ⟨Finset.image D.xx Finset.univ, ?_⟩
  apply le_antisymm
  · rw [Ideal.span_le]
    intro g hg
    simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe, Finset.mem_univ, true_and] at hg
    obtain ⟨i, rfl⟩ := hg
    exact D.hxa i
  · intro y hy
    set Deg : ℕ := Finset.univ.sup D.dd with hDeg
    have hcauchy : ∀ i, ∃ L : A, ∀ n : ℕ,
        partSum D y hy (n + D.dd i) i ≡ L [SMOD (J ^ n • ⊤ : Submodule A A)] := by
      intro i
      refine IsPrecomplete.prec (inferInstanceAs (IsPrecomplete J A))
        (f := fun s => partSum D y hy (s + D.dd i) i) ?_
      intro m n hmn
      rw [SModEq.sub_mem, mem_pow_smul_top_iff]
      have hdiff : partSum D y hy (m + D.dd i) i - partSum D y hy (n + D.dd i) i
          = -∑ s ∈ Finset.Ico (m + D.dd i) (n + D.dd i), coeffSeq D y hy s i := by
        rw [partSum, partSum,
          ← Finset.sum_range_add_sum_Ico _ (by omega : m + D.dd i ≤ n + D.dd i)]
        ring
      rw [hdiff]
      apply neg_mem
      apply Ideal.sum_mem
      intro s hs
      rw [Finset.mem_Ico] at hs
      exact Ideal.pow_le_pow_right (by omega) (coeffSeq_mem D y hy s i)
    choose c hc using hcauchy
    have hgoal : y - ∑ i, c i * D.xx i = 0 := by
      apply IsHausdorff.haus (inferInstance : IsHausdorff J A)
      intro N
      rw [SModEq.zero, mem_pow_smul_top_iff]
      set M : ℕ := N + Deg with hM
      have hMD : ∀ i, D.dd i ≤ M := by
        intro i
        have : D.dd i ≤ Deg := Finset.le_sup (Finset.mem_univ i)
        omega
      have h1 : y - ∑ i, partSum D y hy M i * D.xx i ∈ J ^ N := by
        rw [y_sub_partSum]
        exact Ideal.pow_le_pow_right (by omega) (stateSeq_mem_pow D y hy M)
      have h2 : (∑ i, partSum D y hy M i * D.xx i) - ∑ i, c i * D.xx i ∈ J ^ N := by
        rw [← Finset.sum_sub_distrib]
        apply Ideal.sum_mem
        intro i _
        rw [← sub_mul]
        have hlim := hc i (M - D.dd i)
        rw [SModEq.sub_mem, mem_pow_smul_top_iff] at hlim
        have hidx : (M - D.dd i) + D.dd i = M := Nat.sub_add_cancel (hMD i)
        rw [hidx] at hlim
        have hcM : c i - partSum D y hy M i ∈ J ^ (M - D.dd i) := by
          have := neg_mem hlim; rwa [neg_sub] at this
        have hmul : (partSum D y hy M i - c i) * D.xx i ∈ J ^ (M - D.dd i) * J ^ (D.dd i) := by
          rw [show partSum D y hy M i - c i = -(c i - partSum D y hy M i) by ring]
          exact Ideal.mul_mem_mul (neg_mem hcM) (D.hxJ i)
        rw [← pow_add, hidx] at hmul
        exact Ideal.pow_le_pow_right (by omega) hmul
      have hsum := Ideal.add_mem _ h1 h2
      rw [show y - ∑ i, c i * D.xx i
          = (y - ∑ i, partSum D y hy M i * D.xx i)
            + ((∑ i, partSum D y hy M i * D.xx i) - ∑ i, c i * D.xx i) by ring]
      exact hsum
    have hyeq : y = ∑ i, c i * D.xx i := by rw [← sub_eq_zero]; exact hgoal
    rw [hyeq]
    apply Ideal.sum_mem
    intro i _
    apply Ideal.mul_mem_left
    exact Ideal.subset_span (Finset.mem_coe.mpr (Finset.mem_image_of_mem D.xx (Finset.mem_univ i)))

end AssociatedGraded
