import FormalSchemes.DiagonalClosedEmbedding

set_option linter.style.header false
set_option linter.style.setOption false
set_option linter.unusedSectionVars false

/-!
# Preimages of the affine diagonal locus

Let `(R, I)` be an adic base with `I` finitely generated, `A` a complete adic `R`-algebra, and

```
Δ : Spf A ⟶ Spf (A ⊗̂_R A)
```

the affine diagonal, whose range is the closed "diagonal locus"
(`CompletedTensorProduct.range_diagonal_base`). A recurring problem when gluing formal schemes is
to describe the **preimage of that locus** under `Spf` of a ring map `φ : A ⊗̂_R A →+* A₁ ⊗̂_R B₁`
into another completed tensor product: over a chart of a fibre product it is the *graph* of a
transition isomorphism, and one wants to see it as the range of `Spf` of a surjection.

This file supplies the two general tools for that, plus their packaging.

## Main results

* `FormalSpectrum.preimage_range_subset_range_of_ker_le`: if the level-`0` kernel of a surjection
  `g` is contained in the ideal generated by the image under `φ` of the level-`0` kernel of a
  surjection `c`, then `Spf φ ⁻¹' range (Spf c) ⊆ range (Spf g)`. This is the purely
  scheme-theoretic half, a vanishing-locus comparison.
* `CompletedTensorProduct.mem_sup_of_section`: the ring-theoretic half. If `g : A₁ ⊗̂_R B₁ →+* E`
  admits a *continuous section* `s`, then `g⁻¹(I_E)` is contained in any ideal `K ≥ I·(A₁ ⊗̂ B₁)`
  that already contains the two "graph relations" `inl a - s (g (inl a))` and
  `inr b - s (g (inr b))`. The proof is the universal property `CompletedTensorProduct.hom_ext`
  applied to the two ring maps `mk_K` and `mk_K ∘ s ∘ g` into `(A₁ ⊗̂_R B₁) ⧸ K`, using the trivial
  adic structure `⊥` on the target — so no generation statement for the completed tensor product is
  needed.
* `CompletedTensorProduct.preimage_range_diagonal_subset_range`: the two combined. Given a section
  `s` of `g` whose two graph relations lie in `(ker ∇).map φ`, the preimage of the diagonal locus
  under `Spf φ` is contained in the range of `Spf g`.
* `CompletedTensorProduct.map_inl_sub_map_inr_mem`: the graph relations are automatic whenever they
  are the image under `φ` of a diagonal generator `inl a - inr a`, which is how they arise in
  practice.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.14, §10.15.
-/

noncomputable section

open Ideal AlgebraicGeometry CategoryTheory Topology

universe u

namespace FormalSpectrum

variable {C D E A : Type*} [CommRing C] [CommRing D] [CommRing E] [CommRing A]
variable [TopologicalSpace C] [TopologicalSpace D] [TopologicalSpace E] [TopologicalSpace A]
variable (IC : Ideal C) (ID : Ideal D) (IE : Ideal E) (IA : Ideal A)
variable [IsAdicRing IC] [IsAdicRing ID] [IsAdicRing IE] [IsAdicRing IA]

omit [TopologicalSpace C] [TopologicalSpace D] [TopologicalSpace E] [TopologicalSpace A]
  [IsAdicRing IC] [IsAdicRing ID] [IsAdicRing IE] [IsAdicRing IA] in
/-- Vanishing-locus comparison at the level of prime spectra: a prime of `D ⧸ I_D` whose contraction
along `φ` contains `ker c` contains `ker g`, provided `ker g` is contained in the ideal generated by
`φ (ker c)`. -/
theorem mem_zeroLocus_ker_of_ker_le
    (φ : C →+* D) (hφ : IC ≤ ID.comap φ)
    (g : D →+* E) (hg : ID ≤ IE.comap g)
    (c : C →+* A) (hc : IC ≤ IA.comap c)
    (hker : RingHom.ker (Ideal.quotientMap IE g hg) ≤
      (RingHom.ker (Ideal.quotientMap IA c hc)).map (Ideal.quotientMap ID φ hφ))
    (p : PrimeSpectrum (D ⧸ ID))
    (hp : PrimeSpectrum.comap (Ideal.quotientMap ID φ hφ) p ∈
      PrimeSpectrum.zeroLocus (RingHom.ker (Ideal.quotientMap IA c hc))) :
    p ∈ PrimeSpectrum.zeroLocus (RingHom.ker (Ideal.quotientMap IE g hg)) := by
  rw [PrimeSpectrum.mem_zeroLocus] at hp ⊢
  have hp' : (RingHom.ker (Ideal.quotientMap IA c hc)).map (Ideal.quotientMap ID φ hφ) ≤
      p.asIdeal := Ideal.map_le_iff_le_comap.mpr hp
  exact fun z hz => hp' (hker hz)

/-- **Preimage of the range of a closed immersion.** For surjections `c : C →+* A`, `g : D →+* E`
and any adic map `φ : C →+* D`, if the level-`0` kernel of `g` is contained in the ideal generated
by the image under `φ` of the level-`0` kernel of `c`, then
`Spf φ ⁻¹' range (Spf c) ⊆ range (Spf g)`. Both ranges are vanishing loci
(`FormalSpectrum.range_map_of_surjective`), and the preimage of a vanishing locus is the vanishing
locus of the image. -/
theorem preimage_range_subset_range_of_ker_le
    (φ : C →+* D) (hφ : IC ≤ ID.comap φ)
    (g : D →+* E) (hg : ID ≤ IE.comap g) (hgs : Function.Surjective g)
    (c : C →+* A) (hc : IC ≤ IA.comap c) (hcs : Function.Surjective c)
    (hker : RingHom.ker (Ideal.quotientMap IE g hg) ≤
      (RingHom.ker (Ideal.quotientMap IA c hc)).map (Ideal.quotientMap ID φ hφ)) :
    map IC ID φ hφ ⁻¹' Set.range (map IC IA c hc) ⊆ Set.range (map ID IE g hg) := by
  intro p hp
  rw [Set.mem_preimage, range_map_of_surjective IC IA c hc hcs] at hp
  rw [range_map_of_surjective ID IE g hg hgs]
  exact mem_zeroLocus_ker_of_ker_le IC ID IE IA φ hφ g hg c hc hker p hp

omit [TopologicalSpace C] [TopologicalSpace D] [TopologicalSpace E] [TopologicalSpace A]
  [IsAdicRing IC] [IsAdicRing ID] [IsAdicRing IE] [IsAdicRing IA] in
/-- The kernel hypothesis of `FormalSpectrum.preimage_range_subset_range_of_ker_le`, reduced to a
statement about the rings themselves: it suffices that every `z : D` with `g z ∈ I_E` already lies
in `(ker c).map φ ⊔ I_D`. -/
theorem ker_quotientMap_le_map_of_mem_sup
    (φ : C →+* D) (hφ : IC ≤ ID.comap φ)
    (g : D →+* E) (hg : ID ≤ IE.comap g)
    (c : C →+* A) (hc : IC ≤ IA.comap c)
    (hmem : ∀ z : D, g z ∈ IE → z ∈ ((RingHom.ker c).map φ) ⊔ ID) :
    RingHom.ker (Ideal.quotientMap IE g hg) ≤
      (RingHom.ker (Ideal.quotientMap IA c hc)).map (Ideal.quotientMap ID φ hφ) := by
  intro w hw
  obtain ⟨z, rfl⟩ := Ideal.Quotient.mk_surjective w
  rw [RingHom.mem_ker, Ideal.quotientMap_mk, Ideal.Quotient.eq_zero_iff_mem] at hw
  have hstep : ((RingHom.ker c).map φ) ⊔ ID ≤
      ((RingHom.ker (Ideal.quotientMap IA c hc)).map (Ideal.quotientMap ID φ hφ)).comap
        (Ideal.Quotient.mk ID) := by
    refine sup_le ?_ ?_
    · rw [Ideal.map_le_iff_le_comap]
      intro t ht
      rw [Ideal.mem_comap, Ideal.mem_comap,
        show (Ideal.Quotient.mk ID) (φ t) =
          Ideal.quotientMap ID φ hφ ((Ideal.Quotient.mk IC) t) from
            (Ideal.quotientMap_mk (H := hφ)).symm]
      refine Ideal.mem_map_of_mem _ ?_
      rw [RingHom.mem_ker, Ideal.quotientMap_mk, RingHom.mem_ker.mp ht, map_zero]
    · intro t ht
      rw [Ideal.mem_comap, Ideal.Quotient.eq_zero_iff_mem.mpr ht]
      exact Submodule.zero_mem _
  exact hstep (hmem z hw)

end FormalSpectrum

namespace CompletedTensorProduct

variable {R : Type u} [CommRing R] {I : Ideal R}
variable {A B : Type u} [CommRing A] [CommRing B] [Algebra R A] [Algebra R B]
variable [TopologicalSpace R] [IsAdicRing I]
variable [TopologicalSpace (CompletedTensorProduct R I A B)]
  [IsAdicRing (idealOfDefinition R I A B)]

omit [TopologicalSpace R] [IsAdicRing I] [TopologicalSpace (CompletedTensorProduct R I A B)]
  [IsAdicRing (idealOfDefinition R I A B)] in
/-- A ring map out of `A ⊗̂_R B` killing the ideal of definition maps the powers of the ideal of
definition into the powers of `⊥`. This is the continuity hypothesis of
`CompletedTensorProduct.hom_ext` for the *discrete* target `(A ⊗̂_R B) ⧸ K`, where `K` contains the
ideal of definition. -/
private theorem mem_bot_pow_of_mem {S : Type u} [CommRing S]
    (F : CompletedTensorProduct R I A B →+* S) (hF : ∀ x ∈ idealOfDefinition R I A B, F x = 0)
    (m : ℕ) (x : CompletedTensorProduct R I A B) (hx : x ∈ (idealOfDefinition R I A B) ^ m) :
    F x ∈ (⊥ : Ideal S) ^ m := by
  rcases Nat.eq_zero_or_pos m with rfl | hm
  · rw [pow_zero, Ideal.one_eq_top]
    exact Submodule.mem_top
  · have hb : (⊥ : Ideal S) ^ m = ⊥ := by rw [← Ideal.zero_eq_bot, zero_pow hm.ne']
    rw [hb, Ideal.mem_bot]
    exact hF x (Ideal.pow_le_self hm.ne' hx)

/-- **The graph-relation criterion.** Let `g : A ⊗̂_R B →+* E` be continuous with a continuous
section `s : E →+* A ⊗̂_R B` (`g ∘ s` need not be the identity — only the displayed relations are
used), and let `K` be an ideal of `A ⊗̂_R B` containing the ideal of definition and the two *graph
relations* `inl a - s (g (inl a))`, `inr b - s (g (inr b))`. Then every `z` with `g z ∈ I_E` lies
in `K`.

The proof is `CompletedTensorProduct.hom_ext` for the two ring maps `mk_K` and `mk_K ∘ s ∘ g` into
`(A ⊗̂_R B) ⧸ K`, taken as a *discrete* adic ring (`L = ⊥`): both kill the ideal of definition, and
the graph relations say exactly that they agree on `inl` and `inr`. In particular no description of
`(A ⊗̂_R B)` modulo its ideal of definition by generators is required. -/
theorem mem_of_section (hI : I.FG) {E : Type u} [CommRing E] (IE : Ideal E)
    (g : CompletedTensorProduct R I A B →+* E)
    (hg : ∀ (m : ℕ) (x : CompletedTensorProduct R I A B),
      x ∈ (idealOfDefinition R I A B) ^ m → g x ∈ IE ^ m)
    (s : E →+* CompletedTensorProduct R I A B)
    (hs : ∀ (m : ℕ) (e : E), e ∈ IE ^ m → s e ∈ (idealOfDefinition R I A B) ^ m)
    (K : Ideal (CompletedTensorProduct R I A B)) (hJK : idealOfDefinition R I A B ≤ K)
    (hl : ∀ a : A, inl R I A B a - s (g (inl R I A B a)) ∈ K)
    (hr : ∀ b : B, inr R I A B b - s (g (inr R I A B b)) ∈ K)
    {z : CompletedTensorProduct R I A B} (hz : g z ∈ IE) : z ∈ K := by
  have hsg : ∀ x : CompletedTensorProduct R I A B, x ∈ idealOfDefinition R I A B →
      s (g x) ∈ idealOfDefinition R I A B := by
    intro x hx
    have h1 : g x ∈ IE ^ 1 := hg 1 x (by rwa [pow_one])
    have h2 := hs 1 (g x) h1
    rwa [pow_one] at h2
  have key : (Ideal.Quotient.mk K : CompletedTensorProduct R I A B →+* _) =
      (Ideal.Quotient.mk K).comp (s.comp g) := by
    refine hom_ext (⊥ : Ideal (CompletedTensorProduct R I A B ⧸ K)) hI
      (mem_bot_pow_of_mem _ fun x hx => Ideal.Quotient.eq_zero_iff_mem.mpr (hJK hx))
      (mem_bot_pow_of_mem _ fun x hx => Ideal.Quotient.eq_zero_iff_mem.mpr (hJK (hsg x hx)))
      (fun a => (Ideal.Quotient.mk_eq_mk_iff_sub_mem _ _).mpr (hl a))
      (fun b => (Ideal.Quotient.mk_eq_mk_iff_sub_mem _ _).mpr (hr b))
  have hz1 : s (g z) ∈ K := by
    have h2 := hs 1 (g z) (by rwa [pow_one])
    rw [pow_one] at h2
    exact hJK h2
  have hcong := RingHom.congr_fun key z
  simp only [RingHom.coe_comp, Function.comp_apply] at hcong
  rw [Ideal.Quotient.eq_zero_iff_mem.mpr hz1] at hcong
  exact Ideal.Quotient.eq_zero_iff_mem.mp hcong

section Package

variable {A₁ B₁ : Type u} [CommRing A₁] [CommRing B₁] [Algebra R A₁] [Algebra R B₁]
variable [TopologicalSpace A] [IsAdicRing (I.map (algebraMap R A))]
variable [TopologicalSpace (CompletedTensorProduct R I A A)]
  [IsAdicRing (idealOfDefinition R I A A)]
variable [TopologicalSpace (CompletedTensorProduct R I A₁ B₁)]
  [IsAdicRing (idealOfDefinition R I A₁ B₁)]

/-- The two legs of `A ⊗̂_R A` agree on the codiagonal, so their difference lies in `ker ∇`: this is
the generator of the diagonal ideal. -/
theorem inl_sub_inr_mem_ker_codiagonal (a : A) :
    inl R I A A a - inr R I A A a ∈ RingHom.ker (codiagonal R I A) := by
  rw [RingHom.mem_ker, map_sub, codiagonal_inl, codiagonal_inr, sub_self]

/-- **The graph relations are automatic for the image of a diagonal generator.** For any ring map
`φ` out of `A ⊗̂_R A`, the difference `φ (inl a) - φ (inr a)` lies in `(ker ∇).map φ`. In practice
`φ` is a `CompletedTensorProduct.map`, so the two terms are `inl (u a)` and `inr (v a)`, and this is
the lemma that discharges the `hl` / `hr` hypotheses of
`CompletedTensorProduct.preimage_range_diagonal_subset_range`. -/
theorem map_inl_sub_map_inr_mem {S : Type u} [CommRing S]
    (φ : CompletedTensorProduct R I A A →+* S) (a : A) :
    φ (inl R I A A a) - φ (inr R I A A a) ∈ (RingHom.ker (codiagonal R I A)).map φ := by
  rw [← map_sub]
  exact Ideal.mem_map_of_mem _ (inl_sub_inr_mem_ker_codiagonal a)

/-- **The preimage of the affine diagonal locus lies in the range of `Spf g`.** Let
`φ : A ⊗̂_R A →+* A₁ ⊗̂_R B₁` be adic and let `g : A₁ ⊗̂_R B₁ →+* E` be an adic surjection
admitting a continuous section `s`. If the two *graph relations* `inl a - s (g (inl a))` and
`inr b - s (g (inr b))` lie in the ideal generated by `φ (ker ∇)`, then

```
Spf φ ⁻¹' (range Δ_{A/R}) ⊆ range (Spf g).
```

This is the shape in which the mixed charts of a glued self-fibre product are shown to meet the
diagonal exactly in the graph of a transition isomorphism: `E` is the coordinate ring of the graph,
`g` cuts it out, and `s` is the tautological section supplied by whichever tensor leg of `g` is an
isomorphism. -/
theorem preimage_range_diagonal_subset_range (hI : I.FG)
    {E : Type u} [CommRing E] [TopologicalSpace E] (IE : Ideal E) [IsAdicRing IE]
    (φ : CompletedTensorProduct R I A A →+* CompletedTensorProduct R I A₁ B₁)
    (hφ : idealOfDefinition R I A A ≤ (idealOfDefinition R I A₁ B₁).comap φ)
    (g : CompletedTensorProduct R I A₁ B₁ →+* E)
    (hg : idealOfDefinition R I A₁ B₁ ≤ IE.comap g)
    (hgpow : ∀ (m : ℕ) (x : CompletedTensorProduct R I A₁ B₁),
      x ∈ (idealOfDefinition R I A₁ B₁) ^ m → g x ∈ IE ^ m)
    (hgs : Function.Surjective g)
    (s : E →+* CompletedTensorProduct R I A₁ B₁)
    (hspow : ∀ (m : ℕ) (e : E), e ∈ IE ^ m → s e ∈ (idealOfDefinition R I A₁ B₁) ^ m)
    (hl : ∀ a : A₁, inl R I A₁ B₁ a - s (g (inl R I A₁ B₁ a)) ∈
      (RingHom.ker (codiagonal R I A)).map φ)
    (hr : ∀ b : B₁, inr R I A₁ B₁ b - s (g (inr R I A₁ B₁ b)) ∈
      (RingHom.ker (codiagonal R I A)).map φ) :
    FormalSpectrum.map (idealOfDefinition R I A A) (idealOfDefinition R I A₁ B₁) φ hφ ⁻¹'
        Set.range ⇑(diagonal (A := A) hI).base ⊆
      Set.range (FormalSpectrum.map (idealOfDefinition R I A₁ B₁) IE g hg) := by
  rw [diagonal_base_eq hI]
  refine FormalSpectrum.preimage_range_subset_range_of_ker_le _ _ _ _ φ hφ g hg hgs
    (codiagonal R I A) (codiagonal_le_comap hI) codiagonal_surjective ?_
  refine FormalSpectrum.ker_quotientMap_le_map_of_mem_sup _ _ _ _ φ hφ g hg
    (codiagonal R I A) (codiagonal_le_comap hI) fun z hz => ?_
  exact mem_of_section hI IE g hgpow s hspow _ le_sup_right
    (fun a => Submodule.mem_sup_left (hl a)) (fun b => Submodule.mem_sup_left (hr b)) hz

end Package

end CompletedTensorProduct
