import FormalSchemes.GlueOpenCoverFactor
import FormalSchemes.OpenCoverHomExt
import FormalSchemes.GeneralFibreProductChartInter
import FormalSchemes.AffineFibreProductLRS
import FormalSchemes.SpfGammaFunctorial

set_option linter.style.header false
set_option linter.style.setOption false
set_option maxHeartbeats 3200000
set_option synthInstance.maxHeartbeats 1000000

/-!
# Uniqueness of the general fibre-product mediating morphism `X ×_{Spf R} Y`

For the fully general two-sided fibre product `X ×_{Spf R} Y` of two affine-charted glued formal
schemes `X` (charts `Spf(A i)`) and `Y` (charts `Spf(B j)`) over the affine adic base `Spf R`
(`FormalSchemes.GeneralFibreProductBothObject`), this file proves the **uniqueness half** of the
fibre-product universal property (EGA I §10.7): a morphism `Z ⟶ X ×_{Spf R} Y` out of a locally
finitely-generated formal scheme `Z` is determined by its two composites with the projections
`pr₁`, `pr₂` — provided the per-chart continuity hypotheses (unavoidable at the level of arbitrary
locally-ringed-space morphisms, issue 156) hold.

## Route

Let `m₁, m₂ : Z ⟶ X ×_{Spf R} Y` with `m₁ ≫ pr₁ = m₂ ≫ pr₁` and `m₁ ≫ pr₂ = m₂ ≫ pr₂`. Refine the
source cover of `Z` along `m₁` (`FormalScheme.GlueData.refinedCover`, issue 416): every piece `c`
is a finitely generated affine chart `Spf L_c` of `Z` whose range lands inside a single product
chart `Spf(A_{p.1} ⊗̂_R B_{p.2})` of the fibre product (`p = chartIndex c`), giving the
factorization `factor c ≫ ι p = w ≫ m₁` (`w := refined chart map`). By `OpenCover.hom_ext` it
suffices to show `w ≫ m₁ = w ≫ m₂` for every `c`.

The projection agreements force `m₂`'s image on the piece into the **same** product chart `p` (via
the range/preimage identity `range_ι_eq_pr_preimage_inter`, issue 426), so `w ≫ m₂` lifts through
the open immersion `ι p` to a second factorization `factorSnd c ≫ ι p = w ≫ m₂`. The two lifts
`factor c`, `factorSnd c : Spf L_c ⟶ Spf(A_{p.1} ⊗̂_R B_{p.2})` agree after `fibrePr₁`, `fibrePr₂`
(cancel the mono chart inclusions `ι^X`, `ι^Y`), so the affine uniqueness
`CompletedTensorProduct.fibreLift_unique_lrs` (EGA I 10.7, affine sources) gives
`factor c = factorSnd c`, whence `w ≫ m₁ = w ≫ m₂`.

The single continuity hypothesis `hcont` (continuity of the global-sections map of each `factor c`)
suffices: continuity of `factorSnd c` is *derived* from it, because the ideal of definition
`I·(A ⊗̂_R B)` is generated by `inl(I·A)` and `factor c`, `factorSnd c` agree after `fibrePr₁`.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.7.
* [Bosch, *Lectures on Formal and Rigid Geometry*, LNM 2105], §9.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum
open CompletedTensorProduct

universe u

namespace AlgebraicGeometry

namespace BothChartedFibreDatumXY

variable {R : Type u} [CommRing R] {I : Ideal R} {hI : I.FG}
variable [TopologicalSpace R] [IsAdicRing I]
variable (D : BothChartedFibreDatumXY R I hI)

/-- **Uniqueness of the general fibre-product mediating morphism** (EGA I §10.7, uniqueness half).
Two morphisms `m₁ m₂ : Z ⟶ X ×_{Spf R} Y` out of a locally finitely-generated formal scheme `Z`
that agree after both projections `pr₁`, `pr₂` coincide, provided the global-sections map of each
chart-wise factorization of `m₁` is continuous (`hcont`). -/
theorem fibreLift_unique
    (hV : letI := D.commRingA; letI := D.algebraA; letI := D.commRingB; letI := D.algebraB
      ∀ p p' (h : p ≠ p'), D.V p p' h = bothAlgDataV hI D.gX D.gY p p' h)
    (hf : letI := D.commRingA; letI := D.algebraA; letI := D.commRingB; letI := D.algebraB
      ∀ p p' (h : p ≠ p'),
        D.f p p' h = eqToHom (hV p p' h) ≫ bothAlgDataF hI D.gX D.gY p p' h)
    (ht : letI := D.commRingA; letI := D.algebraA; letI := D.commRingB; letI := D.algebraB
      ∀ p p' (h : p ≠ p'),
        D.t p p' h = eqToHom (hV p p' h) ≫ bothAlgDataT hI D.gX D.gY D.τX D.τY p p' h ≫
          eqToHom (hV p' p h.symm).symm)
    {Z : FormalScheme.{u}}
    (m₁ m₂ : Z.toLocallyRingedSpace ⟶ D.generalFibreProduct.toLocallyRingedSpace)
    (hZ : Z.LocallyFG)
    (hpr₁ : m₁ ≫ D.pr₁ hV hf ht = m₂ ≫ D.pr₁ hV hf ht)
    (hpr₂ : m₁ ≫ D.pr₂ hV hf ht = m₂ ≫ D.pr₂ hV hf ht)
    (hcont : ∀ c : Z,
      letI := D.commRingA; letI := D.algebraA; letI := D.commRingB; letI := D.algebraB
      letI := CompletedTensorProduct.isAdicRing R I
        (D.A (D.formalGlueData.chartIndex m₁ hZ c).1)
        (D.B (D.formalGlueData.chartIndex m₁ hZ c).2) hI
      CompletedTensorProduct.idealOfDefinition R I
          (D.A (D.formalGlueData.chartIndex m₁ hZ c).1)
          (D.B (D.formalGlueData.chartIndex m₁ hZ c).2) ≤
        (D.formalGlueData.refinedChart m₁ hZ c).J.comap
          (FormalSpectrum.globalSectionsMap
            (CompletedTensorProduct.idealOfDefinition R I
              (D.A (D.formalGlueData.chartIndex m₁ hZ c).1)
              (D.B (D.formalGlueData.chartIndex m₁ hZ c).2))
            (D.formalGlueData.refinedChart m₁ hZ c).J
            (D.formalGlueData.factor m₁ hZ c))) :
    m₁ = m₂ := by
  refine (D.formalGlueData.refinedCover m₁ hZ).hom_ext m₁ m₂ (fun c => ?_)
  letI := D.commRingA
  letI := D.algebraA
  letI := D.commRingB
  letI := D.algebraB
  letI := D.topologyA
  letI := D.isAdicA
  letI := D.topologyB
  letI := D.isAdicB
  -- Abbreviations local to the piece `c`.
  set P := D.formalGlueData.chartIndex m₁ hZ c with hP
  haveI : IsAdicRing (idealOfDefinition R I (D.A P.1) (D.B P.2)) :=
    CompletedTensorProduct.isAdicRing R I (D.A P.1) (D.B P.2) hI
  -- The factorization of `w ≫ m₁` through the product chart `P` (issue 416).
  have hfac : D.formalGlueData.factor m₁ hZ c ≫ D.formalGlueData.ι P =
      (D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₁ :=
    D.formalGlueData.factor_comp_ι m₁ hZ c
  -- STEP 3: `m₂`'s image on the piece lands in the same product chart `P`.
  have hsub : Set.range ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂).base ⊆
      Set.range (D.formalGlueData.ι P).base := by
    have hlem := D.range_ι_eq_pr_preimage_inter hV hf ht P
    rintro x ⟨s, rfl⟩
    refine hlem.ge ⟨?_, ?_⟩
    · rw [Set.mem_preimage]
      have e : ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂) ≫ D.pr₁ hV hf ht =
          D.formalGlueData.factor m₁ hZ c ≫ D.formalGlueData.ι P ≫ D.pr₁ hV hf ht := by
        have h1 : D.formalGlueData.factor m₁ hZ c ≫ D.formalGlueData.ι P ≫ D.pr₁ hV hf ht =
            ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₁) ≫ D.pr₁ hV hf ht :=
          (reassoc_of% hfac) (D.pr₁ hV hf ht)
        rw [h1, Category.assoc, Category.assoc, hpr₁]
      have hpt := congrArg (fun m => m.base s) e
      have hip := congrArg (fun m => m.base ((D.formalGlueData.factor m₁ hZ c).base s))
        (D.ι_pr₁ hV hf ht P)
      simp only [LocallyRingedSpace.comp_base, TopCat.comp_app] at hpt hip ⊢
      rw [hpt, hip]
      exact ⟨_, rfl⟩
    · rw [Set.mem_preimage]
      have e : ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂) ≫ D.pr₂ hV hf ht =
          D.formalGlueData.factor m₁ hZ c ≫ D.formalGlueData.ι P ≫ D.pr₂ hV hf ht := by
        have h1 : D.formalGlueData.factor m₁ hZ c ≫ D.formalGlueData.ι P ≫ D.pr₂ hV hf ht =
            ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₁) ≫ D.pr₂ hV hf ht :=
          (reassoc_of% hfac) (D.pr₂ hV hf ht)
        rw [h1, Category.assoc, Category.assoc, hpr₂]
      have hpt := congrArg (fun m => m.base s) e
      have hip := congrArg (fun m => m.base ((D.formalGlueData.factor m₁ hZ c).base s))
        (D.ι_pr₂ hV hf ht P)
      simp only [LocallyRingedSpace.comp_base, TopCat.comp_app] at hpt hip ⊢
      rw [hpt, hip]
      exact ⟨_, rfl⟩
  -- STEP 4: the second lift `factorSnd c`.
  set fSnd := LocallyRingedSpace.IsOpenImmersion.lift (D.formalGlueData.ι P)
    ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂) hsub with hfSnd
  have hfSnd_fac : fSnd ≫ D.formalGlueData.ι P =
      (D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂ := by
    rw [hfSnd]
    exact LocallyRingedSpace.IsOpenImmersion.lift_fac (D.formalGlueData.ι P)
      ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂) hsub
  -- Projection agreements: cancel the mono chart inclusions `ι^X`, `ι^Y`.
  have hproj₁ : D.formalGlueData.factor m₁ hZ c ≫ D.pr₁ChartSelf P =
      fSnd ≫ D.pr₁ChartSelf P := by
    have h1 : D.formalGlueData.factor m₁ hZ c ≫ D.formalGlueData.ι P ≫ D.pr₁ hV hf ht =
        ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₁) ≫ D.pr₁ hV hf ht :=
      (reassoc_of% hfac) (D.pr₁ hV hf ht)
    have h2 : fSnd ≫ D.formalGlueData.ι P ≫ D.pr₁ hV hf ht =
        ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂) ≫ D.pr₁ hV hf ht :=
      (reassoc_of% hfSnd_fac) (D.pr₁ hV hf ht)
    have e1 : (D.formalGlueData.factor m₁ hZ c ≫ D.pr₁ChartSelf P) ≫ D.xFormalGlueData.ι P.1 =
        ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₁) ≫ D.pr₁ hV hf ht :=
      ((Category.assoc _ _ _).trans
        (congrArg (fun t => D.formalGlueData.factor m₁ hZ c ≫ t)
          (D.ι_pr₁ hV hf ht P).symm)).trans h1
    have e2 : (fSnd ≫ D.pr₁ChartSelf P) ≫ D.xFormalGlueData.ι P.1 =
        ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂) ≫ D.pr₁ hV hf ht :=
      ((Category.assoc _ _ _).trans
        (congrArg (fun t => fSnd ≫ t) (D.ι_pr₁ hV hf ht P).symm)).trans h2
    have emid : ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₁) ≫ D.pr₁ hV hf ht =
        ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂) ≫ D.pr₁ hV hf ht := by
      rw [Category.assoc, Category.assoc, hpr₁]
    exact (cancel_mono (D.xFormalGlueData.ι P.1)).mp (e1.trans (emid.trans e2.symm))
  have hproj₂ : D.formalGlueData.factor m₁ hZ c ≫ D.pr₂ChartSelf P =
      fSnd ≫ D.pr₂ChartSelf P := by
    have h1 : D.formalGlueData.factor m₁ hZ c ≫ D.formalGlueData.ι P ≫ D.pr₂ hV hf ht =
        ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₁) ≫ D.pr₂ hV hf ht :=
      (reassoc_of% hfac) (D.pr₂ hV hf ht)
    have h2 : fSnd ≫ D.formalGlueData.ι P ≫ D.pr₂ hV hf ht =
        ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂) ≫ D.pr₂ hV hf ht :=
      (reassoc_of% hfSnd_fac) (D.pr₂ hV hf ht)
    have e1 : (D.formalGlueData.factor m₁ hZ c ≫ D.pr₂ChartSelf P) ≫ D.yFormalGlueData.ι P.2 =
        ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₁) ≫ D.pr₂ hV hf ht :=
      ((Category.assoc _ _ _).trans
        (congrArg (fun t => D.formalGlueData.factor m₁ hZ c ≫ t)
          (D.ι_pr₂ hV hf ht P).symm)).trans h1
    have e2 : (fSnd ≫ D.pr₂ChartSelf P) ≫ D.yFormalGlueData.ι P.2 =
        ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂) ≫ D.pr₂ hV hf ht :=
      ((Category.assoc _ _ _).trans
        (congrArg (fun t => fSnd ≫ t) (D.ι_pr₂ hV hf ht P).symm)).trans h2
    have emid : ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₁) ≫ D.pr₂ hV hf ht =
        ((D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂) ≫ D.pr₂ hV hf ht := by
      rw [Category.assoc, Category.assoc, hpr₂]
    exact (cancel_mono (D.yFormalGlueData.ι P.2)).mp (e1.trans (emid.trans e2.symm))
  -- Continuity of `factorSnd` is derived from that of `factor` (`hcont`).
  have hJ : idealOfDefinition R I (D.A P.1) (D.B P.2) =
      (I.map (algebraMap R (D.A P.1))).map (inl R I (D.A P.1) (D.B P.2)).toRingHom := by
    rw [idealOfDefinition_eq_map, Ideal.map_map]
    congr 1
  have hgpr : globalSectionsMap (I.map (algebraMap R (D.A P.1)))
      (idealOfDefinition R I (D.A P.1) (D.B P.2)) (D.pr₁ChartSelf P) =
      (inl R I (D.A P.1) (D.B P.2)).toRingHom :=
    globalSectionsMap_locallyRingedSpaceMap _ _ _ _
  have hcomp : (globalSectionsMap (idealOfDefinition R I (D.A P.1) (D.B P.2))
        (D.formalGlueData.refinedChart m₁ hZ c).J (D.formalGlueData.factor m₁ hZ c)).comp
        (inl R I (D.A P.1) (D.B P.2)).toRingHom =
      (globalSectionsMap (idealOfDefinition R I (D.A P.1) (D.B P.2))
        (D.formalGlueData.refinedChart m₁ hZ c).J fSnd).comp
        (inl R I (D.A P.1) (D.B P.2)).toRingHom := by
    rw [← hgpr, ← globalSectionsMap_comp, ← globalSectionsMap_comp]
    exact congrArg (globalSectionsMap (I.map (algebraMap R (D.A P.1)))
      (D.formalGlueData.refinedChart m₁ hZ c).J) hproj₁
  have hc2 : idealOfDefinition R I (D.A P.1) (D.B P.2) ≤
      (D.formalGlueData.refinedChart m₁ hZ c).J.comap
        (globalSectionsMap (idealOfDefinition R I (D.A P.1) (D.B P.2))
          (D.formalGlueData.refinedChart m₁ hZ c).J fSnd) := by
    have hc1 := hcont c
    nth_rewrite 1 [hJ] at hc1 ⊢
    rw [Ideal.map_le_iff_le_comap] at hc1 ⊢
    rw [Ideal.comap_comap, ← hcomp, ← Ideal.comap_comap]
    exact hc1
  -- STEP 5: the two lifts coincide by affine uniqueness (issue 234c/EGA I 10.7).
  have hEq : D.formalGlueData.factor m₁ hZ c = fSnd :=
    fibreLift_unique_lrs hI (D.formalGlueData.refinedChart m₁ hZ c).fg
      (D.formalGlueData.factor m₁ hZ c) fSnd (hcont c) hc2 hproj₁ hproj₂
  -- Conclude `w ≫ m₁ = w ≫ m₂`.
  have key : (D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₁ =
      (D.formalGlueData.refinedChart m₁ hZ c).map ≫ m₂ := by
    rw [← hfac, hEq, hfSnd_fac]
  exact key

end BothChartedFibreDatumXY

end AlgebraicGeometry
