import FormalSchemes.Sections

set_option linter.style.header false

/-!
# The stalk of `O_{Spf R}` is generated by sections over basic opens

`FormalSchemes.StructureSheafStalks` names the comparison `O_{Spf R, x} ⟶ lim_n O_{X_n, x}` and the
question `FormalSpectrum.IsStalkLimit` of whether it is an isomorphism, and
`FormalSchemes.StructureSheafStalkLevels` reads its target as `AdicCompletion (I · R_p) R_p`. The
*source* of that comparison — the stalk itself — was described only in prose, in a paragraph of
`FormalSchemes.StructureSheafStalks` which says of its own reading that **no declaration says
this**: that the stalk is the filtered colimit, over the basic opens `D(f)` containing `x`, of
`AdicCompletion (I · R_f) R_f`.

This file makes that reading two theorems. It does **not** build the colimit; it states the two
facts a colimit description exists in order to provide:

* every germ at `x` is the germ of a section over a **basic** open containing `x`, and hence
  (through `FormalSpectrum.sectionsBasicOpenEquiv`) the germ of an element of
  `AdicCompletion (I · R_f) R_f`;
* two sections over basic opens with the same germ at `x` already agree over a smaller basic open.

Together they say that the canonical maps `AdicCompletion (I · R_f) R_f ⟶ O_{Spf R, x}`, over the
`f` with `x ∈ D(f)`, are jointly surjective and identify exactly the pairs that agree on a smaller
basic open — which is the colimit, spelled without a colimit.

## Main results

* `FormalSpectrum.exists_basicOpen_germ_eq`: every germ comes from a section over a basic open.
* `FormalSpectrum.exists_adicCompletion_germ_eq`: the same, with the section read as an element of
  `AdicCompletion (I · R_f) R_f` through `FormalSpectrum.sectionsBasicOpenEquiv`.
* `FormalSpectrum.exists_basicOpen_res_eq`: sections over basic opens with equal germs agree over a
  smaller basic open.

## What is *not* proved here

**Anything about `FormalSpectrum.IsStalkLimit`.** This file identifies the source of the comparison;
it says nothing about the comparison, in either direction, and nothing below mentions it. The
question — the positive stalk half of EGA I 10.8 — is exactly as open as it was.

**The colimit itself, as a categorical statement.** The finality of the basic opens containing `x`
in `TopologicalSpace.OpenNhds x`, which is what would let
`CategoryTheory.Functor.Final.colimitIso` transport `TopCat.Presheaf.stalk`, is not proved. A search
for a ready-made "stalk over a basis" lemma turned up nothing usable — `Mathlib`'s
`Topology/Category/TopCat/OpenNhds.lean` has no `Final` or `IsFiltered` declaration and no
occurrence of "basis", and `Topology/Sheaves/Stalks.lean` uses `Functor.Final` once, for
`TopologicalSpace.OpenNhds.map`. **That is a negative search result, not a theorem**, and a
successor who wants the categorical form should re-run it before writing one by hand.

**The separation statement in terms of adic completions.** `FormalSpectrum.exists_basicOpen_res_eq`
is stated on sections rather than on `AdicCompletion (I · R_f) R_f`, because the restriction map
`Γ(D(f)) ⟶ Γ(D(g))` is not identified with a map of adic completions anywhere I could find. The
nearest landed statements are `FormalSpectrum.awayCompletionAwayEquiv`
(`FormalSchemes.AwayCompletionAway`), which is an isomorphism `R{1/g} ≃+* R_f{1/ḡ}` rather than a
restriction map, and the chart comparison maps of `FormalSchemes.BasicOpenImmersionSheaf`, which
are about `FormalSpectrum.basicOpenChart` and not about an inclusion of two basic opens of one
`Spf R`. Supplying that identification would upgrade the second theorem below and is a row of its
own.

## Implementation notes

Both proofs are the same two moves: take what Mathlib's germ API gives over an arbitrary open
(`TopCat.Presheaf.exists_germ_eq`, `TopCat.Presheaf.germ_eq`), then shrink the open to a basic one
with `FormalSpectrum.isTopologicalBasis_basicOpen` and
`TopologicalSpace.IsTopologicalBasis.exists_subset_of_mem_open`, transporting the section along the
restriction. In the second proof the two restriction morphisms produced that way are not
syntactically the ones in the statement; they are equal because morphisms of `Opens` are a
subsingleton, which is what the local `key` is for.

Neither statement needs `IsAdicRing`, or even a topology on `R`: they are facts about the sheaf on
the space `FormalSpectrum I` and about that space's basis.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.1 and §10.8.
* [The Stacks Project, Tag 0AIX](https://stacks.math.columbia.edu/tag/0AIX)
-/

noncomputable section

open CategoryTheory TopCat AlgebraicGeometry TopologicalSpace Opposite

universe u

namespace FormalSpectrum

variable {R : Type u} [CommRing R] (I : Ideal R)

/-- **Every germ of `O_{Spf R}` at `x` comes from a section over a basic open containing `x`.**
`TopCat.Presheaf.exists_germ_eq` produces a section over some open neighbourhood; the basic opens
are a basis (`FormalSpectrum.isTopologicalBasis_basicOpen`), so the neighbourhood may be shrunk to
one of them, and `TopCat.Presheaf.germ_res_apply` says the restricted section has the same germ. -/
theorem exists_basicOpen_germ_eq (x : FormalSpectrum I)
    (t : ToType ((structureSheaf I).presheaf.stalk x)) :
    ∃ (f : R) (hx : x ∈ basicOpen I f) (s : ToType ((structureSheaf I).presheaf.obj
      (op (basicOpen I f)))), ((structureSheaf I).presheaf.germ (basicOpen I f) x hx) s = t := by
  obtain ⟨U, hU, s, rfl⟩ := (structureSheaf I).presheaf.exists_germ_eq t
  obtain ⟨v, ⟨f, rfl⟩, hxv, hvU⟩ :=
    (isTopologicalBasis_basicOpen I).exists_subset_of_mem_open hU U.isOpen
  exact ⟨f, hxv, ((structureSheaf I).presheaf.map (homOfLE hvU).op) s,
    TopCat.Presheaf.germ_res_apply _ (homOfLE hvU) x hxv s⟩

/-- **Every germ comes from an element of a completed localization.**
`FormalSpectrum.exists_basicOpen_germ_eq` with the section read through
`FormalSpectrum.sectionsBasicOpenEquiv`, which identifies `Γ(D(f), O_{Spf R})` with
`AdicCompletion (I · R_f) R_f`.

This is the surjectivity half of the description of the stalk as the filtered colimit of the
`AdicCompletion (I · R_f) R_f` over the basic opens through `x`. -/
theorem exists_adicCompletion_germ_eq (x : FormalSpectrum I)
    (t : ToType ((structureSheaf I).presheaf.stalk x)) :
    ∃ (f : R) (hx : x ∈ basicOpen I f) (a : AdicCompletion
      (Ideal.map (algebraMap R (Localization.Away f)) I) (Localization.Away f)),
      ((structureSheaf I).presheaf.germ (basicOpen I f) x hx)
        ((sectionsBasicOpenEquiv I f).symm a) = t := by
  obtain ⟨f, hx, s, hs⟩ := exists_basicOpen_germ_eq I x t
  refine ⟨f, hx, sectionsBasicOpenEquiv I f s, ?_⟩
  rw [RingEquiv.symm_apply_apply]
  exact hs

/-- **Two sections over basic opens with the same germ agree over a smaller basic open.**
`TopCat.Presheaf.germ_eq` produces some open on which they agree; shrinking it to a basic one is
the same move as in `FormalSpectrum.exists_basicOpen_germ_eq`.

This is the separation half of the colimit description: with
`FormalSpectrum.exists_adicCompletion_germ_eq` it says that the stalk is exactly the filtered
colimit of the sections over the basic opens through `x`, without a colimit being formed. -/
theorem exists_basicOpen_res_eq (x : FormalSpectrum I) {f g : R}
    (hf : x ∈ basicOpen I f) (hg : x ∈ basicOpen I g)
    (s : ToType ((structureSheaf I).presheaf.obj (op (basicOpen I f))))
    (t : ToType ((structureSheaf I).presheaf.obj (op (basicOpen I g))))
    (h : ((structureSheaf I).presheaf.germ (basicOpen I f) x hf) s =
      ((structureSheaf I).presheaf.germ (basicOpen I g) x hg) t) :
    ∃ e : R, x ∈ basicOpen I e ∧ ∃ (hef : basicOpen I e ≤ basicOpen I f)
      (heg : basicOpen I e ≤ basicOpen I g),
      ((structureSheaf I).presheaf.map (homOfLE hef).op) s =
        ((structureSheaf I).presheaf.map (homOfLE heg).op) t := by
  obtain ⟨W, hxW, iU, iV, hst⟩ := (structureSheaf I).presheaf.germ_eq x hf hg s t h
  obtain ⟨v, ⟨e, rfl⟩, hxv, hvW⟩ :=
    (isTopologicalBasis_basicOpen I).exists_subset_of_mem_open hxW W.isOpen
  refine ⟨e, hxv, (homOfLE hvW).le.trans iU.le, (homOfLE hvW).le.trans iV.le, ?_⟩
  have key : ∀ {A B : (Opens (FormalSpectrum I))ᵒᵖ} (i j : A ⟶ B)
      (z : ToType ((structureSheaf I).presheaf.obj A)),
      ((structureSheaf I).presheaf.map i) z = ((structureSheaf I).presheaf.map j) z := by
    intro A B i j z
    rw [Subsingleton.elim i j]
  have h2 := congrArg (fun z => ((structureSheaf I).presheaf.map (homOfLE hvW).op) z) hst
  simp only [← ConcreteCategory.comp_apply, ← Functor.map_comp] at h2
  exact ((key _ (iU.op ≫ (homOfLE hvW).op) s).trans h2).trans (key _ _ t)

end FormalSpectrum
