import FormalSchemes.Sections

set_option linter.style.header false

/-!
# The stalk of `O_{Spf R}` is generated by sections over basic opens

`FormalSchemes.StructureSheafStalks` names the comparison `O_{Spf R, x} ⟶ lim_n O_{X_n, x}` and the
question `FormalSpectrum.IsStalkLimit` of whether it is an isomorphism, and
`FormalSchemes.StructureSheafStalkLevels` reads its target as `AdicCompletion (I · R_p) R_p`. The
*source* of that comparison — the stalk itself — was described only in prose, in a paragraph of
`FormalSchemes.StructureSheafStalks` which says of its own reading that **no declaration says
this**: that the stalk is the filtered colimit, over the basic opens `D(f)` containing `x`, of
`AdicCompletion (I · R_f) R_f`.

This file makes that reading two theorems. It does **not** build the colimit; it states the two
facts a colimit description exists in order to provide:

* every germ at `x` is the germ of a section over a **basic** open containing `x`, and hence
  (through `FormalSpectrum.sectionsBasicOpenEquiv`) the germ of an element of
  `AdicCompletion (I · R_f) R_f`;
* two sections over basic opens with the same germ at `x` already agree over a smaller basic open.

Together they say that the canonical maps `AdicCompletion (I · R_f) R_f ⟶ O_{Spf R, x}`, over the
`f` with `x ∈ D(f)`, are jointly surjective, and that two sections with the same image already agree
on a smaller basic open — which is the colimit, spelled without a colimit. The converse of the
second, that sections agreeing on a smaller basic open have the same germ, is
`TopCat.Presheaf.germ_res_apply` and is not restated below.

## Main results

* `FormalSpectrum.exists_basicOpen_germ_eq`: every germ comes from a section over a basic open.
* `FormalSpectrum.exists_adicCompletion_germ_eq`: the same, with the section read as an element of
  `AdicCompletion (I · R_f) R_f` through `FormalSpectrum.sectionsBasicOpenEquiv`.
* `FormalSpectrum.exists_basicOpen_res_eq`: sections over basic opens with equal germs agree over a
  smaller basic open.

## What is *not* proved here

**Anything about `FormalSpectrum.IsStalkLimit`.** This file identifies the source of the comparison;
it says nothing about the comparison, in either direction, and nothing below mentions it. The
question — the positive stalk half of EGA I 10.8 — is exactly as open as it was.

**The colimit itself, as a categorical statement.** The finality of the basic opens containing `x`
in `TopologicalSpace.OpenNhds x`, which is what would let
`CategoryTheory.Functor.Final.colimitIso` transport `TopCat.Presheaf.stalk`, is not proved, and
Mathlib does not have it: `Topology/Category/TopCat/OpenNhds.lean` declares no
`CategoryTheory.Functor.Final` or `CategoryTheory.IsFiltered` instance and does not mention a basis,
and `Topology/Sheaves/Stalks.lean` uses `CategoryTheory.Functor.Final` once, for
`TopologicalSpace.OpenNhds.map`. **That is a negative search result, not a theorem**, and a
successor who wants the categorical form should re-run it before writing one by hand.

What Mathlib *does* have, and what the two theorems below are specialisations of, is the
`∃`-statement form of the same idea: `TopCat.Presheaf.exists_mem_germ_eq_of_isBasis` and
`TopCat.Presheaf.germ_eq_of_isBasis`, both in `Topology/Sheaves/Stalks.lean` and both proved for an
arbitrary `TopologicalSpace.Opens.IsBasis`. They are what the proofs below call. The
work left over is naming the `f` — the general form produces an anonymous member of the basis, and
`FormalSpectrum.sectionsBasicOpenEquiv` needs the element of `R` that indexes it, which is why these
statements are worth having separately.

**The separation statement in terms of adic completions.** `FormalSpectrum.exists_basicOpen_res_eq`
is stated on sections rather than on `AdicCompletion (I · R_f) R_f`, because the restriction map
`Γ(D(f)) ⟶ Γ(D(g))` is not identified with a map of adic completions anywhere I could find. The
nearest landed statements are `FormalSpectrum.awayCompletionAwayEquiv`
(`FormalSchemes.AwayCompletionAway`), which is an isomorphism `R{1/g} ≃+* R_f{1/ḡ}` rather than a
restriction map, and the chart comparison maps of `FormalSchemes.BasicOpenImmersionSheaf`, which
are about `FormalSpectrum.basicOpenChart` and not about an inclusion of two basic opens of one
`Spf R`. Supplying that identification would upgrade the second theorem below and is a row of its
own.

## Implementation notes

Both proofs are three lines: apply the Mathlib lemma at `FormalSpectrum.isBasis_basicOpen`, then
destructure. The membership field of the Mathlib statements is `U ∈ Set.range (basicOpen I)`, so it
destructures directly to `⟨f, rfl⟩` and the `f` the statements below quantify over falls out with no
bridging lemma; that is the whole of the specialisation.

`FormalSpectrum.isBasis_basicOpen` is the `TopologicalSpace.Opens.IsBasis` repackaging of
`FormalSpectrum.isTopologicalBasis_basicOpen`. It had been stated in
`FormalSchemes.SpfGammaRoundTrip`, far past the point where it is first useful; this file moves it
beside the basis lemma in `FormalSchemes.FormalSpectrum`, whose `FormalSpectrum.exists_basicOpen_le`
already exists for the same reason. The alternative — restating its two lines here — would have put
a second copy of a landed lemma on the tree, and importing `FormalSchemes.SpfGammaRoundTrip` instead
would have taken this leaf's transitive closure from 7 modules to 32 for the sake of them.

Neither statement needs `IsAdicRing`, or even a topology on `R`: they are facts about the sheaf on
the space `FormalSpectrum I` and about that space's basis.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.1 and §10.8.
* [The Stacks Project, Tag 0AIX](https://stacks.math.columbia.edu/tag/0AIX)
-/

noncomputable section

open CategoryTheory TopCat AlgebraicGeometry TopologicalSpace Opposite

universe u

namespace FormalSpectrum

variable {R : Type u} [CommRing R] (I : Ideal R)

/-- **Every germ of `O_{Spf R}` at `x` comes from a section over a basic open containing `x`.**
`TopCat.Presheaf.exists_mem_germ_eq_of_isBasis` at `FormalSpectrum.isBasis_basicOpen`, whose basis
is a `Set.range`, so its anonymous member of the basis destructures to the `f` this statement
quantifies over. -/
theorem exists_basicOpen_germ_eq (x : FormalSpectrum I)
    (t : ToType ((structureSheaf I).presheaf.stalk x)) :
    ∃ (f : R) (hx : x ∈ basicOpen I f) (s : ToType ((structureSheaf I).presheaf.obj
      (op (basicOpen I f)))), ((structureSheaf I).presheaf.germ (basicOpen I f) x hx) s = t := by
  obtain ⟨U, hxU, ⟨f, rfl⟩, s, hs⟩ :=
    TopCat.Presheaf.exists_mem_germ_eq_of_isBasis (isBasis_basicOpen I)
      (structureSheaf I).presheaf x t
  exact ⟨f, hxU, s, hs⟩

/-- **Every germ comes from an element of a completed localization.**
`FormalSpectrum.exists_basicOpen_germ_eq` with the section read through
`FormalSpectrum.sectionsBasicOpenEquiv`, which identifies `Γ(D(f), O_{Spf R})` with
`AdicCompletion (I · R_f) R_f`.

This is the surjectivity half of the description of the stalk as the filtered colimit of the
`AdicCompletion (I · R_f) R_f` over the basic opens through `x`. -/
theorem exists_adicCompletion_germ_eq (x : FormalSpectrum I)
    (t : ToType ((structureSheaf I).presheaf.stalk x)) :
    ∃ (f : R) (hx : x ∈ basicOpen I f) (a : AdicCompletion
      (Ideal.map (algebraMap R (Localization.Away f)) I) (Localization.Away f)),
      ((structureSheaf I).presheaf.germ (basicOpen I f) x hx)
        ((sectionsBasicOpenEquiv I f).symm a) = t := by
  obtain ⟨f, hx, s, hs⟩ := exists_basicOpen_germ_eq I x t
  refine ⟨f, hx, sectionsBasicOpenEquiv I f s, ?_⟩
  rw [RingEquiv.symm_apply_apply]
  exact hs

/-- **Two sections over basic opens with the same germ agree over a smaller basic open.**
`TopCat.Presheaf.germ_eq_of_isBasis` at `FormalSpectrum.isBasis_basicOpen`, destructured the same
way as in `FormalSpectrum.exists_basicOpen_germ_eq`.

This is the separation half of the colimit description: with
`FormalSpectrum.exists_adicCompletion_germ_eq` it says that the stalk is exactly the filtered
colimit of the sections over the basic opens through `x`, without a colimit being formed. -/
theorem exists_basicOpen_res_eq (x : FormalSpectrum I) {f g : R}
    (hf : x ∈ basicOpen I f) (hg : x ∈ basicOpen I g)
    (s : ToType ((structureSheaf I).presheaf.obj (op (basicOpen I f))))
    (t : ToType ((structureSheaf I).presheaf.obj (op (basicOpen I g))))
    (h : ((structureSheaf I).presheaf.germ (basicOpen I f) x hf) s =
      ((structureSheaf I).presheaf.germ (basicOpen I g) x hg) t) :
    ∃ e : R, x ∈ basicOpen I e ∧ ∃ (hef : basicOpen I e ≤ basicOpen I f)
      (heg : basicOpen I e ≤ basicOpen I g),
      ((structureSheaf I).presheaf.map (homOfLE hef).op) s =
        ((structureSheaf I).presheaf.map (homOfLE heg).op) t := by
  obtain ⟨W, hxW, ⟨e, rfl⟩, hWf, hWg, he⟩ :=
    TopCat.Presheaf.germ_eq_of_isBasis (isBasis_basicOpen I) (structureSheaf I).presheaf x hf hg h
  exact ⟨e, hxW, hWf, hWg, he⟩

end FormalSpectrum
