import FormalSchemes.ActionQuotientRestrictQuotient
import FormalSchemes.TateInvNodeChartQuotientSpf

set_option linter.style.header false

/-!
# `hnode` is exactly the question whether the restricted quotient is affine formal

`AlgebraicGeometry.exists_formalScheme_of_openImmersion_spf_quotientIdeal_of_isLeftRegular_base`
(`FormalSchemes.TateInvNodeChartQuotientSpf`) leaves `hnode` as one existential: an open immersion

```
f : Spf (tateInvNodeChartQuotientIdeal …) ⟶ T_inv/⟨σ⟩
```

whose range contains `Set.range (tateInvNodeChartAmbientHom …).base`. This file removes the
existential and the range condition, and leaves an isomorphism.

The reason it can is that the set to be covered is not merely contained in the named open
`AlgebraicGeometry.tateInvNodeChartQuotientOpens` — it **is** that open, by
`AlgebraicGeometry.range_tateInvNodeChartAmbientHom`, whose right-hand side is the very image the
open is defined to be. So an open immersion with the required range is the inclusion of that open,
and the whole residue is whether its source `T_inv/⟨σ⟩ |_{V₀}` is `Spf` of the ring the tree has
already computed for it.

Restricting further, `AlgebraicGeometry.LocallyRingedSpace.isActionQuotient_restrictπ`
(`FormalSchemes.ActionQuotientRestrictQuotient`) says `T_inv/⟨σ⟩ |_{V₀}` is itself an action
quotient — of `T_inv |_{π ⁻¹ V₀}`, which is the saturation of one patch's node-chart locus
(`AlgebraicGeometry.preimage_tateInvNodeChartQuotientOpens`) — so the residue can be stated with
no quotient of the whole chain in it at all, only the coequalizer of the restricted action. That
is the invariant-sections shape issue 69's row asks for. The one candidate whose range is exactly
that open — the morphism out of `Spf` of a single patch's chart ring — is refuted for `I ≠ ⊤` by
`AlgebraicGeometry.not_isOpenImmersion_tateInvNodeChartAmbientHom_of_ne_top`, which is a statement
about that morphism and not about every open of the chain; what is left is a source built from
sections invariant on the saturation, and the statement below is that hypothesis and nothing more.

## Main results

* `AlgebraicGeometry.LocallyRingedSpace.exists_isOpenImmersion_of_iso_restrict`: general. An
  isomorphism onto `Y|_V` gives an open immersion into `Y` whose range contains any subset of `V`.
* `AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso`: general. The global sections of
  `Y|_V` are the sections of `Y` over `V` — an isomorphism and **not** an equality; see the
  implementation note.
* `AlgebraicGeometry.preimage_tateInvNodeChartQuotientOpens`: the preimage of `V₀` in the chain is
  the saturation of the node-chart locus.
* `AlgebraicGeometry.isActionQuotient_restrictπ_tateInvNodeChartQuotientOpens` and
  `AlgebraicGeometry.tateInvNodeChartRestrictedActionQuotientIso`: `T_inv/⟨σ⟩ |_{V₀}` is the
  quotient of `T_inv |_{π ⁻¹ V₀}` by the restricted action, and is isomorphic to the coequalizer
  of that action.
* `AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens`: **the
  reduction.** Over a principal base ideal generated by a non-zero-divisor, `T_inv/⟨σ⟩` is a
  formal scheme as soon as `T_inv/⟨σ⟩ |_{V₀}` is isomorphic to `Spf` of the ring
  `AlgebraicGeometry.tateInvNodeChartQuotientIdeal` is an ideal of.
* `AlgebraicGeometry.exists_formalScheme_of_iso_actionQuotient_tateInvNodeChartRestrictedAction`:
  the same with the target rewritten as the coequalizer of
  `AlgebraicGeometry.tateInvNodeChartRestrictedAction`.

## Implementation notes

`Γ (Y|_V, ⊤)` is not definitionally `Γ (Y, V)`: the restriction's `⊤` presents as
`V.isOpenEmbedding.isOpenMap.functor.obj ⊤`, and `rfl` fails. The two opens are equal by Mathlib's
`TopologicalSpace.Opens.isOpenEmbedding_obj_top`, and the bridge is that equality transported by
`CategoryTheory.Functor.mapIso`; the `Iso.symm` is needed, since without it the `eqToIso` faces
the wrong way and the application does not typecheck.

## What is *not* proved here

**`hnode` is still undecided, and nothing here attempts it.** No isomorphism is constructed: both
reductions take one as a hypothesis. What changes is the shape of the hypothesis — from "there
exists an open immersion with a prescribed range" to "one named restricted space is affine
formal", and then to a statement about the coequalizer of an action on an open of the chain, with
`T_inv/⟨σ⟩` no longer mentioned.

Nothing here says the restricted quotient *is* affine formal, and nothing here bears on
`AlgebraicGeometry.LocallyRingedSpace.IsFreeProperlyDiscontinuous` for the Tate action, which
`AlgebraicGeometry.not_isFreeProperlyDiscontinuous_tateInvPeriodAction` refutes globally.

Both general lemmas would read better in `FormalSchemes.OpenImmersionIsoOfRangeEq`, next to
`AlgebraicGeometry.LocallyRingedSpace.range_ofRestrict`. They are here instead because that
module's reverse closure is **302** of the project's 520 modules against this leaf's **0**, both
recomputed from the `import` lines at this commit. Moving
`AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso` would cost only that rebuild — its
proof cites nothing outside Mathlib. Moving
`AlgebraicGeometry.LocallyRingedSpace.exists_isOpenImmersion_of_iso_restrict` would cost the
rebuild *and* a decision about
`AlgebraicGeometry.LocallyRingedSpace.exists_isOpenImmersion_of_iso`, which it calls and which
lives in `FormalSchemes.TateInvNodeChartQuotientSpf`, downstream of the proposed home.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.6.
* [Deligne–Rapoport, *Les schémas de modules de courbes elliptiques*], II.1 — the Néron 1-gon.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite

universe u

namespace AlgebraicGeometry

namespace LocallyRingedSpace

/-- **An isomorphism onto `Y|_V` gives an open immersion into `Y` covering `V`.** The composite
`e.hom ≫ Y.ofRestrict V.isOpenEmbedding` is an open immersion with range `V`, so any subset of `V`
lies in its range. General; this is the form in which a chart hypothesis stated as an existential
over open immersions is met by an isomorphism with a restriction.

Proved from `AlgebraicGeometry.LocallyRingedSpace.exists_isOpenImmersion_of_iso` at `e.symm`,
whose input is the inclusion `Y|_V ⟶ Y` and whose range is
`AlgebraicGeometry.LocallyRingedSpace.range_ofRestrict`. -/
theorem exists_isOpenImmersion_of_iso_restrict {X Y : LocallyRingedSpace.{u}}
    (V : Opens Y.toTopCat) (e : X ≅ Y.restrict V.isOpenEmbedding) {T : Set Y.toTopCat}
    (hT : T ⊆ (V : Set Y.toTopCat)) :
    ∃ f : X ⟶ Y, LocallyRingedSpace.IsOpenImmersion f ∧ T ⊆ Set.range f.base :=
  exists_isOpenImmersion_of_iso e.symm
    ⟨Y.ofRestrict V.isOpenEmbedding, inferInstance,
      (LocallyRingedSpace.range_ofRestrict Y V).symm ▸ hT⟩

/-- **The global sections of `Y|_V` are the sections of `Y` over `V`.** An isomorphism, not an
equality: the restriction's `⊤` presents as `V.isOpenEmbedding.isOpenMap.functor.obj ⊤`, so `rfl`
fails on the two rings even though the two opens are equal by
`TopologicalSpace.Opens.isOpenEmbedding_obj_top`.

General. It is what turns a statement about an ideal of `Γ (Y, V)` — such as
`AlgebraicGeometry.tateInvNodeChartQuotientIdeal` — into a statement about the global sections of
the restricted space, which is the side a formal-spectrum comparison is stated on. -/
def restrictTopSectionsIso (Y : LocallyRingedSpace.{u}) (V : Opens Y.toTopCat) :
    (Y.restrict V.isOpenEmbedding).presheaf.obj (op ⊤) ≅ Y.presheaf.obj (op V) :=
  Y.presheaf.mapIso (eqToIso V.isOpenEmbedding_obj_top).symm.op

end LocallyRingedSpace

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

/-! ### The restricted quotient at the node chart's open -/

/-- **The preimage of the node chart's open is the saturation of the node chart locus.**
`AlgebraicGeometry.preimage_tateInvSaturateQuotientOpens` at
`AlgebraicGeometry.tateInvNodeChartLocus`; stated separately because it is what identifies the
source of the restricted projection below as an open of the chain that the tree already knows the
invariant sections of. -/
theorem preimage_tateInvNodeChartQuotientOpens :
    (Opens.map (actionQuotientπ (tateInvPeriodAction R I q hq hI)).toShHom.hom.base).obj
        (tateInvNodeChartQuotientOpens R I q hq hI) =
      tateInvSaturateOpens hq hI (isOpen_tateInvNodeChartLocus R I q) :=
  preimage_tateInvSaturateQuotientOpens (isOpen_tateInvNodeChartLocus R I q)

/-- **The `σ`-action restricted to the saturated node-chart locus.**
`AlgebraicGeometry.LocallyRingedSpace.restrictAction` of
`AlgebraicGeometry.tateInvPeriodAction` at the preimage of
`AlgebraicGeometry.tateInvNodeChartQuotientOpens`, which is invariant for the formal reason that
it is a preimage along an invariant morphism. Named so that the reduction below can be read
without the invariance proof in the way; by
`AlgebraicGeometry.preimage_tateInvNodeChartQuotientOpens` the space it acts on is the saturation
of the node chart locus. -/
def tateInvNodeChartRestrictedAction :
    Multiplicative ℤ →* Aut ((tateChainInv R I q hq hI).toLocallyRingedSpace.restrict
      ((Opens.map (actionQuotientπ (tateInvPeriodAction R I q hq hI)).toShHom.hom.base).obj
        (tateInvNodeChartQuotientOpens R I q hq hI)).isOpenEmbedding) :=
  LocallyRingedSpace.restrictAction (tateInvPeriodAction R I q hq hI) _
    (LocallyRingedSpace.isInvariantOpen_preimage
      (isActionQuotient_actionQuotientπ (tateInvPeriodAction R I q hq hI)).isInvariant
      (tateInvNodeChartQuotientOpens R I q hq hI))

/-- **The restricted projection exhibits `T_inv/⟨σ⟩ |_{V₀}` as a quotient.**
`AlgebraicGeometry.LocallyRingedSpace.isActionQuotient_restrictπ` at the node chart's open. -/
def isActionQuotient_restrictπ_tateInvNodeChartQuotientOpens :
    IsActionQuotient (tateInvNodeChartRestrictedAction R I q hq hI)
      (LocallyRingedSpace.restrictπ (actionQuotientπ (tateInvPeriodAction R I q hq hI))
        (tateInvNodeChartQuotientOpens R I q hq hI)) :=
  LocallyRingedSpace.isActionQuotient_restrictπ
    (isActionQuotient_actionQuotientπ (tateInvPeriodAction R I q hq hI))
    (tateInvNodeChartQuotientOpens R I q hq hI)

/-- **`T_inv/⟨σ⟩ |_{V₀}` is the coequalizer of the restricted action.** The comparison morphism
`AlgebraicGeometry.LocallyRingedSpace.restrictπComparison` is an isomorphism by
`AlgebraicGeometry.LocallyRingedSpace.isIso_restrictπComparison`; this is that isomorphism at the
node chart's open, which is what lets the reduction below be stated without `T_inv/⟨σ⟩` in the
hypothesis. -/
def tateInvNodeChartRestrictedActionQuotientIso :
    actionQuotient (tateInvNodeChartRestrictedAction R I q hq hI) ≅
      (actionQuotient (tateInvPeriodAction R I q hq hI)).restrict
        (tateInvNodeChartQuotientOpens R I q hq hI).isOpenEmbedding :=
  @asIso _ _ _ _ _
    (LocallyRingedSpace.isIso_restrictπComparison
      (isActionQuotient_actionQuotientπ (tateInvPeriodAction R I q hq hI))
      (tateInvNodeChartQuotientOpens R I q hq hI))

/-! ### The reduction -/

/-- **`hnode`'s residue as one isomorphism.** Over a principal base ideal generated by a
non-zero-divisor, `T_inv/⟨σ⟩` is a formal scheme as soon as its restriction to the node chart's
open `AlgebraicGeometry.tateInvNodeChartQuotientOpens` is isomorphic to the formal spectrum of its
own sections there, taken with the adic topology of
`AlgebraicGeometry.tateInvNodeChartQuotientIdeal`.

This is
`AlgebraicGeometry.exists_formalScheme_of_openImmersion_spf_quotientIdeal_of_isLeftRegular_base`
with its existential discharged by
`AlgebraicGeometry.LocallyRingedSpace.exists_isOpenImmersion_of_iso_restrict`. The range condition
of that theorem is not weakened here but met exactly:
`AlgebraicGeometry.range_tateInvNodeChartAmbientHom` computes the set to be covered as the image
of the saturation, which is by definition the open being restricted to.

**It does not decide `hnode`.** The isomorphism is a hypothesis, and no declaration on this tree
produces one. -/
theorem exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens (t : R)
    (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t)
    (he :
      letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
          (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
        (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
      haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
        isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
      Nonempty (FormalSpectrum.locallyRingedSpaceObj
          (tateInvNodeChartQuotientIdeal R I q hq hI) ≅
        (actionQuotient (tateInvPeriodAction R I q hq hI)).restrict
          (tateInvNodeChartQuotientOpens R I q hq hI).isOpenEmbedding)) :
    ∃ X : FormalScheme.{u},
      X.toLocallyRingedSpace = actionQuotient (tateInvPeriodAction R I q hq hI) := by
  letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
    (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
  haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
    isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
  refine exists_formalScheme_of_openImmersion_spf_quotientIdeal_of_isLeftRegular_base
    R I q hq hI t ht hreg ?_
  exact LocallyRingedSpace.exists_isOpenImmersion_of_iso_restrict
    (tateInvNodeChartQuotientOpens R I q hq hI) he.some
    (range_tateInvNodeChartAmbientHom R I q hq hI
      (isActionQuotient_actionQuotientπ (tateInvPeriodAction R I q hq hI))).le

/-- **The same reduction with `T_inv/⟨σ⟩` removed from the hypothesis.** It is enough that the
coequalizer of `AlgebraicGeometry.tateInvNodeChartRestrictedAction` — an action on an open of the
chain, namely the saturation of the node chart locus by
`AlgebraicGeometry.preimage_tateInvNodeChartQuotientOpens` — is the formal spectrum of
`AlgebraicGeometry.tateInvNodeChartQuotientIdeal`'s ring.

`AlgebraicGeometry.tateInvNodeChartRestrictedActionQuotientIso` moves the hypothesis of
`AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens` across, and
that is the whole proof. What it buys is that the outstanding statement no longer mentions the
quotient of the whole chain: it is a statement about invariant data on one saturated open, which
is where the source has to come from once
`AlgebraicGeometry.not_isOpenImmersion_tateInvNodeChartAmbientHom_of_ne_top` has refuted, for
`I ≠ ⊤`, the one morphism whose range is exactly that open. That refutation is about that morphism
and about no other, and nothing here claims more of it.

**It does not decide `hnode`.** -/
theorem exists_formalScheme_of_iso_actionQuotient_tateInvNodeChartRestrictedAction (t : R)
    (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t)
    (he :
      letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
          (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
        (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
      haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
        isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
      Nonempty (FormalSpectrum.locallyRingedSpaceObj
          (tateInvNodeChartQuotientIdeal R I q hq hI) ≅
        actionQuotient (tateInvNodeChartRestrictedAction R I q hq hI))) :
    ∃ X : FormalScheme.{u},
      X.toLocallyRingedSpace = actionQuotient (tateInvPeriodAction R I q hq hI) :=
  exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens R I q hq hI t ht hreg
    ⟨he.some ≪≫ tateInvNodeChartRestrictedActionQuotientIso R I q hq hI⟩

end AlgebraicGeometry
