import FormalSchemes.AdicSectionsRestrictOpen
import FormalSchemes.TateInvNodeChartAdicSections

set_option linter.style.header false

/-!
# The node chart's adicity condition, restated on the chain

`FormalSchemes.TateInvNodeChartAdicSections` reduces `hnode`, over a principal base ideal generated
by a non-zero-divisor, to four things: a witness of
`AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG` at `AlgebraicGeometry.nodeChartPsi`, a
witness of `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.OverlapAdic`, an invariance and an
isomorphism. **None of the four has ever been attempted at the source.** This file makes the first
of them a question that can be attempted: it removes the quotient and the restriction from the
statement, leaving an inequality of ideals in a chart ring of the *chain*.

## What the condition says after this file

`AlgebraicGeometry.adicSectionsLocallyFG_nodeChartPsi_iff_awayIdeal`:

```
AdicSectionsLocallyFG (tateInvNodeChartQuotientIdeal …) (nodeChartPsi …) ↔
  ∀ y ∈ nodeChartSaturationOpens …,
    ∃ (d : AffineChart (tateChainInv …) y) (hd : Set.range d.map.base ⊆ nodeChartSaturationOpens …),
      d.I.FG ∧ tateInvNodeChartAwayIdeal … ≤ d.I.comap (…)
```

The left-hand side is a predicate on `AlgebraicGeometry.nodeChartSaturationFormalScheme`, an open
formal subscheme of the chain; the right-hand side quantifies over affine charts of the **chain**
itself, sitting inside the saturated node-chart locus, and the ideal being bounded is
`AlgebraicGeometry.tateInvNodeChartAwayIdeal` — an ideal of
`AlgebraicGeometry.tateInvNodeChartAwaySubring`, a subring of `A{1/(x + y − 1)}`. No
`AlgebraicGeometry.FormalScheme.restrictOpen` and no `⊤` remain on the right, and the ideal on the
left of the bound mentions the quotient nowhere. **The quotient has not left the statement**:
`CategoryTheory.actionQuotientπ` is still there, inside the elided ring homomorphism the bound is
taken along, and removing it is exactly the computation the next section records as not performed
here.

**It is an equivalence.** A chart family for which the bound provably fails refutes the predicate,
so this reduction is usable for a negative answer as well as a positive one — which was the point
of proving `AlgebraicGeometry.FormalScheme.adicSectionsLocallyFG_restrictOpen_iff` in both
directions rather than only the direction a witness needs.

`AlgebraicGeometry.adicSectionsLocallyFG_nodeChartPsi_of_charts` puts the right-hand side directly
into the `hX` slot of `AlgebraicGeometry.exists_formalScheme_of_adicSections`, under that theorem's
own `letI`/`haveI` packaging, so the reduction is checked against the consumer and not only against
itself.

## The map the bound is taken along, and where it is not yet computed

The right-hand side's ring homomorphism is

```
tateInvNodeChartAwaySubring  --(tateInvNodeChartQuotientRingEquiv).symm-->  Γ (T_inv/⟨σ⟩, V₀)
   --(actionQuotientπ …).c.app V₀-->  Γ (T_inv, π⁻¹ V₀)  --d.opensSectionsHom-->  d.R
```

and **this file does not compute it at any chart.** That is the residue, and it is worth being
precise about what is known:

* the middle map, followed by restriction to the patch at index `0`, is
  `AlgebraicGeometry.tateInvChartSectionHom` (`FormalSchemes.TateInvQuotientChartRing`), out of
  which `AlgebraicGeometry.tateInvChartRingEquiv` — and hence
  `AlgebraicGeometry.tateInvNodeChartQuotientRingEquiv` — is built. So on the patch at index `0` the
  composite of the first two maps is *inverse* to a restriction, which is why the expected answer at
  a chart inside that patch is that the composite is the subring inclusion into
  `FormalSpectrum.awayCompletion`, whose contraction of
  `FormalSpectrum.awayCompletionIdeal` is `AlgebraicGeometry.tateInvNodeChartAwayIdeal` **by
  definition**;
* the saturated locus is not inside one patch, so the other points need the translate of that
  computation, and nothing on the tree performs it;
* `AlgebraicGeometry.LocallyRingedSpace.sectionsMapOfRangeSubset_comp_opens`
  (`FormalSchemes.AdicSectionsRestrictOpen`) is the shape that computation takes — a chart of a
  glued object factors through a patch inclusion whose own range is *not* inside the open, so the
  plain functoriality lemma does not apply to it.

**None of this is a proof and none of it is claimed as one.** In particular the second bullet is
where a witness would have to do work that nothing here does, and the first is an expectation about
a composite that has not been evaluated.

## The contraction, which is not the obstruction it was billed as

`AlgebraicGeometry.tateInvNodeChartAwayIdeal` is a *contraction* — of
`FormalSpectrum.awayCompletionIdeal` along the inclusion of
`AlgebraicGeometry.tateInvNodeChartAwaySubring` — and can be strictly larger than the ideal
generated by the image of the base ideal `I`. That was recorded as the hard point of this question,
on the reading that the bound would have to be proved for every element of the contraction from a
statement about `I` alone. The reduction above shows the reading is the wrong way round: the bound
is a containment `tateInvNodeChartAwayIdeal ≤ d.I.comap (…)`, so a factorisation of the map through
the *ambient* `A{1/(x + y − 1)}` would discharge it from the ambient's own ideal of definition, and
the contraction is exactly what makes such a factorisation sufficient rather than insufficient.
**Whether the map so factors is the open question**, and it is a different one from the one the
contraction was thought to pose.

## Main definitions and results

* `AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso_inv_eq`: the general bridge —
  `AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso`'s inverse is
  `AlgebraicGeometry.LocallyRingedSpace.sectionsMapOfRangeSubset` of the restriction's inclusion.
* `AlgebraicGeometry.FormalScheme.restrictOpenTopSectionsHom_eq`: the same, for
  `AlgebraicGeometry.FormalScheme.restrictOpen`.
* `AlgebraicGeometry.nodeChartPsi_eq`: `AlgebraicGeometry.nodeChartPsi` is the projection's section
  map at the node chart's open, read through that identification — the shape the criterion consumes.
* `AlgebraicGeometry.adicSectionsLocallyFG_nodeChartPsi_iff`: **the reduction**, with the ideal
  still on the quotient's sections.
* `AlgebraicGeometry.le_comap_tateInvNodeChartQuotientIdeal_iff` and
  `AlgebraicGeometry.adicSectionsLocallyFG_nodeChartPsi_iff_awayIdeal`: the same with
  `AlgebraicGeometry.tateInvNodeChartAwayIdeal` in place of
  `AlgebraicGeometry.tateInvNodeChartQuotientIdeal`, which is what removes the quotient from the
  ideal.
* `AlgebraicGeometry.adicSectionsLocallyFG_nodeChartPsi_of_charts`: the reduced condition in the
  packaging `AlgebraicGeometry.exists_formalScheme_of_adicSections` asks for.

## What is *not* proved here

**`hnode` is undecided, in both directions, and nothing here moves it.** Scoring the residue of
`AlgebraicGeometry.exists_formalScheme_of_adicSections` as it stands after this file, its
hypothesis is one `∃` bundling four things and **all four are open**:

1. `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG` at `AlgebraicGeometry.nodeChartPsi` —
   restated here, **not decided here**. What changed is the spelling: it is now an inequality of
   ideals in a chart ring of the chain, and it is an equivalence, so either answer to it is an
   answer to this hypothesis.
2. `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.OverlapAdic` — untouched. It is a condition
   on charts of the *overlaps* of a cover, not on charts of the source, so nothing here applies to
   it, and `FormalSchemes.AdicSectionsChart`'s module docstring records a further open question
   about it.
3. Invariance of `AlgebraicGeometry.nodeChartAdicHom` under
   `AlgebraicGeometry.tateInvNodeChartRestrictedAction` — untouched, and not attempted anywhere.
4. `IsIso` of the descended morphism — untouched, and not attempted anywhere.

**Even a witness of the first would not move `hnode`.** The chain back runs through
`AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens`, which is
one-way, and 2, 3 and 4 would all still be open. Nothing here should be read as evidence for or
against the node chart existing.

**No chart of the chain inside the saturated locus is exhibited**, with or without the bound. The
right-hand side of the reduction is an existential over charts and this file produces no instance of
it; `AlgebraicGeometry.tateChainInv_locallyFG` produces charts at every point of the chain but says
nothing about their ranges or about the bound.

**Nothing here bears on `AlgebraicGeometry.tateInvNodeChartAmbientHom`.**
`AlgebraicGeometry.not_isOpenImmersion_tateInvNodeChartAmbientHom_of_ne_top` refutes it as an open
immersion and that refutation is untouched; the factorisation discussed above is a statement about
*section maps*, which is neither implied by nor implies anything about open immersions, and it is
not proved here either.

## Implementation notes

`AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso_inv_eq` is a **general** statement
about `AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso` and belongs beside it, in
`FormalSchemes.TateInvNodeChartRestrictedQuotient`. It is here because that file does not import
`FormalSchemes.AdicSectionsRestrictOpen` and would have to, for one lemma that only this file's
successors will use. A session that moves `restrictTopSectionsIso` to a general home should take it
along.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.4 (10.4.6), §10.6.
* [Deligne–Rapoport, *Les schémas de modules de courbes elliptiques*], II.1 — the Néron 1-gon.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite

universe u

namespace AlgebraicGeometry

namespace LocallyRingedSpace

/-- **The global sections of a restriction, as a section map.** Both sides are the image, under the
presheaf of `Y`, of a morphism between two spellings of `V` in the poset of opens, so they agree;
what the statement
buys is that a `ψ` built with `AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso` — which
is how the tree spells "a section over `V`, read on the restriction" — is one the criterion of
`FormalSchemes.AdicSectionsRestrictOpen` applies to. -/
theorem restrictTopSectionsIso_inv_eq (Y : LocallyRingedSpace.{u}) (V : Opens Y.toTopCat)
    (h : Set.range (Y.ofRestrict V.isOpenEmbedding).base ⊆ (V : Set Y)) :
    (restrictTopSectionsIso Y V).inv =
      sectionsMapOfRangeSubset (Y.ofRestrict V.isOpenEmbedding) V h := by
  rw [sectionsMapOfRangeSubset, restrictTopSectionsIso, Functor.mapIso_inv]
  erw [← Y.presheaf.map_comp]
  congr 1

end LocallyRingedSpace

namespace FormalScheme

/-- The same identification with the open formal subscheme in place of the bare restriction. The
two objects are definitionally equal, so this is
`AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso_inv_eq` with the inclusion spelled
`AlgebraicGeometry.FormalScheme.restrictOpenι`. -/
theorem restrictOpenTopSectionsHom_eq (X : FormalScheme.{u}) (hX : X.LocallyFG) (U : Opens X) :
    X.restrictOpenTopSectionsHom hX U =
      (LocallyRingedSpace.restrictTopSectionsIso X.toLocallyRingedSpace U).inv.hom := by
  rw [restrictOpenTopSectionsHom,
    LocallyRingedSpace.restrictTopSectionsIso_inv_eq X.toLocallyRingedSpace U
      (range_restrictOpenι_subset X hX U)]
  rfl

end FormalScheme

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

/-! ### `nodeChartPsi` in the shape the criterion consumes -/

/-- **`AlgebraicGeometry.nodeChartPsi` factors through the sections of the chain over the saturated
locus.** Its definition already is the projection's section map followed by
`AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso`; this restates that with the second
factor in the form
`AlgebraicGeometry.FormalScheme.adicSectionsLocallyFG_restrictOpen_iff` recognises. -/
theorem nodeChartPsi_eq :
    nodeChartPsi R I q hq hI =
      ((tateChainInv R I q hq hI).restrictOpenTopSectionsHom (tateChainInv_locallyFG R I q hq hI)
        (nodeChartSaturationOpens R I q hq hI)).comp
        ((actionQuotientπ (tateInvPeriodAction R I q hq hI)).c.app
          (op (tateInvNodeChartQuotientOpens R I q hq hI))).hom := by
  rw [nodeChartPsi, nodeChartSectionsHom, CommRingCat.hom_comp,
    FormalScheme.restrictOpenTopSectionsHom_eq]
  rfl

/-! ### The reduction -/

section Reduction

/-- **The first of the four hypotheses of `AlgebraicGeometry.exists_formalScheme_of_adicSections`,
as a condition on charts of the chain.** An equivalence: `AlgebraicGeometry.nodeChartPsi` is adic on
a neighbourhood basis exactly when every point of the saturated node-chart locus has a finitely
generated affine chart of the **chain**, sitting inside that locus, along which the ideal of
definition of the quotient's sections pulls back into the chart's own.

Nothing about the quotient survives on the right except through the ring homomorphism; the source of
the predicate, `AlgebraicGeometry.nodeChartSaturationFormalScheme`, has disappeared entirely. -/
theorem adicSectionsLocallyFG_nodeChartPsi_iff :
    FormalScheme.AdicSectionsLocallyFG (tateInvNodeChartQuotientIdeal R I q hq hI)
        (nodeChartPsi R I q hq hI) ↔
      ∀ y ∈ nodeChartSaturationOpens R I q hq hI,
        ∃ (d : FormalScheme.AffineChart (tateChainInv R I q hq hI) y)
          (hd : Set.range d.map.base ⊆ SetLike.coe (nodeChartSaturationOpens R I q hq hI)),
          d.I.FG ∧ tateInvNodeChartQuotientIdeal R I q hq hI ≤ d.I.comap
            ((d.opensSectionsHom (nodeChartSaturationOpens R I q hq hI) hd).comp
              ((actionQuotientπ (tateInvPeriodAction R I q hq hI)).c.app
                (op (tateInvNodeChartQuotientOpens R I q hq hI))).hom) := by
  rw [nodeChartPsi_eq]
  exact FormalScheme.adicSectionsLocallyFG_restrictOpen_iff _ _ _ _

/-- **The ideal may be taken on the subring of `A{1/(x + y − 1)}` instead.**
`AlgebraicGeometry.tateInvNodeChartQuotientIdeal` is
`AlgebraicGeometry.tateInvNodeChartAwayIdeal` pushed along an isomorphism, so
`Ideal.map_le_iff_le_comap` moves the bound to the other side and `Ideal.comap_comap` absorbs the
isomorphism into the map. -/
theorem le_comap_tateInvNodeChartQuotientIdeal_iff {S : Type u} [CommRing S] (J : Ideal S)
    (g : ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) →+* S) :
    tateInvNodeChartQuotientIdeal R I q hq hI ≤ J.comap g ↔
      tateInvNodeChartAwayIdeal R I q hq hI ≤
        J.comap (g.comp (tateInvNodeChartQuotientRingEquiv R I q hq hI).symm) := by
  rw [tateInvNodeChartQuotientIdeal, Ideal.map_le_iff_le_comap, Ideal.comap_comap]

/-- **The reduction, with no `CategoryTheory.actionQuotient` in the ideal.** This is the form the
question should be attacked in: an inequality of ideals whose left-hand side is an ideal of
`AlgebraicGeometry.tateInvNodeChartAwaySubring`, a named subring of a twice-completed localization,
and whose right-hand side is the ideal of definition of a chart of the chain. -/
theorem adicSectionsLocallyFG_nodeChartPsi_iff_awayIdeal :
    FormalScheme.AdicSectionsLocallyFG (tateInvNodeChartQuotientIdeal R I q hq hI)
        (nodeChartPsi R I q hq hI) ↔
      ∀ y ∈ nodeChartSaturationOpens R I q hq hI,
        ∃ (d : FormalScheme.AffineChart (tateChainInv R I q hq hI) y)
          (hd : Set.range d.map.base ⊆ SetLike.coe (nodeChartSaturationOpens R I q hq hI)),
          d.I.FG ∧ tateInvNodeChartAwayIdeal R I q hq hI ≤ d.I.comap
            (((d.opensSectionsHom (nodeChartSaturationOpens R I q hq hI) hd).comp
              ((actionQuotientπ (tateInvPeriodAction R I q hq hI)).c.app
                (op (tateInvNodeChartQuotientOpens R I q hq hI))).hom).comp
              (tateInvNodeChartQuotientRingEquiv R I q hq hI).symm) := by
  rw [adicSectionsLocallyFG_nodeChartPsi_iff]
  refine forall_congr' fun y => forall_congr' fun _ => exists_congr fun d => exists_congr fun hd =>
    and_congr_right fun _ => ?_
  exact le_comap_tateInvNodeChartQuotientIdeal_iff R I q hq hI _ _

/-- **The reduced condition, in the packaging the headline asks for.** The `letI`/`haveI` are the
ones `AlgebraicGeometry.exists_formalScheme_of_adicSections` states its own hypothesis under, so
this theorem's conclusion is literally the first component of that theorem's `∃` — which is the
check that the reduction is about the right statement and not about a variant of it.

Everything to the left of the colon mentions the chain and the annulus algebras and nothing else.
**It is not proved to be satisfiable**; see this file's "What is *not* proved here". -/
theorem adicSectionsLocallyFG_nodeChartPsi_of_charts (t : R) (ht : I = Ideal.span {t})
    (hreg : IsLeftRegular t)
    (h : ∀ y ∈ nodeChartSaturationOpens R I q hq hI,
        ∃ (d : FormalScheme.AffineChart (tateChainInv R I q hq hI) y)
          (hd : Set.range d.map.base ⊆ SetLike.coe (nodeChartSaturationOpens R I q hq hI)),
          d.I.FG ∧ tateInvNodeChartAwayIdeal R I q hq hI ≤ d.I.comap
            (((d.opensSectionsHom (nodeChartSaturationOpens R I q hq hI) hd).comp
              ((actionQuotientπ (tateInvPeriodAction R I q hq hI)).c.app
                (op (tateInvNodeChartQuotientOpens R I q hq hI))).hom).comp
              (tateInvNodeChartQuotientRingEquiv R I q hq hI).symm)) :
    letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
        (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
      (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
    haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
      isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
    FormalScheme.AdicSectionsLocallyFG (tateInvNodeChartQuotientIdeal R I q hq hI)
      (nodeChartPsi R I q hq hI) :=
  (adicSectionsLocallyFG_nodeChartPsi_iff_awayIdeal R I q hq hI).mpr h

end Reduction

end AlgebraicGeometry

end
