import FormalSchemes.AdicSectionsOverlap
import FormalSchemes.TateInvNodeChartPatchChartAdic

set_option linter.style.header false

/-!
# Hypothesis 2 of the node chart's four, and `hnode` over two conditions instead of four

`AlgebraicGeometry.exists_formalScheme_of_adicSections`
(`FormalSchemes.TateInvNodeChartAdicSections`) reduces `hnode`, over a principal base ideal
generated by a non-zero-divisor, to one `∃` bundling four things:

1. `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG` at `AlgebraicGeometry.nodeChartPsi` —
   proved in `FormalSchemes.TateInvNodeChartPatchChartAdic` as
   `AlgebraicGeometry.adicSectionsLocallyFG_nodeChartPsi`;
2. `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.OverlapAdic` — **this file**;
3. invariance of `AlgebraicGeometry.nodeChartAdicHom` under
   `AlgebraicGeometry.tateInvNodeChartRestrictedAction`;
4. `IsIso` of the descended morphism.

Hypothesis 2 costs nothing, and not for a reason special to the Tate curve:
`AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.overlapAdic`
(`FormalSchemes.AdicSectionsOverlap`) holds on **every** formal scheme, so the overlap condition of
hypothesis 1's witness is discharged by hypothesis 1 itself.
`AlgebraicGeometry.overlapAdic_nodeChartPsi` is that theorem at the node chart, and
`AlgebraicGeometry.exists_formalScheme_of_invariant_isIso` is the headline with hypotheses 1 and 2
filled in.

## What this changes and what it does not

Hypotheses 3 and 4 could not previously be *stated* at the node chart: `nodeChartAdicHom` takes both
a `hX` and a `hov` as arguments, so hypothesis 3 needs a witness of hypothesis 2 in its own type.
Both now have canonical arguments to be stated at, and
`AlgebraicGeometry.exists_formalScheme_of_invariant_isIso` states them.

**That is a change in what can be asked, not in what is known.** Neither 3 nor 4 has ever been
attempted, in either direction, and this file attempts neither.

## What is *not* proved here

**`hnode` is undecided, in both directions, and nothing here moves it.** Two of the four
obligations of `AlgebraicGeometry.exists_formalScheme_of_adicSections` are now discharged and two
are open; and even all four would only give the existence of the formal scheme, because the chain
back through `AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens`
is **one-way**. Nothing here should be read as evidence that the node chart exists.

**Nothing here bears on `AlgebraicGeometry.tateInvNodeChartAmbientHom`.**
`AlgebraicGeometry.not_isOpenImmersion_tateInvNodeChartAmbientHom_of_ne_top` refutes it as an open
immersion and that refutation is untouched, as is
`FormalSchemes.TateInvNodeChartAmbient`'s record that
`AlgebraicGeometry.tateInvNodeChartAwayIdeal` is not shown to be an ideal of definition.

**No Tate-specific fact is used.** `AlgebraicGeometry.overlapAdic_nodeChartPsi` is an instance of a
general theorem; nothing about the annulus, the node locus or the `σ`-action enters it. A reader
looking for the content should read `FormalSchemes.AdicSectionsOverlap`, not this file.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.4 (10.4.6), §10.6.
* [Deligne–Rapoport, *Les schémas de modules de courbes elliptiques*], II.1 — the Néron 1-gon.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite

universe u

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

/-- **The overlap condition at the node chart's witness**, i.e. the second of the four hypotheses of
`AlgebraicGeometry.exists_formalScheme_of_adicSections`.

This is `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.overlapAdic`
(`FormalSchemes.AdicSectionsOverlap`) at
`AlgebraicGeometry.adicSectionsLocallyFG_nodeChartPsi`; the `letI`/`haveI` are the ones the
headline states its hypothesis under. No Tate input is used. -/
theorem overlapAdic_nodeChartPsi (t : R) (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t) :
    letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
        (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
      (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
    haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
      isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
    (adicSectionsLocallyFG_nodeChartPsi R I q hq hI t ht hreg).OverlapAdic
      (nodeChartPsi R I q hq hI) := by
  letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
    (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
  haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
    isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
  exact FormalScheme.AdicSectionsLocallyFG.overlapAdic _ _ _

/-- **`hnode` over two conditions instead of four**, over a principal base ideal generated by a
non-zero-divisor. `AlgebraicGeometry.exists_formalScheme_of_adicSections` asks for four things;
hypothesis 1 is `AlgebraicGeometry.adicSectionsLocallyFG_nodeChartPsi` and hypothesis 2 is
`AlgebraicGeometry.overlapAdic_nodeChartPsi`, so what is left is the invariance of
`AlgebraicGeometry.nodeChartAdicHom` and the `IsIso` of the morphism it descends to.

Both remaining conditions are stated here at the two canonical witnesses, which is the first time
either can be stated at all: `AlgebraicGeometry.nodeChartAdicHom` takes hypotheses 1 and 2 as
arguments.

**Neither remaining condition is proved, or refuted, anywhere.** This is a shorter list of
obligations and not progress on any of them, and the implication runs one way: it produces the
formal scheme and not the converse. -/
theorem exists_formalScheme_of_invariant_isIso (t : R) (ht : I = Ideal.span {t})
    (hreg : IsLeftRegular t)
    (he :
      letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
          (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
        (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
      haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
        isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
      ∃ hk : IsActionInvariant (tateInvNodeChartRestrictedAction R I q hq hI)
          (nodeChartAdicHom R I q hq hI
            (fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg)
            (adicSectionsLocallyFG_nodeChartPsi R I q hq hI t ht hreg)
            (overlapAdic_nodeChartPsi R I q hq hI t ht hreg)),
        IsIso ((isActionQuotient_actionQuotientπ
          (tateInvNodeChartRestrictedAction R I q hq hI)).desc _ hk)) :
    ∃ X : FormalScheme.{u},
      X.toLocallyRingedSpace = actionQuotient (tateInvPeriodAction R I q hq hI) := by
  refine exists_formalScheme_of_adicSections R I q hq hI t ht hreg ?_
  obtain ⟨hk, hiso⟩ := he
  exact ⟨_, _, hk, hiso⟩

end AlgebraicGeometry

end
