import FormalSchemes.TateInvNodeChartDescent

set_option linter.style.header false

/-!
# The candidate morphism into the node chart's formal spectrum, constructed

`AlgebraicGeometry.exists_formalScheme_of_isIso_desc` (`FormalSchemes.TateInvNodeChartDescent`)
reduces the node-chart question to one morphism

```
k : nodeChartSaturationFormalScheme … ⟶ Spf (tateInvNodeChartQuotientIdeal …)
```

together with its invariance for `AlgebraicGeometry.tateInvNodeChartRestrictedAction` and the
descent of `k` along the coequalizer being an isomorphism. That file names the construction such a
`k` would come from — `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom`
(`FormalSchemes.GlueHomToSpf`) applied to `AlgebraicGeometry.nodeChartSectionsHom` — and then lists
its remaining arguments as undischarged: `charts`, `hfg`, `hcont`, `hI`, `ocharts`, `hofg`, `hf`
and `hg`, the input `ψ` being `AlgebraicGeometry.nodeChartSectionsHom` itself.

**Five of those eight were never open questions.** They are choices the tree already makes, or
lemmas it already has:

* the affine charts of the source and the finite generation of their ideals of definition are
  `AlgebraicGeometry.FormalScheme.LocallyFG.chart` and `LocallyFG.fg_chart`
  (`FormalSchemes.GlobalSectionsHom`), available because of
  `AlgebraicGeometry.nodeChartSaturationFormalScheme_locallyFG`;
* the affine charts on the pairwise overlaps of that cover, and the finite generation of *their*
  ideals, are `AlgebraicGeometry.FormalScheme.LocallyFG.overlapChart` and
  `LocallyFG.fg_overlapChart` (`FormalSchemes.GlueHomToSpf`), available for the same reason one
  level down;
* finite generation of the target's ideal is
  `AlgebraicGeometry.fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base`
  (`FormalSchemes.TateInvNodeChartQuotientOpen`), **whose hypotheses are exactly the `t`, `ht`,
  `hreg` that the headline of `FormalSchemes.TateInvNodeChartDescent` already carries**.

So this file builds `k`. What is left over is the three continuity families, bundled as
`AlgebraicGeometry.FormalScheme.SpfHomContinuity`, and they are left over unproved; see the last
section, which is the point of this file as much as the construction is.

The gain is that the outstanding invariance and isomorphism are now questions about a **named**
morphism rather than about an unspecified one. `AlgebraicGeometry.nodeChartCandidateHom` induces
`AlgebraicGeometry.nodeChartSectionsHom` on global sections
(`AlgebraicGeometry.globalSectionsHom_nodeChartCandidateHom`), and by
`AlgebraicGeometry.FormalScheme.chart_comp_homOfGlobalSectionsHomOfLocallyFG` its restriction to
each chart of the chosen cover is `Spf` of the chart-restriction of that homomorphism, so both
questions can be attacked chart by chart.

## Main definitions and results

* `AlgebraicGeometry.nodeChartCandidateHom`: **the candidate `k`**, built by
  `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHomOfLocallyFG` from
  `AlgebraicGeometry.nodeChartSectionsHom` over a proof of
  `AlgebraicGeometry.FormalScheme.SpfHomContinuity`.
* `AlgebraicGeometry.globalSectionsHom_nodeChartCandidateHom`: it induces
  `AlgebraicGeometry.nodeChartSectionsHom` on global sections, so it is the morphism that
  homomorphism was the candidate input for and not merely some morphism.
* `AlgebraicGeometry.exists_formalScheme_of_spfHomContinuity`: **the accounting**, as a statement.
  Over a principal base ideal generated by a non-zero-divisor, the quotient of the chain by the
  period action is a formal scheme as soon as the three continuity families hold, the resulting
  morphism is invariant, and its descent is an isomorphism.

## What is *not* proved here

**No continuity condition is discharged, no invariance is proved, and no isomorphism is produced.
Nothing here decides whether the node chart exists, in either direction.** The proof of the
headline is one application of `AlgebraicGeometry.exists_formalScheme_of_isIso_desc`: this file
changes no mathematics, it removes five hypotheses by naming their inhabitants.

In particular `AlgebraicGeometry.FormalScheme.SpfHomContinuity` is **not** shown to hold at this
instance, and it must not be read as a formality. Its three families are the content of the
construction that consumes them:

* that each chart-restriction of `AlgebraicGeometry.nodeChartSectionsHom` is continuous;
* that the two restrictions being compared on each pairwise overlap of the chosen cover are
  continuous, on the chosen affine cover of that overlap.

`FormalSchemes.GlueHomToSpf`'s module docstring calls exactly these hypotheses "inherited, not
incidental", and `FormalSchemes.GlobalSectionsHomGlue`'s scope note says why they cannot simply be
dropped: `FormalSpectrum.spfGammaEquiv` inverts `Spf` only on the continuity-restricted subtype,
and the general statement that open immersions are adic is false. **Anyone who claims the three
hold must check it by producing them.**

Invariance of `AlgebraicGeometry.nodeChartCandidateHom` for
`AlgebraicGeometry.tateInvNodeChartRestrictedAction` is likewise unattempted, and so is the
descent being an isomorphism. Both are hypotheses of the headline below.

Refuting any of these does **not** refute `hnode`. The chain back to it passes through
`AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens`, which
discharges a containment of ranges and is sufficient rather than equivalent; the three reductions
downstream of it are equivalent to one another and to the descent packaging, and
`FormalSchemes.TateInvNodeChartRestrictedQuotient` scores them one by one.

## Implementation notes

The instances the statements need — the adic topology on the quotient's sections over the node
chart's open, and that `AlgebraicGeometry.tateInvNodeChartQuotientIdeal` is adic for it — are
**instance binders** on `AlgebraicGeometry.nodeChartCandidateHom`, in the style of
`AlgebraicGeometry.exists_isIso_desc_tateInvNodeChartRestrictedAction_iff`, and a `letI`/`haveI`
block only in the theorem that supplies them from `t`, `ht`, `hreg`. A `letI` in the *statement* of
a definition does not scope over its body, which fails with a synthesis error for the topology
rather than with anything that points at the cause.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.4 (10.4.6) and §10.6.
* [Deligne–Rapoport, *Les schémas de modules de courbes elliptiques*], II.1 — the Néron 1-gon.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite

universe u

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)
variable [TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
  (op (tateInvNodeChartQuotientOpens R I q hq hI)))]
variable [IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI)]

/-- **The candidate morphism into the node chart's formal spectrum.**
`AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHomOfLocallyFG` at the source
`AlgebraicGeometry.nodeChartSaturationFormalScheme`, which is locally finitely generated, and the
homomorphism `AlgebraicGeometry.nodeChartSectionsHom` on its global sections.

Everything the construction needs is supplied here except finite generation of the target's ideal,
which the caller has from `t`, `ht`, `hreg`, and the three continuity families of
`AlgebraicGeometry.FormalScheme.SpfHomContinuity`, which **are not proved anywhere**. -/
def nodeChartCandidateHom
    (hIfg : (tateInvNodeChartQuotientIdeal R I q hq hI).FG)
    (d : FormalScheme.SpfHomContinuity (tateInvNodeChartQuotientIdeal R I q hq hI)
      (nodeChartSaturationFormalScheme_locallyFG R I q hq hI)
      (nodeChartSectionsHom R I q hq hI).hom) :
    (nodeChartSaturationFormalScheme R I q hq hI).toLocallyRingedSpace ⟶
      FormalSpectrum.locallyRingedSpaceObj (tateInvNodeChartQuotientIdeal R I q hq hI) :=
  FormalScheme.homOfGlobalSectionsHomOfLocallyFG _
    (nodeChartSaturationFormalScheme_locallyFG R I q hq hI)
    (nodeChartSectionsHom R I q hq hI).hom hIfg d

/-- **The candidate induces the homomorphism it was built from.** This is what makes
`AlgebraicGeometry.nodeChartCandidateHom` the morphism `AlgebraicGeometry.nodeChartSectionsHom` was
the candidate input for, rather than an arbitrary morphism with the right type. -/
theorem globalSectionsHom_nodeChartCandidateHom
    (hIfg : (tateInvNodeChartQuotientIdeal R I q hq hI).FG)
    (d : FormalScheme.SpfHomContinuity (tateInvNodeChartQuotientIdeal R I q hq hI)
      (nodeChartSaturationFormalScheme_locallyFG R I q hq hI)
      (nodeChartSectionsHom R I q hq hI).hom) :
    globalSectionsHom (tateInvNodeChartQuotientIdeal R I q hq hI)
        (nodeChartSaturationFormalScheme R I q hq hI).toLocallyRingedSpace
        (nodeChartCandidateHom R I q hq hI hIfg d) =
      (nodeChartSectionsHom R I q hq hI).hom :=
  FormalScheme.globalSectionsHom_homOfGlobalSectionsHomOfLocallyFG _
    (nodeChartSaturationFormalScheme_locallyFG R I q hq hI)
    (nodeChartSectionsHom R I q hq hI).hom hIfg d

end AlgebraicGeometry

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

/-- **The node-chart question over the continuity families of the construction.** Over a principal
base ideal generated by a non-zero-divisor, the quotient of the inversion-glued chain by the period
action is a formal scheme as soon as `AlgebraicGeometry.FormalScheme.SpfHomContinuity` holds for
`AlgebraicGeometry.nodeChartSectionsHom`, the resulting `AlgebraicGeometry.nodeChartCandidateHom`
is invariant for `AlgebraicGeometry.tateInvNodeChartRestrictedAction`, and its descent along the
coequalizer is an isomorphism.

The proof is one application of `AlgebraicGeometry.exists_formalScheme_of_isIso_desc`: the morphism
that statement quantifies over is supplied by `AlgebraicGeometry.nodeChartCandidateHom` and the
finite generation it needs by
`AlgebraicGeometry.fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base`. **Nothing is decided
here that was not decided there**, and none of the three hypotheses is proved; see the module
docstring. -/
theorem exists_formalScheme_of_spfHomContinuity (t : R)
    (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t)
    (he :
      letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
          (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
        (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
      haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
        isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
      ∃ d : FormalScheme.SpfHomContinuity (tateInvNodeChartQuotientIdeal R I q hq hI)
          (nodeChartSaturationFormalScheme_locallyFG R I q hq hI)
          (nodeChartSectionsHom R I q hq hI).hom,
        ∃ hk : IsActionInvariant (tateInvNodeChartRestrictedAction R I q hq hI)
            (nodeChartCandidateHom R I q hq hI
              (fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg) d),
          IsIso ((isActionQuotient_actionQuotientπ
            (tateInvNodeChartRestrictedAction R I q hq hI)).desc _ hk)) :
    ∃ X : FormalScheme.{u},
      X.toLocallyRingedSpace = actionQuotient (tateInvPeriodAction R I q hq hI) := by
  letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
    (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
  haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
    isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
  obtain ⟨d, hk, hiso⟩ := he
  exact exists_formalScheme_of_isIso_desc R I q hq hI t ht hreg ⟨_, hk, hiso⟩

end AlgebraicGeometry

end
