import FormalSchemes.AdicSectionsInvariant
import FormalSchemes.TateInvNodeChartOverlapAdic

set_option linter.style.header false

/-!
# Hypothesis 3 of the node chart's four: the morphism is invariant, and for a structural reason

`AlgebraicGeometry.exists_formalScheme_of_adicSections`
(`FormalSchemes.TateInvNodeChartAdicSections`) reduces `hnode`, over a principal base ideal
generated by a non-zero-divisor, to one `∃` bundling four things:

1. `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG` at `AlgebraicGeometry.nodeChartPsi` —
   `AlgebraicGeometry.adicSectionsLocallyFG_nodeChartPsi`;
2. `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.OverlapAdic` —
   `AlgebraicGeometry.overlapAdic_nodeChartPsi`;
3. invariance of `AlgebraicGeometry.nodeChartAdicHom` under
   `AlgebraicGeometry.tateInvNodeChartRestrictedAction` — **this file**;
4. `IsIso` of the descended morphism.

## Why hypothesis 3 costs nothing

`AlgebraicGeometry.FormalScheme.isActionInvariant_homOfGlobalSectionsHomOfAdicSections_iff`
(`FormalSchemes.AdicSectionsInvariant`) says the morphism built from a `ψ`-adic neighbourhood basis
is invariant **exactly when `ψ` is**, so hypothesis 3 is not a condition on the charts —
which is what it looks like, since `AlgebraicGeometry.nodeChartAdicHom` is built from
`AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.chart` and that is `Classical.choice`.

And `AlgebraicGeometry.nodeChartPsi` is invariant for a reason that has nothing to do with the
annulus, the node locus or the `σ`-action's geometry: it *is* the section map of the projection
`T_inv ⟶ T_inv/⟨σ⟩` at the node chart's open, read on the global sections of the saturation
(`AlgebraicGeometry.nodeChartSectionsHom_eq`), and a section map of an invariant morphism is
invariant (`AlgebraicGeometry.LocallyRingedSpace.sectionsMapOfRangeSubset_comp_c_app_of_invariant`).
The morphism it is the section map of is
`T_inv|_{π⁻¹ V₀} ⟶ T_inv ⟶ T_inv/⟨σ⟩`, which is invariant because `π` is
(`AlgebraicGeometry.LocallyRingedSpace.isActionInvariant_ofRestrict_comp`).

No orbit argument is needed, and no property of the node locus is used. The row that filed this
asked whether the invariance would have to be checked chart by chart; it does not.

## Main results

* `AlgebraicGeometry.nodeChartSectionsHom_eq`: `AlgebraicGeometry.nodeChartSectionsHom` is a
  section map in the sense of `AlgebraicGeometry.LocallyRingedSpace.sectionsMapOfRangeSubset`.
* `AlgebraicGeometry.isInvariantSectionsHom_nodeChartPsi`: `AlgebraicGeometry.nodeChartPsi` is
  invariant on global sections.
* `AlgebraicGeometry.isActionInvariant_nodeChartAdicHom`: **hypothesis 3**, at *any* pair of
  witnesses, not only the canonical ones.
* `AlgebraicGeometry.exists_formalScheme_of_isIso_desc_nodeChartAdicHom`: the headline of
  `AlgebraicGeometry.exists_formalScheme_of_adicSections` with hypotheses 1, 2 and 3 filled in.

## What is *not* proved here

**`hnode` is undecided, in both directions, and nothing here moves it.** Hypothesis 4 is open, has
never been attempted in either direction, and even all four would only give the existence of the
formal scheme: the chain back through
`AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens` is
**one-way**.

**The headline below is a weaker theorem than
`AlgebraicGeometry.exists_formalScheme_of_isIso_desc`, not a stronger one**, and it is important
not to read it the other way. That theorem's hypothesis is *existential* — some invariant morphism
whose descent is an isomorphism — and
`AlgebraicGeometry.exists_isIso_desc_tateInvNodeChartRestrictedAction_iff` shows it equivalent to
an isomorphism between the formal spectrum of `AlgebraicGeometry.tateInvNodeChartQuotientIdeal`
and the quotient of `AlgebraicGeometry.tateInvNodeChartRestrictedAction`, which was already on the
tree. The hypothesis below is an `IsIso` at the **named** morphism, so it implies that existential
and is a priori stronger. What is gained is not logical strength: it is that the remaining
obligation is now stated at a morphism this cluster constructed, so that it can be attacked at
all.

**Nothing here bears on `AlgebraicGeometry.tateInvNodeChartAmbientHom`.**
`AlgebraicGeometry.not_isOpenImmersion_tateInvNodeChartAmbientHom_of_ne_top` refutes it as an open
immersion and that refutation is untouched, as is `FormalSchemes.TateInvNodeChartAmbient`'s record
that `AlgebraicGeometry.tateInvNodeChartAwayIdeal` is not shown to be an ideal of definition.

**No Tate-specific fact is used**, beyond the definition of
`AlgebraicGeometry.nodeChartSectionsHom` as a pullback along the projection. A reader looking for
the content should read `FormalSchemes.AdicSectionsInvariant`.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.4 (10.4.6), §10.6.
* [Deligne–Rapoport, *Les schémas de modules de courbes elliptiques*], II.1 — the Néron 1-gon.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite

universe u

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

/-! ### The candidate homomorphism is a section map -/

set_option linter.style.setOption false in
set_option backward.isDefEq.respectTransparency false in
/-- **`AlgebraicGeometry.nodeChartSectionsHom` is the section map of
`T_inv|_{π⁻¹ V₀} ⟶ T_inv ⟶ T_inv/⟨σ⟩` over the node chart's open.** Its definition is the
projection's comparison map at `V₀` followed by
`AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso`; that second factor is a section map
by `AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso_inv_eq`, and
`AlgebraicGeometry.LocallyRingedSpace.sectionsMapOfRangeSubset_comp_opens` absorbs the first
factor into it.

This is the only Tate-specific step of the file: everything after it is a general statement about
invariant morphisms. -/
theorem nodeChartSectionsHom_eq :
    nodeChartSectionsHom R I q hq hI =
      LocallyRingedSpace.sectionsMapOfRangeSubset _ _
        (LocallyRingedSpace.range_ofRestrict_comp_subset
          (actionQuotientπ (tateInvPeriodAction R I q hq hI))
          (tateInvNodeChartQuotientOpens R I q hq hI)) := by
  rw [LocallyRingedSpace.sectionsMapOfRangeSubset_comp_opens _ _ _
    (le_of_eq (LocallyRingedSpace.range_ofRestrict _ _)), nodeChartSectionsHom,
    LocallyRingedSpace.restrictTopSectionsIso_inv_eq _ _
      (le_of_eq (LocallyRingedSpace.range_ofRestrict _ _))]

set_option linter.style.setOption false in
set_option backward.isDefEq.respectTransparency false in
/-- **`AlgebraicGeometry.nodeChartPsi` is invariant on global sections.** By
`AlgebraicGeometry.nodeChartSectionsHom_eq` it is the section map of an invariant morphism, and
`AlgebraicGeometry.LocallyRingedSpace.sectionsMapOfRangeSubset_comp_c_app_of_invariant` needs
nothing else — in particular it does not need `π` to be a quotient projection, only invariant.

`AlgebraicGeometry.FormalScheme.isInvariantSectionsHom_iff_forall_apply` reads this pointwise: the
pullback of a section over `V₀` is fixed by every `σ ^ n`. -/
theorem isInvariantSectionsHom_nodeChartPsi :
    FormalScheme.IsInvariantSectionsHom (tateInvNodeChartRestrictedAction R I q hq hI)
      (nodeChartPsi R I q hq hI) := by
  intro g
  have hgen := LocallyRingedSpace.sectionsMapOfRangeSubset_comp_c_app_of_invariant _
    (LocallyRingedSpace.isActionInvariant_ofRestrict_comp
      (isActionQuotient_actionQuotientπ (tateInvPeriodAction R I q hq hI)).isInvariant
      (tateInvNodeChartQuotientOpens R I q hq hI))
    (tateInvNodeChartQuotientOpens R I q hq hI)
    (LocallyRingedSpace.range_ofRestrict_comp_subset _ _) g
  rw [← nodeChartSectionsHom_eq] at hgen
  have hring := congrArg CommRingCat.Hom.hom hgen
  rw [CommRingCat.hom_comp] at hring
  exact hring

/-! ### Hypothesis 3 -/

section Instances

variable [TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
  (op (tateInvNodeChartQuotientOpens R I q hq hI)))]
variable [IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI)]

/-- **Hypothesis 3 of `AlgebraicGeometry.exists_formalScheme_of_adicSections`, proved.**
`AlgebraicGeometry.nodeChartAdicHom` is invariant under
`AlgebraicGeometry.tateInvNodeChartRestrictedAction`.

It holds at **any** pair of witnesses, not only the canonical ones, because
`AlgebraicGeometry.FormalScheme.isActionInvariant_homOfGlobalSectionsHomOfAdicSections_iff` reduces
the invariance of the morphism to the invariance of `AlgebraicGeometry.nodeChartPsi`, which no
witness enters. So the charts a witness happens to choose are irrelevant to hypothesis 3, which is
the reason it is provable at all: they are chosen by `Classical.choice` and cannot be named. -/
theorem isActionInvariant_nodeChartAdicHom
    (hfgI : (tateInvNodeChartQuotientIdeal R I q hq hI).FG)
    (hX : FormalScheme.AdicSectionsLocallyFG (tateInvNodeChartQuotientIdeal R I q hq hI)
      (nodeChartPsi R I q hq hI))
    (hov : hX.OverlapAdic (nodeChartPsi R I q hq hI)) :
    IsActionInvariant (tateInvNodeChartRestrictedAction R I q hq hI)
      (nodeChartAdicHom R I q hq hI hfgI hX hov) :=
  (FormalScheme.isActionInvariant_homOfGlobalSectionsHomOfAdicSections_iff _ _ _ hX hfgI hov).mpr
    (isInvariantSectionsHom_nodeChartPsi R I q hq hI)

end Instances

/-! ### The residue -/

/-- **`hnode` from the descent of one named morphism.** Over a principal base ideal generated by a
non-zero-divisor, `T_inv/⟨σ⟩` is a formal scheme as soon as the descent of
`AlgebraicGeometry.nodeChartAdicHom`, at the canonical witnesses of hypotheses 1, 2 and 3, is an
isomorphism. That is hypothesis 4 of
`AlgebraicGeometry.exists_formalScheme_of_adicSections` and the only one left.

**It is not a strengthening of `AlgebraicGeometry.exists_formalScheme_of_isIso_desc`**, whose
hypothesis is existential and which this one's hypothesis implies; see the module docstring. What
it buys is a named morphism to state hypothesis 4 at, which is what a successor attacking it
needs. **Hypothesis 4 is open in both directions and nothing here bears on it.** -/
theorem exists_formalScheme_of_isIso_desc_nodeChartAdicHom (t : R) (ht : I = Ideal.span {t})
    (hreg : IsLeftRegular t)
    (he :
      letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
          (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
        (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
      haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
        isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
      IsIso ((isActionQuotient_actionQuotientπ
        (tateInvNodeChartRestrictedAction R I q hq hI)).desc
          (nodeChartAdicHom R I q hq hI
            (fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg)
            (adicSectionsLocallyFG_nodeChartPsi R I q hq hI t ht hreg)
            (overlapAdic_nodeChartPsi R I q hq hI t ht hreg))
          (isActionInvariant_nodeChartAdicHom R I q hq hI _ _ _))) :
    ∃ X : FormalScheme.{u},
      X.toLocallyRingedSpace = actionQuotient (tateInvPeriodAction R I q hq hI) := by
  letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
    (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
  haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
    isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
  exact exists_formalScheme_of_invariant_isIso R I q hq hI t ht hreg ⟨_, he⟩

end AlgebraicGeometry

end
