import FormalSchemes.TateInvNodeChartNontrivial
import FormalSchemes.TateInvNodeChartSpf

set_option linter.style.header false

/-!
# `Spf` of the node chart ring is nonempty

`FormalSchemes.TateInvNodeChartNontrivial` showed the node chart ring is not the zero ring, and
`FormalSchemes.TateInvNodeChartSpf` showed it is an adic ring over a principal base generated by a
non-zero-divisor, so that `Spf` of it is an affine formal scheme. Neither says that formal
spectrum has a **point**, and a nonzero ring is not enough: `Spf S = Spec (S ⧸ J)` is empty exactly
when `J = ⊤`, which a nonzero `S` permits.

That matters for the one hypothesis issue 1197 has left. Its residue is a single open immersion

```
f : Spf (tateInvNodeChartAwayIdeal …) ⟶ T_inv/⟨σ⟩
```

whose range contains `Set.range (tateInvNodeChartAmbientHom …).base`, and that target set is
**nonempty** for `I ≠ ⊤`. An open immersion out of an empty formal spectrum has empty range, so had
the source been empty the hypothesis would have been *refutable* rather than open. This file rules
that out.

## The argument

`AlgebraicGeometry.tateInvNodeChartAwayIdeal` is the ideal of definition of the ambient
`A{1/(x + y − 1)}` pulled back along the subring inclusion, so it is proper as soon as the ambient
one is (`Ideal.comap_ne_top`), and the ambient one is proper exactly when
`Spf (A{1/(x + y − 1)})` has a point. That formal spectrum's underlying map to `Spf A` has range
the basic open `D(x + y − 1)` (`FormalSpectrum.range_basicOpenChartBase`), which is the node chart
locus by definition and is nonempty for `I ≠ ⊤`
(`AlgebraicGeometry.tateInvNodeChartLocus_nonempty`). So the whole chain is driven by the same
point that `FormalSchemes.TateInvNodeChartNontrivial` used, and needs the same single hypothesis.

## Main results

* `FormalSpectrum.nonempty_iff_ne_top`: `Spf R` is nonempty iff `I ≠ ⊤`. General, and the shape
  the tree has been proving one instance of at a time — `annulus_formalSpectrum_nonempty` and
  `FormalSpectrum.nonempty_twoAdic` are both this plus a properness fact.
* `FormalSpectrum.ne_top_awayCompletionIdeal_of_nonempty_basicOpen`: the ideal of definition of
  `R{1/f}` is proper as soon as `D(f) ⊆ Spf R` has a point.
* `AlgebraicGeometry.ne_top_tateInvNodeChartAwayIdeal` and
  **`AlgebraicGeometry.nonempty_formalSpectrum_tateInvNodeChartAwayIdeal`**: for `I ≠ ⊤`, the node
  chart's candidate ideal of definition is proper and `Spf` of the node chart ring has a point.
  `AlgebraicGeometry.nonempty_formalSpectrum_tateInvNodeChartAwayIdeal_powerSeriesInt` is that at
  `R = ℤ⟦X⟧`, `I = (X)`, `q = X`, the base at which
  `AlgebraicGeometry.isAdicRing_tateInvNodeChartAwayIdeal_powerSeriesInt` holds — so at that base
  `Spf` of the node chart ring is a nonempty affine formal scheme.
* `AlgebraicGeometry.tateInvSaturate_nonempty` and
  **`AlgebraicGeometry.nonempty_range_tateInvNodeChartAmbientHom`**: the other half of the pairing
  — the set the sought open immersion must cover is itself nonempty for `I ≠ ⊤`, so neither side
  of issue 1197's residual hypothesis is empty for a trivial reason.
* **`exists_isAdicComplete_nontrivial_sections_tateInvNodeChart_of_isLeftRegular_base`**, in the
  `AlgebraicGeometry` namespace like everything else on this list bar the first two:
  `AlgebraicGeometry.exists_isAdicComplete_sections_tateInvNodeChart_of_isLeftRegular_base`
  (`FormalSchemes.TateInvNodeChartSpf`) with `Nontrivial (Γ (T_inv/⟨σ⟩, V))` added to its
  conclusion, so that its `K.FG ∧ IsAdicComplete K …` is a statement about a nonzero ring inside
  the same existential rather than one that has to be paired up with a second one afterwards.

## What is *not* proved here

**Not issue 1223's goal 3.** No element of the chart ring outside the image of `Γ(Spf R, ·)` is
exhibited; `0` and `1` are both in that image. This file is a further non-vacuity measurement, of
the kind 1223's fallback branch authorises, and nothing more.

**Nothing here builds the morphism `f`.** Issue 1197's residue is untouched: this says only that
the source of the sought open immersion is nonempty, not that the immersion exists.
`FormalSchemes.TateInvNodeChartSpf` records that no construction on this tree produces a morphism
out of a formal spectrum into a general locally ringed space.

**No converse for the general lemma at the node chart**: `I = ⊤` is not shown to make
`tateInvNodeChartAwayIdeal` equal to `⊤`. It makes `Spf A` empty, so the argument below simply
stops.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.1, 10.6.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite TopCat.Presheaf

universe u

namespace FormalSpectrum

variable {R : Type u} [CommRing R] (I : Ideal R)

/-- **`Spf R` is nonempty exactly when its ideal of definition is proper.** `Spf R` is
`Spec (R ⧸ I)` by definition, `PrimeSpectrum.nonempty_iff_nontrivial` turns that into
nontriviality of the special fibre, and `Ideal.Quotient.nontrivial_iff` into `I ≠ ⊤`.

The tree has been proving instances of this one at a time — `annulus_formalSpectrum_nonempty`
(`FormalSchemes.AnnulusNontrivial`) and `FormalSpectrum.nonempty_twoAdic`
(`FormalSchemes.TwoAdicDegeneracy`) are each this plus a properness fact about their own ideal. -/
theorem nonempty_iff_ne_top : Nonempty (FormalSpectrum I) ↔ I ≠ ⊤ :=
  PrimeSpectrum.nonempty_iff_nontrivial.trans Ideal.Quotient.nontrivial_iff

variable (f : R)

/-- **The ideal of definition of `R{1/f}` is proper once `D(f)` has a point.**
`FormalSpectrum.range_basicOpenChartBase` computes the range of `Spf R{1/f} → Spf R` as
`D(f)`, so a point of `D(f)` is a point of `Spf R{1/f}`, and
`FormalSpectrum.nonempty_iff_ne_top` converts. -/
theorem ne_top_awayCompletionIdeal_of_nonempty_basicOpen (hI : I.FG)
    (hne : (basicOpen I f : Set (FormalSpectrum I)).Nonempty) :
    awayCompletionIdeal I f ≠ ⊤ := by
  have hrange : (Set.range (basicOpenChartBase I f)).Nonempty := by
    rw [range_basicOpenChartBase I f hI]
    exact hne
  exact (nonempty_iff_ne_top _).1 (Set.range_nonempty_iff_nonempty.mp hrange)

end FormalSpectrum

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R]

omit [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] in
/-- **The ambient's ideal of definition is proper at the node chart**: `D(x + y − 1)` is the node
chart locus, which is nonempty for `I ≠ ⊤`. -/
theorem ne_top_awayCompletionIdeal_annulusNodeChartCoord (hq : q ∈ I) (hI : I.FG) (hItop : I ≠ ⊤) :
    awayCompletionIdeal (annulusIdealOfDefinition R I q) (annulusNodeChartCoord R I q) ≠ ⊤ :=
  FormalSpectrum.ne_top_awayCompletionIdeal_of_nonempty_basicOpen _ _
    (annulusIdealOfDefinition_fg R I q hI) (tateInvNodeChartLocus_nonempty R I q hq hI hItop)

/-- **The node chart's candidate ideal of definition is proper**, for `I ≠ ⊤`. It is the ambient
one pulled back along the subring inclusion, and `Ideal.comap_ne_top` needs nothing else. -/
theorem ne_top_tateInvNodeChartAwayIdeal (hq : q ∈ I) (hI : I.FG) (hItop : I ≠ ⊤) :
    tateInvNodeChartAwayIdeal R I q hq hI ≠ ⊤ :=
  Ideal.comap_ne_top _ (ne_top_awayCompletionIdeal_annulusNodeChartCoord R I q hq hI hItop)

/-- **`Spf` of the node chart ring has a point**, for `I ≠ ⊤`.

Together with
`AlgebraicGeometry.isAdicRing_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base`
(`FormalSchemes.TateInvNodeChartSpf`) this says the source of the open immersion issue 1197 is
looking for is a **nonempty** affine formal scheme. That is not a formality: an open immersion out
of an empty formal spectrum has empty range, and the set it must cover,
`Set.range (tateInvNodeChartAmbientHom …).base`, is nonempty for the same `I ≠ ⊤`. -/
theorem nonempty_formalSpectrum_tateInvNodeChartAwayIdeal (hq : q ∈ I) (hI : I.FG)
    (hItop : I ≠ ⊤) :
    Nonempty (FormalSpectrum (tateInvNodeChartAwayIdeal R I q hq hI)) :=
  (FormalSpectrum.nonempty_iff_ne_top _).2
    (ne_top_tateInvNodeChartAwayIdeal R I q hq hI hItop)

section Target

variable (hq : q ∈ I) (hI : I.FG)

omit [TopologicalSpace R] [IsAdicRing I] in
/-- **Saturating a nonempty set keeps it nonempty.** `tateInvSaturate` is a union over the patch
inclusions, and `AlgebraicGeometry.image_ι_subset_tateInvSaturate` puts patch `0`'s copy inside
it. -/
theorem tateInvSaturate_nonempty {S : Set (FormalSpectrum.locallyRingedSpaceObj
    (annulusIdealOfDefinition R I q))} (hS : S.Nonempty) :
    (tateInvSaturate R I q hq hI S).Nonempty :=
  (hS.image _).mono (image_ι_subset_tateInvSaturate hq hI S ⟨0⟩)

variable {Q : LocallyRingedSpace.{u}}
variable {π : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Q}

/-- **The set a node chart must cover is nonempty**, for `I ≠ ⊤`. This is the other half of the
pairing in this file's module docstring: the source of the sought open immersion has a point
(`AlgebraicGeometry.nonempty_formalSpectrum_tateInvNodeChartAwayIdeal`) and so does the set its
range has to contain, so neither side of issue 1197's residual hypothesis is empty for a trivial
reason. -/
theorem nonempty_range_tateInvNodeChartAmbientHom (hItop : I ≠ ⊤)
    (h : IsActionQuotient (tateInvPeriodAction R I q hq hI) π) :
    (Set.range (tateInvNodeChartAmbientHom R I q hq hI (π := π)).base).Nonempty := by
  rw [range_tateInvNodeChartAmbientHom R I q hq hI h]
  exact (tateInvSaturate_nonempty R I q hq hI
    (tateInvNodeChartLocus_nonempty R I q hq hI hItop)).image _

end Target

section Sections

/-- **The adic data on `Γ (T_inv/⟨σ⟩, V)` at the node chart's domain, with nontriviality inside the
same existential.** This is
`AlgebraicGeometry.exists_isAdicComplete_sections_tateInvNodeChart_of_isLeftRegular_base`
(`FormalSchemes.TateInvNodeChartSpf`) with `Nontrivial` added to its conclusion.

The point of stating it once rather than pairing two existentials afterwards is that
`AlgebraicGeometry.exists_nontrivial_actionQuotient_sections_tateInvNodeChartLocus` produces its
own `V`, and matching the two would need `π.base` to be surjective. No such argument is required:
`AlgebraicGeometry.nontrivial_actionQuotient_sections` is stated for an **arbitrary** `V` with
`π⁻¹ V = tateInvSaturateOpens hq hI hS`, which is exactly the `hV` the theorem above already
produces, so the nontriviality attaches to *that* `V` directly. -/
theorem exists_isAdicComplete_nontrivial_sections_tateInvNodeChart_of_isLeftRegular_base
    (hq : q ∈ I) (hI : I.FG) (hItop : I ≠ ⊤) (t : R) (ht : I = Ideal.span {t})
    (hreg : IsLeftRegular t) :
    ∃ (V : Opens (actionQuotient (tateInvPeriodAction R I q hq hI)).toTopCat)
      (_ : (Opens.map (actionQuotientπ
        (tateInvPeriodAction R I q hq hI)).toShHom.hom.base).obj V =
          tateInvSaturateOpens hq hI (isOpen_tateInvNodeChartLocus R I q))
      (K : Ideal ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj (op V))),
      K.FG ∧ IsAdicComplete K
        ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj (op V)) ∧
        Nontrivial ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj (op V)) := by
  obtain ⟨V, hV, K, hfg, hcomplete⟩ :=
    exists_isAdicComplete_sections_tateInvNodeChart_of_isLeftRegular_base R I q hq hI t ht hreg
  obtain ⟨x, hx⟩ := tateInvNodeChartLocus_nonempty R I q hq hI hItop
  refine ⟨V, hV, K, hfg, hcomplete,
    nontrivial_actionQuotient_sections (hq := hq) (hI := hI) V _ hV (x := x) ?_⟩
  rw [tateInvPatchSaturateOpens_tateInvNodeChartLocus R I q hq hI]
  exact hx

end Sections

section Witness

/-- **`Spf` of the node chart ring has a point at `R = ℤ⟦X⟧`, `I = (X)`, `q = X`**, with no
hypothesis at all — the base at which
`AlgebraicGeometry.isAdicRing_tateInvNodeChartAwayIdeal_powerSeriesInt` makes it an affine formal
scheme and `AlgebraicGeometry.nontrivial_tateInvNodeChartAwaySubring_powerSeriesInt` makes its ring
nonzero. `I ≠ ⊤` is `PowerSeries.span_X_isPrime`'s `Ideal.IsPrime.ne_top`. -/
theorem nonempty_formalSpectrum_tateInvNodeChartAwayIdeal_powerSeriesInt :
    letI : TopologicalSpace (PowerSeries ℤ) :=
      (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}).adicTopology
    haveI : IsAdicRing (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) := ⟨rfl⟩
    Nonempty (FormalSpectrum (tateInvNodeChartAwayIdeal (PowerSeries ℤ)
      (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
      (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _))) :=
  letI : TopologicalSpace (PowerSeries ℤ) :=
    (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}).adicTopology
  haveI : IsAdicRing (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) := ⟨rfl⟩
  nonempty_formalSpectrum_tateInvNodeChartAwayIdeal _ _ _
    (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _)
    (PowerSeries.span_X_isPrime (R := ℤ)).ne_top

end Witness

end AlgebraicGeometry
