import FormalSchemes.AnnulusSpecialFibre
import FormalSchemes.TateInvPeriodNotDiscontinuous
import FormalSchemes.TateChartTransitionInvAlgEq
import FormalSchemes.TateGraphCodiagonalBridge

set_option linter.style.header false

/-!
# The node of the Tate annulus, and the answer for the period-`q` shift

`FormalSchemes.TateInvPeriodNotDiscontinuous` reduces the whole of the period-`q` question — is the
shift `σ` on the inversion-glued Tate chain `T_inv` free and properly discontinuous? — to a single
statement about one affine patch: a point `v` of the `x`-overlap `Spf A{1/x}` whose `x`-chart image
and whose transported `y`-chart image both **specialize** to one point `N` of `Spf A`.

This file produces that `v` and that `N`, and so answers the question: **no**, as soon as the base
has a prime `𝔭 ⊇ I` — that is, as soon as `I ≠ ⊤`.

## The geometry, and the shape of the proof

The special fibre of the annulus is `A ⧸ I·A = (R ⧸ I)[x, y]/(x·y)`, a pair of affine lines meeting
at the origin; the point `N` is the generic point of that origin over `𝔭`, and `v` is the generic
point of the `𝔾m` overlap over `𝔭`. The `x`-chart carries `v` to the generic point of the `x`-line,
and the inversion transition followed by the `y`-chart carries it to the generic point of the
`y`-line. Both lines pass through the node, so both generic points specialize to `N`.

The proof never computes the special fibre. Instead it uses three evaluation maps out of it, all
built from `annulusFibreEval` over the domain `D = R ⧸ 𝔭`:

* `annulusBranchX : A ⧸ I·A →+* D[X]`, `x ↦ X`, `y ↦ 0` — the `x`-line;
* `annulusBranchY : A ⧸ I·A →+* D[X]`, `x ↦ 0`, `y ↦ X` — the `y`-line;
* `annulusNode : A ⧸ I·A →+* D`, `x, y ↦ 0` — the node.

The two specializations are then *free*: `annulusNode` is `X ↦ 0` composed with either branch
(`annulusNode_eq_evalZero_comp_branchX`), so each branch's kernel is contained in the node's, which
is exactly the specialization (`PrimeSpectrum.le_iff_specializes`). The work is in identifying the
two chart maps with the two branches, which is done in the Laurent polynomial ring `D[T, T⁻¹]` —
the smallest ring in which both `X` and `X⁻¹` live, and where the gluing `x_n · y_{n+1} = 1` is
visible. There is no ring map out of a ring in which `X` is invertible sending `X` to `0`, which is
why the factorisation has to go through the subring `D[X] ⊆ D[T, T⁻¹]`; that is the whole reason
the branches are stated with a polynomial, not a Laurent, target.

The identification of the chart maps uses `annulusFibre_ext`: the special fibre is generated by the
two coordinates, so it is enough to compare values at `x` and at `y`.

## Main results

* `AlgebraicGeometry.annulusTransitionedChartY`: the `y`-chart of the next patch, transported into
  the `x`-chart algebra by the 𝔾m-inversion transition.
* `AlgebraicGeometry.not_isFreeProperlyDiscontinuous_tateInvPeriodAction`: **the `q^ℤ`-shift `σ` on
  `T_inv` is not free and properly discontinuous** whenever `I ≠ ⊤`. Consequently `T_inv/⟨σ⟩` — the
  period-`q` Tate curve — is not reachable by `freeActionQuotientFormalScheme`, in contrast with
  `𝔈_q = T_inv/⟨σ²⟩`, which is (`tateInvPeriodSq_isFreeProperlyDiscontinuous`).

## References

* [Bosch, *Lectures on Formal and Rigid Geometry*, LNM 2105], §9 — `E_q` is formed on the rigid
  side, not the formal one.
* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.6.
-/

noncomputable section

open CategoryTheory Ideal AlgebraicGeometry FormalSpectrum Topology
open Polynomial LaurentPolynomial RestrictedLaurentSeries

universe u

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R) (hI : I.FG)

/-! ### The transported `y`-chart -/

/-- **The `y`-chart of the next patch, read in the `x`-chart algebra.** The structural map
`A → A{1/y}` of the patch `U_{n+1}`, followed by the 𝔾m-inversion chart transition
`A{1/y} ≃ A{1/x}`. Its `Spf` is the composite `Spf A{1/x} ≅ Spf A{1/y} ⟶ Spf A` appearing in
`annulusOverlapChart_comp_ι`. -/
def annulusTransitionedChartY : annulusAlgebra R I q →+*
    awayCompletion (annulusIdealOfDefinition R I q) (overlapX R I q) :=
  (annulusChartTransitionInvAlg R I q hI).symm.toRingHom.comp
    (awayCompletionHom (annulusIdealOfDefinition R I q) (overlapY R I q))

theorem annulusTransitionedChartY_le_comap :
    annulusIdealOfDefinition R I q ≤
      (awayCompletionIdeal (annulusIdealOfDefinition R I q) (overlapX R I q)).comap
        (annulusTransitionedChartY R I q hI) :=
  le_comap_comp _ _ (le_comap_awayCompletionHom _ _)
    (annulusChartTransitionInvAlg_symm_le_comap R I q hI)

/-- **The transported `y`-chart, read in the completed localization `A[x⁻¹]^∧`.** Composing with
the chart-domain identification turns it into the inverse inversion transition applied to the
structural map of `A[y⁻¹]^∧`. Everything is kept at the `RingHom.comp` level:
`AdicCompletion.congrIdealₐ` is an `Eq.rec` at these concrete completion types, and applying its
coercion to an element is not kernel-checkable in reasonable time. -/
theorem chartOverlapAlgX_comp_annulusTransitionedChartY :
    (annulusChartOverlapAlgX R I q).toRingHom.comp (annulusTransitionedChartY R I q hI) =
      (annulusOverlapInversion R I q hI).symm.toRingHom.comp
        (algebraMap (annulusAlgebra R I q) (annulusOverlapY R I q)) := by
  rw [annulusTransitionedChartY, annulusChartTransitionInvAlg_symm_toRingHom_eq,
    annulusChartOverlapAlgX, AdicCompletion.congrIdealₐ_toRingHom, ← RingHom.comp_assoc,
    ← RingHom.comp_assoc, ← RingHom.comp_assoc, RingEquiv.toRingHom_comp_symm_toRingHom,
    RingHom.id_comp, RingHom.comp_assoc]
  congr 1
  rw [← AdicCompletion.congrIdealₐ_toRingHom R (annulusChartY_locIdeal_eq R I q)]
  exact chartOverlapAlgY_comp_awayCompletionHom R I q

/-! ### The three evaluation maps over a prime of the base -/

section Node

variable (𝔭 : Ideal R) (h𝔭 : I ≤ 𝔭) (hq : q ∈ I)

include h𝔭 in
theorem map_algebraMap_le_bot_quotient : I.map (algebraMap R (R ⧸ 𝔭)) ≤ ⊥ := by
  rw [Ideal.map_le_iff_le_comap]
  intro r hr
  simp only [Ideal.mem_comap, Ideal.mem_bot, Ideal.Quotient.algebraMap_eq,
    Ideal.Quotient.eq_zero_iff_mem]
  exact h𝔭 hr

include h𝔭 in
theorem map_algebraMap_le_bot_polynomial :
    I.map (algebraMap R (Polynomial (R ⧸ 𝔭))) ≤ ⊥ := by
  rw [Ideal.map_le_iff_le_comap]
  intro r hr
  simp only [Ideal.mem_comap, Ideal.mem_bot, Polynomial.algebraMap_apply,
    Ideal.Quotient.algebraMap_eq]
  rw [Ideal.Quotient.eq_zero_iff_mem.mpr (h𝔭 hr), map_zero]

include h𝔭 in
theorem map_algebraMap_le_bot_laurent :
    I.map (algebraMap R (LaurentPolynomial (R ⧸ 𝔭))) ≤ ⊥ := by
  rw [Ideal.map_le_iff_le_comap]
  intro r hr
  simp only [Ideal.mem_comap, Ideal.mem_bot, LaurentPolynomial.algebraMap_apply,
    Ideal.Quotient.algebraMap_eq]
  rw [Ideal.Quotient.eq_zero_iff_mem.mpr (h𝔭 hr), map_zero]

include h𝔭 hq in
theorem algebraMap_q_eq_zero_polynomial :
    algebraMap R (Polynomial (R ⧸ 𝔭)) q = (0 : Polynomial (R ⧸ 𝔭)) := by
  simp only [Polynomial.algebraMap_apply, Ideal.Quotient.algebraMap_eq]
  rw [Ideal.Quotient.eq_zero_iff_mem.mpr (h𝔭 hq), map_zero]

include h𝔭 hq in
theorem algebraMap_q_eq_zero_quotient :
    algebraMap R (R ⧸ 𝔭) q = (0 : R ⧸ 𝔭) := by
  simp only [Ideal.Quotient.algebraMap_eq]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr (h𝔭 hq)

include h𝔭 hq in
theorem algebraMap_q_eq_zero_laurent :
    algebraMap R (LaurentPolynomial (R ⧸ 𝔭)) q = (0 : LaurentPolynomial (R ⧸ 𝔭)) := by
  simp only [LaurentPolynomial.algebraMap_apply, Ideal.Quotient.algebraMap_eq]
  rw [Ideal.Quotient.eq_zero_iff_mem.mpr (h𝔭 hq), map_zero]

/-- **The node of the special fibre over `𝔭`**: evaluation of `A ⧸ I·A` at `x = y = 0` with values
in the domain `D = R ⧸ 𝔭`. -/
def annulusNode : annulusFibre R I q →+* R ⧸ 𝔭 :=
  annulusFibreEval R I q (map_algebraMap_le_bot_quotient R I 𝔭 h𝔭) ![0, 0] <| by
    rw [algebraMap_q_eq_zero_quotient R I q 𝔭 h𝔭 hq]
    simp

/-- **The `x`-branch of the special fibre over `𝔭`**: evaluation at `x = X`, `y = 0`, with values in
the polynomial ring `D[X]`. -/
def annulusBranchX : annulusFibre R I q →+* Polynomial (R ⧸ 𝔭) :=
  annulusFibreEval R I q (map_algebraMap_le_bot_polynomial R I 𝔭 h𝔭) ![Polynomial.X, 0] <| by
    rw [algebraMap_q_eq_zero_polynomial R I q 𝔭 h𝔭 hq]
    simp

/-- **The `y`-branch of the special fibre over `𝔭`**: evaluation at `x = 0`, `y = X`. -/
def annulusBranchY : annulusFibre R I q →+* Polynomial (R ⧸ 𝔭) :=
  annulusFibreEval R I q (map_algebraMap_le_bot_polynomial R I 𝔭 h𝔭) ![0, Polynomial.X] <| by
    rw [algebraMap_q_eq_zero_polynomial R I q 𝔭 h𝔭 hq]
    simp

include hI h𝔭 hq in
/-- **The node lies on the `x`-branch**: setting `X = 0` in the `x`-branch gives the node. This is
the whole content of "the node is a specialization of the generic point of the `x`-line". -/
theorem annulusNode_eq_evalZero_comp_branchX :
    annulusNode R I q 𝔭 h𝔭 hq =
      (Polynomial.evalRingHom (0 : R ⧸ 𝔭)).comp (annulusBranchX R I q 𝔭 h𝔭 hq) := by
  refine annulusFibre_ext R I q hI _ _ (fun r => ?_) ?_ ?_
  · simp [annulusNode, annulusBranchX, annulusFibreEval_algebraMap, Polynomial.algebraMap_apply]
  · simp only [annulusNode, annulusBranchX, RingHom.comp_apply, annulusFibreEval_fibreX]
    simp
  · simp only [annulusNode, annulusBranchX, RingHom.comp_apply, annulusFibreEval_fibreY]
    simp

include hI h𝔭 hq in
/-- **The node lies on the `y`-branch**, the mirror of `annulusNode_eq_evalZero_comp_branchX`. -/
theorem annulusNode_eq_evalZero_comp_branchY :
    annulusNode R I q 𝔭 h𝔭 hq =
      (Polynomial.evalRingHom (0 : R ⧸ 𝔭)).comp (annulusBranchY R I q 𝔭 h𝔭 hq) := by
  refine annulusFibre_ext R I q hI _ _ (fun r => ?_) ?_ ?_
  · simp [annulusNode, annulusBranchY, annulusFibreEval_algebraMap, Polynomial.algebraMap_apply]
  · simp only [annulusNode, annulusBranchY, RingHom.comp_apply, annulusFibreEval_fibreX]
    simp
  · simp only [annulusNode, annulusBranchY, RingHom.comp_apply, annulusFibreEval_fibreY]
    simp

/-! ### The Laurent evaluation of the `x`-chart -/

/-- The unit `T` of the Laurent polynomial ring `D[T, T⁻¹]`. -/
def laurentUnitT : (LaurentPolynomial (R ⧸ 𝔭))ˣ :=
  ⟨T 1, T (-1), by rw [← T_add]; simp, by rw [← T_add]; simp⟩

@[simp] theorem laurentUnitT_val : ((laurentUnitT R 𝔭 : (LaurentPolynomial (R ⧸ 𝔭))ˣ) :
    LaurentPolynomial (R ⧸ 𝔭)) = T 1 := rfl

include h𝔭 in
/-- **Evaluation of the overlap `Ĝm = Spf R{X, X⁻¹}` at the Laurent variable**, over the residue
domain `D = R ⧸ 𝔭`: the continuous `R`-algebra map `R{X, X⁻¹} →ₐ[R] D[T, T⁻¹]` sending `X ↦ T`. -/
def annulusOverlapEvalLaurent :
    RestrictedLaurentSeries R I →ₐ[R] LaurentPolynomial (R ⧸ 𝔭) :=
  RestrictedLaurentSeries.unitEvalAlgHom R I (⊥ : Ideal (LaurentPolynomial (R ⧸ 𝔭)))
    (map_algebraMap_le_bot_laurent R I 𝔭 h𝔭) (laurentUnitT R 𝔭)

include h𝔭 in
theorem annulusOverlapEvalLaurent_X_one :
    annulusOverlapEvalLaurent R I 𝔭 h𝔭 (RestrictedLaurentSeries.X R I 1) = T 1 := by
  rw [annulusOverlapEvalLaurent, RestrictedLaurentSeries.unitEvalAlgHom_X, zpow_one,
    laurentUnitT_val]

include h𝔭 in
theorem annulusOverlapEvalLaurent_X_neg_one :
    annulusOverlapEvalLaurent R I 𝔭 h𝔭 (RestrictedLaurentSeries.X R I (-1)) = T (-1) := by
  rw [annulusOverlapEvalLaurent, RestrictedLaurentSeries.unitEvalAlgHom_X, zpow_neg, zpow_one]
  rfl

include hI h𝔭 in
/-- **The Laurent evaluation of the `x`-chart algebra `A{1/x}`**: the chart-domain identification
with `A[x⁻¹]^∧`, the overlap identification `A[x⁻¹]^∧ ≅ R{X, X⁻¹}`, and evaluation at `T`. -/
def annulusChartEvalLaurent :
    awayCompletion (annulusIdealOfDefinition R I q) (overlapX R I q) →+*
      LaurentPolynomial (R ⧸ 𝔭) :=
  (((annulusOverlapEvalLaurent R I 𝔭 h𝔭).toRingHom.comp
    (overlapEquiv R I q hI).toRingHom)).comp (annulusChartOverlapAlgX R I q).toRingHom

include hI h𝔭 in
theorem annulusChartEvalLaurent_comp_awayCompletionHom :
    (annulusChartEvalLaurent R I q hI 𝔭 h𝔭).comp
        (awayCompletionHom (annulusIdealOfDefinition R I q) (overlapX R I q)) =
      ((annulusOverlapEvalLaurent R I 𝔭 h𝔭).toRingHom.comp
        (overlapEquiv R I q hI).toRingHom).comp
          (algebraMap (annulusAlgebra R I q) (annulusOverlap R I q)) := by
  rw [annulusChartEvalLaurent, RingHom.comp_assoc, chartOverlapAlgX_comp_awayCompletionHom]

include hI h𝔭 in
theorem annulusChartEvalLaurent_comp_annulusTransitionedChartY :
    (annulusChartEvalLaurent R I q hI 𝔭 h𝔭).comp (annulusTransitionedChartY R I q hI) =
      ((annulusOverlapEvalLaurent R I 𝔭 h𝔭).toRingHom.comp
        (overlapEquiv R I q hI).toRingHom).comp
          ((annulusOverlapInversion R I q hI).symm.toRingHom.comp
            (algebraMap (annulusAlgebra R I q) (annulusOverlapY R I q))) := by
  rw [annulusChartEvalLaurent, RingHom.comp_assoc,
    chartOverlapAlgX_comp_annulusTransitionedChartY]

/-! ### The two chart maps are the two branches -/

include hI h𝔭 in
/-- The Laurent evaluation kills the ideal of definition of the chart algebra: `I` acts as zero on
`D[T, T⁻¹]`. -/
theorem annulusChartEvalLaurent_le_ker :
    awayCompletionIdeal (annulusIdealOfDefinition R I q) (overlapX R I q) ≤
      RingHom.ker (annulusChartEvalLaurent R I q hI 𝔭 h𝔭) := by
  rw [← map_algebraMap_awayCompletion (overlapX R I q) (annulus_map_eq R I q),
    Ideal.map_le_iff_le_comap]
  intro r hr
  simp only [Ideal.mem_comap, RingHom.mem_ker]
  have h1 : algebraMap R (awayCompletion (annulusIdealOfDefinition R I q) (overlapX R I q)) r =
      awayCompletionHom (annulusIdealOfDefinition R I q) (overlapX R I q)
        (algebraMap R (annulusAlgebra R I q) r) :=
    (RingHom.congr_fun (awayCompletionHom_comp_algebraMap
      (L := annulusIdealOfDefinition R I q) (overlapX R I q)) r).symm
  have h2 := RingHom.congr_fun (annulusChartEvalLaurent_comp_awayCompletionHom R I q hI 𝔭 h𝔭)
    (algebraMap R (annulusAlgebra R I q) r)
  simp only [RingHom.comp_apply, RingEquiv.toRingHom_eq_coe,
    AlgHom.toRingHom_eq_coe, RingHom.coe_coe] at h2
  rw [h1, h2, ← IsScalarTower.algebraMap_apply R (annulusAlgebra R I q) (annulusOverlap R I q) r,
    show overlapEquiv R I q hI (algebraMap R (annulusOverlap R I q) r) =
      algebraMap R (RestrictedLaurentSeries R I) r from (overlapHomAlg R I q hI).commutes r,
    show annulusOverlapEvalLaurent R I 𝔭 h𝔭 (algebraMap R (RestrictedLaurentSeries R I) r) =
      algebraMap R (LaurentPolynomial (R ⧸ 𝔭)) r from
        (annulusOverlapEvalLaurent R I 𝔭 h𝔭).commutes r]
  exact Ideal.mem_bot.mp (map_algebraMap_le_bot_laurent R I 𝔭 h𝔭 (Ideal.mem_map_of_mem _ hr))

include hI h𝔭 in
/-- The Laurent evaluation of the `x`-chart, descended to the residue ring of the chart algebra —
that is, to the underlying space of `Spf A{1/x}`. -/
def annulusChartEvalLaurentFibre :
    (awayCompletion (annulusIdealOfDefinition R I q) (overlapX R I q) ⧸
      awayCompletionIdeal (annulusIdealOfDefinition R I q) (overlapX R I q)) →+*
        LaurentPolynomial (R ⧸ 𝔭) :=
  Ideal.Quotient.lift _ (annulusChartEvalLaurent R I q hI 𝔭 h𝔭)
    fun _ ha => annulusChartEvalLaurent_le_ker R I q hI 𝔭 h𝔭 ha

include hI h𝔭 in
theorem annulusChartEvalLaurentFibre_quotientMap (φ : annulusAlgebra R I q →+*
      awayCompletion (annulusIdealOfDefinition R I q) (overlapX R I q))
    (hφ : annulusIdealOfDefinition R I q ≤
      (awayCompletionIdeal (annulusIdealOfDefinition R I q) (overlapX R I q)).comap φ)
    (a : annulusAlgebra R I q) :
    annulusChartEvalLaurentFibre R I q hI 𝔭 h𝔭
        (Ideal.quotientMap _ φ hφ (Ideal.Quotient.mk _ a)) =
      annulusChartEvalLaurent R I q hI 𝔭 h𝔭 (φ a) := by
  rw [Ideal.quotientMap_mk]
  rfl

include hI h𝔭 hq in
/-- **The `x`-chart is the `x`-branch.** Read on residue rings, the structural map
`A → A{1/x}` followed by the Laurent evaluation is the `x`-branch `x ↦ X`, `y ↦ 0` followed by the
inclusion `D[X] ↪ D[T, T⁻¹]`. Both sides are computed on the two coordinates and on the image of
`R`, which suffices by `annulusFibre_ext`. -/
theorem annulusChartEvalLaurentFibre_comp_chartX :
    (annulusChartEvalLaurentFibre R I q hI 𝔭 h𝔭).comp
        (Ideal.quotientMap _ (awayCompletionHom (annulusIdealOfDefinition R I q) (overlapX R I q))
          (le_comap_awayCompletionHom _ _)) =
      Polynomial.toLaurent.comp (annulusBranchX R I q 𝔭 h𝔭 hq) := by
  have key : ∀ a : annulusAlgebra R I q,
      (annulusChartEvalLaurentFibre R I q hI 𝔭 h𝔭).comp
          (Ideal.quotientMap _ (awayCompletionHom (annulusIdealOfDefinition R I q)
            (overlapX R I q)) (le_comap_awayCompletionHom _ _)) (Ideal.Quotient.mk _ a) =
        annulusOverlapEvalLaurent R I 𝔭 h𝔭 (overlapEquiv R I q hI
          (algebraMap (annulusAlgebra R I q) (annulusOverlap R I q) a)) := by
    intro a
    rw [RingHom.comp_apply, annulusChartEvalLaurentFibre_quotientMap]
    have h2 := RingHom.congr_fun (annulusChartEvalLaurent_comp_awayCompletionHom R I q hI 𝔭 h𝔭) a
    simp only [RingHom.comp_apply, RingEquiv.toRingHom_eq_coe,
      AlgHom.toRingHom_eq_coe, RingHom.coe_coe] at h2
    exact h2
  refine annulusFibre_ext R I q hI _ _ (fun r => ?_) ?_ ?_
  · rw [show algebraMap R (annulusFibre R I q) r =
        Ideal.Quotient.mk _ (algebraMap R (annulusAlgebra R I q) r) from rfl, key,
      ← IsScalarTower.algebraMap_apply R (annulusAlgebra R I q) (annulusOverlap R I q) r,
      show overlapEquiv R I q hI (algebraMap R (annulusOverlap R I q) r) =
        algebraMap R (RestrictedLaurentSeries R I) r from (overlapHomAlg R I q hI).commutes r,
      show annulusOverlapEvalLaurent R I 𝔭 h𝔭 (algebraMap R (RestrictedLaurentSeries R I) r) =
        algebraMap R (LaurentPolynomial (R ⧸ 𝔭)) r from
          (annulusOverlapEvalLaurent R I 𝔭 h𝔭).commutes r,
      RingHom.comp_apply, annulusBranchX, annulusFibreEval_mk, annulusEvalHom_algebraMap,
      Polynomial.algebraMap_apply, LaurentPolynomial.algebraMap_apply, Polynomial.toLaurent_C]
  · rw [show fibreX R I q = Ideal.Quotient.mk _ (overlapX R I q) from rfl, key,
      overlapEquiv_overlapX, annulusOverlapEvalLaurent_X_one, RingHom.comp_apply, annulusBranchX,
      annulusFibreEval_mk, annulusEvalHom_overlapX]
    simp
  · rw [show fibreY R I q = Ideal.Quotient.mk _ (overlapY R I q) from rfl, key,
      show overlapY R I q = annulusMk R I q (annulusY R I) from rfl, overlapEquiv_annulusY,
      map_mul, annulusOverlapEvalLaurent_X_neg_one,
      show annulusOverlapEvalLaurent R I 𝔭 h𝔭 (algebraMap R (RestrictedLaurentSeries R I) q) =
        algebraMap R (LaurentPolynomial (R ⧸ 𝔭)) q from
          (annulusOverlapEvalLaurent R I 𝔭 h𝔭).commutes q,
      algebraMap_q_eq_zero_laurent R I q 𝔭 h𝔭 hq, zero_mul, RingHom.comp_apply, annulusBranchX,
      annulusFibreEval_mk, annulusEvalHom_overlapY]
    simp

include hI h𝔭 hq in
/-- **The transported `y`-chart kills `x`.** In the overlap coordinates the transported `x` is
`q · X`, and `q` dies in the residue domain `D = R ⧸ 𝔭`. Proved from the Tate relation `x·y = q`
and the fact that the transported `y` is the *unit* `T⁻¹`. -/
theorem annulusOverlapEvalLaurent_inversion_overlapX :
    annulusOverlapEvalLaurent R I 𝔭 h𝔭 (overlapEquiv R I q hI
      ((annulusOverlapInversion R I q hI).symm
        (algebraMap (annulusAlgebra R I q) (annulusOverlapY R I q) (overlapX R I q)))) = 0 := by
  have hlin : (annulusOverlapInversion R I q hI).symm
      (algebraMap R (annulusOverlapY R I q) q) = algebraMap R (annulusOverlap R I q) q := by
    have := RingHom.congr_fun (annulusOverlapInversion_symm_comp_algebraMap R I q hI) q
    simpa only [RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom] using this
  have hprod : (annulusOverlapInversion R I q hI).symm
        (algebraMap (annulusAlgebra R I q) (annulusOverlapY R I q) (overlapX R I q)) *
      (annulusOverlapInversion R I q hI).symm
        (algebraMap (annulusAlgebra R I q) (annulusOverlapY R I q) (overlapY R I q)) =
      algebraMap R (annulusOverlap R I q) q := by
    rw [← map_mul, ← map_mul, overlapX_mul_overlapY,
      ← IsScalarTower.algebraMap_apply R (annulusAlgebra R I q) (annulusOverlapY R I q) q, hlin]
  have hq0 : annulusOverlapEvalLaurent R I 𝔭 h𝔭 (overlapEquiv R I q hI
      (algebraMap R (annulusOverlap R I q) q)) = 0 := by
    rw [show overlapEquiv R I q hI (algebraMap R (annulusOverlap R I q) q) =
        algebraMap R (RestrictedLaurentSeries R I) q from (overlapHomAlg R I q hI).commutes q,
      show annulusOverlapEvalLaurent R I 𝔭 h𝔭 (algebraMap R (RestrictedLaurentSeries R I) q) =
        algebraMap R (LaurentPolynomial (R ⧸ 𝔭)) q from
          (annulusOverlapEvalLaurent R I 𝔭 h𝔭).commutes q,
      algebraMap_q_eq_zero_laurent R I q 𝔭 h𝔭 hq]
  have hmul := congrArg (fun z => annulusOverlapEvalLaurent R I 𝔭 h𝔭 (overlapEquiv R I q hI z))
    hprod
  simp only [map_mul, overlapEquiv_annulusOverlapInversion_symm_overlapY,
    annulusOverlapEvalLaurent_X_neg_one] at hmul
  rw [hq0] at hmul
  have hTT : (T (-1) : LaurentPolynomial (R ⧸ 𝔭)) * T 1 = 1 := by rw [← T_add]; simp
  calc annulusOverlapEvalLaurent R I 𝔭 h𝔭 (overlapEquiv R I q hI
          ((annulusOverlapInversion R I q hI).symm
            (algebraMap (annulusAlgebra R I q) (annulusOverlapY R I q) (overlapX R I q))))
      = annulusOverlapEvalLaurent R I 𝔭 h𝔭 (overlapEquiv R I q hI
          ((annulusOverlapInversion R I q hI).symm
            (algebraMap (annulusAlgebra R I q) (annulusOverlapY R I q) (overlapX R I q)))) *
          ((T (-1) : LaurentPolynomial (R ⧸ 𝔭)) * T 1) := by rw [hTT, mul_one]
    _ = 0 := by rw [← mul_assoc, hmul, zero_mul]

include hI h𝔭 hq in
/-- **The transported `y`-chart is the `y`-branch.** Read on residue rings, the structural map of
the *next* patch, transported by the 𝔾m-inversion transition, is the `y`-branch `x ↦ 0`, `y ↦ X`
followed by `D[X] ↪ D[T, T⁻¹]`, `X ↦ T⁻¹`. The inversion `T ↦ T⁻¹` is where the gluing
`x_n · y_{n+1} = 1` enters. -/
theorem annulusChartEvalLaurentFibre_comp_transitionedChartY :
    (annulusChartEvalLaurentFibre R I q hI 𝔭 h𝔭).comp
        (Ideal.quotientMap _ (annulusTransitionedChartY R I q hI)
          (annulusTransitionedChartY_le_comap R I q hI)) =
      (LaurentPolynomial.invert.toRingHom.comp Polynomial.toLaurent).comp
        (annulusBranchY R I q 𝔭 h𝔭 hq) := by
  have key : ∀ a : annulusAlgebra R I q,
      (annulusChartEvalLaurentFibre R I q hI 𝔭 h𝔭).comp
          (Ideal.quotientMap _ (annulusTransitionedChartY R I q hI)
            (annulusTransitionedChartY_le_comap R I q hI)) (Ideal.Quotient.mk _ a) =
        annulusOverlapEvalLaurent R I 𝔭 h𝔭 (overlapEquiv R I q hI
          ((annulusOverlapInversion R I q hI).symm
            (algebraMap (annulusAlgebra R I q) (annulusOverlapY R I q) a))) := by
    intro a
    rw [RingHom.comp_apply, annulusChartEvalLaurentFibre_quotientMap]
    have h2 := RingHom.congr_fun
      (annulusChartEvalLaurent_comp_annulusTransitionedChartY R I q hI 𝔭 h𝔭) a
    simp only [RingHom.comp_apply, RingEquiv.toRingHom_eq_coe,
      AlgHom.toRingHom_eq_coe, RingHom.coe_coe] at h2
    exact h2
  refine annulusFibre_ext R I q hI _ _ (fun r => ?_) ?_ ?_
  · rw [show algebraMap R (annulusFibre R I q) r =
        Ideal.Quotient.mk _ (algebraMap R (annulusAlgebra R I q) r) from rfl, key,
      ← IsScalarTower.algebraMap_apply R (annulusAlgebra R I q) (annulusOverlapY R I q) r,
      show (annulusOverlapInversion R I q hI).symm (algebraMap R (annulusOverlapY R I q) r) =
        algebraMap R (annulusOverlap R I q) r from by
          simpa only [RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom]
            using RingHom.congr_fun (annulusOverlapInversion_symm_comp_algebraMap R I q hI) r,
      show overlapEquiv R I q hI (algebraMap R (annulusOverlap R I q) r) =
        algebraMap R (RestrictedLaurentSeries R I) r from (overlapHomAlg R I q hI).commutes r,
      show annulusOverlapEvalLaurent R I 𝔭 h𝔭 (algebraMap R (RestrictedLaurentSeries R I) r) =
        algebraMap R (LaurentPolynomial (R ⧸ 𝔭)) r from
          (annulusOverlapEvalLaurent R I 𝔭 h𝔭).commutes r,
      RingHom.comp_apply, RingHom.comp_apply, annulusBranchY, annulusFibreEval_mk,
      annulusEvalHom_algebraMap, Polynomial.algebraMap_apply, Polynomial.toLaurent_C]
    simp [LaurentPolynomial.algebraMap_apply]
  · rw [show fibreX R I q = Ideal.Quotient.mk _ (overlapX R I q) from rfl, key,
      annulusOverlapEvalLaurent_inversion_overlapX R I q hI 𝔭 h𝔭 hq, RingHom.comp_apply,
      RingHom.comp_apply, annulusBranchY, annulusFibreEval_mk, annulusEvalHom_overlapX]
    simp
  · rw [show fibreY R I q = Ideal.Quotient.mk _ (overlapY R I q) from rfl, key,
      overlapEquiv_annulusOverlapInversion_symm_overlapY, annulusOverlapEvalLaurent_X_neg_one,
      RingHom.comp_apply, RingHom.comp_apply, annulusBranchY, annulusFibreEval_mk,
      annulusEvalHom_overlapY]
    simp

/-! ### The two points, and the answer -/

variable [𝔭.IsPrime]

include hI h𝔭 in
/-- **The generic point of the `𝔾m` overlap over `𝔭`**: the kernel of the Laurent evaluation of the
`x`-chart, a prime because `D[T, T⁻¹]` is a domain. Stated as a point of the residue ring, which is
by definition the underlying space of `Spf A{1/x}`. -/
def annulusOverlapGenericPoint : PrimeSpectrum
    (awayCompletion (annulusIdealOfDefinition R I q) (overlapX R I q) ⧸
      awayCompletionIdeal (annulusIdealOfDefinition R I q) (overlapX R I q)) :=
  PrimeSpectrum.comap (annulusChartEvalLaurentFibre R I q hI 𝔭 h𝔭) ⟨⊥, Ideal.isPrime_bot⟩

include h𝔭 hq in
/-- **The node of the special fibre over `𝔭`**, as a point of `Spf A`: the kernel of `annulusNode`,
a prime because `D = R ⧸ 𝔭` is a domain. -/
def annulusNodePoint : PrimeSpectrum (annulusFibre R I q) :=
  PrimeSpectrum.comap (annulusNode R I q 𝔭 h𝔭 hq) ⟨⊥, Ideal.isPrime_bot⟩

include hI h𝔭 hq in
/-- **The `x`-chart image of the overlap generic point specializes to the node**: the generic point
of the `x`-line passes through the node. Only a containment of kernels is used, and that is
`annulusNode_eq_evalZero_comp_branchX`. -/
theorem annulusOverlapChart_genericPoint_specializes :
    PrimeSpectrum.comap (Ideal.quotientMap
        (awayCompletionIdeal (annulusIdealOfDefinition R I q) (overlapX R I q))
        (awayCompletionHom (annulusIdealOfDefinition R I q) (overlapX R I q))
        (le_comap_awayCompletionHom _ _)) (annulusOverlapGenericPoint R I q hI 𝔭 h𝔭) ⤳
      annulusNodePoint R I q 𝔭 h𝔭 hq := by
  rw [← PrimeSpectrum.le_iff_specializes, annulusOverlapGenericPoint, annulusNodePoint,
    ← PrimeSpectrum.comap_comp_apply, annulusChartEvalLaurentFibre_comp_chartX R I q hI 𝔭 h𝔭 hq,
    annulusNode_eq_evalZero_comp_branchX R I q hI 𝔭 h𝔭 hq,
    PrimeSpectrum.comap_comp_apply, PrimeSpectrum.comap_comp_apply]
  have h0 : Ideal.comap (Polynomial.toLaurent (R := R ⧸ 𝔭)) (⊥ : Ideal _) = ⊥ := by
    rw [← RingHom.ker_eq_comap_bot]
    exact (RingHom.injective_iff_ker_eq_bot _).mp Polynomial.toLaurent_injective
  change Ideal.comap (annulusBranchX R I q 𝔭 h𝔭 hq) _ ≤
    Ideal.comap (annulusBranchX R I q 𝔭 h𝔭 hq) _
  exact Ideal.comap_mono (le_of_eq_of_le h0 bot_le)

include hI h𝔭 hq in
/-- **The transported `y`-chart image of the same overlap generic point also specializes to the
node**: the generic point of the `y`-line passes through the node too. Mirror of
`annulusOverlapChart_genericPoint_specializes`, over `annulusNode_eq_evalZero_comp_branchY`. -/
theorem annulusTransitionedChartY_genericPoint_specializes :
    PrimeSpectrum.comap (Ideal.quotientMap
        (awayCompletionIdeal (annulusIdealOfDefinition R I q) (overlapX R I q))
        (annulusTransitionedChartY R I q hI) (annulusTransitionedChartY_le_comap R I q hI))
        (annulusOverlapGenericPoint R I q hI 𝔭 h𝔭) ⤳
      annulusNodePoint R I q 𝔭 h𝔭 hq := by
  rw [← PrimeSpectrum.le_iff_specializes, annulusOverlapGenericPoint, annulusNodePoint,
    ← PrimeSpectrum.comap_comp_apply,
    annulusChartEvalLaurentFibre_comp_transitionedChartY R I q hI 𝔭 h𝔭 hq,
    annulusNode_eq_evalZero_comp_branchY R I q hI 𝔭 h𝔭 hq]
  simp only [PrimeSpectrum.comap_comp_apply]
  have h0 : Ideal.comap (Polynomial.toLaurent (R := R ⧸ 𝔭))
      (Ideal.comap (LaurentPolynomial.invert (R := R ⧸ 𝔭)).toRingHom (⊥ : Ideal _)) = ⊥ := by
    rw [Ideal.comap_comap, ← RingHom.ker_eq_comap_bot]
    exact (RingHom.injective_iff_ker_eq_bot _).mp
      (LaurentPolynomial.invert.injective.comp Polynomial.toLaurent_injective)
  change Ideal.comap (annulusBranchY R I q 𝔭 h𝔭 hq) _ ≤
    Ideal.comap (annulusBranchY R I q 𝔭 h𝔭 hq) _
  exact Ideal.comap_mono (le_of_eq_of_le h0 bot_le)

end Node

section Refutation

variable (𝔭 : Ideal R) [𝔭.IsPrime] (h𝔭 : I ≤ 𝔭) (hq : q ∈ I)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R]

include hI h𝔭 hq in
/-- **The `q^ℤ`-shift on the inversion-glued Tate chain is not free and properly discontinuous**,
as soon as the base has a prime containing the ideal of definition. Its node has no separating
neighbourhood: the two branches through it are exchanged by the shift, and each contains the other's
generic point in every neighbourhood of the node. -/
theorem not_isFreeProperlyDiscontinuous_tateInvPeriodAction_of_prime :
    ¬ LocallyRingedSpace.IsFreeProperlyDiscontinuous (tateInvPeriodAction R I q hq hI) := by
  refine not_isFreeProperlyDiscontinuous_tateInvPeriodAction_of_specializes R I q hq hI
    (annulusOverlapGenericPoint R I q hI 𝔭 h𝔭) (annulusNodePoint R I q 𝔭 h𝔭 hq) ?_ ?_
  · exact annulusOverlapChart_genericPoint_specializes R I q hI 𝔭 h𝔭 hq
  · have h : (annulusOverlapChartY R I q).base
        ((annulusChartTransitionInvSpf R I q hI).hom.base
          (annulusOverlapGenericPoint R I q hI 𝔭 h𝔭)) =
        PrimeSpectrum.comap (Ideal.quotientMap
          (awayCompletionIdeal (annulusIdealOfDefinition R I q) (overlapX R I q))
          (annulusTransitionedChartY R I q hI) (annulusTransitionedChartY_le_comap R I q hI))
          (annulusOverlapGenericPoint R I q hI 𝔭 h𝔭) := by
      -- `FormalSpectrum.map_comp` is stated over abstract rings, so instantiating it here is a
      -- substitution and the kernel never revisits the Tate completion types; proving the same
      -- identity in place would make it unfold `AdicCompletion.congrIdealₐ`.
      rw [annulusChartTransitionInvSpf_hom_eq]
      exact (congrFun (FormalSpectrum.map_comp _ _ _
        (awayCompletionHom (annulusIdealOfDefinition R I q) (overlapY R I q))
        (annulusChartTransitionInvAlg R I q hI).symm.toRingHom
        (le_comap_awayCompletionHom _ _) (annulusChartTransitionInvAlg_symm_le_comap R I q hI)
        (annulusTransitionedChartY_le_comap R I q hI)) _).symm
    rw [h]
    exact annulusTransitionedChartY_genericPoint_specializes R I q hI 𝔭 h𝔭 hq

include hI hq in
/-- **The period-`q` answer.** Whenever `I ≠ ⊤` — that is, whenever `Spf R` is nonempty — the
`q^ℤ`-shift `σ` on `T_inv` is not free and properly discontinuous, so the period-`q` Tate curve
`T_inv/⟨σ⟩` is **not** reachable by `LocallyRingedSpace.freeActionQuotientFormalScheme`. The
period-`q²` object `𝔈_q = T_inv/⟨σ²⟩` that the tree builds is therefore not a naming accident: it
is forced. -/
theorem not_isFreeProperlyDiscontinuous_tateInvPeriodAction (hItop : I ≠ ⊤) :
    ¬ LocallyRingedSpace.IsFreeProperlyDiscontinuous (tateInvPeriodAction R I q hq hI) := by
  obtain ⟨𝔪, h𝔪, h𝔪le⟩ := Ideal.exists_le_maximal I hItop
  haveI : 𝔪.IsPrime := h𝔪.isPrime
  exact not_isFreeProperlyDiscontinuous_tateInvPeriodAction_of_prime R I q hI 𝔪 h𝔪le hq

end Refutation

end AlgebraicGeometry
