import FormalSchemes.TateInvNodeChartNontrivial
import FormalSchemes.TateInvNodeChartSpf

set_option linter.style.header false

/-!
# The node chart's open in `T_inv/⟨σ⟩` is unique, so it can be named

Every statement this tree makes about the node chart's domain in the quotient is an *existential*
over an open `V` of `T_inv/⟨σ⟩` with `π⁻¹ V = tateInvSaturateOpens hq hI hS`: the ring
identification (`AlgebraicGeometry.exists_tateInvNodeChartAwayRingEquiv`), the nontriviality
(`AlgebraicGeometry.exists_nontrivial_actionQuotient_sections_tateInvNodeChartLocus`) and the
finitely generated adically complete ideal
(`AlgebraicGeometry.exists_isAdicComplete_sections_tateInvNodeChart_of_isLeftRegular_base`) are
three separate existentials, each carrying its own `V`, so their conclusions cannot be conjoined
without an argument that the three `V`s coincide.

They do, and the argument is two lines. `π` is surjective on points for **any** action quotient
(`AlgebraicGeometry.LocallyRingedSpace.base_surjective_of_isActionQuotient`,
`FormalSchemes.ActionQuotientCarrier`, with no hypothesis on the action), and preimage along a
surjection is injective, so the defining property determines `V` outright. This file names the
open, proves the uniqueness, and restates the three results at the named open — where they can be
conjoined, which as separate existentials they could not be.

## What is here

* `TopologicalSpace.Opens.map_obj_injective`: preimage of opens along a surjective continuous map
  is injective. General, and stated at the root namespace.
* `AlgebraicGeometry.LocallyRingedSpace.injective_opens_map_base_of_isActionQuotient`: that at the
  projection of an action quotient, where the surjectivity is automatic.
* `AlgebraicGeometry.tateInvSaturateQuotientOpens`: the open of `T_inv/⟨σ⟩` under which
  `tateInvSaturateOpens hq hI hS` sits, as a `def` — it is the image of the saturation, which is
  the witness `AlgebraicGeometry.exists_preimage_eq_tateInvSaturateOpens` already produced.
  `AlgebraicGeometry.preimage_tateInvSaturateQuotientOpens` is its defining property and
  `AlgebraicGeometry.eq_tateInvSaturateQuotientOpens` is the uniqueness.
* `AlgebraicGeometry.tateInvNodeChartQuotientOpens`: that at the node chart locus, with
  `AlgebraicGeometry.tateInvNodeChartQuotientRingEquiv` identifying its sections with
  `AlgebraicGeometry.tateInvNodeChartAwaySubring` — a `def`, not a `Nonempty`, because the open is
  no longer existentially quantified.
  `AlgebraicGeometry.eq_tateInvNodeChartQuotientOpens` is the uniqueness at that locus, which is
  how each of the tree's three existentials is read at the named open.
* `AlgebraicGeometry.tateInvNodeChartQuotientIdeal`, the candidate ideal of definition on those
  sections, again a `def`, with
  `AlgebraicGeometry.nontrivial_sections_tateInvNodeChartQuotientOpens`,
  `AlgebraicGeometry.fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base`,
  `AlgebraicGeometry.isAdicComplete_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base` and
  `AlgebraicGeometry.isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base` — so over a
  principal base ideal generated by a non-zero-divisor the candidate chart's target ring is a
  **nonzero adic ring with a finitely generated ideal of definition**, all at one named open.
* `AlgebraicGeometry.isAdicRing_and_nontrivial_tateInvNodeChartQuotientIdeal_powerSeriesInt`: that
  at `R = ℤ⟦X⟧`, `I = (X)`, `q = X`, with no hypothesis at all.

## What is *not* proved

**`hnode` is still undecided.** Nothing here builds a morphism
`Spf (tateInvNodeChartAwaySubring …) ⟶ T_inv/⟨σ⟩`, which is what
`AlgebraicGeometry.exists_formalScheme_of_exists_openImmersion_spf_of_isLeftRegular_base`
(`FormalSchemes.TateInvNodeChartSpf`) still takes as a hypothesis, and nothing here says the open
`tateInvNodeChartQuotientOpens` is an affine formal chart. What changes is that the ring, the
ideal and the open are now named objects with `IsAdicRing`-grade properties attached to *the same*
open, rather than three existentials that could not be combined.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.6.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite TopCat.Presheaf

universe u v

/-- **Preimage of opens along a surjective continuous map is injective.** `Set.preimage_injective`
packaged for `TopologicalSpace.Opens.map`, whose object part is preimage with the openness proof
carried along, so `TopologicalSpace.Opens.ext` reduces the two. -/
theorem TopologicalSpace.Opens.map_obj_injective {X Y : TopCat.{u}} {f : X ⟶ Y}
    (hf : Function.Surjective f) : Function.Injective (Opens.map f).obj := by
  intro U V h
  have hpre : (⇑f) ⁻¹' (U : Set Y) = (⇑f) ⁻¹' (V : Set Y) :=
    congrArg (fun W : Opens X => (W : Set X)) h
  exact Opens.ext (Set.preimage_injective.mpr hf hpre)

namespace AlgebraicGeometry

namespace LocallyRingedSpace

variable {G : Type v} [Group G] [Small.{u} G]
variable {X Q : LocallyRingedSpace.{u}} {a : G →* Aut X} {π : X ⟶ Q}

/-- **An open of an action quotient is determined by its preimage.** The projection is surjective
on points with no hypothesis on the action
(`AlgebraicGeometry.LocallyRingedSpace.base_surjective_of_isActionQuotient`), and that is the
whole proof. -/
theorem injective_opens_map_base_of_isActionQuotient (h : IsActionQuotient a π) :
    Function.Injective (Opens.map π.toShHom.hom.base).obj :=
  Opens.map_obj_injective (base_surjective_of_isActionQuotient h)

end LocallyRingedSpace

variable {R : Type u} [CommRing R] {I : Ideal R} {q : R}
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] {hq : q ∈ I} {hI : I.FG}
variable {S : Set (FormalSpectrum.locallyRingedSpaceObj (annulusIdealOfDefinition R I q))}

/-! ### The open, at an arbitrary open of the model patch -/

/-- **The open of `T_inv/⟨σ⟩` whose preimage is the saturation of `S`**, as a `def`: the image of
the saturation under the projection, which is open because `π` is an open map for any action
quotient. This is the witness `AlgebraicGeometry.exists_preimage_eq_tateInvSaturateOpens`
(`FormalSchemes.TateInvQuotientSections`) already produced; naming it is what lets several
statements be made about the *same* open. -/
def tateInvSaturateQuotientOpens (hS : IsOpen S) :
    Opens (actionQuotient (tateInvPeriodAction R I q hq hI)).toTopCat :=
  ⟨_, isOpen_image_base_tateInvSaturate hq hI (isActionQuotient_actionQuotientπ _) hS⟩

/-- **The defining property.** -/
@[simp]
theorem preimage_tateInvSaturateQuotientOpens (hS : IsOpen S) :
    (Opens.map (actionQuotientπ (tateInvPeriodAction R I q hq hI)).toShHom.hom.base).obj
        (tateInvSaturateQuotientOpens (hq := hq) (hI := hI) hS) =
      tateInvSaturateOpens hq hI hS :=
  Opens.ext (preimage_image_base_tateInvSaturate hq hI (isActionQuotient_actionQuotientπ _) S)

/-- **And it is the only open with that property.** Preimage along `π.base` is injective because
`π.base` is surjective, with no hypothesis on the action; this is what turns the tree's several
existentials over such an open into statements about one named object. -/
theorem eq_tateInvSaturateQuotientOpens (hS : IsOpen S)
    {V : Opens (actionQuotient (tateInvPeriodAction R I q hq hI)).toTopCat}
    (hV : (Opens.map (actionQuotientπ (tateInvPeriodAction R I q hq hI)).toShHom.hom.base).obj V =
      tateInvSaturateOpens hq hI hS) :
    V = tateInvSaturateQuotientOpens (hq := hq) (hI := hI) hS := by
  refine LocallyRingedSpace.injective_opens_map_base_of_isActionQuotient
    (isActionQuotient_actionQuotientπ (tateInvPeriodAction R I q hq hI)) ?_
  rw [hV, preimage_tateInvSaturateQuotientOpens]

/-! ### The node chart -/

variable (R I q)

/-- **The node chart's open in `T_inv/⟨σ⟩`**: `tateInvSaturateQuotientOpens` at the node chart
locus. `AlgebraicGeometry.eq_tateInvSaturateQuotientOpens` says every open the tree produces for
this locus is this one. -/
def tateInvNodeChartQuotientOpens (hq : q ∈ I) (hI : I.FG) :
    Opens (actionQuotient (tateInvPeriodAction R I q hq hI)).toTopCat :=
  tateInvSaturateQuotientOpens (hq := hq) (hI := hI) (isOpen_tateInvNodeChartLocus R I q)

/-- **Every open the tree produces for the node chart is this one.**
`AlgebraicGeometry.eq_tateInvSaturateQuotientOpens` at the node chart locus; stated separately
because the existentials of `AlgebraicGeometry.exists_tateInvNodeChartAwayRingEquiv`,
`AlgebraicGeometry.exists_nontrivial_actionQuotient_sections_tateInvNodeChartLocus` and
`AlgebraicGeometry.exists_isAdicComplete_sections_tateInvNodeChart_of_isLeftRegular_base` all have
exactly this hypothesis, so this is how each of them is read at the named open. -/
theorem eq_tateInvNodeChartQuotientOpens (hq : q ∈ I) (hI : I.FG)
    {V : Opens (actionQuotient (tateInvPeriodAction R I q hq hI)).toTopCat}
    (hV : (Opens.map (actionQuotientπ (tateInvPeriodAction R I q hq hI)).toShHom.hom.base).obj V =
      tateInvSaturateOpens hq hI (isOpen_tateInvNodeChartLocus R I q)) :
    V = tateInvNodeChartQuotientOpens R I q hq hI :=
  eq_tateInvSaturateQuotientOpens (isOpen_tateInvNodeChartLocus R I q) hV

/-- **`Γ (T_inv/⟨σ⟩, V) ≅ tateInvNodeChartAwaySubring` at the named open**, as a `def` rather than
the `Nonempty` of `AlgebraicGeometry.exists_tateInvNodeChartAwayRingEquiv`: with the open named,
`AlgebraicGeometry.tateInvChartAnnulusRingEquiv` applies directly and no existential has to be
opened. -/
def tateInvNodeChartQuotientRingEquiv (hq : q ∈ I) (hI : I.FG) :
    ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
        (op (tateInvNodeChartQuotientOpens R I q hq hI)) : Type u) ≃+*
      tateInvNodeChartAwaySubring R I q hq hI :=
  (tateInvChartAnnulusRingEquiv _ (isOpen_tateInvNodeChartLocus R I q)
      (preimage_tateInvSaturateQuotientOpens (isOpen_tateInvNodeChartLocus R I q))).trans
    (tateInvNodeChartSubringEquivAway R I q hq hI)

/-- **The section ring at the named open is nonzero**, for `I ≠ ⊤` — the `V`-free form of
`AlgebraicGeometry.exists_nontrivial_actionQuotient_sections_tateInvNodeChartLocus`. -/
theorem nontrivial_sections_tateInvNodeChartQuotientOpens (hq : q ∈ I) (hI : I.FG)
    (hItop : I ≠ ⊤) :
    Nontrivial ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
  haveI := nontrivial_tateInvNodeChartAwaySubring R I q hq hI hItop
  (tateInvNodeChartQuotientRingEquiv R I q hq hI).toRingHom.domain_nontrivial

/-- **The candidate ideal of definition, on the quotient's own sections**:
`AlgebraicGeometry.tateInvNodeChartAwayIdeal` carried back along the identification above. -/
def tateInvNodeChartQuotientIdeal (hq : q ∈ I) (hI : I.FG) :
    Ideal ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
  (tateInvNodeChartAwayIdeal R I q hq hI).map
    ((tateInvNodeChartQuotientRingEquiv R I q hq hI).symm :
      tateInvNodeChartAwaySubring R I q hq hI →+*
        ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
          (op (tateInvNodeChartQuotientOpens R I q hq hI))))

/-- **It is finitely generated**, over a principal base ideal generated by a non-zero-divisor. -/
theorem fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base (hq : q ∈ I) (hI : I.FG) (t : R)
    (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t) :
    (tateInvNodeChartQuotientIdeal R I q hq hI).FG :=
  Ideal.fg_map_ringEquiv_symm (tateInvNodeChartQuotientRingEquiv R I q hq hI)
    (fg_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base R I q hq hI t ht hreg)

/-- **And the section ring is complete for it.** -/
theorem isAdicComplete_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base (hq : q ∈ I)
    (hI : I.FG) (t : R) (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t) :
    IsAdicComplete (tateInvNodeChartQuotientIdeal R I q hq hI)
      ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
        (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
  IsAdicComplete.map_ringEquiv_symm (tateInvNodeChartQuotientRingEquiv R I q hq hI) _
    (isAdicComplete_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base R I q hq hI t ht
      hreg)

/-- **The quotient's sections over the node chart's open form an adic ring**, with
`AlgebraicGeometry.tateInvNodeChartQuotientIdeal` as ideal of definition and the topology that
ideal defines. This is
`AlgebraicGeometry.isAdicRing_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base`
(`FormalSchemes.TateInvNodeChartSpf`) moved off the subring of `A{1/(x + y − 1)}` and onto
`T_inv/⟨σ⟩` itself, and it is where that file's `IsAdicRing` statement had to end up: the source of
a chart is `Spf` of *these* sections, over *this* open.

Not an instance, for the same reasons as there — the topology is a choice and `ht`, `hreg` are not
synthesizable. Together with
`AlgebraicGeometry.nontrivial_sections_tateInvNodeChartQuotientOpens` and
`AlgebraicGeometry.fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base` this says the candidate
chart's target ring is a **nonzero** adic ring with a finitely generated ideal of definition, all
at one named open. -/
theorem isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base (hq : q ∈ I) (hI : I.FG)
    (t : R) (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t) :
    letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
        (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
      (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
    IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
  letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
    (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
  haveI := isAdicComplete_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
  ⟨rfl⟩

section Witness

/-- **The node chart's open, its section ring and its ideal at `R = ℤ⟦X⟧`, `I = (X)`, `q = X`**:
the sections are a nonzero adic ring with a finitely generated ideal of definition, with no
hypothesis at all. This is the concrete form of everything above, at the base of
`AlgebraicGeometry.isAdicRing_tateInvNodeChartAwayIdeal_powerSeriesInt`; `I ≠ ⊤` is
`PowerSeries.span_X_isPrime`'s `Ideal.IsPrime.ne_top` and the base generator `t = X` is a
non-zero-divisor. -/
theorem isAdicRing_and_nontrivial_tateInvNodeChartQuotientIdeal_powerSeriesInt :
    letI : TopologicalSpace (PowerSeries ℤ) :=
      (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}).adicTopology
    haveI : IsAdicRing (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) := ⟨rfl⟩
    letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction (PowerSeries ℤ)
        (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
        (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _))).presheaf.obj
      (op (tateInvNodeChartQuotientOpens (PowerSeries ℤ)
        (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
        (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _)))) :=
      (tateInvNodeChartQuotientIdeal (PowerSeries ℤ)
        (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
        (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _)).adicTopology
    IsAdicRing (tateInvNodeChartQuotientIdeal (PowerSeries ℤ)
        (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
        (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _)) ∧
      (tateInvNodeChartQuotientIdeal (PowerSeries ℤ)
        (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
        (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _)).FG ∧
      Nontrivial ((actionQuotient (tateInvPeriodAction (PowerSeries ℤ)
        (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
        (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _))).presheaf.obj
      (op (tateInvNodeChartQuotientOpens (PowerSeries ℤ)
        (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
        (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _)))) :=
  letI : TopologicalSpace (PowerSeries ℤ) :=
    (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}).adicTopology
  haveI : IsAdicRing (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) := ⟨rfl⟩
  ⟨isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base _ _ _
      (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _) PowerSeries.X rfl
      (IsRegular.of_ne_zero PowerSeries.X_ne_zero).left,
    fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base _ _ _
      (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _) PowerSeries.X rfl
      (IsRegular.of_ne_zero PowerSeries.X_ne_zero).left,
    nontrivial_sections_tateInvNodeChartQuotientOpens _ _ _
      (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _)
      (PowerSeries.span_X_isPrime (R := ℤ)).ne_top⟩

end Witness

end AlgebraicGeometry
