import FormalSchemes.TateAnnulusRegular
import FormalSchemes.TateInvNodeChartBaseRegular

set_option linter.style.header false

/-!
# The node chart's principal-base results at a base whose generator is a non-zero-divisor

`FormalSchemes.TateInvNodeChartBaseRegular` proves adic completeness of the node chart's candidate
ideal of definition, the filtration bridge under it and finite generation of the ideal, over a base
with `I = Ideal.span {t}`, from one hypothesis:

```
IsLeftRegular (algebraMap R (annulusAlgebra R I q) t)
```

`FormalSchemes.TateAnnulusRegular` proves that hypothesis holds whenever `t` is a non-zero-divisor
in `R`. **This file is the composite**: the three results with `hreg` replaced by `IsLeftRegular t`,
a statement about the base ring alone, and one instantiation of them at a concrete base.

## Main results

* The three principal-base results on the hypothesis `IsLeftRegular t` in `R`:
  `AlgebraicGeometry.hasCofinalInducedFiltration_tateInvNodeChartAwaySubring_of_isLeftRegular_base`,
  **`isAdicComplete_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base`** (also in
  `AlgebraicGeometry`) and
  `AlgebraicGeometry.fg_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base`.
* **`AlgebraicGeometry.isAdicComplete_tateInvNodeChartAwayIdeal_powerSeriesInt`** and
  `AlgebraicGeometry.fg_tateInvNodeChartAwayIdeal_powerSeriesInt`: those results at
  `R = ℤ⟦X⟧`, `I = Ideal.span {X}`, `q = X`, `t = X`, with the `X`-adic topology supplied by a
  `letI` as in `AlgebraicGeometry.tateInvPeriodQuotientGlobalSectionsEquivPowerSeriesInt`. Here
  `q ≠ 0`, `t ≠ 0` and `annulusAlgebra` is nontrivial
  (`AlgebraicGeometry.nontrivial_annulusAlgebra_powerSeriesInt`), so the hypotheses of the three
  results are inhabited at a base that is not the zero ring and not the discrete family.

## What is *not* proved here

Nothing about `hnode`, about a chart of the quotient, or about the size of the chart ring; those
are issues 1197 and 1223. Nothing in `FormalSchemes.TateInvNodeChartBaseRegular`,
`FormalSchemes.AwayCompletionRegular` or `FormalSchemes.TateInvNodeChartPrincipal` is re-proved or
restated — every result below is a one-line composite of a theorem from one of those files with
`AlgebraicGeometry.isLeftRegular_algebraMap_annulusAlgebra`.

`IsLeftRegular t` is not shown to be necessary for the conclusions: it is sufficient, and
`AlgebraicGeometry.isLeftRegular_algebraMap_annulusAlgebra_iff` shows only that it is equivalent to
the hypothesis it replaces, not that either is needed for adic completeness.

## References

* [Bosch, *Lectures on Formal and Rigid Geometry*, LNM 2105], §9.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite TopCat.Presheaf

universe u

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

/-- **The filtration bridge over a principal base ideal generated by a non-zero-divisor.** -/
theorem hasCofinalInducedFiltration_tateInvNodeChartAwaySubring_of_isLeftRegular_base (t : R)
    (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t) :
    (tateInvNodeChartAwaySubring R I q hq hI).HasCofinalInducedFiltration
      (awayCompletionIdeal (annulusIdealOfDefinition R I q) (annulusNodeChartCoord R I q)) :=
  haveI : IsAdicComplete I R := ‹IsAdicRing I›.toIsAdicComplete
  hasCofinalInducedFiltration_tateInvNodeChartAwaySubring_of_isLeftRegular R I q hq hI t ht
    (isLeftRegular_algebraMap_annulusAlgebra q hI hreg)

/-- **The node chart ring is a complete adic ring over a principal base ideal generated by a
non-zero-divisor.** This is issue 1284's obstruction (b) discharged: the hypothesis left standing by
`isAdicComplete_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular` is a statement about the
twice-completed annulus algebra, and `isLeftRegular_algebraMap_annulusAlgebra` supplies it from
regularity of `t` in `R`. -/
theorem isAdicComplete_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base (t : R)
    (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t) :
    IsAdicComplete (tateInvNodeChartAwayIdeal R I q hq hI)
      (tateInvNodeChartAwaySubring R I q hq hI) :=
  haveI : IsAdicComplete I R := ‹IsAdicRing I›.toIsAdicComplete
  isAdicComplete_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular R I q hq hI t ht
    (isLeftRegular_algebraMap_annulusAlgebra q hI hreg)

/-- **Finite generation of the candidate ideal of definition over a principal base ideal generated
by a non-zero-divisor.** -/
theorem fg_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base (t : R)
    (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t) :
    (tateInvNodeChartAwayIdeal R I q hq hI).FG :=
  haveI : IsAdicComplete I R := ‹IsAdicRing I›.toIsAdicComplete
  fg_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular R I q hq hI t ht
    (isLeftRegular_algebraMap_annulusAlgebra q hI hreg)

/-! ### The three results at the universal Tate base -/

section Witness

/-- **The node chart ring is a complete adic ring at `R = ℤ⟦X⟧`, `I = (X)`, `q = X`**, the
universal Tate base, with the `X`-adic topology supplied by the `letI`. The base generator is
`t = X`, which is a non-zero-divisor, so
`isAdicComplete_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base` applies with
`ht : I = Ideal.span {X}` closed by `rfl`. -/
theorem isAdicComplete_tateInvNodeChartAwayIdeal_powerSeriesInt :
    letI : TopologicalSpace (PowerSeries ℤ) :=
      (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}).adicTopology
    haveI : IsAdicRing (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) := ⟨rfl⟩
    IsAdicComplete
      (tateInvNodeChartAwayIdeal (PowerSeries ℤ)
        (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
        (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _))
      (tateInvNodeChartAwaySubring (PowerSeries ℤ)
        (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
        (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _)) :=
  letI : TopologicalSpace (PowerSeries ℤ) :=
    (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}).adicTopology
  haveI : IsAdicRing (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) := ⟨rfl⟩
  isAdicComplete_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base _ _ _
    (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _) PowerSeries.X rfl
    (IsRegular.of_ne_zero PowerSeries.X_ne_zero).left

/-- **The candidate ideal of definition of the node chart is finitely generated at the universal
Tate base.** -/
theorem fg_tateInvNodeChartAwayIdeal_powerSeriesInt :
    letI : TopologicalSpace (PowerSeries ℤ) :=
      (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}).adicTopology
    haveI : IsAdicRing (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) := ⟨rfl⟩
    (tateInvNodeChartAwayIdeal (PowerSeries ℤ)
      (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) PowerSeries.X
      (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _)).FG :=
  letI : TopologicalSpace (PowerSeries ℤ) :=
    (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}).adicTopology
  haveI : IsAdicRing (Ideal.span {(PowerSeries.X : PowerSeries ℤ)}) := ⟨rfl⟩
  fg_tateInvNodeChartAwayIdeal_of_principal_of_isLeftRegular_base _ _ _
    (Ideal.mem_span_singleton_self _) (Submodule.fg_span_singleton _) PowerSeries.X rfl
    (IsRegular.of_ne_zero PowerSeries.X_ne_zero).left

end Witness

end AlgebraicGeometry
