import FormalSchemes.TateActionInv
import FormalSchemes.TateCurveModel

set_option linter.style.header false

/-!
# The Tate curve model as the quotient `𝔈_q = T_inv / ⟨σ²⟩`

Fix an adic base `(R, I)` with `I` finitely generated, `R` Noetherian, and a topologically nilpotent
Tate parameter `q ∈ I`. Two objects have been built from the formal annulus `Spf A`,
`A = R{x, y}/(x·y − q)`:

* the **inversion-glued chain** `T_inv = tateChainInv R I q hq hI`
  (`FormalSchemes.TateChainInvGlue`), a `ℤ`-indexed line of annuli glued along the 𝔾m-inversion
  `x_n · y_{n+1} = 1`, carrying the `q^ℤ`-shift `σ = tateInvShiftAut`
  (`FormalSchemes.TateActionInv`);
* the **two-chart circular model** `𝔈_q = tateCurveModel R I q hq hI`
  (`FormalSchemes.TateCurveModel`), two copies of `Spf A` glued to each other along *both* overlaps
  `D(x) ⊔ D(y)`, by the same 𝔾m-inversion transition.

This file identifies the second as a quotient of the first: the **parity map** `U_n ↦` chart
`n mod 2` glues to a morphism `π : T_inv ⟶ 𝔈_q`, and `π` exhibits `𝔈_q` as the quotient of `T_inv`
by the subgroup generated by `σ²`, in the sense of `CategoryTheory.IsActionQuotient`
(`FormalSchemes.ActionQuotient`).

## Why `σ²` and not `σ`

Two independent counts, both of which should be redone by hand before trusting this file (the
project has twice lost weeks to a prescribed route that was mathematically false):

* **The model is a 2-gon.** On the special fibre each patch `U_n` is `Spec R̄[x, y]/(x·y)`, two
  affine lines meeting at a node, and the inversion glues the `x`-line of `U_n` to the `y`-line of
  `U_{n+1}` along a `𝔾ₘ`; so each index contributes one `ℙ¹` and one node. `tateCurveGlueData'`
  glues `U₀` to `U₁` along **both** `D(x₀) ≅ D(y₁)` and `D(y₀) ≅ D(x₁)`, hence has two components
  and two nodes — the Néron **2-gon**, i.e. two shift-steps' worth of chain.
* **The 1-gon is not expressible here, and the one route past that is now closed too.**
  `CategoryTheory.GlueData'` declares `V : ∀ i j, i ≠ j → C`, so a one-object glue datum has no
  overlaps at all and its glued object is the patch itself. Two charts is the minimum, and
  `T_inv/⟨σ⟩` therefore has no model in *that* framework. This file used to stop there, calling it
  a statement about presentations rather than about existence, with the quotient locally ringed
  space existing as a coequalizer
  (`AlgebraicGeometry.LocallyRingedSpace.exists_isActionQuotient` in
  `FormalSchemes.TateQuotientColimit`) and the formal-scheme question open. What has changed is
  that the tree now has a *sufficient* criterion for that question,
  `AlgebraicGeometry.LocallyRingedSpace.freeActionQuotientFormalScheme`
  (`FormalSchemes.FreeActionQuotientFormalScheme`), which makes the quotient a formal scheme with
  no glue datum anywhere in sight — but only for a **free, properly discontinuous** action, and
  `AlgebraicGeometry.not_isFreeProperlyDiscontinuous_tateInvPeriodAction`
  (`FormalSchemes.TateInvPeriodNodePoint`) shows that `σ` is **not** one, whenever `I ≠ ⊤`: a node
  of the special fibre has no separating neighbourhood, because the generic points of the two
  branches through it are exchanged by `σ` and each lies in every neighbourhood of the node. So the
  `σ²` choice is not explained by `GlueData'` — that account is stale, the criterion needs no glue
  datum — but by the geometry of the special fibre. **Whether `T_inv/⟨σ⟩` is a formal scheme is
  still open**: the criterion is sufficient, not necessary, and nothing proved here is a negative
  statement about the quotient itself. In the literature the period-`q` curve `E_q` is formed on
  the rigid generic fibre (Bosch, §9; issue 70), which is evidence for a dead end on the formal
  side, not a proof of one.

The construction below confirms the count independently: `π` is invariant under `σ²`
(`tateQuotientPi_isActionInvariant`) precisely because the parity of `n` is unchanged by
`n ↦ n + 2`. The same computation for `σ` itself lands on chart `!b` instead of chart `b`, so the
argument does not extend to the full `σ^ℤ`-action. (Turning that into a *proof* that `π` is not
`σ`-invariant would additionally need the two charts of `𝔈_q` to have distinct images; that is not
proved here, and nothing below depends on it.)

## A naming consequence — the object called `𝔈_q` has period `q²`

On the generic fibre the inversion gluing `x_n · y_{n+1} = 1` together with `x_n · y_n = q` gives
`x_{n+1} = q · x_n`, so `σ` is multiplication by `q` and `T_inv/⟨σ²⟩ = 𝔾ₘ/q^{2ℤ}`. The formal
scheme this project calls `tateCurveModel R I q` is thus the Tate curve of period `q²` — read its
annulus parameter as a square root of the period. This is documented rather than renamed (see the
same note in `FormalSchemes.TateActionInv`); issue 620 tracks the wider docstring correction.

## Main definitions

* `AlgebraicGeometry.tateChartIndex`: the parity index map `ULift ℤ → ULift Bool`, `n ↦ n mod 2`.
* `AlgebraicGeometry.tateChartSection`: the section `⟨false⟩ ↦ ⟨0⟩`, `⟨true⟩ ↦ ⟨1⟩`.
* `AlgebraicGeometry.tateQuotientPi`: **the quotient map `π : T_inv ⟶ 𝔈_q`**.
* `AlgebraicGeometry.tateInvPeriodSqAction`: the `q^{2ℤ}`-action `n ↦ σ^{2n}` on `T_inv`.
* `AlgebraicGeometry.tateQuotientDesc`: the mediating morphism out of `𝔈_q` induced by an invariant
  morphism out of `T_inv`.
* `AlgebraicGeometry.tateQuotientIsActionQuotient`: **the headline** — `π` exhibits `𝔈_q` as
  `T_inv / ⟨σ²⟩`.

## Main results

* `AlgebraicGeometry.tateCurveModel_glueMorphisms_compat`: the abstract criterion for gluing a
  family of morphisms out of the two-chart model, the `𝔈_q`-side analogue of
  `tateChainInv_glueMorphisms_compat`.
* `AlgebraicGeometry.tateQuotientPi_isActionInvariant`, `tateQuotientPi_comp_tateQuotientDesc`,
  `tateQuotientDesc_uniq`: the three fields of the universal property.
* `AlgebraicGeometry.tateQuotientPi_comp_tateCurveModelStructMap` and
  `tateQuotientDesc_structMap`: the structural morphism `T_inv ⟶ Spf R` descends along `π`, and the
  descent is the model's own structural morphism `tateCurveModelStructMap`.

## Note on freeness

`IsActionQuotient` is a purely categorical statement and nothing below uses freeness of the action
(issue 615's `tateInvPeriodAction_injective`). Freeness is what makes `π` a *local* isomorphism and
`𝔈_q` a genuine orbit space; it is not needed to exhibit the universal property.

## References

* [Bosch, *Lectures on Formal and Rigid Geometry*, LNM 2105], §9.
* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.6.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum

universe u

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

/-! ### The parity index map -/

/-- **The parity index map.** The patch `U_n` of the chain `T_inv` is sent to the chart of the
two-chart model `𝔈_q` indexed by the parity of `n`. -/
def tateChartIndex (i : ULift.{u} ℤ) : ULift.{u} Bool := ⟨decide (i.down % 2 = 1)⟩

/-- **A section of `tateChartIndex`**: chart `⟨false⟩` is represented by the patch `U₀` and chart
`⟨true⟩` by the patch `U₁`. -/
def tateChartSection (b : ULift.{u} Bool) : ULift.{u} ℤ := ⟨if b.down then 1 else 0⟩

/-- A forward step flips the parity. -/
theorem tateChartIndex_succ {i j : ULift.{u} ℤ} (h : j.down - i.down = 1) :
    tateChartIndex j = ⟨!(tateChartIndex i).down⟩ := by
  simp only [tateChartIndex, ULift.up.injEq]
  by_cases hp : i.down % 2 = 1 <;> simp [hp] <;> omega

/-- A backward step flips the parity. -/
theorem tateChartIndex_pred {i j : ULift.{u} ℤ} (h : j.down - i.down = -1) :
    tateChartIndex j = ⟨!(tateChartIndex i).down⟩ := by
  simp only [tateChartIndex, ULift.up.injEq]
  by_cases hp : i.down % 2 = 1 <;> simp [hp] <;> omega

@[simp]
theorem tateChartIndex_tateChartSection (b : ULift.{u} Bool) :
    tateChartIndex (tateChartSection b) = b := by
  obtain ⟨b⟩ := b
  cases b <;> simp [tateChartIndex, tateChartSection]

@[simp]
theorem tateChartSection_false : tateChartSection ⟨false⟩ = (⟨0⟩ : ULift.{u} ℤ) := rfl

@[simp]
theorem tateChartSection_true : tateChartSection ⟨true⟩ = (⟨1⟩ : ULift.{u} ℤ) := rfl

/-- The representative of the flipped chart is one step forward, modulo `2`. -/
theorem tateChartSection_not_emod (b : Bool) :
    (tateChartSection (⟨!b⟩ : ULift.{u} Bool)).down % 2 =
      ((tateChartSection (⟨b⟩ : ULift.{u} Bool)).down + 1) % 2 := by
  cases b <;> simp [tateChartSection]

/-- The representative of the flipped chart is one step backward, modulo `2`. -/
theorem tateChartSection_pred_emod (b : Bool) :
    ((tateChartSection (⟨b⟩ : ULift.{u} Bool)).down - 1) % 2 =
      (tateChartSection (⟨!b⟩ : ULift.{u} Bool)).down % 2 := by
  cases b <;> simp [tateChartSection]

/-- `tateChartSection ∘ tateChartIndex` is the identity modulo `2`. -/
theorem tateChartSection_tateChartIndex_emod (i : ULift.{u} ℤ) :
    (tateChartSection (tateChartIndex i)).down % 2 = i.down % 2 := by
  simp only [tateChartSection, tateChartIndex]
  by_cases hp : i.down % 2 = 1
  · simp only [hp, decide_true, if_pos]
    omega
  · simp only [hp, decide_false, Bool.false_eq_true, if_neg, not_false_eq_true]
    omega

/-! ### The overlap identities of the two-chart model -/

omit [TopologicalSpace R] [IsAdicRing I] in
/-- **The two-chart model's glue condition at the pair `(⟨b⟩, ⟨!b⟩)`**, with both the overlap chart
and the transition spelled out. Obtained from `CategoryTheory.GlueData.glue_condition` by unfolding
`ofGlueData'` off the diagonal (the two indices `⟨b⟩`, `⟨!b⟩` are distinct) and cancelling the
`eqToHom` prefix common to `f i j` and `t i j`. -/
theorem tateCurveModel_glue_condition_desc (b : Bool) :
    coprod.desc (annulusOverlapChart R I q) (annulusOverlapChartY R I q) ≫
        (tateCurveFormalGlueData R I q hq hI).ι ⟨b⟩ =
      coprod.desc ((annulusChartTransitionInvSpf R I q hI).hom ≫ coprod.inr)
          ((annulusChartTransitionInvSpf R I q hI).inv ≫ coprod.inl) ≫
        coprod.desc (annulusOverlapChart R I q) (annulusOverlapChartY R I q) ≫
          (tateCurveFormalGlueData R I q hq hI).ι ⟨!b⟩ := by
  haveI : IsAdicRing (annulusIdealOfDefinition R I q) := annulus_isAdicRing R I q hI
  have hij' : ¬ @Eq (ULift.{u} Bool) ⟨b⟩ ⟨!b⟩ := by simp [ULift.ext_iff]
  have hji' : ¬ @Eq (ULift.{u} Bool) ⟨!b⟩ ⟨b⟩ := fun h => hij' h.symm
  have key :=
    (tateCurveFormalGlueData R I q hq hI).toLocallyRingedSpaceGlueData.toGlueData.glue_condition
      ⟨b⟩ ⟨!b⟩
  simp only [tateCurveFormalGlueData, tateCurveLRSGlueData, tateCurveGlueData',
    CategoryTheory.GlueData.ofGlueData', CategoryTheory.GlueData'.f', dif_neg hij', dif_neg hji',
    Category.assoc, eqToHom_trans_assoc, eqToHom_refl, Category.id_comp] at key
  exact ((cancel_epi (eqToHom _)).mp key).symm

omit [TopologicalSpace R] [IsAdicRing I] in
/-- **The `x`-chart of one chart of `𝔈_q` is the `y`-chart of the other**, over the 𝔾m-inversion.
The `x`-summand of `tateCurveModel_glue_condition_desc`. -/
theorem annulusOverlapChart_comp_ι_tateCurve (b : Bool) :
    annulusOverlapChart R I q ≫ (tateCurveFormalGlueData R I q hq hI).ι ⟨b⟩ =
      (annulusChartTransitionInvSpf R I q hI).hom ≫ annulusOverlapChartY R I q ≫
        (tateCurveFormalGlueData R I q hq hI).ι ⟨!b⟩ := by
  have h := coprod.inl ≫= tateCurveModel_glue_condition_desc R I q hq hI b
  simp only [Category.assoc, coprod.inl_desc_assoc, coprod.inr_desc_assoc] at h
  exact h

omit [TopologicalSpace R] [IsAdicRing I] in
/-- **The `y`-chart of one chart of `𝔈_q` is the `x`-chart of the other**, over the inverse of the
𝔾m-inversion. The `y`-summand of `tateCurveModel_glue_condition_desc`. -/
theorem annulusOverlapChartY_comp_ι_tateCurve (b : Bool) :
    annulusOverlapChartY R I q ≫ (tateCurveFormalGlueData R I q hq hI).ι ⟨b⟩ =
      (annulusChartTransitionInvSpf R I q hI).inv ≫ annulusOverlapChart R I q ≫
        (tateCurveFormalGlueData R I q hq hI).ι ⟨!b⟩ := by
  have h := coprod.inr ≫= tateCurveModel_glue_condition_desc R I q hq hI b
  simp only [Category.assoc, coprod.inl_desc_assoc, coprod.inr_desc_assoc] at h
  exact h

/-! ### Gluing morphisms out of the two-chart model -/

omit [TopologicalSpace R] [IsAdicRing I] in
/-- **Abstract criterion for gluing a family of morphisms out of the two-chart model `𝔈_q`.** A
family `k b : Spf A ⟶ Y` satisfies the obligation of `FormalScheme.GlueData.glueMorphisms` as soon
as the `x`- and `y`-charts agree with `k` over the 𝔾m-inversion chart transition. The two-chart
analogue of `tateChainInv_glueMorphisms_compat`; on the diagonal the transition is the identity
(`GlueData.t_id`), and off it the overlap is a coproduct, so the obligation is checked summandwise
by `coprod.hom_ext`. -/
theorem tateCurveModel_glueMorphisms_compat {Y : LocallyRingedSpace.{u}}
    (k : ∀ _ : ULift.{u} Bool, locallyRingedSpaceObj (annulusIdealOfDefinition R I q) ⟶ Y)
    (hx : ∀ b : Bool, annulusOverlapChart R I q ≫ k ⟨b⟩ =
      (annulusChartTransitionInvSpf R I q hI).hom ≫ annulusOverlapChartY R I q ≫ k ⟨!b⟩)
    (hy : ∀ b : Bool, annulusOverlapChartY R I q ≫ k ⟨b⟩ =
      (annulusChartTransitionInvSpf R I q hI).inv ≫ annulusOverlapChart R I q ≫ k ⟨!b⟩)
    (i j : ULift.{u} Bool) :
    (tateCurveFormalGlueData R I q hq hI).toLocallyRingedSpaceGlueData.toGlueData.f i j ≫ k i =
      (tateCurveFormalGlueData R I q hq hI).toLocallyRingedSpaceGlueData.toGlueData.t i j ≫
        (tateCurveFormalGlueData R I q hq hI).toLocallyRingedSpaceGlueData.toGlueData.f j i ≫
          k j := by
  haveI : IsAdicRing (annulusIdealOfDefinition R I q) := annulus_isAdicRing R I q hI
  by_cases hij : i = j
  · subst hij
    simp only [CategoryTheory.GlueData.t_id, Category.id_comp]
  · have hij' : ¬ @Eq (ULift.{u} Bool) i j := hij
    have hji' : ¬ @Eq (ULift.{u} Bool) j i := fun h => hij h.symm
    have hj : j = ⟨!i.down⟩ := by
      obtain ⟨bi⟩ := i; obtain ⟨bj⟩ := j
      cases bi <;> cases bj <;> simp_all
    subst hj
    simp only [tateCurveFormalGlueData, tateCurveLRSGlueData, tateCurveGlueData',
      CategoryTheory.GlueData.ofGlueData', CategoryTheory.GlueData'.f', dif_neg hij',
      dif_neg hji', Category.assoc, eqToHom_trans_assoc, eqToHom_refl, Category.id_comp]
    congr 1
    refine coprod.hom_ext ?_ ?_
    · rw [coprod.inl_desc_assoc, coprod.inl_desc_assoc, Category.assoc, coprod.inr_desc_assoc]
      exact hx i.down
    · rw [coprod.inr_desc_assoc, coprod.inr_desc_assoc, Category.assoc, coprod.inl_desc_assoc]
      exact hy i.down

/-! ### The quotient map -/

/-- **The quotient map `π : T_inv ⟶ 𝔈_q`.** The patch `U_n` of the chain is sent to the chart of the
two-chart model indexed by the parity of `n`, via `FormalScheme.GlueData.glueMorphisms`. The
compatibility obligation is `tateChainInv_glueMorphisms_compat` fed by the model's own overlap
identities: this is the step at which the two transitions must agree, and it is exactly what was
unprovable before the reroute of issue 606 — the chain used the coordinate *swap* while the model
used the 𝔾m-*inversion*. -/
def tateQuotientPi :
    (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶
      (tateCurveModel R I q hq hI).toLocallyRingedSpace :=
  (tateChainInvFormalGlueData R I q hq hI).glueMorphisms
    (fun i => (tateCurveFormalGlueData R I q hq hI).ι (tateChartIndex i))
    (tateChainInv_glueMorphisms_compat R I q hq hI _
      (fun i j h => by
        rw [tateChartIndex_succ h]
        exact annulusOverlapChart_comp_ι_tateCurve R I q hq hI (tateChartIndex i).down)
      (fun i j h => by
        rw [tateChartIndex_pred h]
        exact annulusOverlapChartY_comp_ι_tateCurve R I q hq hI (tateChartIndex i).down))

/-- The quotient map restricts along `ι i` to the inclusion of the chart of parity `i`. -/
@[reassoc (attr := simp)]
theorem ι_tateQuotientPi (i : ULift.{u} ℤ) :
    (tateChainInvFormalGlueData R I q hq hI).ι i ≫ tateQuotientPi R I q hq hI =
      (tateCurveFormalGlueData R I q hq hI).ι (tateChartIndex i) := by
  rw [tateQuotientPi, FormalScheme.GlueData.ι_glueMorphisms]

/-! ### The `q^{2ℤ}`-action -/

/-- **The `q^{2ℤ}`-period action on `T_inv`**: the group homomorphism `ℤ → Aut T_inv` sending the
additive generator to `σ²`. This — and not `tateInvPeriodAction` — is the action `𝔈_q` is the
quotient by; see the module docstring for the two counts that fix the exponent. -/
def tateInvPeriodSqAction :
    Multiplicative ℤ →* CategoryTheory.Aut (tateChainInv R I q hq hI).toLocallyRingedSpace :=
  zpowersHom _ ((tateInvShiftAut R I q hq hI) ^ (2 : ℤ))

theorem tateInvPeriodSqAction_apply (n : Multiplicative ℤ) :
    tateInvPeriodSqAction R I q hq hI n = (tateInvShiftAut R I q hq hI) ^ (2 * n.toAdd) := by
  rw [tateInvPeriodSqAction, zpowersHom_apply, zpow_mul]

/-- **An invariant morphism out of `T_inv` does not see a shift by an even number of steps.** -/
theorem tateChainInv_ι_comp_of_invariant {Y : LocallyRingedSpace.{u}}
    (f : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Y)
    (hf : IsActionInvariant (tateInvPeriodSqAction R I q hq hI) f) (i : ULift.{u} ℤ) (n : ℤ) :
    (tateChainInvFormalGlueData R I q hq hI).ι ⟨i.down + 2 * n⟩ ≫ f =
      (tateChainInvFormalGlueData R I q hq hI).ι i ≫ f := by
  have h := hf (Multiplicative.ofAdd n)
  rw [tateInvPeriodSqAction_apply] at h
  exact (congrArg (· ≫ f) (ι_tateInvShiftAut_zpow R I q hq hI (2 * n) i)).symm.trans
    ((Category.assoc _ _ _).trans (congrArg _ h))

/-- **An invariant morphism out of `T_inv` only sees the parity of the patch index.** -/
theorem tateChainInv_ι_comp_congr_of_invariant {Y : LocallyRingedSpace.{u}}
    (f : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Y)
    (hf : IsActionInvariant (tateInvPeriodSqAction R I q hq hI) f) {m n : ULift.{u} ℤ}
    (h : m.down % 2 = n.down % 2) :
    (tateChainInvFormalGlueData R I q hq hI).ι m ≫ f =
      (tateChainInvFormalGlueData R I q hq hI).ι n ≫ f := by
  obtain ⟨k, hk⟩ : ∃ k : ℤ, m.down = n.down + 2 * k := ⟨(m.down - n.down) / 2, by omega⟩
  have hm : m = (⟨n.down + 2 * k⟩ : ULift.{u} ℤ) := ULift.down_injective hk
  subst hm
  exact tateChainInv_ι_comp_of_invariant R I q hq hI f hf n k

/-- **The quotient map is invariant under the `q^{2ℤ}`-action.** The shift `σ^{2n}` translates the
cover by `2n` (`ι_tateInvShiftAut_zpow`), which does not change the parity of the index. The
corresponding computation for `σ` itself lands on the *other* chart, which is why the quotient is
taken by `σ²`; see the module docstring. -/
theorem tateQuotientPi_isActionInvariant :
    IsActionInvariant (tateInvPeriodSqAction R I q hq hI) (tateQuotientPi R I q hq hI) := by
  intro g
  rw [tateInvPeriodSqAction_apply]
  apply (tateChainInvFormalGlueData R I q hq hI).hom_ext
  intro i
  have e1 := congrArg (· ≫ tateQuotientPi R I q hq hI)
    (ι_tateInvShiftAut_zpow R I q hq hI (2 * g.toAdd) i)
  have h2 : tateChartIndex (⟨i.down + 2 * g.toAdd⟩ : ULift.{u} ℤ) = tateChartIndex i := by
    simp only [tateChartIndex, ULift.up.injEq, decide_eq_decide]
    omega
  refine (Category.assoc _ _ _).symm.trans (e1.trans ?_)
  rw [ι_tateQuotientPi, ← h2]
  exact ι_tateQuotientPi R I q hq hI _

/-! ### Adjacent-overlap identities of the chain, at fixed indices -/

/-- The forward adjacent-overlap identity of `T_inv`, at a fixed pair of indices. -/
theorem tateChainInv_overlap_forward {m n : ULift.{u} ℤ} (h : n.down - m.down = 1) :
    annulusOverlapChart R I q ≫ (tateChainInvFormalGlueData R I q hq hI).ι m =
      (annulusChartTransitionInvSpf R I q hI).hom ≫ annulusOverlapChartY R I q ≫
        (tateChainInvFormalGlueData R I q hq hI).ι n :=
  tateInvShift_overlap_forward_gen R I q hq hI id h

/-- The backward adjacent-overlap identity of `T_inv`, at a fixed pair of indices. -/
theorem tateChainInv_overlap_backward {m n : ULift.{u} ℤ} (h : n.down - m.down = -1) :
    annulusOverlapChartY R I q ≫ (tateChainInvFormalGlueData R I q hq hI).ι m =
      (annulusChartTransitionInvSpf R I q hI).inv ≫ annulusOverlapChart R I q ≫
        (tateChainInvFormalGlueData R I q hq hI).ι n :=
  tateInvShift_overlap_backward_gen R I q hq hI id h

/-- `tateChainInv_overlap_forward` postcomposed with an arbitrary morphism. -/
theorem tateChainInv_overlap_forward_comp {Y : LocallyRingedSpace.{u}}
    (f : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Y) {m n : ULift.{u} ℤ}
    (h : n.down - m.down = 1) :
    annulusOverlapChart R I q ≫ (tateChainInvFormalGlueData R I q hq hI).ι m ≫ f =
      (annulusChartTransitionInvSpf R I q hI).hom ≫ annulusOverlapChartY R I q ≫
        (tateChainInvFormalGlueData R I q hq hI).ι n ≫ f := by
  rw [← Category.assoc, tateChainInv_overlap_forward R I q hq hI h, Category.assoc,
    Category.assoc]

/-- `tateChainInv_overlap_backward` postcomposed with an arbitrary morphism. -/
theorem tateChainInv_overlap_backward_comp {Y : LocallyRingedSpace.{u}}
    (f : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Y) {m n : ULift.{u} ℤ}
    (h : n.down - m.down = -1) :
    annulusOverlapChartY R I q ≫ (tateChainInvFormalGlueData R I q hq hI).ι m ≫ f =
      (annulusChartTransitionInvSpf R I q hI).inv ≫ annulusOverlapChart R I q ≫
        (tateChainInvFormalGlueData R I q hq hI).ι n ≫ f := by
  rw [← Category.assoc, tateChainInv_overlap_backward R I q hq hI h, Category.assoc,
    Category.assoc]

/-- **The forward overlap identity for an invariant morphism, up to parity.** The target index need
only agree with `m + 1` modulo `2`: the discrepancy is absorbed by invariance. This is what makes
the two-chart model's *second* overlap available — for one of the two charts the naive step lands
on `U₂` rather than `U₀`. -/
theorem tateChainInv_overlap_forward_of_invariant {Y : LocallyRingedSpace.{u}}
    (f : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Y)
    (hf : IsActionInvariant (tateInvPeriodSqAction R I q hq hI) f) {m n : ULift.{u} ℤ}
    (h : n.down % 2 = (m.down + 1) % 2) :
    annulusOverlapChart R I q ≫ (tateChainInvFormalGlueData R I q hq hI).ι m ≫ f =
      (annulusChartTransitionInvSpf R I q hI).hom ≫ annulusOverlapChartY R I q ≫
        (tateChainInvFormalGlueData R I q hq hI).ι n ≫ f := by
  refine (tateChainInv_overlap_forward_comp R I q hq hI f (m := m)
    (n := ⟨m.down + 1⟩) (by simp)).trans ?_
  exact congrArg (fun z => (annulusChartTransitionInvSpf R I q hI).hom ≫
      annulusOverlapChartY R I q ≫ z)
    (tateChainInv_ι_comp_congr_of_invariant R I q hq hI f hf
      (m := (⟨m.down + 1⟩ : ULift.{u} ℤ)) (n := n) h.symm)

/-- **The backward overlap identity for an invariant morphism, up to parity.** -/
theorem tateChainInv_overlap_backward_of_invariant {Y : LocallyRingedSpace.{u}}
    (f : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Y)
    (hf : IsActionInvariant (tateInvPeriodSqAction R I q hq hI) f) {m n : ULift.{u} ℤ}
    (h : n.down % 2 = (m.down - 1) % 2) :
    annulusOverlapChartY R I q ≫ (tateChainInvFormalGlueData R I q hq hI).ι m ≫ f =
      (annulusChartTransitionInvSpf R I q hI).inv ≫ annulusOverlapChart R I q ≫
        (tateChainInvFormalGlueData R I q hq hI).ι n ≫ f := by
  refine (tateChainInv_overlap_backward_comp R I q hq hI f (m := m)
    (n := ⟨m.down - 1⟩) (by simp)).trans ?_
  exact congrArg (fun z => (annulusChartTransitionInvSpf R I q hI).inv ≫
      annulusOverlapChart R I q ≫ z)
    (tateChainInv_ι_comp_congr_of_invariant R I q hq hI f hf
      (m := (⟨m.down - 1⟩ : ULift.{u} ℤ)) (n := n) h.symm)

/-! ### The universal property -/

/-- **The mediating morphism `𝔈_q ⟶ Y` induced by an invariant morphism `f : T_inv ⟶ Y`.** Chart
`b` of the model is sent to the restriction of `f` along the representative patch
`U_{tateChartSection b}`. Well-definedness on the model's *two* overlaps is exactly where
invariance under `σ²` is consumed: one of the four summand obligations lands on a patch two steps
away from its representative. -/
def tateQuotientDesc {Y : LocallyRingedSpace.{u}}
    (f : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Y)
    (hf : IsActionInvariant (tateInvPeriodSqAction R I q hq hI) f) :
    (tateCurveModel R I q hq hI).toLocallyRingedSpace ⟶ Y :=
  (tateCurveFormalGlueData R I q hq hI).glueMorphisms
    (fun b => (tateChainInvFormalGlueData R I q hq hI).ι (tateChartSection b) ≫ f)
    (tateCurveModel_glueMorphisms_compat R I q hq hI _
      (fun b => tateChainInv_overlap_forward_of_invariant R I q hq hI f hf
        (m := tateChartSection ⟨b⟩) (n := tateChartSection ⟨!b⟩) (tateChartSection_not_emod b))
      (fun b => tateChainInv_overlap_backward_of_invariant R I q hq hI f hf
        (m := tateChartSection ⟨b⟩) (n := tateChartSection ⟨!b⟩)
        (tateChartSection_pred_emod b).symm))

/-- The mediating morphism restricts along `ι b` to `f` on the representative patch. -/
@[reassoc (attr := simp)]
theorem ι_tateQuotientDesc {Y : LocallyRingedSpace.{u}}
    (f : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Y)
    (hf : IsActionInvariant (tateInvPeriodSqAction R I q hq hI) f) (b : ULift.{u} Bool) :
    (tateCurveFormalGlueData R I q hq hI).ι b ≫ tateQuotientDesc R I q hq hI f hf =
      (tateChainInvFormalGlueData R I q hq hI).ι (tateChartSection b) ≫ f := by
  rw [tateQuotientDesc, FormalScheme.GlueData.ι_glueMorphisms]
  rfl

/-- **The mediating morphism factors `f` through `π`.** -/
theorem tateQuotientPi_comp_tateQuotientDesc {Y : LocallyRingedSpace.{u}}
    (f : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Y)
    (hf : IsActionInvariant (tateInvPeriodSqAction R I q hq hI) f) :
    tateQuotientPi R I q hq hI ≫ tateQuotientDesc R I q hq hI f hf = f := by
  apply (tateChainInvFormalGlueData R I q hq hI).hom_ext
  intro i
  exact (Category.assoc _ _ _).symm.trans
    ((congrArg (· ≫ tateQuotientDesc R I q hq hI f hf) (ι_tateQuotientPi R I q hq hI i)).trans
      ((ι_tateQuotientDesc R I q hq hI f hf _).trans
        (tateChainInv_ι_comp_congr_of_invariant R I q hq hI f hf
          (tateChartSection_tateChartIndex_emod i))))

/-- **The mediating morphism is the unique factorisation of `f` through `π`.** Uniqueness is
`FormalScheme.GlueData.hom_ext` on the *model*: chart `b` of `𝔈_q` is the image of the patch
`U_{tateChartSection b}` under `π`, so any factorisation is pinned down there. -/
theorem tateQuotientDesc_uniq {Y : LocallyRingedSpace.{u}}
    (f : (tateChainInv R I q hq hI).toLocallyRingedSpace ⟶ Y)
    (hf : IsActionInvariant (tateInvPeriodSqAction R I q hq hI) f)
    (m : (tateCurveModel R I q hq hI).toLocallyRingedSpace ⟶ Y)
    (hm : tateQuotientPi R I q hq hI ≫ m = f) :
    m = tateQuotientDesc R I q hq hI f hf := by
  apply (tateCurveFormalGlueData R I q hq hI).hom_ext
  intro b
  rw [ι_tateQuotientDesc]
  have h1 : (tateCurveFormalGlueData R I q hq hI).ι b =
      (tateChainInvFormalGlueData R I q hq hI).ι (tateChartSection b) ≫
        tateQuotientPi R I q hq hI := by
    rw [ι_tateQuotientPi, tateChartIndex_tateChartSection]
  rw [h1]
  exact (Category.assoc _ _ _).trans (congrArg _ hm)

/-- **The headline: `𝔈_q` is the quotient of `T_inv` by the `q^{2ℤ}`-action.** The quotient map `π`
is invariant and initial among invariant morphisms out of `T_inv`. -/
def tateQuotientIsActionQuotient :
    IsActionQuotient (tateInvPeriodSqAction R I q hq hI) (tateQuotientPi R I q hq hI) where
  isInvariant := tateQuotientPi_isActionInvariant R I q hq hI
  desc f hf := tateQuotientDesc R I q hq hI f hf
  fac f hf := tateQuotientPi_comp_tateQuotientDesc R I q hq hI f hf
  uniq f hf m hm := tateQuotientDesc_uniq R I q hq hI f hf m hm

/-! ### The structural morphism descends -/

/-- **The structural morphism `T_inv ⟶ Spf R` is invariant under the `q^{2ℤ}`-action.** The
`σ^ℤ`-statement `tateChainInvStructMap_isActionInvariant` does not typecheck in this position — the
`MonoidHom` is a different one — but its content `tateInvShiftAut_zpow_comp_structMap` is stated for
all exponents, so the restatement is free. -/
theorem tateChainInvStructMap_isActionInvariant_sq :
    IsActionInvariant (tateInvPeriodSqAction R I q hq hI) (tateChainInvStructMap R I q hq hI) := by
  intro g
  rw [tateInvPeriodSqAction_apply]
  exact tateInvShiftAut_zpow_comp_structMap R I q hq hI (2 * g.toAdd)

/-- The model's structural morphism restricts to `annulusStructMap` on each chart. -/
@[reassoc (attr := simp)]
theorem ι_tateCurveModelStructMap (b : ULift.{u} Bool) :
    (tateCurveFormalGlueData R I q hq hI).ι b ≫ tateCurveModelStructMap R I q hq hI =
      annulusStructMap R I q hI := by
  rw [tateCurveModelStructMap, FormalScheme.GlueData.ι_glueMorphisms]

/-- **The quotient map is over `Spf R`.** -/
theorem tateQuotientPi_comp_tateCurveModelStructMap :
    tateQuotientPi R I q hq hI ≫ tateCurveModelStructMap R I q hq hI =
      tateChainInvStructMap R I q hq hI := by
  apply (tateChainInvFormalGlueData R I q hq hI).hom_ext
  intro i
  exact (Category.assoc _ _ _).symm.trans
    ((congrArg (· ≫ tateCurveModelStructMap R I q hq hI) (ι_tateQuotientPi R I q hq hI i)).trans
      ((ι_tateCurveModelStructMap R I q hq hI _).trans
        (ι_tateChainInvStructMap R I q hq hI i).symm))

/-- **The descent of the chain's structural morphism is the model's own structural morphism.** The
morphism `𝔈_q ⟶ Spf R` produced by the universal property from
`tateChainInvStructMap_isActionInvariant_sq` is `tateCurveModelStructMap`, so the quotient
presentation is compatible with the base. -/
theorem tateQuotientDesc_structMap :
    tateQuotientDesc R I q hq hI (tateChainInvStructMap R I q hq hI)
        (tateChainInvStructMap_isActionInvariant_sq R I q hq hI) =
      tateCurveModelStructMap R I q hq hI :=
  (tateQuotientDesc_uniq R I q hq hI _ _ _
    (tateQuotientPi_comp_tateCurveModelStructMap R I q hq hI)).symm

end AlgebraicGeometry
