import FormalSchemes.TateInvNodeChartDescent

set_option linter.style.header false

/-!
# The node chart's morphism into the formal spectrum, from three continuity families

`AlgebraicGeometry.exists_formalScheme_of_isIso_desc` (`FormalSchemes.TateInvNodeChartDescent`)
leaves `hnode` as one invariant morphism

```
k : nodeChartSaturationFormalScheme … ⟶ Spf (tateInvNodeChartQuotientIdeal …)
```

whose descent along the coequalizer is an isomorphism, and says of the construction that would
build such a `k` out of `AlgebraicGeometry.nodeChartSectionsHom` —
`AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom` (`FormalSchemes.GlueHomToSpf`) — that not
one of its arguments has been discharged or attempted.

That is true of the ones that carry the content and **false of the rest**. Of the nine arguments
`charts`, `hfg`, `ψ`, `hcont`, `hI`, `ocharts`, `hofg`, `hf`, `hg`, six are supplied by
declarations already on the tree:

* `ψ` is `AlgebraicGeometry.nodeChartSectionsHom` read through `CommRingCat`'s forgetful map, which
  is `AlgebraicGeometry.nodeChartPsi` below;
* `hI` is `AlgebraicGeometry.fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base`
  (`FormalSchemes.TateInvNodeChartQuotientOpen`), under the `t`, `ht`, `hreg` this cluster's
  reductions already carry;
* `ocharts` and `hofg` are `AlgebraicGeometry.FormalScheme.OpenCover.overlapChart` and
  `AlgebraicGeometry.FormalScheme.OpenCover.overlapChart_fg` (`FormalSchemes.GlueHomToSpf`), which
  exist for exactly this argument;
* `charts` and `hfg` are supplied by the caller, and for a caller who has nothing better to supply
  `AlgebraicGeometry.FormalScheme.LocallyFG.chart` and `LocallyFG.fg_chart`
  (`FormalSchemes.GlobalSectionsHom`) give a family at once, since
  `AlgebraicGeometry.nodeChartSaturationFormalScheme_locallyFG` is available.

**So the residue is `hcont`, `hf` and `hg` — three families, all of them continuity — and given
them the morphism is constructed rather than hypothesised.** That is what this file records.

**It does not make `hnode` any more likely to be true.** Nine unchecked hypotheses become three
unchecked ones plus the two obligations the descent packaging already had; not one continuity
family is discharged here, no invariance is proved, and no isomorphism is produced. If all three
families were false of every chart family, everything below would still be correct and `hnode`
would still be open. And the chain back to `hnode` still passes through
`AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens`, which
discharges a containment of ranges — see the `Sufficient, and not equivalent` paragraph of
`FormalSchemes.TateInvNodeChartRestrictedQuotient` — so refuting the hypothesis of the headline
below refutes neither `hnode` nor the existence of the node chart.

## Main definitions and results

* `AlgebraicGeometry.nodeChartPsi`: `AlgebraicGeometry.nodeChartSectionsHom` as a `RingHom`, which
  is the form the construction takes.
* `AlgebraicGeometry.nodeChartOcharts` and `AlgebraicGeometry.nodeChartOcharts_fg`: the affine
  charts on the pairwise overlaps of a supplied chart family, and the finite generation of their
  ideals. Both come from `AlgebraicGeometry.FormalScheme.OpenCover.overlapChart`.
* `AlgebraicGeometry.NodeChartChartContinuous`,
  `AlgebraicGeometry.NodeChartOverlapContinuousFst` and
  `AlgebraicGeometry.NodeChartOverlapContinuousSnd`: the three continuity families, named so that
  the residue can be stated in one line and so that a successor can attack one of them without
  reproducing the others.
* `AlgebraicGeometry.nodeChartHom`: **the morphism**, for a supplied chart family and the three
  continuity families.
* `AlgebraicGeometry.nodeChartSaturationCharts` and
  `AlgebraicGeometry.nodeChartSaturationCharts_fg`: the family available when nothing better is
  supplied. See the implementation note on why it is probably the wrong one to attempt continuity
  at.
* `AlgebraicGeometry.exists_formalScheme_of_isIso_desc_nodeChartHom`: **the headline.** Over a
  principal base ideal generated by a non-zero-divisor, `T_inv/⟨σ⟩` is a formal scheme as soon as
  some chart family carries the three continuity families and the resulting morphism is invariant
  with an isomorphism for its descent.

## What is *not* proved here

**No continuity family is discharged, at any chart family, and nothing here says one can be.**
`AlgebraicGeometry.NodeChartChartContinuous` is a statement about the ideal of definition of each
chart and the chart-restriction of `AlgebraicGeometry.nodeChartPsi`; the two overlap families are
statements about the two restrictions being compared on a cover of each overlap. Each is a genuine
side condition, not a formality — `FormalSchemes.GlueHomToSpf`'s module docstring says the
continuity hypotheses there are "inherited, not incidental", and this file inherits them unchanged.

**Nor is the morphism shown to be invariant, or its descent to be an isomorphism.** Those two are
the hypothesis of `AlgebraicGeometry.exists_formalScheme_of_isIso_desc` and they stay exactly where
that file left them. What changes is only that the morphism they are about is now built by a named
construction from three continuity families instead of being quantified over.

**Nothing here bears on `AlgebraicGeometry.LocallyRingedSpace.IsFreeProperlyDiscontinuous` for the
period action**, which `AlgebraicGeometry.not_isFreeProperlyDiscontinuous_tateInvPeriodAction`
refutes globally.

## Implementation notes

**Why the headline packages its five obligations inside one `∃` rather than taking them as
arguments.** `AlgebraicGeometry.exists_formalScheme_of_isIso_desc` states its own hypothesis under
`letI`/`haveI` for the adic topology on `Γ (T_inv/⟨σ⟩, V₀)` and for
`IsAdicRing (tateInvNodeChartQuotientIdeal …)`. A statement with those two as free instance binders
cannot be fed to it, since the instances there are the canonical ones and not arbitrary. So the
whole residue has to live inside a hypothesis elaborated in that same `letI` scope.

`AlgebraicGeometry.nodeChartSaturationFormalScheme_toLocallyRingedSpace` is `rfl`, so
`AlgebraicGeometry.nodeChartHom`'s source — the formal scheme — is accepted where the packaging
expects a morphism out of the bare restriction. No transport is needed and none is used.

The three continuity families are `abbrev` and not `def` on purpose: they are passed straight back
to `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom`, whose own binders are the unfolded
inequalities, and a semireducible definition makes that application depend on unfolding during
unification.

**`AlgebraicGeometry.nodeChartSaturationCharts` is offered, not recommended, and the library says
why in so many words.** `AlgebraicGeometry.FormalScheme.LocallyFG.chart` is a `Classical.choice` of
a chart at each point, so `AlgebraicGeometry.NodeChartChartContinuous` at that family is a
statement about charts nothing describes. `FormalSchemes.GeneralFibreProductLiftAdic`'s module
docstring records that a per-chart continuity witness of exactly that shape — its `hs` — was
*unreachable* for a `Classical.choice` cover (issues 460/468/472/487), that the layer carrying it
was deleted rather than proved (issue 805), and it says: **do not reintroduce an `hs`-shaped
hypothesis in a new construction.** Everything above is stated for a supplied `charts` so that a
caller need not.

**What the reachable form looks like, and why it is not attempted here.** The fix that library
found was to choose the charts from a neighbourhood basis that already records the bound:
`AlgebraicGeometry.FormalScheme.AdicOverBaseLocallyFG` (`FormalSchemes.AdicOverBaseChart`) is
`LocallyFG` with the adic-over-base conjunct added to the chart it produces, and
`AlgebraicGeometry.FormalScheme.exists_affineChart_subset_adicOverBase` is what makes such a chart
available. Two of the three families here are that predicate's continuity conjunct, at a supplied
chart instead of an existential one: `AlgebraicGeometry.NodeChartOverlapContinuousFst` is it for
the overlap's chart over the base morphism `pullback.fst … ≫ chartMap …`, and
`AlgebraicGeometry.NodeChartOverlapContinuousSnd` the same over `pullback.snd … ≫ chartMap …`. The
third is that shape with the ring homomorphism `AlgebraicGeometry.nodeChartPsi` in place of a
morphism's global-sections map, and there is no morphism to state it over yet — building one is
what this file is for. Turning the three into basis conditions, so that a single witness supplies
the charts *and* discharges the continuity the way
`AlgebraicGeometry.FormalScheme.AdicOverBaseLocallyFG.locallyFG` and
`AlgebraicGeometry.BothChartedFibreDatumXY.adicBothCharts`
(`FormalSchemes.GeneralFibreProductLiftAdic`) do one door down, is a separate step and is not taken
here.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.4 (10.4.6), §10.6.
* [Deligne–Rapoport, *Les schémas de modules de courbes elliptiques*], II.1 — the Néron 1-gon.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite

universe u

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

/-! ### The charts on the overlaps, for a supplied chart family -/

variable (charts : ∀ x : nodeChartSaturationFormalScheme R I q hq hI,
  FormalScheme.AffineChart (nodeChartSaturationFormalScheme R I q hq hI) x)
variable (hfg : ∀ x, (charts x).I.FG)

/-- **The affine chart at a point of the `(i, j)` overlap** of the cover by a supplied chart
family. `AlgebraicGeometry.FormalScheme.OpenCover.overlapChart` exists for precisely this argument
of `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom`: the overlap of two pieces of
`AlgebraicGeometry.FormalScheme.OpenCover.ofAffineCharts` is again a locally finitely generated
formal scheme, so a chart is available at each of its points.

`AlgebraicGeometry.FormalScheme.chartOverlap` is an abbreviation for that overlap taken at
`AlgebraicGeometry.FormalScheme.ofAffineCharts_obj_locallyFG`, which is the same witness used here,
so this lands definitionally where the construction wants it. -/
def nodeChartOcharts (i j : nodeChartSaturationFormalScheme R I q hq hI)
    (x : FormalScheme.chartOverlap charts hfg i j) :
    FormalScheme.AffineChart (FormalScheme.chartOverlap charts hfg i j) x :=
  (FormalScheme.OpenCover.ofAffineCharts charts).overlapChart i j
    (FormalScheme.ofAffineCharts_obj_locallyFG charts hfg i) x

/-- The ideal of definition of `AlgebraicGeometry.nodeChartOcharts` is finitely generated, which is
the `hofg` argument of `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom`. -/
theorem nodeChartOcharts_fg (i j : nodeChartSaturationFormalScheme R I q hq hI)
    (x : FormalScheme.chartOverlap charts hfg i j) :
    (nodeChartOcharts R I q hq hI charts hfg i j x).I.FG :=
  (FormalScheme.OpenCover.ofAffineCharts charts).overlapChart_fg i j
    (FormalScheme.ofAffineCharts_obj_locallyFG charts hfg i) x

section Instances

variable [TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
  (op (tateInvNodeChartQuotientOpens R I q hq hI)))]
variable [IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI)]

/-! ### The homomorphism on global sections, as the construction wants it -/

/-- **`AlgebraicGeometry.nodeChartSectionsHom` as a ring homomorphism.** That definition is a
morphism of `CommRingCat`; `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom` takes a
`RingHom` into the global sections of the source formal scheme, and the forgetful map is the whole
bridge — the source and target types match on the nose, with no transport. -/
def nodeChartPsi :
    ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
        (op (tateInvNodeChartQuotientOpens R I q hq hI))) →+*
      (nodeChartSaturationFormalScheme R I q hq hI).presheaf.obj
        (op (⊤ : Opens (nodeChartSaturationFormalScheme R I q hq hI))) :=
  (nodeChartSectionsHom R I q hq hI).hom

/-! ### The three continuity families -/

/-- **Continuity of the chart-restrictions of `AlgebraicGeometry.nodeChartPsi`**, the `hcont`
argument of `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom`. It says that the ideal of
definition of the target pulls back into the ideal of definition of each chart along the
restriction of `ψ` to that chart, which is what makes the chart's morphism of formal spectra exist
at all. -/
abbrev NodeChartChartContinuous : Prop :=
  ∀ x, tateInvNodeChartQuotientIdeal R I q hq hI ≤ (charts x).I.comap
    (FormalScheme.chartHom charts (nodeChartPsi R I q hq hI) x)

/-- **Continuity of the first of the two restrictions compared on an overlap**, the `hf` argument
of `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom`. The two chart morphisms of an overlap
have to be shown equal, which is done one level down on the charts of the overlap; this is the
continuity that step needs on the first projection. -/
abbrev NodeChartOverlapContinuousFst (hcont : NodeChartChartContinuous R I q hq hI charts) : Prop :=
  ∀ i j, ∀ x : FormalScheme.chartOverlap charts hfg i j,
    tateInvNodeChartQuotientIdeal R I q hq hI ≤
      (nodeChartOcharts R I q hq hI charts hfg i j x).I.comap
        (globalSectionsMap (tateInvNodeChartQuotientIdeal R I q hq hI)
          (nodeChartOcharts R I q hq hI charts hfg i j x).I
          ((nodeChartOcharts R I q hq hI charts hfg i j x).map ≫
            pullback.fst ((FormalScheme.OpenCover.ofAffineCharts charts).cmap i)
                ((FormalScheme.OpenCover.ofAffineCharts charts).cmap j) ≫
              FormalScheme.chartMap (tateInvNodeChartQuotientIdeal R I q hq hI) charts
                (nodeChartPsi R I q hq hI) i (hcont i)))

/-- **Continuity of the second of the two restrictions compared on an overlap**, the `hg` argument
of `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom`. It is
`AlgebraicGeometry.NodeChartOverlapContinuousFst` with the second projection and the chart at `j`;
the two are separate hypotheses of the construction and neither implies the other. -/
abbrev NodeChartOverlapContinuousSnd (hcont : NodeChartChartContinuous R I q hq hI charts) : Prop :=
  ∀ i j, ∀ x : FormalScheme.chartOverlap charts hfg i j,
    tateInvNodeChartQuotientIdeal R I q hq hI ≤
      (nodeChartOcharts R I q hq hI charts hfg i j x).I.comap
        (globalSectionsMap (tateInvNodeChartQuotientIdeal R I q hq hI)
          (nodeChartOcharts R I q hq hI charts hfg i j x).I
          ((nodeChartOcharts R I q hq hI charts hfg i j x).map ≫
            pullback.snd ((FormalScheme.OpenCover.ofAffineCharts charts).cmap i)
                ((FormalScheme.OpenCover.ofAffineCharts charts).cmap j) ≫
              FormalScheme.chartMap (tateInvNodeChartQuotientIdeal R I q hq hI) charts
                (nodeChartPsi R I q hq hI) j (hcont j)))

/-! ### The morphism -/

/-- **The morphism into the node chart's formal spectrum, built from the three continuity
families.** Every other argument of `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom` is
supplied here: `ψ` by `AlgebraicGeometry.nodeChartPsi`, the overlap charts by
`AlgebraicGeometry.nodeChartOcharts` and `AlgebraicGeometry.nodeChartOcharts_fg`, and the chart
family by the caller.

This is a construction and not a hypothesis, but it says nothing about whether its inputs can be
met: the three continuity families are exactly the content, and none of them is discharged
anywhere on this tree. -/
def nodeChartHom (hfgI : (tateInvNodeChartQuotientIdeal R I q hq hI).FG)
    (hcont : NodeChartChartContinuous R I q hq hI charts)
    (hf : NodeChartOverlapContinuousFst R I q hq hI charts hfg hcont)
    (hg : NodeChartOverlapContinuousSnd R I q hq hI charts hfg hcont) :
    (nodeChartSaturationFormalScheme R I q hq hI).toLocallyRingedSpace ⟶
      locallyRingedSpaceObj (tateInvNodeChartQuotientIdeal R I q hq hI) :=
  FormalScheme.homOfGlobalSectionsHom (tateInvNodeChartQuotientIdeal R I q hq hI) charts hfg
    (nodeChartPsi R I q hq hI) hcont hfgI
    (nodeChartOcharts R I q hq hI charts hfg) (nodeChartOcharts_fg R I q hq hI charts hfg) hf hg

end Instances

/-! ### The chart family available when nothing better is supplied -/

/-- **A chosen finitely generated affine chart at each point of the saturated node-chart locus.**
`AlgebraicGeometry.nodeChartSaturationFormalScheme_locallyFG` is what makes it available, through
`AlgebraicGeometry.FormalScheme.LocallyFG.chart`.

It is offered for completeness and not recommended: see the implementation note on why continuity
at a `Classical.choice` of charts is the shape this tree has already found unreachable once. -/
def nodeChartSaturationCharts (x : nodeChartSaturationFormalScheme R I q hq hI) :
    FormalScheme.AffineChart (nodeChartSaturationFormalScheme R I q hq hI) x :=
  (nodeChartSaturationFormalScheme_locallyFG R I q hq hI).chart x

/-- The ideal of definition of `AlgebraicGeometry.nodeChartSaturationCharts` is finitely generated,
which is what choosing the chart through `LocallyFG` rather than through
`AlgebraicGeometry.FormalScheme.AffineChart.choice` buys. -/
theorem nodeChartSaturationCharts_fg (x : nodeChartSaturationFormalScheme R I q hq hI) :
    (nodeChartSaturationCharts R I q hq hI x).I.FG :=
  (nodeChartSaturationFormalScheme_locallyFG R I q hq hI).fg_chart x

/-! ### The headline -/

/-- **`hnode` from three continuity families, an invariance and an isomorphism.** Over a principal
base ideal generated by a non-zero-divisor, `T_inv/⟨σ⟩` is a formal scheme as soon as some family
of finitely generated affine charts of
`AlgebraicGeometry.nodeChartSaturationFormalScheme` carries the three continuity families and the
morphism `AlgebraicGeometry.nodeChartHom` they build is invariant with an isomorphism for its
descent.

This is `AlgebraicGeometry.exists_formalScheme_of_isIso_desc`
(`FormalSchemes.TateInvNodeChartDescent`) with its quantified morphism replaced by the named one,
and that is the whole proof. What it buys is that the morphism no longer has to be found: it is
constructed, and what is left to check about it is continuity chart by chart, plus the two
obligations the descent packaging already carried.

**It does not decide `hnode`**, and it is sufficient rather than equivalent: the chain back to
`hnode` passes through
`AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens`, which
discharges a containment of ranges, so refuting the hypothesis below refutes neither `hnode` nor
the existence of the node chart. Nor is the hypothesis weaker than the descent packaging's: a
morphism produced some other way need not be `AlgebraicGeometry.nodeChartHom` of anything. -/
theorem exists_formalScheme_of_isIso_desc_nodeChartHom (t : R) (ht : I = Ideal.span {t})
    (hreg : IsLeftRegular t)
    (he :
      letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
          (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
        (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
      haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
        isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
      ∃ (hcont : NodeChartChartContinuous R I q hq hI charts)
        (hf : NodeChartOverlapContinuousFst R I q hq hI charts hfg hcont)
        (hg : NodeChartOverlapContinuousSnd R I q hq hI charts hfg hcont)
        (hk : IsActionInvariant (tateInvNodeChartRestrictedAction R I q hq hI)
          (nodeChartHom R I q hq hI charts hfg
            (fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg)
            hcont hf hg)),
        IsIso ((isActionQuotient_actionQuotientπ
          (tateInvNodeChartRestrictedAction R I q hq hI)).desc _ hk)) :
    ∃ X : FormalScheme.{u},
      X.toLocallyRingedSpace = actionQuotient (tateInvPeriodAction R I q hq hI) := by
  letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
    (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
  haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
    isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
  obtain ⟨hcont, hf, hg, hk, hiso⟩ := he
  exact exists_formalScheme_of_isIso_desc R I q hq hI t ht hreg ⟨_, hk, hiso⟩

end AlgebraicGeometry

end
