import FormalSchemes.TateInvNodeChartRestrictedQuotient

set_option linter.style.header false

/-!
# The node chart as one invariant morphism, descended

`AlgebraicGeometry.exists_formalScheme_of_iso_actionQuotient_tateInvNodeChartRestrictedAction`
(`FormalSchemes.TateInvNodeChartRestrictedQuotient`) leaves the node-chart question as one
isomorphism of locally ringed spaces,

```
Spf (tateInvNodeChartQuotientIdeal …) ≅ actionQuotient (tateInvNodeChartRestrictedAction …)
```

between a formal spectrum and the coequalizer of an action on an open of the chain. Nothing in that
statement says which direction to build the isomorphism in, and the two sides are of quite
different kinds: one is `Spf` of a ring the tree has already computed, the other a colimit.

This file fixes the direction. The coequalizer has a universal property —
`CategoryTheory.IsActionQuotient.desc` — so a morphism *out* of it is the same thing as an
invariant morphism out of the open of the chain it is a quotient of. Feeding that through gives
`AlgebraicGeometry.exists_formalScheme_of_isIso_desc`, whose hypothesis is

> one morphism from an open of the chain into a formal spectrum, its invariance, and that its
> descent is an isomorphism.

The gain is one of *direction*, not of strength. A morphism into a formal spectrum is a `Spf`-target
problem, which is the direction this tree has a construction for
(`AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom`, `FormalSchemes.GlueHomToSpf`); the
`Spf`-source direction is the one `FormalSchemes.TateInvNodeChartHomExt` records as circular here,
since every mapping-out property it has needs the target charted already, which is what is being
asked. Whether that construction can actually be run at this source is **not settled below**; see
the last section, which names its hypotheses.

The source is packaged as a formal scheme rather than a bare restriction, because that is what any
such construction takes: `AlgebraicGeometry.nodeChartSaturationFormalScheme` is the open of the
chain cut out by the preimage of the node chart's open, which by
`AlgebraicGeometry.preimage_tateInvNodeChartQuotientOpens` is the saturation of one patch's
node-chart locus, and it is locally finitely generated because the chain is.

**Nothing here decides whether the node chart exists.** Every statement is a repackaging of a
hypothesis, and the hypothesis of the headline is no weaker and no stronger than the isomorphism it
replaces — `CategoryTheory.IsActionQuotient.desc` and `CategoryTheory.IsActionQuotient.uniq` make
the two descriptions of a morphism out of the coequalizer interchangeable, and the headline's proof
uses only the first.

## Main definitions and results

* `AlgebraicGeometry.nodeChartSaturationOpens`: the preimage in the chain of the node chart's open
  of the quotient. By `AlgebraicGeometry.preimage_tateInvNodeChartQuotientOpens` it is the
  saturation of the node chart locus.
* `AlgebraicGeometry.nodeChartSaturationFormalScheme`: that open as a formal scheme, with
  `AlgebraicGeometry.nodeChartSaturationFormalScheme_locallyFG` and
  `AlgebraicGeometry.nodeChartSaturationFormalScheme_toLocallyRingedSpace`, the latter `rfl`.
* `AlgebraicGeometry.nodeChartSectionsHom`: the projection's own section map at the node chart's
  open, landed on the global sections of that formal scheme.
* `AlgebraicGeometry.exists_formalScheme_of_isIso_desc`: **the packaging.** Over a principal base
  ideal generated by a non-zero-divisor, the quotient of the chain by the period action is a formal
  scheme as soon as some invariant morphism from
  `AlgebraicGeometry.nodeChartSaturationFormalScheme` into the formal spectrum descends to an
  isomorphism.

## What is *not* proved here

**No morphism into the formal spectrum is constructed, and none is claimed to exist.** The
hypothesis of `AlgebraicGeometry.exists_formalScheme_of_isIso_desc` quantifies over one, and
nothing on this tree produces it.

In particular, whether that morphism can be obtained from
`AlgebraicGeometry.nodeChartSectionsHom` by `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom`
is **unchecked**. That construction's source is a locally finitely generated formal scheme and its
target is a formal spectrum, so `AlgebraicGeometry.nodeChartSaturationFormalScheme` puts the source
in range, and the shape matches: the `ψ` it takes is a ring homomorphism into the global sections
of the source, which is what `AlgebraicGeometry.nodeChartSectionsHom` becomes under `CommRingCat`'s
`CategoryTheory.ConcreteCategory.hom`. But the shape is not the content. Its remaining arguments
are, and **not one of them has been discharged or attempted here**:

* a family `charts` of affine charts of the source, and `hfg`, that each of their ideals of
  definition is finitely generated;
* `hcont`, that each chart-restriction of `ψ` is continuous;
* `hI`, finite generation of the ideal of the target;
* a family `ocharts` of affine charts on every pairwise overlap of that cover, with `hofg` for
  their ideals, and the two families `hf` and `hg` of continuity conditions comparing the two
  restrictions on each overlap.

`FormalSchemes.GlueHomToSpf`'s own module docstring says the continuity hypotheses there are
"inherited, not incidental". **Anyone who claims the morphism exists must check it by producing
it**; that is a separate row and it is where the work is.

Nothing here bears on `AlgebraicGeometry.LocallyRingedSpace.IsFreeProperlyDiscontinuous` for the
period action, which `AlgebraicGeometry.not_isFreeProperlyDiscontinuous_tateInvPeriodAction`
refutes globally, and nothing here weakens it.

## Implementation notes

`CategoryTheory.asIso` must be applied with the `CategoryTheory.IsIso` instance explicit. When the
expected type is stated through a project definition — here
`AlgebraicGeometry.tateInvNodeChartRestrictedAction` — rather than through the unfolded action,
instance synthesis does not find the hypothesis in context, and the `@`-form is what goes through.

`CategoryTheory.isActionQuotient_actionQuotientπ` lives in the CategoryTheory namespace, not in
`AlgebraicGeometry.LocallyRingedSpace`, even though every use of it here is at locally ringed
spaces.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.6 (10.4.6, 10.6.10).
* [Deligne–Rapoport, *Les schémas de modules de courbes elliptiques*], II.1 — the Néron 1-gon.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite

universe u

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

/-! ### The saturated node-chart locus as a formal scheme -/

/-- **The open of the chain that the restricted action lives on**, as the preimage of the node
chart's open along the projection. It is named because four statements mention it and its
definitional spelling is a preimage rather than the saturation it is equal to.

By `AlgebraicGeometry.preimage_tateInvNodeChartQuotientOpens` it *is* the saturation of the node
chart locus, so the section computations of `FormalSchemes.TateInvNodeChartQuotientOpen` are
computations about this open. -/
def nodeChartSaturationOpens : Opens (tateChainInv R I q hq hI).toLocallyRingedSpace :=
  (Opens.map (actionQuotientπ (tateInvPeriodAction R I q hq hI)).toShHom.hom.base).obj
    (tateInvNodeChartQuotientOpens R I q hq hI)

/-- **The saturated node-chart locus as a formal scheme.** An open of a formal scheme is one, by
`AlgebraicGeometry.FormalScheme.restrictOpen`; the chain is locally finitely generated by
`AlgebraicGeometry.tateChainInv_locallyFG`, so this is too. Packaging it this way is what lets it
be the source of a construction of morphisms into a formal spectrum, which take a formal scheme
and not a bare locally ringed space. -/
def nodeChartSaturationFormalScheme : FormalScheme.{u} :=
  (tateChainInv R I q hq hI).restrictOpen (tateChainInv_locallyFG R I q hq hI)
    (nodeChartSaturationOpens R I q hq hI)

/-- `AlgebraicGeometry.nodeChartSaturationFormalScheme` is locally finitely generated, which is the
hypothesis every chart-wise construction on it asks for. -/
theorem nodeChartSaturationFormalScheme_locallyFG :
    (nodeChartSaturationFormalScheme R I q hq hI).LocallyFG :=
  FormalScheme.restrictOpen_locallyFG _ _ _

/-- **The packaging changes nothing definitionally**: the underlying locally ringed space of
`AlgebraicGeometry.nodeChartSaturationFormalScheme` is the restriction the action of
`AlgebraicGeometry.tateInvNodeChartRestrictedAction` is an action on, by `rfl`. This is what lets
a morphism out of the formal scheme be used as a morphism out of that restriction with no
transport. -/
theorem nodeChartSaturationFormalScheme_toLocallyRingedSpace :
    (nodeChartSaturationFormalScheme R I q hq hI).toLocallyRingedSpace =
      (tateChainInv R I q hq hI).toLocallyRingedSpace.restrict
        (nodeChartSaturationOpens R I q hq hI).isOpenEmbedding :=
  rfl

/-! ### The section map a morphism into the formal spectrum would induce -/

/-- **The projection's section map at the node chart's open, read on global sections.** A
construction of a morphism into a formal spectrum out of a homomorphism on global sections wants
its input to land in the global sections of the source; the projection gives its section map at the
open, and `AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso` carries that to the
restriction's `⊤`, which is not definitionally the sections over the open.

This is the candidate input, not a construction: nothing below uses it, and the module docstring
says what applying `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom` to it would still
require. -/
def nodeChartSectionsHom :
    ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
        (op (tateInvNodeChartQuotientOpens R I q hq hI))) ⟶
      (nodeChartSaturationFormalScheme R I q hq hI).presheaf.obj (op ⊤) :=
  (actionQuotientπ (tateInvPeriodAction R I q hq hI)).c.app
      (op (tateInvNodeChartQuotientOpens R I q hq hI)) ≫
    (LocallyRingedSpace.restrictTopSectionsIso _ _).inv

/-! ### The descent packaging -/

/-- **The node-chart question as one invariant morphism into the formal spectrum.** Over a
principal base ideal generated by a non-zero-divisor, the quotient of the inversion-glued chain by
the period action is a formal scheme as soon as there is a morphism from
`AlgebraicGeometry.nodeChartSaturationFormalScheme` into the formal spectrum of
`AlgebraicGeometry.tateInvNodeChartQuotientIdeal`'s ring which is invariant for
`AlgebraicGeometry.tateInvNodeChartRestrictedAction` and whose descent along the coequalizer is an
isomorphism.

This is
`AlgebraicGeometry.exists_formalScheme_of_iso_actionQuotient_tateInvNodeChartRestrictedAction`
with its isomorphism supplied by `CategoryTheory.IsActionQuotient.desc`, in the direction that
makes the outstanding object a morphism *into* a formal spectrum rather than an isomorphism of
locally ringed spaces.

**It does not decide whether the node chart exists.** The morphism is a hypothesis, no declaration
on this tree produces one, and the module docstring names what the obvious candidate construction
would still need. -/
theorem exists_formalScheme_of_isIso_desc (t : R)
    (ht : I = Ideal.span {t}) (hreg : IsLeftRegular t)
    (he :
      letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
          (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
        (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
      haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
        isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
      ∃ (k : (nodeChartSaturationFormalScheme R I q hq hI).toLocallyRingedSpace ⟶
            FormalSpectrum.locallyRingedSpaceObj (tateInvNodeChartQuotientIdeal R I q hq hI))
        (hk : IsActionInvariant (tateInvNodeChartRestrictedAction R I q hq hI) k),
        IsIso ((isActionQuotient_actionQuotientπ
          (tateInvNodeChartRestrictedAction R I q hq hI)).desc k hk)) :
    ∃ X : FormalScheme.{u},
      X.toLocallyRingedSpace = actionQuotient (tateInvPeriodAction R I q hq hI) := by
  letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
    (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
  haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
    isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
  obtain ⟨k, hk, hiso⟩ := he
  exact exists_formalScheme_of_iso_actionQuotient_tateInvNodeChartRestrictedAction
    R I q hq hI t ht hreg ⟨(@asIso _ _ _ _ _ hiso).symm⟩

end AlgebraicGeometry
