import FormalSchemes.TateInvNodeChartInvariant

set_option linter.style.header false

/-!
# Hypothesis 4 of the node chart's four: what the descent being an isomorphism actually says

`AlgebraicGeometry.exists_formalScheme_of_isIso_desc_nodeChartAdicHom`
(`FormalSchemes.TateInvNodeChartInvariant`) leaves exactly one obligation. Over a principal base
ideal generated by a non-zero-divisor, `T_inv/⟨σ⟩` is a formal scheme as soon as

```
(isActionQuotient_actionQuotientπ (tateInvNodeChartRestrictedAction …)).desc
  (nodeChartAdicHom …) (isActionInvariant_nodeChartAdicHom …)
```

is an isomorphism. Hypotheses 1 and 3 are proved (`adicSectionsLocallyFG_nodeChartPsi`,
`isActionInvariant_nodeChartAdicHom`) and the overlap condition is not a hypothesis at all since
`AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.overlapAdic`. This file takes the last one
apart. It does **not** decide it.

## The packaging comes off, and what is left when it has

`CategoryTheory.IsActionQuotient.isIso_desc_iff` (`FormalSchemes.ActionQuotient`) says a mediating
morphism is an isomorphism exactly when the invariant morphism it descends is *itself* a quotient
projection. Applied here that is
`AlgebraicGeometry.isIso_desc_nodeChartAdicHom_iff_isActionQuotient`: hypothesis 4 says nothing
about the coequalizer object, only

> `AlgebraicGeometry.nodeChartAdicHom` exhibits `Spf (tateInvNodeChartQuotientIdeal …)` as the
> quotient of the saturated node-chart locus by the restricted `σ`-action.

Because the right-hand side names no quotient object, the condition cannot depend on which
presentation of the quotient the descent was taken along
(`CategoryTheory.IsActionQuotient.isIso_desc_iff_isIso_desc`). Descending along
`AlgebraicGeometry.LocallyRingedSpace.restrictπ` instead of along the coequalizer therefore gives
the same condition at a morphism out of an honest open of `T_inv/⟨σ⟩`:

> `AlgebraicGeometry.nodeChartQuotientHom : (T_inv/⟨σ⟩)|_{V₀} ⟶ Spf (Γ (T_inv/⟨σ⟩, V₀))`,
> the unique morphism with `restrictπ ≫ nodeChartQuotientHom = nodeChartAdicHom`,

and `AlgebraicGeometry.isIso_desc_nodeChartAdicHom_iff` says hypothesis 4 is exactly that this is
an isomorphism. What comes off is the descent packaging: neither
`CategoryTheory.IsActionQuotient.desc` nor the coequalizer of the restricted action occurs in it.
What does not come off, checked on the elaborated statement rather than read off the source:
`CategoryTheory.actionQuotient` still occurs, at the *period* action, because the source is an open
of `T_inv/⟨σ⟩` itself and that is the object in question, and
`AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG` still occurs, as the type of the witness the
morphism is built from. In words: **the node chart's open of the quotient is the formal spectrum
of its own ring of sections, via the canonical comparison.**

`AlgebraicGeometry.exists_formalScheme_of_isIso_nodeChartQuotientHom` restates the headline over
that morphism.

## The two halves, and which one is discharged

`AlgebraicGeometry.LocallyRingedSpace.isIso_iff_isIso_base_and_isIso_c_app`
(`FormalSchemes.ActionQuotientRestrictQuotient`) splits it into the base map and the comparison
maps on sections, in both directions, so a refutation of either half refutes hypothesis 4. That is
`AlgebraicGeometry.isIso_desc_nodeChartAdicHom_iff_base_and_c`:

* the **space half** — the continuous map from `V₀ ⊆ T_inv/⟨σ⟩` to
  `FormalSpectrum (tateInvNodeChartQuotientIdeal …)` is a homeomorphism;
* the **sheaf half** — for every open `U` of that formal spectrum, the comparison
  `Γ (Spf …, U) ⟶ Γ ((T_inv/⟨σ⟩)|_{V₀}, f ⁻¹ U)` is an isomorphism of rings.

**The sheaf half is discharged at `U = ⊤`**, unconditionally:
`AlgebraicGeometry.isIso_c_app_top_nodeChartQuotientHom`. The route is
`AlgebraicGeometry.globalSectionsHom_nodeChartQuotientHom`, which computes the global-sections
homomorphism of the descent to be the canonical identification
`AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso`, using only that
`AlgebraicGeometry.nodeChartAdicHom` induces `AlgebraicGeometry.nodeChartPsi` on global sections
(`AlgebraicGeometry.globalSectionsHom_nodeChartAdicHom`), that `nodeChartPsi` is the pullback of
sections along the projection (`AlgebraicGeometry.nodeChartSectionsHom_eq_restrictπ`), and that a
section of a quotient is determined by its pullback
(`CategoryTheory.IsActionQuotient.injective_c_app`).

**This is a structural discharge and not progress on the geometry, and it should not be read as
one.** No property of the node locus, of the annulus algebras or of the `σ`-action enters; the
morphism was *built* from `nodeChartPsi`, so its global-sections comparison could hardly be
anything else. What it buys is a narrowing: the content of hypothesis 4 is entirely in the base map
and in the sheaf comparison at the *proper* opens of the formal spectrum.

## Main definitions and results

* `CategoryTheory.IsActionQuotient.globalSectionsHom_desc_eq`: the global-sections homomorphism of
  a descent is pinned by that of the morphism descended, because a quotient projection is injective
  on sections.
* `FormalSpectrum.isIso_c_app_top_of_bijective_globalSectionsHom`: a morphism into a formal
  spectrum whose global-sections homomorphism is bijective has an invertible comparison map at `⊤`.
* `AlgebraicGeometry.nodeChartSectionsHom_eq_restrictπ`: the node chart's section map is the
  pullback along `AlgebraicGeometry.LocallyRingedSpace.restrictπ`, read through
  `AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso`.
* `AlgebraicGeometry.nodeChartQuotientHom` and
  `AlgebraicGeometry.restrictπ_comp_nodeChartQuotientHom`: the descent along the restricted
  projection, and its defining factorisation.
* `AlgebraicGeometry.isIso_desc_nodeChartAdicHom_iff_isActionQuotient`,
  `AlgebraicGeometry.isIso_desc_nodeChartAdicHom_iff`,
  `AlgebraicGeometry.isIso_desc_nodeChartAdicHom_iff_base_and_c`: **the reductions.**
* `AlgebraicGeometry.globalSectionsHom_nodeChartQuotientHom` and
  `AlgebraicGeometry.isIso_c_app_top_nodeChartQuotientHom`: the sheaf half at `⊤`.
* `AlgebraicGeometry.exists_formalScheme_of_isIso_nodeChartQuotientHom`: the headline restated over
  the canonical comparison.

## What is *not* proved here

**`hnode` is undecided, in both directions, and nothing here moves it.** The score of
`AlgebraicGeometry.exists_formalScheme_of_adicSections` after this file is unchanged: hypothesis 1
proved, the overlap condition a theorem rather than a component, hypothesis 3 proved, **hypothesis
4 open**. No witness of hypothesis 4 is produced, and no argument that one exists is given.

**Refuting hypothesis 4 would not refute `hnode`.** The hypothesis of
`AlgebraicGeometry.exists_formalScheme_of_isIso_desc` is *existential* — some invariant morphism
whose descent is an isomorphism — and hypothesis 4 is that condition at a **named** morphism, so it
implies the existential and is a priori stronger. The chain onward through
`AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens` discharges a
containment of ranges and is one-way as well. Everything below is a restatement of hypothesis 4 and
inherits both facts.

**Neither half is decided.** For the space half, the only description of
`AlgebraicGeometry.nodeChartAdicHom` on points that exists is chart-by-chart
(`AlgebraicGeometry.FormalScheme.chart_comp_homOfGlobalSectionsHomOfAdicSections`), and
`AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.chart` is `Classical.choice`, so no
computation of the base map is available on this tree; what a decision needs is the primes of
`AlgebraicGeometry.tateInvNodeChartQuotientIdeal`'s ring, which is a statement about the invariant
sections of the chain and not a general fact. For the sheaf half at a proper open `U`, what is
needed is that `Γ (Spf …, U)` agrees with the invariant sections of the chain over the preimage of
`U` — by `AlgebraicGeometry.LocallyRingedSpace.exists_c_app_restrictπ_eq_iff_isInvariantSection`
the right-hand side of the comparison *is* those invariant sections — and that is the computation
`FormalSchemes.TateInvNodeChartQuotientOpen` carries out at `V₀` itself, at a proper open. **So the
space half is blocked by there being no handle on the base map, and the sheaf half by a
Tate-specific section computation.** Neither of those sentences is asserted by a declaration below;
they are a reading of what is present, and the reader should check it against
`AlgebraicGeometry.isIso_desc_nodeChartAdicHom_iff_base_and_c` rather than take it.

**Nothing here bears on `AlgebraicGeometry.tateInvNodeChartAmbientHom`.**
`AlgebraicGeometry.not_isOpenImmersion_tateInvNodeChartAmbientHom_of_ne_top` refutes it as an open
immersion and that refutation is untouched, as is `FormalSchemes.TateInvNodeChartAmbient`'s record
that `AlgebraicGeometry.tateInvNodeChartAwayIdeal` is not shown to be an ideal of definition. The
morphism reduced to below has a different source and a different target and no relation to it is
proved.

**Nothing here bears on `AlgebraicGeometry.LocallyRingedSpace.IsFreeProperlyDiscontinuous` for the
period action**, which `AlgebraicGeometry.not_isFreeProperlyDiscontinuous_tateInvPeriodAction`
refutes globally.

## Implementation notes

`CategoryTheory.IsActionQuotient.isIso_desc_iff` and
`CategoryTheory.IsActionQuotient.isIso_desc_iff_isIso_desc` are **not** here: they are statements
of the categorical interface with no formal scheme and no Tate hypothesis in them, and they go
beside `CategoryTheory.IsActionQuotient.exists_isIso_desc_of_iso` and
`CategoryTheory.IsActionQuotient.ofIso`, whose subject is exactly which characterisations of the
quotient are two-way. That is the disposition
`FormalSchemes.TateInvNodeChartDescent`'s implementation notes argued for and took for
`CategoryTheory.IsActionQuotient.exists_isIso_desc_of_iso` itself, at the same price:
`FormalSchemes.ActionQuotient` has reverse closure **96** — 95 before this file, which reaches
it — against this file's **7**.
`AlgebraicGeometry.LocallyRingedSpace.isIso_iff_isIso_base_and_isIso_c_app` goes beside the
one-way `AlgebraicGeometry.LocallyRingedSpace.isIso_of_isIso_base_of_isIso_c_app` in
`FormalSchemes.ActionQuotientRestrictQuotient` (reverse closure **16**, 15 before this file) for the
same reason and much more cheaply.

The two general statements that *are* here —
`CategoryTheory.IsActionQuotient.globalSectionsHom_desc_eq` and
`FormalSpectrum.isIso_c_app_top_of_bijective_globalSectionsHom` — have no existing home:
`FormalSchemes.GlobalSectionsHom` and `FormalSchemes.ActionQuotientSectionInjective` are
**import-incomparable**, neither being in the other's closure, with forward closures **42** and
**6** counted with the module itself; a home for the first would therefore be a new leaf at forward
closure **49** (48 modules besides itself). Each has one consumer, both in this file, so they are
kept here and that leaf should be cut when a second consumer appears, which is the standing
disposition on this tree for a general statement with a single consumer. This file's own forward
closure is **253** with itself, so a general statement parked here is reachable only at that
price.

`CategoryTheory.IsActionQuotient.injective_c_app` carries `HasCoproduct` and `HasCoequalizer`
instance hypotheses even though it is stated at an arbitrary presentation of the quotient — it is
proved by transporting the coequalizer case — so
`CategoryTheory.IsActionQuotient.globalSectionsHom_desc_eq` carries them too. They are discharged by
`AlgebraicGeometry.LocallyRingedSpace`'s cocompleteness at every use below.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.4 (10.4.6), §10.6.
* [Deligne–Rapoport, *Les schémas de modules de courbes elliptiques*], II.1 — the Néron 1-gon.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite

universe v u w

namespace CategoryTheory

variable {G : Type v} [Group G] {W P : AlgebraicGeometry.LocallyRingedSpace.{u}}
variable {a : G →* Aut W} {π : W ⟶ P}
variable [Limits.HasCoproduct fun _ : G => W]
  [Limits.HasCoequalizer (actionQuotientLeft a) (actionQuotientRight G W)]

/-- **The global-sections homomorphism of a descent is pinned by the one it descends.** If the
invariant `k : W ⟶ Spf S` induces `u` on global sections after pullback along the projection, then
its mediating morphism induces `u` itself.

`FormalSpectrum.globalSectionsHom_comp` gives the factorisation and
`CategoryTheory.IsActionQuotient.injective_c_app` cancels the projection, which is the whole proof:
a section of a quotient is determined by its pullback. It is what turns a computation of the
sections of a morphism *out of the source* into one about the descended morphism, where the source
is the quotient and nothing is directly computable. -/
theorem IsActionQuotient.globalSectionsHom_desc_eq {S : Type u} [CommRing S] [TopologicalSpace S]
    (J : Ideal S) [IsAdicRing J] (h : IsActionQuotient a π)
    (k : W ⟶ FormalSpectrum.locallyRingedSpaceObj J) (hk : IsActionInvariant a k)
    (u : S →+* P.presheaf.obj (op (⊤ : Opens P)))
    (hu : FormalSpectrum.globalSectionsHom J W k = (π.c.app (op (⊤ : Opens P))).hom.comp u) :
    FormalSpectrum.globalSectionsHom J P (h.desc k hk) = u := by
  have h1 : FormalSpectrum.globalSectionsHom J W k =
      (π.c.app (op (⊤ : Opens P))).hom.comp
        (FormalSpectrum.globalSectionsHom J P (h.desc k hk)) := by
    rw [← FormalSpectrum.globalSectionsHom_comp, h.fac k hk]
  refine RingHom.ext fun s => h.injective_c_app (⊤ : Opens P) ?_
  exact congrArg (fun φ : S →+* _ => φ s) (h1.symm.trans hu)

end CategoryTheory

namespace FormalSpectrum

variable {S : Type u} [CommRing S] [TopologicalSpace S] (J : Ideal S) [IsAdicRing J]

/-- **A bijective global-sections homomorphism inverts the comparison map at `⊤`.**
`FormalSpectrum.globalSectionsHom` is the comparison map at `⊤` precomposed with the isomorphism
`FormalSpectrum.globalSectionsEquiv`, so the two are bijective together; the direction stated is
the one a computation of the global-sections homomorphism feeds.

It is the `⊤` component of the sheaf half of an isomorphism criterion, and nothing more: it says
nothing about any proper open. -/
theorem isIso_c_app_top_of_bijective_globalSectionsHom {P : LocallyRingedSpace.{u}}
    (f : P ⟶ locallyRingedSpaceObj J) (h : Function.Bijective (globalSectionsHom J P f)) :
    IsIso (f.c.app (op (⊤ : Opens (FormalSpectrum J)))) := by
  rw [ConcreteCategory.isIso_iff_bijective]
  have he : ⇑(CommRingCat.Hom.hom (f.c.app (op (⊤ : Opens (FormalSpectrum J))))) =
      (globalSectionsHom J P f) ∘ (globalSectionsEquiv J) := by
    funext s
    rw [Function.comp_apply, globalSectionsHom_apply, (globalSectionsEquiv J).symm_apply_apply]
  rw [he]
  exact h.comp (globalSectionsEquiv J).bijective

end FormalSpectrum

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

/-! ### The section map, read on the restricted projection -/

set_option linter.style.setOption false in
set_option backward.isDefEq.respectTransparency false in
/-- **The node chart's section map is the pullback along the restricted projection.**
`AlgebraicGeometry.nodeChartSectionsHom_eq` presents it as the section map of
`T_inv|_{π⁻¹ V₀} ⟶ T_inv ⟶ T_inv/⟨σ⟩`; that composite factors as
`AlgebraicGeometry.LocallyRingedSpace.restrictπ` followed by the inclusion of `V₀`
(`AlgebraicGeometry.LocallyRingedSpace.restrictOpensHom_comp_ofRestrict`), and
`AlgebraicGeometry.LocallyRingedSpace.sectionsMapOfRangeSubset_comp` splits the section map along
that factorisation. The first factor is then
`AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso`, by
`AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso_inv_eq`.

This is what lets the sections of the node chart be compared with the sections of an *open of the
quotient* rather than with the sections of the chain. -/
theorem nodeChartSectionsHom_eq_restrictπ :
    nodeChartSectionsHom R I q hq hI =
      (LocallyRingedSpace.restrictTopSectionsIso (actionQuotient (tateInvPeriodAction R I q hq hI))
        (tateInvNodeChartQuotientOpens R I q hq hI)).inv ≫
        (LocallyRingedSpace.restrictπ (actionQuotientπ (tateInvPeriodAction R I q hq hI))
          (tateInvNodeChartQuotientOpens R I q hq hI)).c.app (op ⊤) := by
  rw [nodeChartSectionsHom_eq,
    LocallyRingedSpace.sectionsMapOfRangeSubset_congr
      (LocallyRingedSpace.restrictOpensHom_comp_ofRestrict
        (actionQuotientπ (tateInvPeriodAction R I q hq hI)) _ _ _).symm _
      (LocallyRingedSpace.range_ofRestrict_comp_subset _ _),
    LocallyRingedSpace.sectionsMapOfRangeSubset_comp,
    LocallyRingedSpace.restrictTopSectionsIso_inv_eq]
  all_goals first
    | rfl
    | exact le_of_eq (LocallyRingedSpace.range_ofRestrict _ _)
    | (rw [LocallyRingedSpace.restrictOpensHom_comp_ofRestrict]
       exact LocallyRingedSpace.range_ofRestrict_comp_subset _ _)

section Instances

variable [TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
  (op (tateInvNodeChartQuotientOpens R I q hq hI)))]
variable [IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI)]
variable (hfgI : (tateInvNodeChartQuotientIdeal R I q hq hI).FG)
variable (hX : FormalScheme.AdicSectionsLocallyFG (tateInvNodeChartQuotientIdeal R I q hq hI)
  (nodeChartPsi R I q hq hI))

/-! ### The descent, taken along the restricted projection -/

/-- **The canonical comparison from the node chart's open of the quotient to the formal spectrum of
its sections.** `AlgebraicGeometry.nodeChartAdicHom` is invariant
(`AlgebraicGeometry.isActionInvariant_nodeChartAdicHom`) and
`AlgebraicGeometry.LocallyRingedSpace.restrictπ` is a quotient projection for the restricted action
(`AlgebraicGeometry.isActionQuotient_restrictπ_tateInvNodeChartQuotientOpens`), so it descends. The
target's ring is `Γ (T_inv/⟨σ⟩, V₀)` itself, so this is the comparison an affineness question is
asked at.

Descending along `restrictπ` rather than along the coequalizer is not a second morphism in any
sense that matters: by `CategoryTheory.IsActionQuotient.isIso_desc_iff_isIso_desc` the two are
isomorphisms together, which is `AlgebraicGeometry.isIso_desc_nodeChartAdicHom_iff`. What it buys
is that the source is an open of `T_inv/⟨σ⟩` and not a coequalizer nobody can compute in. -/
def nodeChartQuotientHom :
    (actionQuotient (tateInvPeriodAction R I q hq hI)).restrict
        (tateInvNodeChartQuotientOpens R I q hq hI).isOpenEmbedding ⟶
      locallyRingedSpaceObj (tateInvNodeChartQuotientIdeal R I q hq hI) :=
  (isActionQuotient_restrictπ_tateInvNodeChartQuotientOpens R I q hq hI).desc
    (nodeChartAdicHom R I q hq hI hfgI hX)
    (isActionInvariant_nodeChartAdicHom R I q hq hI hfgI hX)

/-- **Its defining property**: pulled back along the restricted projection it is
`AlgebraicGeometry.nodeChartAdicHom`. `CategoryTheory.IsActionQuotient.fac`, recorded because every
computation below runs through it. -/
theorem restrictπ_comp_nodeChartQuotientHom :
    LocallyRingedSpace.restrictπ (actionQuotientπ (tateInvPeriodAction R I q hq hI))
        (tateInvNodeChartQuotientOpens R I q hq hI) ≫
      nodeChartQuotientHom R I q hq hI hfgI hX = nodeChartAdicHom R I q hq hI hfgI hX :=
  (isActionQuotient_restrictπ_tateInvNodeChartQuotientOpens R I q hq hI).fac _ _

/-! ### The reductions -/

/-- **Hypothesis 4 says `AlgebraicGeometry.nodeChartAdicHom` is itself a quotient projection.**
`CategoryTheory.IsActionQuotient.isIso_desc_iff` at the node chart. The right-hand side names no
quotient object and no mediating morphism, so this is the packaging coming off: what hypothesis 4
asks is that the morphism into the formal spectrum exhibit that formal spectrum as
`T_inv|_{π⁻¹ V₀} / ⟨σ⟩`.

`Nonempty` because `CategoryTheory.IsActionQuotient` carries its mediating morphism as data. -/
theorem isIso_desc_nodeChartAdicHom_iff_isActionQuotient :
    IsIso ((isActionQuotient_actionQuotientπ (tateInvNodeChartRestrictedAction R I q hq hI)).desc
        (nodeChartAdicHom R I q hq hI hfgI hX)
        (isActionInvariant_nodeChartAdicHom R I q hq hI hfgI hX)) ↔
      Nonempty (IsActionQuotient (tateInvNodeChartRestrictedAction R I q hq hI)
        (nodeChartAdicHom R I q hq hI hfgI hX)) :=
  IsActionQuotient.isIso_desc_iff _ _ _

/-- **Hypothesis 4, at a morphism out of an open of `T_inv/⟨σ⟩`.** The descent along the
coequalizer and the descent along `AlgebraicGeometry.LocallyRingedSpace.restrictπ` are isomorphisms
together, by `CategoryTheory.IsActionQuotient.isIso_desc_iff_isIso_desc`. So hypothesis 4 is:

> the canonical comparison `(T_inv/⟨σ⟩)|_{V₀} ⟶ Spf (Γ (T_inv/⟨σ⟩, V₀))` is an isomorphism.

The right-hand side mentions neither `CategoryTheory.IsActionQuotient.desc` nor the coequalizer of
the restricted action. It does still mention `CategoryTheory.actionQuotient`, at the *period*
action — the source is an open of `T_inv/⟨σ⟩`, which is what `hnode` is about and cannot be traded
away — and it carries the `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG` witness in its
binders. This is the form in which the residue is to be attacked. -/
theorem isIso_desc_nodeChartAdicHom_iff :
    IsIso ((isActionQuotient_actionQuotientπ (tateInvNodeChartRestrictedAction R I q hq hI)).desc
        (nodeChartAdicHom R I q hq hI hfgI hX)
        (isActionInvariant_nodeChartAdicHom R I q hq hI hfgI hX)) ↔
      IsIso (nodeChartQuotientHom R I q hq hI hfgI hX) :=
  IsActionQuotient.isIso_desc_iff_isIso_desc _
    (isActionQuotient_restrictπ_tateInvNodeChartQuotientOpens R I q hq hI) _ _

/-- **The two halves of hypothesis 4**, by
`AlgebraicGeometry.LocallyRingedSpace.isIso_iff_isIso_base_and_isIso_c_app`: the base map is a
homeomorphism, and every comparison map on sections is invertible. The equivalence is two-way, so
a refutation of either half refutes hypothesis 4 — while a refutation of hypothesis 4 refutes
neither `hnode` nor the existential form; see the module docstring.

The second conjunct is discharged at `O = op ⊤` by
`AlgebraicGeometry.isIso_c_app_top_nodeChartQuotientHom`, for a structural reason and with no
geometry. Neither the first conjunct nor the second at a proper open is decided anywhere. -/
theorem isIso_desc_nodeChartAdicHom_iff_base_and_c :
    IsIso ((isActionQuotient_actionQuotientπ (tateInvNodeChartRestrictedAction R I q hq hI)).desc
        (nodeChartAdicHom R I q hq hI hfgI hX)
        (isActionInvariant_nodeChartAdicHom R I q hq hI hfgI hX)) ↔
      IsIso (nodeChartQuotientHom R I q hq hI hfgI hX).base ∧
        ∀ O : (Opens (FormalSpectrum (tateInvNodeChartQuotientIdeal R I q hq hI)))ᵒᵖ,
          IsIso ((nodeChartQuotientHom R I q hq hI hfgI hX).c.app O) :=
  (isIso_desc_nodeChartAdicHom_iff R I q hq hI hfgI hX).trans
    (LocallyRingedSpace.isIso_iff_isIso_base_and_isIso_c_app _)

/-! ### The sheaf half at the top open -/

set_option linter.style.setOption false in
set_option backward.isDefEq.respectTransparency false in
/-- **The descent induces the canonical identification on global sections.** Both sides are ring
homomorphisms `Γ (T_inv/⟨σ⟩, V₀) →+* Γ ((T_inv/⟨σ⟩)|_{V₀}, ⊤)`; the right-hand side is the
identification of `AlgebraicGeometry.LocallyRingedSpace.restrictTopSectionsIso`, which is an
isomorphism.

`CategoryTheory.IsActionQuotient.globalSectionsHom_desc_eq` reduces this to the same statement one
level down, at `AlgebraicGeometry.nodeChartAdicHom`, where it is
`AlgebraicGeometry.globalSectionsHom_nodeChartAdicHom` followed by
`AlgebraicGeometry.nodeChartSectionsHom_eq_restrictπ`. -/
theorem globalSectionsHom_nodeChartQuotientHom :
    globalSectionsHom (tateInvNodeChartQuotientIdeal R I q hq hI) _
        (nodeChartQuotientHom R I q hq hI hfgI hX) =
      (LocallyRingedSpace.restrictTopSectionsIso
        (actionQuotient (tateInvPeriodAction R I q hq hI))
        (tateInvNodeChartQuotientOpens R I q hq hI)).inv.hom := by
  refine (isActionQuotient_restrictπ_tateInvNodeChartQuotientOpens R I q hq
    hI).globalSectionsHom_desc_eq _ _ _ _ ?_
  refine (globalSectionsHom_nodeChartAdicHom R I q hq hI hfgI hX).trans ?_
  rw [show nodeChartPsi R I q hq hI = (nodeChartSectionsHom R I q hq hI).hom from rfl,
    nodeChartSectionsHom_eq_restrictπ, CommRingCat.hom_comp]

/-- **The sheaf half of hypothesis 4 holds at `⊤`.** The comparison map of
`AlgebraicGeometry.nodeChartQuotientHom` at the top open is an isomorphism, with no hypothesis
beyond the ones already standing.

**It is not evidence for hypothesis 4.** The morphism is built from
`AlgebraicGeometry.nodeChartPsi`, which *is* the identification of `Γ (T_inv/⟨σ⟩, V₀)` with the
invariant sections, so the computation of
`AlgebraicGeometry.globalSectionsHom_nodeChartQuotientHom` uses no property of the node locus, the
annulus algebras or the `σ`-action. What it establishes is where hypothesis 4's content is not:
neither at the top open, nor in any general fact about descents. -/
theorem isIso_c_app_top_nodeChartQuotientHom :
    IsIso ((nodeChartQuotientHom R I q hq hI hfgI hX).c.app
      (op (⊤ : Opens (FormalSpectrum (tateInvNodeChartQuotientIdeal R I q hq hI))))) := by
  refine isIso_c_app_top_of_bijective_globalSectionsHom _ _ ?_
  rw [globalSectionsHom_nodeChartQuotientHom]
  exact (ConcreteCategory.isIso_iff_bijective _).mp inferInstance

end Instances

/-! ### The headline over the canonical comparison -/

/-- **`hnode` from one isomorphism at a canonical morphism.** Over a principal base ideal generated
by a non-zero-divisor, `T_inv/⟨σ⟩` is a formal scheme as soon as its restriction to the node
chart's open is carried isomorphically onto the formal spectrum of its own sections by
`AlgebraicGeometry.nodeChartQuotientHom`.

This is `AlgebraicGeometry.exists_formalScheme_of_isIso_desc_nodeChartAdicHom` with hypothesis 4
traded across `AlgebraicGeometry.isIso_desc_nodeChartAdicHom_iff`, so nothing is given up: the two
hypotheses are equivalent. What is bought is that the hypothesis is now an isomorphism at a
morphism out of an open of the quotient, which is what
`AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens` asks for as a
bare `Nonempty` of an isomorphism, here with the isomorphism named.

**It does not decide `hnode`.** The isomorphism is a hypothesis; no declaration on this tree
produces one, and refuting it refutes neither `hnode` nor the existential form. -/
theorem exists_formalScheme_of_isIso_nodeChartQuotientHom (t : R) (ht : I = Ideal.span {t})
    (hreg : IsLeftRegular t)
    (he :
      letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
          (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
        (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
      haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
        isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
      IsIso (nodeChartQuotientHom R I q hq hI
        (fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg)
        (adicSectionsLocallyFG_nodeChartPsi R I q hq hI t ht hreg))) :
    ∃ X : FormalScheme.{u},
      X.toLocallyRingedSpace = actionQuotient (tateInvPeriodAction R I q hq hI) := by
  letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
    (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
  haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
    isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
  exact exists_formalScheme_of_isIso_desc_nodeChartAdicHom R I q hq hI t ht hreg
    ((isIso_desc_nodeChartAdicHom_iff R I q hq hI _ _).mpr he)

end AlgebraicGeometry

end
