import FormalSchemes.AdicSectionsChart
import FormalSchemes.TateInvNodeChartHomOfSections

set_option linter.style.header false

/-!
# The node chart's morphism from two neighbourhood-basis witnesses

`FormalSchemes.TateInvNodeChartHomOfSections` reduced the construction of the morphism

```
k : nodeChartSaturationFormalScheme … ⟶ Spf (tateInvNodeChartQuotientIdeal …)
```

to three families of continuity conditions —
`AlgebraicGeometry.NodeChartChartContinuous`,
`AlgebraicGeometry.NodeChartOverlapContinuousFst` and
`AlgebraicGeometry.NodeChartOverlapContinuousSnd` — and stopped there, because all three are of
the shape `FormalSchemes.GeneralFibreProductLiftAdic` records as unreachable for a chart family
drawn by `Classical.choice`, and says not to reintroduce.

`FormalSchemes.AdicSectionsChart` runs that module's own fix on
`AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom`: choose the charts from a neighbourhood
basis that already records the bounds. This file is that construction at the node chart.

## What changes, and what does not

The three continuity families are replaced by two existential conditions on
`AlgebraicGeometry.nodeChartSaturationFormalScheme`:

* `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG` at
  `AlgebraicGeometry.nodeChartPsi`, which supplies the charts, the finite generation of their
  ideals **and** the first continuity family;
* `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.OverlapAdic`, which supplies the affine
  cover of each overlap **and** the other two.

**Nothing is proved to exist.** No witness of either condition is produced here, at the node chart
or anywhere else, and this file does not argue that one can be. What it removes is the demand that
a bound hold at charts nothing describes; what it leaves is the demand that charts carrying the
bounds exist, which is a statement about the annulus algebras of
`FormalSchemes.TateInvNodeChartQuotientOpen` and is where the geometry is.

`AlgebraicGeometry.nodeChartAdicHom_eq_nodeChartHom` records that this is not a different morphism:
at the same chart family it **is** `AlgebraicGeometry.nodeChartHom`, whatever overlap data that one
was given.

## Main definitions and results

* `AlgebraicGeometry.nodeChartAdicHom`: the morphism, from the two witnesses.
* `AlgebraicGeometry.nodeChartAdicHom_eq_nodeChartHom`: it is
  `AlgebraicGeometry.nodeChartHom` at the charts the first witness supplies.
* `AlgebraicGeometry.globalSectionsHom_nodeChartAdicHom`: it induces
  `AlgebraicGeometry.nodeChartPsi` on global sections.
* `AlgebraicGeometry.exists_formalScheme_of_adicSections`: **the headline.** Over a principal base
  ideal generated by a non-zero-divisor, `T_inv/⟨σ⟩` is a formal scheme as soon as the two
  neighbourhood-basis witnesses exist and the morphism they build is invariant with an isomorphism
  for its descent.

## What is *not* proved here

**`hnode` is undecided, in both directions, and nothing here moves it.** Three unchecked families
become two unchecked existentials; no continuity bound is discharged, no invariance is proved and
no isomorphism is produced. If both conditions were false of the node chart's source, everything
below would still be correct and `hnode` would still be open.

**The two conditions are not weaker than the three families in any proved sense.** They imply them
— that is what `AlgebraicGeometry.FormalScheme.AdicSectionsLocallyFG.cont` and the two projections
of `AlgebraicGeometry.FormalScheme.AdicOverBasePairLocallyFG` are — and no converse is claimed. The
gain is that they are the *reachable* shape: a witness is produced by exhibiting charts, whereas
the families demand a bound of charts already chosen.

**The overlap condition's own status is open**, and `FormalSchemes.AdicSectionsChart`'s module
docstring says exactly where: whether one adic-over-base witness for each of the two base morphisms
yields a single chart adic over both is not settled, and the obvious refinement argument is blocked
by the same false statement — "an open immersion is adic on sections" — that made the original
hypothesis unreachable (issues 460/468/472/487).

**The chain back to `hnode` is still one-way.** It passes through
`AlgebraicGeometry.exists_formalScheme_of_iso_restrict_tateInvNodeChartQuotientOpens`, which
discharges a containment of ranges, so refuting the hypothesis of the headline below refutes
neither `hnode` nor the existence of the node chart. Nor is that hypothesis weaker than the descent
packaging's: a morphism produced some other way need not be `AlgebraicGeometry.nodeChartAdicHom` of
anything.

**Nothing here bears on `AlgebraicGeometry.LocallyRingedSpace.IsFreeProperlyDiscontinuous` for the
period action**, which `AlgebraicGeometry.not_isFreeProperlyDiscontinuous_tateInvPeriodAction`
refutes globally.

## References

* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.4 (10.4.6), §10.6.
* [Deligne–Rapoport, *Les schémas de modules de courbes elliptiques*], II.1 — the Néron 1-gon.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry FormalSpectrum TopologicalSpace
open Opposite

universe u

namespace AlgebraicGeometry

variable (R : Type u) [CommRing R] (I : Ideal R) (q : R)
variable [TopologicalSpace R] [IsAdicRing I] [IsNoetherianRing R] (hq : q ∈ I) (hI : I.FG)

section Instances

variable [TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
  (op (tateInvNodeChartQuotientOpens R I q hq hI)))]
variable [IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI)]

variable (hfgI : (tateInvNodeChartQuotientIdeal R I q hq hI).FG)
variable (hX : FormalScheme.AdicSectionsLocallyFG (tateInvNodeChartQuotientIdeal R I q hq hI)
  (nodeChartPsi R I q hq hI))
variable (hov : hX.OverlapAdic (nodeChartPsi R I q hq hI))

/-- **The morphism into the node chart's formal spectrum, built from two neighbourhood-basis
witnesses.** Every argument of `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHom` comes from
the two witnesses except finite generation of the target's ideal, which
`AlgebraicGeometry.fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base` supplies under the
hypotheses this cluster's reductions already carry.

No continuity bound is asked of a chart this construction did not itself produce. That is the whole
difference from `AlgebraicGeometry.nodeChartHom`, which is otherwise the same morphism
(`nodeChartAdicHom_eq_nodeChartHom`). -/
def nodeChartAdicHom :
    (nodeChartSaturationFormalScheme R I q hq hI).toLocallyRingedSpace ⟶
      locallyRingedSpaceObj (tateInvNodeChartQuotientIdeal R I q hq hI) :=
  FormalScheme.homOfGlobalSectionsHomOfAdicSections (nodeChartPsi R I q hq hI) hX hfgI hov

/-- **It is `AlgebraicGeometry.nodeChartHom` at the charts the witness supplies**, for any overlap
data that one was given. So this file does not introduce a second morphism: it introduces a second
route to the same one, whose inputs are reachable.

This is `AlgebraicGeometry.FormalScheme.homOfGlobalSectionsHomOfAdicSections_eq`, which is in turn
`AlgebraicGeometry.FormalScheme.hom_ext_of_chart_comp` — both morphisms restrict to
`AlgebraicGeometry.FormalScheme.chartMap` of the chart-restriction of
`AlgebraicGeometry.nodeChartPsi` on every chart. -/
theorem nodeChartAdicHom_eq_nodeChartHom
    (hf : NodeChartOverlapContinuousFst R I q hq hI hX.chart hX.fg_chart hX.cont)
    (hg : NodeChartOverlapContinuousSnd R I q hq hI hX.chart hX.fg_chart hX.cont) :
    nodeChartAdicHom R I q hq hI hfgI hX hov =
      nodeChartHom R I q hq hI hX.chart hX.fg_chart hfgI hX.cont hf hg :=
  FormalScheme.homOfGlobalSectionsHomOfAdicSections_eq (nodeChartPsi R I q hq hI) hX hfgI hov
    (nodeChartOcharts R I q hq hI hX.chart hX.fg_chart)
    (nodeChartOcharts_fg R I q hq hI hX.chart hX.fg_chart) hf hg

/-- **It induces `AlgebraicGeometry.nodeChartPsi` on global sections**, so it is the morphism that
homomorphism was the candidate input for and not merely some morphism. -/
theorem globalSectionsHom_nodeChartAdicHom :
    globalSectionsHom (tateInvNodeChartQuotientIdeal R I q hq hI)
        (nodeChartSaturationFormalScheme R I q hq hI).toLocallyRingedSpace
        (nodeChartAdicHom R I q hq hI hfgI hX hov) = nodeChartPsi R I q hq hI :=
  FormalScheme.globalSectionsHom_homOfGlobalSectionsHomOfAdicSections
    (nodeChartPsi R I q hq hI) hX hfgI hov

end Instances

/-- **`hnode` from two neighbourhood-basis witnesses, an invariance and an isomorphism.** Over a
principal base ideal generated by a non-zero-divisor, `T_inv/⟨σ⟩` is a formal scheme as soon as
`AlgebraicGeometry.nodeChartSaturationFormalScheme` is adic over
`AlgebraicGeometry.nodeChartPsi` on a neighbourhood basis, its overlaps are adic over the two
compared morphisms on a neighbourhood basis, and the morphism
`AlgebraicGeometry.nodeChartAdicHom` those witnesses build is invariant with an isomorphism for its
descent.

This is `AlgebraicGeometry.exists_formalScheme_of_isIso_desc`
(`FormalSchemes.TateInvNodeChartDescent`) with its quantified morphism replaced by the named one,
and that is the whole proof. The hypothesis is stated inside one `∃` for the reason
`AlgebraicGeometry.exists_formalScheme_of_isIso_desc_nodeChartHom` gives: the packaging states its
own hypothesis under `letI`/`haveI` at the canonical instances, so a version with free instance
binders cannot be fed to it.

**It does not decide `hnode`**, and it is sufficient rather than equivalent — see the module
docstring. -/
theorem exists_formalScheme_of_adicSections (t : R) (ht : I = Ideal.span {t})
    (hreg : IsLeftRegular t)
    (he :
      letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
          (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
        (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
      haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
        isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
      ∃ (hX : FormalScheme.AdicSectionsLocallyFG (tateInvNodeChartQuotientIdeal R I q hq hI)
            (nodeChartPsi R I q hq hI))
        (hov : hX.OverlapAdic (nodeChartPsi R I q hq hI))
        (hk : IsActionInvariant (tateInvNodeChartRestrictedAction R I q hq hI)
          (nodeChartAdicHom R I q hq hI
            (fg_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg)
            hX hov)),
        IsIso ((isActionQuotient_actionQuotientπ
          (tateInvNodeChartRestrictedAction R I q hq hI)).desc _ hk)) :
    ∃ X : FormalScheme.{u},
      X.toLocallyRingedSpace = actionQuotient (tateInvPeriodAction R I q hq hI) := by
  letI : TopologicalSpace ((actionQuotient (tateInvPeriodAction R I q hq hI)).presheaf.obj
      (op (tateInvNodeChartQuotientOpens R I q hq hI))) :=
    (tateInvNodeChartQuotientIdeal R I q hq hI).adicTopology
  haveI : IsAdicRing (tateInvNodeChartQuotientIdeal R I q hq hI) :=
    isAdicRing_tateInvNodeChartQuotientIdeal_of_isLeftRegular_base R I q hq hI t ht hreg
  obtain ⟨hX, hov, hk, hiso⟩ := he
  exact exists_formalScheme_of_isIso_desc R I q hq hI t ht hreg ⟨_, hk, hiso⟩

end AlgebraicGeometry

end
