import FormalSchemes.TopFiniteType
import FormalSchemes.BaseChange

set_option linter.style.header false

/-!
# Base change of algebras topologically of finite type

This file completes the **finite base-change** property of algebras topologically of finite type
(tf-type, `FormalSchemes/TopFiniteType.lean`), following Bosch, *Lectures on Formal and Rigid
Geometry* (LNM 2105), §7.3.

The finite base-change isomorphism `S ⊗̂_R R{X₁, …, Xₙ} ≃+* S{X₁, …, Xₙ}`
(`RestrictedPowerSeries.baseChangeEquiv`, `FormalSchemes/BaseChange.lean`) exhibits the completed
tensor product of the formal polydisc over `R` with `S` as the formal polydisc over `S`. Combined
with the crux surjectivity result of this file, it yields: if `A` is tf-type over `(R, I)`, then
its completed base change `S ⊗̂_R A` is tf-type over `(S, I·S)`.

## Main results

* `CompletedTensorProduct.map_surjective`: the functorial map `A ⊗̂_R B →+* A' ⊗̂_R B'` induced by a
  pair of **surjective** `R`-algebra maps is surjective. This is "completion carries surjections of
  the underlying tensor products to surjections", proved via
  `AdicCompletion.surjective_of_mk_map_comp_surjective`: a continuous ring map into a complete adic
  ring which is surjective modulo the ideal of definition is surjective, and modulo the ideal of
  definition everything reduces to the (surjective) tensor-product map of the underlying rings.
* `RestrictedPowerSeries.isTopologicallyFiniteType`: the restricted power series ring `R{X₁, …, Xₙ}`
  is itself tf-type over `(R, I)` — the identity presentation.
* `IsTopologicallyFiniteType.baseChange`: if `A` is tf-type over `(R, I)`, then `S ⊗̂_R A` is
  tf-type over `(S, I·S)`, with ideal of definition the extension of `I·S`.

## References

* [Bosch, *Lectures on Formal and Rigid Geometry*, LNM 2105], §7.3.
* [Grothendieck, *Éléments de géométrie algébrique I*][EGA1], Ch. I, §10.13.
-/

noncomputable section

open Ideal TensorProduct

universe u

namespace CompletedTensorProduct

variable {R : Type u} [CommRing R] {I : Ideal R}
variable {A B A' B' : Type u} [CommRing A] [CommRing B] [CommRing A'] [CommRing B']
  [Algebra R A] [Algebra R B] [Algebra R A'] [Algebra R B']

/-- The functorial map is compatible with the base-ring structure map: it sends `algebraMap R`
to `algebraMap R`. -/
theorem map_algebraMap (hI : I.FG) (f : A →ₐ[R] A') (g : B →ₐ[R] B') (r : R) :
    map hI f g (algebraMap R (CompletedTensorProduct R I A B) r) =
      algebraMap R (CompletedTensorProduct R I A' B') r := by
  rw [← (inl R I A B).commutes r, map_inl, f.commutes, (inl R I A' B').commutes]

/-- The functorial map is compatible with the base-ring structure map (composed form). -/
theorem map_comp_algebraMap (hI : I.FG) (f : A →ₐ[R] A') (g : B →ₐ[R] B') :
    (map hI f g).comp (algebraMap R (CompletedTensorProduct R I A B)) =
      algebraMap R (CompletedTensorProduct R I A' B') :=
  RingHom.ext (map_algebraMap hI f g)

/-- The functorial map carries the ideal of definition onto the ideal of definition of the target:
it is the extension of `I` on both sides. -/
theorem idealOfDefinition_map (hI : I.FG) (f : A →ₐ[R] A') (g : B →ₐ[R] B') :
    (idealOfDefinition R I A B).map (map hI f g) = idealOfDefinition R I A' B' := by
  rw [idealOfDefinition_eq_map, Ideal.map_map, map_comp_algebraMap hI f g,
    ← idealOfDefinition_eq_map]

/-- The completion map of any element of the underlying tensor product `A' ⊗[R] B'` lies in the
range of the functorial map, when the two component maps are surjective. The image of `map` is a
subring containing the completion image of every `f a ⊗ g b`, and the underlying tensor product is
generated by such elements. -/
theorem of_mem_range_map (hI : I.FG) {f : A →ₐ[R] A'} {g : B →ₐ[R] B'}
    (hf : Function.Surjective f) (hg : Function.Surjective g) (w : A' ⊗[R] B') :
    AdicCompletion.of (I.map (algebraMap R (A' ⊗[R] B'))) (A' ⊗[R] B') w ∈
      (map hI f g).range := by
  induction w using TensorProduct.induction_on with
  | zero => rw [map_zero]; exact Subring.zero_mem (map hI f g).range
  | tmul a' b' =>
    obtain ⟨a, rfl⟩ := hf a'
    obtain ⟨b, rfl⟩ := hg b'
    refine ⟨inl R I A B a * inr R I A B b, ?_⟩
    rw [map_mul, map_inl, map_inr, inl_apply, inr_apply, ← map_mul,
      Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul]
    rfl
  | add x y hx hy =>
    rw [map_add]
    exact Subring.add_mem _ hx hy

/-- **Surjectivity of the functorial map of the completed tensor product**: if `f` and `g` are
surjective `R`-algebra maps then the induced map `A ⊗̂_R B →+* A' ⊗̂_R B'` is surjective
(for `I` finitely generated).

The argument is `AdicCompletion.surjective_of_mk_map_comp_surjective`: a continuous ring map from a
precomplete ring into a Hausdorff adic ring that is surjective modulo the (image of the) ideal of
definition is surjective. Modulo the ideal of definition the completed tensor products are the
residue rings of the underlying tensor products, and there the map is the tensor-product map of the
surjections `f`, `g`, hence surjective. -/
theorem map_surjective (hI : I.FG) {f : A →ₐ[R] A'} {g : B →ₐ[R] B'}
    (hf : Function.Surjective f) (hg : Function.Surjective g) :
    Function.Surjective (map hI f g) := by
  haveI hsc : IsAdicComplete (idealOfDefinition R I A B) (CompletedTensorProduct R I A B) :=
    (isAdicRing R I A B hI).toIsAdicComplete
  haveI htc : IsAdicComplete (idealOfDefinition R I A' B') (CompletedTensorProduct R I A' B') :=
    (isAdicRing R I A' B' hI).toIsAdicComplete
  have hJ : (idealOfDefinition R I A B).map (map hI f g) = idealOfDefinition R I A' B' :=
    idealOfDefinition_map hI f g
  haveI hhaus : IsHausdorff ((idealOfDefinition R I A B).map (map hI f g))
      (CompletedTensorProduct R I A' B') := by
    rw [hJ]; infer_instance
  refine surjective_of_mk_map_comp_surjective
    (I := idealOfDefinition R I A B) (f := (map hI f g)) ?_
  -- surjectivity modulo the ideal of definition
  intro ybar
  obtain ⟨y, rfl⟩ := Ideal.Quotient.mk_surjective ybar
  -- represent `evalₐ 1 y` by an element `w` of the underlying tensor product
  obtain ⟨w, hw⟩ := Ideal.Quotient.mk_surjective
    (AdicCompletion.evalₐ (I.map (algebraMap R (A' ⊗[R] B'))) 1 y)
  -- lift `of' w` through `map`
  obtain ⟨t, ht⟩ := RingHom.mem_range.mp (of_mem_range_map hI hf hg w)
  refine ⟨t, ?_⟩
  -- `y - of' w` lies in the ideal of definition, since both have the same first thickening
  have hev : AdicCompletion.evalₐ (I.map (algebraMap R (A' ⊗[R] B'))) 1
      (y - AdicCompletion.of (I.map (algebraMap R (A' ⊗[R] B'))) (A' ⊗[R] B') w) = 0 := by
    rw [map_sub, sub_eq_zero, AdicCompletion.evalₐ_of, hw]
  have hker : y - AdicCompletion.of (I.map (algebraMap R (A' ⊗[R] B'))) (A' ⊗[R] B') w ∈
      idealOfDefinition R I A' B' := by
    have hmem : y - AdicCompletion.of (I.map (algebraMap R (A' ⊗[R] B'))) (A' ⊗[R] B') w ∈
        RingHom.ker (AdicCompletion.evalₐ (I.map (algebraMap R (A' ⊗[R] B'))) 1).toRingHom :=
      RingHom.mem_ker.mpr hev
    rwa [AdicCompletion.ker_evalₐ _ (hI.map _) 1, pow_one] at hmem
  rw [RingHom.coe_comp, Function.comp_apply, Ideal.Quotient.mk_eq_mk_iff_sub_mem, hJ, ht]
  have hneg := neg_mem hker
  rwa [neg_sub] at hneg

end CompletedTensorProduct

namespace RestrictedPowerSeries

variable (R : Type u) [CommRing R] (I : Ideal R) (n : ℕ)

/-- The restricted power series ring `R{X₁, …, Xₙ}` is itself topologically of finite type over
`(R, I)`, via the identity presentation. -/
theorem isTopologicallyFiniteType :
    IsTopologicallyFiniteType R I (RestrictedPowerSeries R I n) (idealOfDefinition R I n) :=
  ⟨n, AlgHom.id R (RestrictedPowerSeries R I n), Function.surjective_id, by
    simp [Ideal.map_id]⟩

end RestrictedPowerSeries

namespace IsTopologicallyFiniteType

variable {R : Type u} [CommRing R] {I : Ideal R}
variable {A : Type u} [CommRing A] [Algebra R A] {L : Ideal A}
variable {S : Type u} [CommRing S] [Algebra R S]

/-- **Finite base change of tf-type algebras**: if `A` is topologically of finite type over
`(R, I)`, then the completed base change `S ⊗̂_R A` is topologically of finite type over
`(S, I·S)`, with ideal of definition the extension of `I·S` (equivalently `I·(S ⊗̂_R A)`).

The presentation is the composite `S{X₁, …, Xₙ} ≃ S ⊗̂_R R{X₁, …, Xₙ} ↠ S ⊗̂_R A`, where the first
map is the finite base-change isomorphism `RestrictedPowerSeries.baseChangeEquiv` and the second is
the completed base change `map (id_S) ψ` of a presentation `ψ : R{X₁, …, Xₙ} ↠ A` of `A`; the latter
is surjective by `CompletedTensorProduct.map_surjective`. -/
theorem baseChange (hI : I.FG) (h : IsTopologicallyFiniteType R I A L) :
    IsTopologicallyFiniteType S (I.map (algebraMap R S))
      (CompletedTensorProduct R I S A)
      (CompletedTensorProduct.idealOfDefinition R I S A) := by
  obtain ⟨n, ψ, hψ, _⟩ := h
  -- the base-change isomorphism `S{X} ≃ S ⊗̂_R R{X}` as an `S`-algebra map
  haveI hcc : IsAdicComplete
      (CompletedTensorProduct.idealOfDefinition R I S (RestrictedPowerSeries R I n))
      (CompletedTensorProduct R I S (RestrictedPowerSeries R I n)) :=
    (CompletedTensorProduct.isAdicRing R I S (RestrictedPowerSeries R I n) hI).toIsAdicComplete
  -- `baseChangeInvHom` as an `S`-algebra homomorphism `S{X} →ₐ[S] S ⊗̂_R R{X}`
  let e : RestrictedPowerSeries S (I.map (algebraMap R S)) n →ₐ[S]
      CompletedTensorProduct R I S (RestrictedPowerSeries R I n) :=
    { RestrictedPowerSeries.baseChangeInvHom (S := S) hI with
      commutes' := fun s => by
        simp only [RingHom.toMonoidHom_eq_coe, OneHom.toFun_eq_coe, MonoidHom.toOneHom_coe,
          MonoidHom.coe_coe]
        rw [RestrictedPowerSeries.baseChangeInvHom_algebraMap]
        rfl }
  -- `map (id_S) ψ` as an `S`-algebra homomorphism `S ⊗̂_R R{X} →ₐ[S] S ⊗̂_R A`
  let m : CompletedTensorProduct R I S (RestrictedPowerSeries R I n) →ₐ[S]
      CompletedTensorProduct R I S A :=
    { CompletedTensorProduct.map hI (AlgHom.id R S) ψ with
      commutes' := fun s => by
        simp only [RingHom.toMonoidHom_eq_coe, OneHom.toFun_eq_coe, MonoidHom.toOneHom_coe,
          MonoidHom.coe_coe]
        rw [show algebraMap S (CompletedTensorProduct R I S (RestrictedPowerSeries R I n)) s
              = CompletedTensorProduct.inl R I S (RestrictedPowerSeries R I n) s from rfl,
          CompletedTensorProduct.map_inl]
        rfl }
  refine ⟨n, m.comp e, ?_, ?_⟩
  · -- surjectivity: `m` is surjective (base change of surjections), `e` is an isomorphism
    refine (CompletedTensorProduct.map_surjective hI Function.surjective_id hψ).comp ?_
    exact (RestrictedPowerSeries.baseChangeEquiv (S := S) hI).symm.surjective
  · -- the ideal of definition maps onto the ideal of definition of `S ⊗̂_R A`
    rw [show (m.comp e).toRingHom = m.toRingHom.comp e.toRingHom from rfl, ← Ideal.map_map]
    have hcomp : e.toRingHom.comp
        (algebraMap R (RestrictedPowerSeries S (I.map (algebraMap R S)) n)) =
        algebraMap R (CompletedTensorProduct R I S (RestrictedPowerSeries R I n)) := by
      refine RingHom.ext fun r => ?_
      simp only [RingHom.comp_apply]
      rw [IsScalarTower.algebraMap_apply R S
          (RestrictedPowerSeries S (I.map (algebraMap R S)) n) r]
      change e (algebraMap S _ (algebraMap R S r)) = _
      rw [e.commutes, ← IsScalarTower.algebraMap_apply]
    have he : (RestrictedPowerSeries.idealOfDefinition S (I.map (algebraMap R S)) n).map
        e.toRingHom =
        CompletedTensorProduct.idealOfDefinition R I S (RestrictedPowerSeries R I n) := by
      rw [RestrictedPowerSeries.baseChange_idealOfDefinition_eq, Ideal.map_map, hcomp,
        ← CompletedTensorProduct.idealOfDefinition_eq_map]
    rw [he]
    exact CompletedTensorProduct.idealOfDefinition_map hI (AlgHom.id R S) ψ

end IsTopologicallyFiniteType
